# This file was created automatically by SWIG 1.3.29.
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _zxid
import new
new_instancemethod = new.instancemethod
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


ZXERR_EOF = _zxid.ZXERR_EOF
ZXERR_MISMATCH_CLOSE = _zxid.ZXERR_MISMATCH_CLOSE
ZXERR_BAD_ATTR_NS = _zxid.ZXERR_BAD_ATTR_NS
ZXERR_BAD_ELEM_NS = _zxid.ZXERR_BAD_ELEM_NS
ZXERR_MISSING_ATTR = _zxid.ZXERR_MISSING_ATTR
ZXERR_EXTRA_ATTR = _zxid.ZXERR_EXTRA_ATTR
ZXERR_MISSING_ELEM = _zxid.ZXERR_MISSING_ELEM
ZXERR_EXTRA_ELEM = _zxid.ZXERR_EXTRA_ELEM
ZXERR_ELEM_ORDER = _zxid.ZXERR_ELEM_ORDER
ZXERR_BAD_NS_PREFIX = _zxid.ZXERR_BAD_NS_PREFIX
ZXERR_TAG_NOT_CLOSED = _zxid.ZXERR_TAG_NOT_CLOSED
ZXERR_MASK = _zxid.ZXERR_MASK
ZXERR_ATTR_FLAG = _zxid.ZXERR_ATTR_FLAG
class zx_ns_s(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, zx_ns_s, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, zx_ns_s, name)
    __repr__ = _swig_repr
    __swig_setmethods__["n"] = _zxid.zx_ns_s_n_set
    __swig_getmethods__["n"] = _zxid.zx_ns_s_n_get
    if _newclass:n = property(_zxid.zx_ns_s_n_get, _zxid.zx_ns_s_n_set)
    __swig_setmethods__["m"] = _zxid.zx_ns_s_m_set
    __swig_getmethods__["m"] = _zxid.zx_ns_s_m_get
    if _newclass:m = property(_zxid.zx_ns_s_m_get, _zxid.zx_ns_s_m_set)
    __swig_setmethods__["seen"] = _zxid.zx_ns_s_seen_set
    __swig_getmethods__["seen"] = _zxid.zx_ns_s_seen_get
    if _newclass:seen = property(_zxid.zx_ns_s_seen_get, _zxid.zx_ns_s_seen_set)
    __swig_setmethods__["seen_n"] = _zxid.zx_ns_s_seen_n_set
    __swig_getmethods__["seen_n"] = _zxid.zx_ns_s_seen_n_get
    if _newclass:seen_n = property(_zxid.zx_ns_s_seen_n_get, _zxid.zx_ns_s_seen_n_set)
    __swig_setmethods__["seen_p"] = _zxid.zx_ns_s_seen_p_set
    __swig_getmethods__["seen_p"] = _zxid.zx_ns_s_seen_p_get
    if _newclass:seen_p = property(_zxid.zx_ns_s_seen_p_get, _zxid.zx_ns_s_seen_p_set)
    __swig_setmethods__["seen_pop"] = _zxid.zx_ns_s_seen_pop_set
    __swig_getmethods__["seen_pop"] = _zxid.zx_ns_s_seen_pop_get
    if _newclass:seen_pop = property(_zxid.zx_ns_s_seen_pop_get, _zxid.zx_ns_s_seen_pop_set)
    __swig_setmethods__["inc_n"] = _zxid.zx_ns_s_inc_n_set
    __swig_getmethods__["inc_n"] = _zxid.zx_ns_s_inc_n_get
    if _newclass:inc_n = property(_zxid.zx_ns_s_inc_n_get, _zxid.zx_ns_s_inc_n_set)
    __swig_setmethods__["prefix_len"] = _zxid.zx_ns_s_prefix_len_set
    __swig_getmethods__["prefix_len"] = _zxid.zx_ns_s_prefix_len_get
    if _newclass:prefix_len = property(_zxid.zx_ns_s_prefix_len_get, _zxid.zx_ns_s_prefix_len_set)
    __swig_setmethods__["prefix"] = _zxid.zx_ns_s_prefix_set
    __swig_getmethods__["prefix"] = _zxid.zx_ns_s_prefix_get
    if _newclass:prefix = property(_zxid.zx_ns_s_prefix_get, _zxid.zx_ns_s_prefix_set)
    __swig_setmethods__["url_len"] = _zxid.zx_ns_s_url_len_set
    __swig_getmethods__["url_len"] = _zxid.zx_ns_s_url_len_get
    if _newclass:url_len = property(_zxid.zx_ns_s_url_len_get, _zxid.zx_ns_s_url_len_set)
    __swig_setmethods__["url"] = _zxid.zx_ns_s_url_set
    __swig_getmethods__["url"] = _zxid.zx_ns_s_url_get
    if _newclass:url = property(_zxid.zx_ns_s_url_get, _zxid.zx_ns_s_url_set)
    def __init__(self, *args): 
        this = _zxid.new_zx_ns_s(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _zxid.delete_zx_ns_s
    __del__ = lambda self : None;
zx_ns_s_swigregister = _zxid.zx_ns_s_swigregister
zx_ns_s_swigregister(zx_ns_s)

class zx_ctx(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, zx_ctx, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, zx_ctx, name)
    __repr__ = _swig_repr
    __swig_setmethods__["base"] = _zxid.zx_ctx_base_set
    __swig_getmethods__["base"] = _zxid.zx_ctx_base_get
    if _newclass:base = property(_zxid.zx_ctx_base_get, _zxid.zx_ctx_base_set)
    __swig_setmethods__["p"] = _zxid.zx_ctx_p_set
    __swig_getmethods__["p"] = _zxid.zx_ctx_p_get
    if _newclass:p = property(_zxid.zx_ctx_p_get, _zxid.zx_ctx_p_set)
    __swig_setmethods__["lim"] = _zxid.zx_ctx_lim_set
    __swig_getmethods__["lim"] = _zxid.zx_ctx_lim_get
    if _newclass:lim = property(_zxid.zx_ctx_lim_get, _zxid.zx_ctx_lim_set)
    __swig_setmethods__["ns_tab"] = _zxid.zx_ctx_ns_tab_set
    __swig_getmethods__["ns_tab"] = _zxid.zx_ctx_ns_tab_get
    if _newclass:ns_tab = property(_zxid.zx_ctx_ns_tab_get, _zxid.zx_ctx_ns_tab_set)
    __swig_setmethods__["unknown_ns"] = _zxid.zx_ctx_unknown_ns_set
    __swig_getmethods__["unknown_ns"] = _zxid.zx_ctx_unknown_ns_get
    if _newclass:unknown_ns = property(_zxid.zx_ctx_unknown_ns_get, _zxid.zx_ctx_unknown_ns_set)
    __swig_setmethods__["guard_seen_n"] = _zxid.zx_ctx_guard_seen_n_set
    __swig_getmethods__["guard_seen_n"] = _zxid.zx_ctx_guard_seen_n_get
    if _newclass:guard_seen_n = property(_zxid.zx_ctx_guard_seen_n_get, _zxid.zx_ctx_guard_seen_n_set)
    __swig_setmethods__["guard_seen_p"] = _zxid.zx_ctx_guard_seen_p_set
    __swig_getmethods__["guard_seen_p"] = _zxid.zx_ctx_guard_seen_p_get
    if _newclass:guard_seen_p = property(_zxid.zx_ctx_guard_seen_p_get, _zxid.zx_ctx_guard_seen_p_set)
    __swig_setmethods__["exclude_sig"] = _zxid.zx_ctx_exclude_sig_set
    __swig_getmethods__["exclude_sig"] = _zxid.zx_ctx_exclude_sig_get
    if _newclass:exclude_sig = property(_zxid.zx_ctx_exclude_sig_get, _zxid.zx_ctx_exclude_sig_set)
    __swig_setmethods__["inc_ns_len"] = _zxid.zx_ctx_inc_ns_len_set
    __swig_getmethods__["inc_ns_len"] = _zxid.zx_ctx_inc_ns_len_get
    if _newclass:inc_ns_len = property(_zxid.zx_ctx_inc_ns_len_get, _zxid.zx_ctx_inc_ns_len_set)
    __swig_setmethods__["inc_ns"] = _zxid.zx_ctx_inc_ns_set
    __swig_getmethods__["inc_ns"] = _zxid.zx_ctx_inc_ns_get
    if _newclass:inc_ns = property(_zxid.zx_ctx_inc_ns_get, _zxid.zx_ctx_inc_ns_set)
    __swig_setmethods__["malloc_func"] = _zxid.zx_ctx_malloc_func_set
    __swig_getmethods__["malloc_func"] = _zxid.zx_ctx_malloc_func_get
    if _newclass:malloc_func = property(_zxid.zx_ctx_malloc_func_get, _zxid.zx_ctx_malloc_func_set)
    __swig_setmethods__["realloc_func"] = _zxid.zx_ctx_realloc_func_set
    __swig_getmethods__["realloc_func"] = _zxid.zx_ctx_realloc_func_get
    if _newclass:realloc_func = property(_zxid.zx_ctx_realloc_func_get, _zxid.zx_ctx_realloc_func_set)
    __swig_setmethods__["free_func"] = _zxid.zx_ctx_free_func_set
    __swig_getmethods__["free_func"] = _zxid.zx_ctx_free_func_get
    if _newclass:free_func = property(_zxid.zx_ctx_free_func_get, _zxid.zx_ctx_free_func_set)
    def __init__(self, *args): 
        this = _zxid.new_zx_ctx(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _zxid.delete_zx_ctx
    __del__ = lambda self : None;
zx_ctx_swigregister = _zxid.zx_ctx_swigregister
zx_ctx_swigregister(zx_ctx)

class zx_node_s(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, zx_node_s, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, zx_node_s, name)
    __repr__ = _swig_repr
    __swig_setmethods__["n"] = _zxid.zx_node_s_n_set
    __swig_getmethods__["n"] = _zxid.zx_node_s_n_get
    if _newclass:n = property(_zxid.zx_node_s_n_get, _zxid.zx_node_s_n_set)
    __swig_setmethods__["wo"] = _zxid.zx_node_s_wo_set
    __swig_getmethods__["wo"] = _zxid.zx_node_s_wo_get
    if _newclass:wo = property(_zxid.zx_node_s_wo_get, _zxid.zx_node_s_wo_set)
    __swig_setmethods__["ns"] = _zxid.zx_node_s_ns_set
    __swig_getmethods__["ns"] = _zxid.zx_node_s_ns_get
    if _newclass:ns = property(_zxid.zx_node_s_ns_get, _zxid.zx_node_s_ns_set)
    __swig_setmethods__["tok"] = _zxid.zx_node_s_tok_set
    __swig_getmethods__["tok"] = _zxid.zx_node_s_tok_get
    if _newclass:tok = property(_zxid.zx_node_s_tok_get, _zxid.zx_node_s_tok_set)
    __swig_setmethods__["err"] = _zxid.zx_node_s_err_set
    __swig_getmethods__["err"] = _zxid.zx_node_s_err_get
    if _newclass:err = property(_zxid.zx_node_s_err_get, _zxid.zx_node_s_err_set)
    def __init__(self, *args): 
        this = _zxid.new_zx_node_s(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _zxid.delete_zx_node_s
    __del__ = lambda self : None;
zx_node_s_swigregister = _zxid.zx_node_s_swigregister
zx_node_s_swigregister(zx_node_s)

class zx_elem_s(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, zx_elem_s, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, zx_elem_s, name)
    __repr__ = _swig_repr
    __swig_setmethods__["g"] = _zxid.zx_elem_s_g_set
    __swig_getmethods__["g"] = _zxid.zx_elem_s_g_get
    if _newclass:g = property(_zxid.zx_elem_s_g_get, _zxid.zx_elem_s_g_set)
    __swig_setmethods__["kids"] = _zxid.zx_elem_s_kids_set
    __swig_getmethods__["kids"] = _zxid.zx_elem_s_kids_get
    if _newclass:kids = property(_zxid.zx_elem_s_kids_get, _zxid.zx_elem_s_kids_set)
    __swig_setmethods__["any_attr"] = _zxid.zx_elem_s_any_attr_set
    __swig_getmethods__["any_attr"] = _zxid.zx_elem_s_any_attr_get
    if _newclass:any_attr = property(_zxid.zx_elem_s_any_attr_get, _zxid.zx_elem_s_any_attr_set)
    __swig_setmethods__["any_elem"] = _zxid.zx_elem_s_any_elem_set
    __swig_getmethods__["any_elem"] = _zxid.zx_elem_s_any_elem_get
    if _newclass:any_elem = property(_zxid.zx_elem_s_any_elem_get, _zxid.zx_elem_s_any_elem_set)
    __swig_setmethods__["xmlns"] = _zxid.zx_elem_s_xmlns_set
    __swig_getmethods__["xmlns"] = _zxid.zx_elem_s_xmlns_get
    if _newclass:xmlns = property(_zxid.zx_elem_s_xmlns_get, _zxid.zx_elem_s_xmlns_set)
    __swig_setmethods__["content"] = _zxid.zx_elem_s_content_set
    __swig_getmethods__["content"] = _zxid.zx_elem_s_content_get
    if _newclass:content = property(_zxid.zx_elem_s_content_get, _zxid.zx_elem_s_content_set)
    def __init__(self, *args): 
        this = _zxid.new_zx_elem_s(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _zxid.delete_zx_elem_s
    __del__ = lambda self : None;
zx_elem_s_swigregister = _zxid.zx_elem_s_swigregister
zx_elem_s_swigregister(zx_elem_s)

zx_new_simple_elem = _zxid.zx_new_simple_elem
zx_ref_len_simple_elem = _zxid.zx_ref_len_simple_elem
zx_ref_simple_elem = _zxid.zx_ref_simple_elem
zx_dup_len_simple_elem = _zxid.zx_dup_len_simple_elem
zx_dup_simple_elem = _zxid.zx_dup_simple_elem
class zx_str(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, zx_str, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, zx_str, name)
    __repr__ = _swig_repr
    __swig_setmethods__["g"] = _zxid.zx_str_g_set
    __swig_getmethods__["g"] = _zxid.zx_str_g_get
    if _newclass:g = property(_zxid.zx_str_g_get, _zxid.zx_str_g_set)
    __swig_setmethods__["len"] = _zxid.zx_str_len_set
    __swig_getmethods__["len"] = _zxid.zx_str_len_get
    if _newclass:len = property(_zxid.zx_str_len_get, _zxid.zx_str_len_set)
    __swig_setmethods__["s"] = _zxid.zx_str_s_set
    __swig_getmethods__["s"] = _zxid.zx_str_s_get
    if _newclass:s = property(_zxid.zx_str_s_get, _zxid.zx_str_s_set)
    def __init__(self, *args): 
        this = _zxid.new_zx_str(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _zxid.delete_zx_str
    __del__ = lambda self : None;
zx_str_swigregister = _zxid.zx_str_swigregister
zx_str_swigregister(zx_str)

zx_ref_str = _zxid.zx_ref_str
zx_ref_len_str = _zxid.zx_ref_len_str
zx_new_len_str = _zxid.zx_new_len_str
zx_dup_str = _zxid.zx_dup_str
zx_dup_len_str = _zxid.zx_dup_len_str
zx_alloc_sprintf = _zxid.zx_alloc_sprintf
zx_strf = _zxid.zx_strf
zx_str_free = _zxid.zx_str_free
zx_str_to_c = _zxid.zx_str_to_c
zx_str_conv = _zxid.zx_str_conv
zx_str_ends_in = _zxid.zx_str_ends_in
class zx_any_elem_s(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, zx_any_elem_s, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, zx_any_elem_s, name)
    __repr__ = _swig_repr
    __swig_setmethods__["gg"] = _zxid.zx_any_elem_s_gg_set
    __swig_getmethods__["gg"] = _zxid.zx_any_elem_s_gg_get
    if _newclass:gg = property(_zxid.zx_any_elem_s_gg_get, _zxid.zx_any_elem_s_gg_set)
    __swig_setmethods__["name_len"] = _zxid.zx_any_elem_s_name_len_set
    __swig_getmethods__["name_len"] = _zxid.zx_any_elem_s_name_len_get
    if _newclass:name_len = property(_zxid.zx_any_elem_s_name_len_get, _zxid.zx_any_elem_s_name_len_set)
    __swig_setmethods__["name"] = _zxid.zx_any_elem_s_name_set
    __swig_getmethods__["name"] = _zxid.zx_any_elem_s_name_get
    if _newclass:name = property(_zxid.zx_any_elem_s_name_get, _zxid.zx_any_elem_s_name_set)
    def __init__(self, *args): 
        this = _zxid.new_zx_any_elem_s(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _zxid.delete_zx_any_elem_s
    __del__ = lambda self : None;
zx_any_elem_s_swigregister = _zxid.zx_any_elem_s_swigregister
zx_any_elem_s_swigregister(zx_any_elem_s)

class zx_any_attr_s(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, zx_any_attr_s, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, zx_any_attr_s, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ss"] = _zxid.zx_any_attr_s_ss_set
    __swig_getmethods__["ss"] = _zxid.zx_any_attr_s_ss_get
    if _newclass:ss = property(_zxid.zx_any_attr_s_ss_get, _zxid.zx_any_attr_s_ss_set)
    __swig_setmethods__["name_len"] = _zxid.zx_any_attr_s_name_len_set
    __swig_getmethods__["name_len"] = _zxid.zx_any_attr_s_name_len_get
    if _newclass:name_len = property(_zxid.zx_any_attr_s_name_len_get, _zxid.zx_any_attr_s_name_len_set)
    __swig_setmethods__["name"] = _zxid.zx_any_attr_s_name_set
    __swig_getmethods__["name"] = _zxid.zx_any_attr_s_name_get
    if _newclass:name = property(_zxid.zx_any_attr_s_name_get, _zxid.zx_any_attr_s_name_set)
    def __init__(self, *args): 
        this = _zxid.new_zx_any_attr_s(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _zxid.delete_zx_any_attr_s
    __del__ = lambda self : None;
zx_any_attr_s_swigregister = _zxid.zx_any_attr_s_swigregister
zx_any_attr_s_swigregister(zx_any_attr_s)

zx_memmem = _zxid.zx_memmem
zx_alloc = _zxid.zx_alloc
zx_zalloc = _zxid.zx_zalloc
zx_free = _zxid.zx_free
zx_dup_cstr = _zxid.zx_dup_cstr
zx_reset_ctx = _zxid.zx_reset_ctx
zx_init_ctx = _zxid.zx_init_ctx
ZX_TOK_XMLNS = _zxid.ZX_TOK_XMLNS
ZX_TOK_DATA = _zxid.ZX_TOK_DATA
ZX_TOK_NOT_FOUND = _zxid.ZX_TOK_NOT_FOUND
class zx_tok(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, zx_tok, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, zx_tok, name)
    __repr__ = _swig_repr
    __swig_setmethods__["name"] = _zxid.zx_tok_name_set
    __swig_getmethods__["name"] = _zxid.zx_tok_name_get
    if _newclass:name = property(_zxid.zx_tok_name_get, _zxid.zx_tok_name_set)
    __swig_setmethods__["prefix"] = _zxid.zx_tok_prefix_set
    __swig_getmethods__["prefix"] = _zxid.zx_tok_prefix_get
    if _newclass:prefix = property(_zxid.zx_tok_prefix_get, _zxid.zx_tok_prefix_set)
    __swig_setmethods__["ns"] = _zxid.zx_tok_ns_set
    __swig_getmethods__["ns"] = _zxid.zx_tok_ns_get
    if _newclass:ns = property(_zxid.zx_tok_ns_get, _zxid.zx_tok_ns_set)
    def __init__(self, *args): 
        this = _zxid.new_zx_tok(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _zxid.delete_zx_tok
    __del__ = lambda self : None;
zx_tok_swigregister = _zxid.zx_tok_swigregister
zx_tok_swigregister(zx_tok)

zx_date_time_to_secs = _zxid.zx_date_time_to_secs
write2_or_append_lock_c_path = _zxid.write2_or_append_lock_c_path
zx_report_openssl_error = _zxid.zx_report_openssl_error
zx_fix_any_elem_dec = _zxid.zx_fix_any_elem_dec
zx_locate_ns_by_prefix = _zxid.zx_locate_ns_by_prefix
zx_is_ns_prefix = _zxid.zx_is_ns_prefix
zx_prefix_seen = _zxid.zx_prefix_seen
zx_prefix_seen_whine = _zxid.zx_prefix_seen_whine
zx_scan_xmlns = _zxid.zx_scan_xmlns
zx_pop_seen = _zxid.zx_pop_seen
zx_raw_cipher = _zxid.zx_raw_cipher
zx_rsa_pub_enc = _zxid.zx_rsa_pub_enc
zx_rsa_pub_dec = _zxid.zx_rsa_pub_dec
zx_rsa_priv_dec = _zxid.zx_rsa_priv_dec
zx_rsa_priv_enc = _zxid.zx_rsa_priv_enc
zx_get_rsa_pub_from_cert = _zxid.zx_get_rsa_pub_from_cert
zx_rand = _zxid.zx_rand
zx_tok_by_ns = _zxid.zx_tok_by_ns
zx_len_xmlns_if_not_seen = _zxid.zx_len_xmlns_if_not_seen
zx_enc_xmlns_if_not_seen = _zxid.zx_enc_xmlns_if_not_seen
zx_add_xmlns_if_not_seen = _zxid.zx_add_xmlns_if_not_seen
zx_enc_seen = _zxid.zx_enc_seen
zx_len_so_common = _zxid.zx_len_so_common
zx_len_wo_common = _zxid.zx_len_wo_common
zx_enc_unknown_attrs = _zxid.zx_enc_unknown_attrs
zx_enc_so_unknown_elems_and_content = _zxid.zx_enc_so_unknown_elems_and_content
zx_easy_enc_common = _zxid.zx_easy_enc_common
zx_attr_so_len = _zxid.zx_attr_so_len
zx_attr_so_enc = _zxid.zx_attr_so_enc
zx_attr_wo_len = _zxid.zx_attr_wo_len
zx_attr_wo_enc = _zxid.zx_attr_wo_enc
zx_free_attr = _zxid.zx_free_attr
zx_free_elem_common = _zxid.zx_free_elem_common
zx_free_simple_elems = _zxid.zx_free_simple_elems
zx_prepare_dec_ctx = _zxid.zx_prepare_dec_ctx
zx_scan_data = _zxid.zx_scan_data
zx_scan_pi_or_comment = _zxid.zx_scan_pi_or_comment
zx_dec_unknown_attr = _zxid.zx_dec_unknown_attr
zx_dec_attr_val = _zxid.zx_dec_attr_val
zx_xml_parse_err = _zxid.zx_xml_parse_err
zx_len_inc_ns = _zxid.zx_len_inc_ns
zx_add_inc_ns = _zxid.zx_add_inc_ns
zx_enc_inc_ns = _zxid.zx_enc_inc_ns
SIG_ALGO_RSA_SHA1 = _zxid.SIG_ALGO_RSA_SHA1
SIG_ALGO_DSA_SHA1 = _zxid.SIG_ALGO_DSA_SHA1
SIG_ALGO = _zxid.SIG_ALGO
DIGEST_ALGO = _zxid.DIGEST_ALGO
CANON_ALGO = _zxid.CANON_ALGO
ENVELOPED_ALGO = _zxid.ENVELOPED_ALGO
ENC_ALGO_TRIPLEDES_CBC = _zxid.ENC_ALGO_TRIPLEDES_CBC
ENC_ALGO_AES128_CBC = _zxid.ENC_ALGO_AES128_CBC
ENC_ALGO_AES192_CBC = _zxid.ENC_ALGO_AES192_CBC
ENC_ALGO_AES256_CBC = _zxid.ENC_ALGO_AES256_CBC
ENC_ALGO = _zxid.ENC_ALGO
ENC_KEYTRAN_RSA_1_5 = _zxid.ENC_KEYTRAN_RSA_1_5
ENC_KEYTRAN_RSA_OAEP = _zxid.ENC_KEYTRAN_RSA_OAEP
ENC_KEYTRAN_ALGO = _zxid.ENC_KEYTRAN_ALGO
ENC_ENCKEY_METH = _zxid.ENC_ENCKEY_METH
ENC_TYPE_ELEMENT = _zxid.ENC_TYPE_ELEMENT
ENC_TYPE_CONTENT = _zxid.ENC_TYPE_CONTENT
ZXID_CONF_MAGIC = _zxid.ZXID_CONF_MAGIC
class zxid_conf(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, zxid_conf, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, zxid_conf, name)
    __repr__ = _swig_repr
    __swig_setmethods__["magic"] = _zxid.zxid_conf_magic_set
    __swig_getmethods__["magic"] = _zxid.zxid_conf_magic_get
    if _newclass:magic = property(_zxid.zxid_conf_magic_get, _zxid.zxid_conf_magic_set)
    __swig_setmethods__["ctx"] = _zxid.zxid_conf_ctx_set
    __swig_getmethods__["ctx"] = _zxid.zxid_conf_ctx_get
    if _newclass:ctx = property(_zxid.zxid_conf_ctx_get, _zxid.zxid_conf_ctx_set)
    __swig_setmethods__["cot"] = _zxid.zxid_conf_cot_set
    __swig_getmethods__["cot"] = _zxid.zxid_conf_cot_get
    if _newclass:cot = property(_zxid.zxid_conf_cot_get, _zxid.zxid_conf_cot_set)
    __swig_setmethods__["path_supplied"] = _zxid.zxid_conf_path_supplied_set
    __swig_getmethods__["path_supplied"] = _zxid.zxid_conf_path_supplied_get
    if _newclass:path_supplied = property(_zxid.zxid_conf_path_supplied_get, _zxid.zxid_conf_path_supplied_set)
    __swig_setmethods__["path_len"] = _zxid.zxid_conf_path_len_set
    __swig_getmethods__["path_len"] = _zxid.zxid_conf_path_len_get
    if _newclass:path_len = property(_zxid.zxid_conf_path_len_get, _zxid.zxid_conf_path_len_set)
    __swig_setmethods__["path"] = _zxid.zxid_conf_path_set
    __swig_getmethods__["path"] = _zxid.zxid_conf_path_get
    if _newclass:path = property(_zxid.zxid_conf_path_get, _zxid.zxid_conf_path_set)
    __swig_setmethods__["url"] = _zxid.zxid_conf_url_set
    __swig_getmethods__["url"] = _zxid.zxid_conf_url_get
    if _newclass:url = property(_zxid.zxid_conf_url_get, _zxid.zxid_conf_url_set)
    __swig_setmethods__["non_standard_entityid"] = _zxid.zxid_conf_non_standard_entityid_set
    __swig_getmethods__["non_standard_entityid"] = _zxid.zxid_conf_non_standard_entityid_get
    if _newclass:non_standard_entityid = property(_zxid.zxid_conf_non_standard_entityid_get, _zxid.zxid_conf_non_standard_entityid_set)
    __swig_setmethods__["cdc_url"] = _zxid.zxid_conf_cdc_url_set
    __swig_getmethods__["cdc_url"] = _zxid.zxid_conf_cdc_url_get
    if _newclass:cdc_url = property(_zxid.zxid_conf_cdc_url_get, _zxid.zxid_conf_cdc_url_set)
    __swig_setmethods__["cdc_choice"] = _zxid.zxid_conf_cdc_choice_set
    __swig_getmethods__["cdc_choice"] = _zxid.zxid_conf_cdc_choice_get
    if _newclass:cdc_choice = property(_zxid.zxid_conf_cdc_choice_get, _zxid.zxid_conf_cdc_choice_set)
    __swig_setmethods__["md_fetch"] = _zxid.zxid_conf_md_fetch_set
    __swig_getmethods__["md_fetch"] = _zxid.zxid_conf_md_fetch_get
    if _newclass:md_fetch = property(_zxid.zxid_conf_md_fetch_get, _zxid.zxid_conf_md_fetch_set)
    __swig_setmethods__["md_populate_cache"] = _zxid.zxid_conf_md_populate_cache_set
    __swig_getmethods__["md_populate_cache"] = _zxid.zxid_conf_md_populate_cache_get
    if _newclass:md_populate_cache = property(_zxid.zxid_conf_md_populate_cache_get, _zxid.zxid_conf_md_populate_cache_set)
    __swig_setmethods__["md_cache_first"] = _zxid.zxid_conf_md_cache_first_set
    __swig_getmethods__["md_cache_first"] = _zxid.zxid_conf_md_cache_first_get
    if _newclass:md_cache_first = property(_zxid.zxid_conf_md_cache_first_get, _zxid.zxid_conf_md_cache_first_set)
    __swig_setmethods__["md_cache_last"] = _zxid.zxid_conf_md_cache_last_set
    __swig_getmethods__["md_cache_last"] = _zxid.zxid_conf_md_cache_last_get
    if _newclass:md_cache_last = property(_zxid.zxid_conf_md_cache_last_get, _zxid.zxid_conf_md_cache_last_set)
    __swig_setmethods__["user_local"] = _zxid.zxid_conf_user_local_set
    __swig_getmethods__["user_local"] = _zxid.zxid_conf_user_local_get
    if _newclass:user_local = property(_zxid.zxid_conf_user_local_get, _zxid.zxid_conf_user_local_set)
    __swig_setmethods__["authn_req_sign"] = _zxid.zxid_conf_authn_req_sign_set
    __swig_getmethods__["authn_req_sign"] = _zxid.zxid_conf_authn_req_sign_get
    if _newclass:authn_req_sign = property(_zxid.zxid_conf_authn_req_sign_get, _zxid.zxid_conf_authn_req_sign_set)
    __swig_setmethods__["want_sso_a7n_signed"] = _zxid.zxid_conf_want_sso_a7n_signed_set
    __swig_getmethods__["want_sso_a7n_signed"] = _zxid.zxid_conf_want_sso_a7n_signed_get
    if _newclass:want_sso_a7n_signed = property(_zxid.zxid_conf_want_sso_a7n_signed_get, _zxid.zxid_conf_want_sso_a7n_signed_set)
    __swig_setmethods__["sso_soap_sign"] = _zxid.zxid_conf_sso_soap_sign_set
    __swig_getmethods__["sso_soap_sign"] = _zxid.zxid_conf_sso_soap_sign_get
    if _newclass:sso_soap_sign = property(_zxid.zxid_conf_sso_soap_sign_get, _zxid.zxid_conf_sso_soap_sign_set)
    __swig_setmethods__["sso_soap_resp_sign"] = _zxid.zxid_conf_sso_soap_resp_sign_set
    __swig_getmethods__["sso_soap_resp_sign"] = _zxid.zxid_conf_sso_soap_resp_sign_get
    if _newclass:sso_soap_resp_sign = property(_zxid.zxid_conf_sso_soap_resp_sign_get, _zxid.zxid_conf_sso_soap_resp_sign_set)
    __swig_setmethods__["nameid_enc"] = _zxid.zxid_conf_nameid_enc_set
    __swig_getmethods__["nameid_enc"] = _zxid.zxid_conf_nameid_enc_get
    if _newclass:nameid_enc = property(_zxid.zxid_conf_nameid_enc_get, _zxid.zxid_conf_nameid_enc_set)
    __swig_setmethods__["affiliation"] = _zxid.zxid_conf_affiliation_set
    __swig_getmethods__["affiliation"] = _zxid.zxid_conf_affiliation_get
    if _newclass:affiliation = property(_zxid.zxid_conf_affiliation_get, _zxid.zxid_conf_affiliation_set)
    __swig_setmethods__["nice_name"] = _zxid.zxid_conf_nice_name_set
    __swig_getmethods__["nice_name"] = _zxid.zxid_conf_nice_name_get
    if _newclass:nice_name = property(_zxid.zxid_conf_nice_name_get, _zxid.zxid_conf_nice_name_set)
    __swig_setmethods__["ses_arch_dir"] = _zxid.zxid_conf_ses_arch_dir_set
    __swig_getmethods__["ses_arch_dir"] = _zxid.zxid_conf_ses_arch_dir_get
    if _newclass:ses_arch_dir = property(_zxid.zxid_conf_ses_arch_dir_get, _zxid.zxid_conf_ses_arch_dir_set)
    __swig_setmethods__["ses_cookie_name"] = _zxid.zxid_conf_ses_cookie_name_set
    __swig_getmethods__["ses_cookie_name"] = _zxid.zxid_conf_ses_cookie_name_get
    if _newclass:ses_cookie_name = property(_zxid.zxid_conf_ses_cookie_name_get, _zxid.zxid_conf_ses_cookie_name_set)
    __swig_setmethods__["ipport"] = _zxid.zxid_conf_ipport_set
    __swig_getmethods__["ipport"] = _zxid.zxid_conf_ipport_get
    if _newclass:ipport = property(_zxid.zxid_conf_ipport_get, _zxid.zxid_conf_ipport_set)
    __swig_setmethods__["log_err"] = _zxid.zxid_conf_log_err_set
    __swig_getmethods__["log_err"] = _zxid.zxid_conf_log_err_get
    if _newclass:log_err = property(_zxid.zxid_conf_log_err_get, _zxid.zxid_conf_log_err_set)
    __swig_setmethods__["log_act"] = _zxid.zxid_conf_log_act_set
    __swig_getmethods__["log_act"] = _zxid.zxid_conf_log_act_get
    if _newclass:log_act = property(_zxid.zxid_conf_log_act_get, _zxid.zxid_conf_log_act_set)
    __swig_setmethods__["log_issue_a7n"] = _zxid.zxid_conf_log_issue_a7n_set
    __swig_getmethods__["log_issue_a7n"] = _zxid.zxid_conf_log_issue_a7n_get
    if _newclass:log_issue_a7n = property(_zxid.zxid_conf_log_issue_a7n_get, _zxid.zxid_conf_log_issue_a7n_set)
    __swig_setmethods__["log_issue_msg"] = _zxid.zxid_conf_log_issue_msg_set
    __swig_getmethods__["log_issue_msg"] = _zxid.zxid_conf_log_issue_msg_get
    if _newclass:log_issue_msg = property(_zxid.zxid_conf_log_issue_msg_get, _zxid.zxid_conf_log_issue_msg_set)
    __swig_setmethods__["log_rely_a7n"] = _zxid.zxid_conf_log_rely_a7n_set
    __swig_getmethods__["log_rely_a7n"] = _zxid.zxid_conf_log_rely_a7n_get
    if _newclass:log_rely_a7n = property(_zxid.zxid_conf_log_rely_a7n_get, _zxid.zxid_conf_log_rely_a7n_set)
    __swig_setmethods__["log_rely_msg"] = _zxid.zxid_conf_log_rely_msg_set
    __swig_getmethods__["log_rely_msg"] = _zxid.zxid_conf_log_rely_msg_get
    if _newclass:log_rely_msg = property(_zxid.zxid_conf_log_rely_msg_get, _zxid.zxid_conf_log_rely_msg_set)
    __swig_setmethods__["log_err_in_act"] = _zxid.zxid_conf_log_err_in_act_set
    __swig_getmethods__["log_err_in_act"] = _zxid.zxid_conf_log_err_in_act_get
    if _newclass:log_err_in_act = property(_zxid.zxid_conf_log_err_in_act_get, _zxid.zxid_conf_log_err_in_act_set)
    __swig_setmethods__["log_sigfail_is_err"] = _zxid.zxid_conf_log_sigfail_is_err_set
    __swig_getmethods__["log_sigfail_is_err"] = _zxid.zxid_conf_log_sigfail_is_err_get
    if _newclass:log_sigfail_is_err = property(_zxid.zxid_conf_log_sigfail_is_err_get, _zxid.zxid_conf_log_sigfail_is_err_set)
    __swig_setmethods__["log_level"] = _zxid.zxid_conf_log_level_set
    __swig_getmethods__["log_level"] = _zxid.zxid_conf_log_level_get
    if _newclass:log_level = property(_zxid.zxid_conf_log_level_get, _zxid.zxid_conf_log_level_set)
    __swig_setmethods__["sig_fatal"] = _zxid.zxid_conf_sig_fatal_set
    __swig_getmethods__["sig_fatal"] = _zxid.zxid_conf_sig_fatal_get
    if _newclass:sig_fatal = property(_zxid.zxid_conf_sig_fatal_get, _zxid.zxid_conf_sig_fatal_set)
    __swig_setmethods__["nosig_fatal"] = _zxid.zxid_conf_nosig_fatal_set
    __swig_getmethods__["nosig_fatal"] = _zxid.zxid_conf_nosig_fatal_get
    if _newclass:nosig_fatal = property(_zxid.zxid_conf_nosig_fatal_get, _zxid.zxid_conf_nosig_fatal_set)
    __swig_setmethods__["timeout_fatal"] = _zxid.zxid_conf_timeout_fatal_set
    __swig_getmethods__["timeout_fatal"] = _zxid.zxid_conf_timeout_fatal_get
    if _newclass:timeout_fatal = property(_zxid.zxid_conf_timeout_fatal_get, _zxid.zxid_conf_timeout_fatal_set)
    __swig_setmethods__["audience_fatal"] = _zxid.zxid_conf_audience_fatal_set
    __swig_getmethods__["audience_fatal"] = _zxid.zxid_conf_audience_fatal_get
    if _newclass:audience_fatal = property(_zxid.zxid_conf_audience_fatal_get, _zxid.zxid_conf_audience_fatal_set)
    __swig_setmethods__["dup_a7n_fatal"] = _zxid.zxid_conf_dup_a7n_fatal_set
    __swig_getmethods__["dup_a7n_fatal"] = _zxid.zxid_conf_dup_a7n_fatal_get
    if _newclass:dup_a7n_fatal = property(_zxid.zxid_conf_dup_a7n_fatal_get, _zxid.zxid_conf_dup_a7n_fatal_set)
    __swig_setmethods__["dup_msg_fatal"] = _zxid.zxid_conf_dup_msg_fatal_set
    __swig_getmethods__["dup_msg_fatal"] = _zxid.zxid_conf_dup_msg_fatal_get
    if _newclass:dup_msg_fatal = property(_zxid.zxid_conf_dup_msg_fatal_get, _zxid.zxid_conf_dup_msg_fatal_set)
    __swig_setmethods__["before_slop"] = _zxid.zxid_conf_before_slop_set
    __swig_getmethods__["before_slop"] = _zxid.zxid_conf_before_slop_get
    if _newclass:before_slop = property(_zxid.zxid_conf_before_slop_get, _zxid.zxid_conf_before_slop_set)
    __swig_setmethods__["after_slop"] = _zxid.zxid_conf_after_slop_set
    __swig_getmethods__["after_slop"] = _zxid.zxid_conf_after_slop_get
    if _newclass:after_slop = property(_zxid.zxid_conf_after_slop_get, _zxid.zxid_conf_after_slop_set)
    __swig_setmethods__["timeskew"] = _zxid.zxid_conf_timeskew_set
    __swig_getmethods__["timeskew"] = _zxid.zxid_conf_timeskew_get
    if _newclass:timeskew = property(_zxid.zxid_conf_timeskew_get, _zxid.zxid_conf_timeskew_set)
    __swig_setmethods__["redir_to_content"] = _zxid.zxid_conf_redir_to_content_set
    __swig_getmethods__["redir_to_content"] = _zxid.zxid_conf_redir_to_content_get
    if _newclass:redir_to_content = property(_zxid.zxid_conf_redir_to_content_get, _zxid.zxid_conf_redir_to_content_set)
    __swig_setmethods__["max_soap_retry"] = _zxid.zxid_conf_max_soap_retry_set
    __swig_getmethods__["max_soap_retry"] = _zxid.zxid_conf_max_soap_retry_get
    if _newclass:max_soap_retry = property(_zxid.zxid_conf_max_soap_retry_get, _zxid.zxid_conf_max_soap_retry_set)
    __swig_setmethods__["defaultqs"] = _zxid.zxid_conf_defaultqs_set
    __swig_getmethods__["defaultqs"] = _zxid.zxid_conf_defaultqs_get
    if _newclass:defaultqs = property(_zxid.zxid_conf_defaultqs_get, _zxid.zxid_conf_defaultqs_set)
    __swig_setmethods__["mod_saml_attr_prefix"] = _zxid.zxid_conf_mod_saml_attr_prefix_set
    __swig_getmethods__["mod_saml_attr_prefix"] = _zxid.zxid_conf_mod_saml_attr_prefix_get
    if _newclass:mod_saml_attr_prefix = property(_zxid.zxid_conf_mod_saml_attr_prefix_get, _zxid.zxid_conf_mod_saml_attr_prefix_set)
    __swig_setmethods__["idp_sel_start"] = _zxid.zxid_conf_idp_sel_start_set
    __swig_getmethods__["idp_sel_start"] = _zxid.zxid_conf_idp_sel_start_get
    if _newclass:idp_sel_start = property(_zxid.zxid_conf_idp_sel_start_get, _zxid.zxid_conf_idp_sel_start_set)
    __swig_setmethods__["idp_sel_new_idp"] = _zxid.zxid_conf_idp_sel_new_idp_set
    __swig_getmethods__["idp_sel_new_idp"] = _zxid.zxid_conf_idp_sel_new_idp_get
    if _newclass:idp_sel_new_idp = property(_zxid.zxid_conf_idp_sel_new_idp_get, _zxid.zxid_conf_idp_sel_new_idp_set)
    __swig_setmethods__["idp_sel_our_eid"] = _zxid.zxid_conf_idp_sel_our_eid_set
    __swig_getmethods__["idp_sel_our_eid"] = _zxid.zxid_conf_idp_sel_our_eid_get
    if _newclass:idp_sel_our_eid = property(_zxid.zxid_conf_idp_sel_our_eid_get, _zxid.zxid_conf_idp_sel_our_eid_set)
    __swig_setmethods__["idp_sel_tech_user"] = _zxid.zxid_conf_idp_sel_tech_user_set
    __swig_getmethods__["idp_sel_tech_user"] = _zxid.zxid_conf_idp_sel_tech_user_get
    if _newclass:idp_sel_tech_user = property(_zxid.zxid_conf_idp_sel_tech_user_get, _zxid.zxid_conf_idp_sel_tech_user_set)
    __swig_setmethods__["idp_sel_tech_site"] = _zxid.zxid_conf_idp_sel_tech_site_set
    __swig_getmethods__["idp_sel_tech_site"] = _zxid.zxid_conf_idp_sel_tech_site_get
    if _newclass:idp_sel_tech_site = property(_zxid.zxid_conf_idp_sel_tech_site_get, _zxid.zxid_conf_idp_sel_tech_site_set)
    __swig_setmethods__["idp_sel_footer"] = _zxid.zxid_conf_idp_sel_footer_set
    __swig_getmethods__["idp_sel_footer"] = _zxid.zxid_conf_idp_sel_footer_get
    if _newclass:idp_sel_footer = property(_zxid.zxid_conf_idp_sel_footer_get, _zxid.zxid_conf_idp_sel_footer_set)
    __swig_setmethods__["idp_sel_end"] = _zxid.zxid_conf_idp_sel_end_set
    __swig_getmethods__["idp_sel_end"] = _zxid.zxid_conf_idp_sel_end_get
    if _newclass:idp_sel_end = property(_zxid.zxid_conf_idp_sel_end_get, _zxid.zxid_conf_idp_sel_end_set)
    __swig_setmethods__["mgmt_start"] = _zxid.zxid_conf_mgmt_start_set
    __swig_getmethods__["mgmt_start"] = _zxid.zxid_conf_mgmt_start_get
    if _newclass:mgmt_start = property(_zxid.zxid_conf_mgmt_start_get, _zxid.zxid_conf_mgmt_start_set)
    __swig_setmethods__["mgmt_logout"] = _zxid.zxid_conf_mgmt_logout_set
    __swig_getmethods__["mgmt_logout"] = _zxid.zxid_conf_mgmt_logout_get
    if _newclass:mgmt_logout = property(_zxid.zxid_conf_mgmt_logout_get, _zxid.zxid_conf_mgmt_logout_set)
    __swig_setmethods__["mgmt_defed"] = _zxid.zxid_conf_mgmt_defed_set
    __swig_getmethods__["mgmt_defed"] = _zxid.zxid_conf_mgmt_defed_get
    if _newclass:mgmt_defed = property(_zxid.zxid_conf_mgmt_defed_get, _zxid.zxid_conf_mgmt_defed_set)
    __swig_setmethods__["mgmt_footer"] = _zxid.zxid_conf_mgmt_footer_set
    __swig_getmethods__["mgmt_footer"] = _zxid.zxid_conf_mgmt_footer_get
    if _newclass:mgmt_footer = property(_zxid.zxid_conf_mgmt_footer_get, _zxid.zxid_conf_mgmt_footer_set)
    __swig_setmethods__["mgmt_end"] = _zxid.zxid_conf_mgmt_end_set
    __swig_getmethods__["mgmt_end"] = _zxid.zxid_conf_mgmt_end_get
    if _newclass:mgmt_end = property(_zxid.zxid_conf_mgmt_end_get, _zxid.zxid_conf_mgmt_end_set)
    __swig_setmethods__["dbg"] = _zxid.zxid_conf_dbg_set
    __swig_getmethods__["dbg"] = _zxid.zxid_conf_dbg_get
    if _newclass:dbg = property(_zxid.zxid_conf_dbg_get, _zxid.zxid_conf_dbg_set)
    def __init__(self, *args): 
        this = _zxid.new_zxid_conf(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _zxid.delete_zxid_conf
    __del__ = lambda self : None;
zxid_conf_swigregister = _zxid.zxid_conf_swigregister
zxid_conf_swigregister(zxid_conf)

ZXID_CGI_MAGIC = _zxid.ZXID_CGI_MAGIC
class zxid_cgi(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, zxid_cgi, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, zxid_cgi, name)
    __repr__ = _swig_repr
    __swig_setmethods__["magic"] = _zxid.zxid_cgi_magic_set
    __swig_getmethods__["magic"] = _zxid.zxid_cgi_magic_get
    if _newclass:magic = property(_zxid.zxid_cgi_magic_get, _zxid.zxid_cgi_magic_set)
    __swig_setmethods__["op"] = _zxid.zxid_cgi_op_set
    __swig_getmethods__["op"] = _zxid.zxid_cgi_op_get
    if _newclass:op = property(_zxid.zxid_cgi_op_get, _zxid.zxid_cgi_op_set)
    __swig_setmethods__["pr_ix"] = _zxid.zxid_cgi_pr_ix_set
    __swig_getmethods__["pr_ix"] = _zxid.zxid_cgi_pr_ix_get
    if _newclass:pr_ix = property(_zxid.zxid_cgi_pr_ix_get, _zxid.zxid_cgi_pr_ix_set)
    __swig_setmethods__["allow_create"] = _zxid.zxid_cgi_allow_create_set
    __swig_getmethods__["allow_create"] = _zxid.zxid_cgi_allow_create_get
    if _newclass:allow_create = property(_zxid.zxid_cgi_allow_create_get, _zxid.zxid_cgi_allow_create_set)
    __swig_setmethods__["ispassive"] = _zxid.zxid_cgi_ispassive_set
    __swig_getmethods__["ispassive"] = _zxid.zxid_cgi_ispassive_get
    if _newclass:ispassive = property(_zxid.zxid_cgi_ispassive_get, _zxid.zxid_cgi_ispassive_set)
    __swig_setmethods__["force_authn"] = _zxid.zxid_cgi_force_authn_set
    __swig_getmethods__["force_authn"] = _zxid.zxid_cgi_force_authn_get
    if _newclass:force_authn = property(_zxid.zxid_cgi_force_authn_get, _zxid.zxid_cgi_force_authn_set)
    __swig_setmethods__["enc_hint"] = _zxid.zxid_cgi_enc_hint_set
    __swig_getmethods__["enc_hint"] = _zxid.zxid_cgi_enc_hint_get
    if _newclass:enc_hint = property(_zxid.zxid_cgi_enc_hint_get, _zxid.zxid_cgi_enc_hint_set)
    __swig_setmethods__["sid"] = _zxid.zxid_cgi_sid_set
    __swig_getmethods__["sid"] = _zxid.zxid_cgi_sid_get
    if _newclass:sid = property(_zxid.zxid_cgi_sid_get, _zxid.zxid_cgi_sid_set)
    __swig_setmethods__["nid"] = _zxid.zxid_cgi_nid_set
    __swig_getmethods__["nid"] = _zxid.zxid_cgi_nid_get
    if _newclass:nid = property(_zxid.zxid_cgi_nid_get, _zxid.zxid_cgi_nid_set)
    __swig_setmethods__["user"] = _zxid.zxid_cgi_user_set
    __swig_getmethods__["user"] = _zxid.zxid_cgi_user_get
    if _newclass:user = property(_zxid.zxid_cgi_user_get, _zxid.zxid_cgi_user_set)
    __swig_setmethods__["pw"] = _zxid.zxid_cgi_pw_set
    __swig_getmethods__["pw"] = _zxid.zxid_cgi_pw_get
    if _newclass:pw = property(_zxid.zxid_cgi_pw_get, _zxid.zxid_cgi_pw_set)
    __swig_setmethods__["cdc"] = _zxid.zxid_cgi_cdc_set
    __swig_getmethods__["cdc"] = _zxid.zxid_cgi_cdc_get
    if _newclass:cdc = property(_zxid.zxid_cgi_cdc_get, _zxid.zxid_cgi_cdc_set)
    __swig_setmethods__["eid"] = _zxid.zxid_cgi_eid_set
    __swig_getmethods__["eid"] = _zxid.zxid_cgi_eid_get
    if _newclass:eid = property(_zxid.zxid_cgi_eid_get, _zxid.zxid_cgi_eid_set)
    __swig_setmethods__["nid_fmt"] = _zxid.zxid_cgi_nid_fmt_set
    __swig_getmethods__["nid_fmt"] = _zxid.zxid_cgi_nid_fmt_get
    if _newclass:nid_fmt = property(_zxid.zxid_cgi_nid_fmt_get, _zxid.zxid_cgi_nid_fmt_set)
    __swig_setmethods__["affil"] = _zxid.zxid_cgi_affil_set
    __swig_getmethods__["affil"] = _zxid.zxid_cgi_affil_get
    if _newclass:affil = property(_zxid.zxid_cgi_affil_get, _zxid.zxid_cgi_affil_set)
    __swig_setmethods__["consent"] = _zxid.zxid_cgi_consent_set
    __swig_getmethods__["consent"] = _zxid.zxid_cgi_consent_get
    if _newclass:consent = property(_zxid.zxid_cgi_consent_get, _zxid.zxid_cgi_consent_set)
    __swig_setmethods__["matching_rule"] = _zxid.zxid_cgi_matching_rule_set
    __swig_getmethods__["matching_rule"] = _zxid.zxid_cgi_matching_rule_get
    if _newclass:matching_rule = property(_zxid.zxid_cgi_matching_rule_get, _zxid.zxid_cgi_matching_rule_set)
    __swig_setmethods__["authn_ctx"] = _zxid.zxid_cgi_authn_ctx_set
    __swig_getmethods__["authn_ctx"] = _zxid.zxid_cgi_authn_ctx_get
    if _newclass:authn_ctx = property(_zxid.zxid_cgi_authn_ctx_get, _zxid.zxid_cgi_authn_ctx_set)
    __swig_setmethods__["pxy_count"] = _zxid.zxid_cgi_pxy_count_set
    __swig_getmethods__["pxy_count"] = _zxid.zxid_cgi_pxy_count_get
    if _newclass:pxy_count = property(_zxid.zxid_cgi_pxy_count_get, _zxid.zxid_cgi_pxy_count_set)
    __swig_setmethods__["get_complete"] = _zxid.zxid_cgi_get_complete_set
    __swig_getmethods__["get_complete"] = _zxid.zxid_cgi_get_complete_get
    if _newclass:get_complete = property(_zxid.zxid_cgi_get_complete_get, _zxid.zxid_cgi_get_complete_set)
    __swig_setmethods__["idppxylist"] = _zxid.zxid_cgi_idppxylist_set
    __swig_getmethods__["idppxylist"] = _zxid.zxid_cgi_idppxylist_get
    if _newclass:idppxylist = property(_zxid.zxid_cgi_idppxylist_get, _zxid.zxid_cgi_idppxylist_set)
    __swig_setmethods__["rs"] = _zxid.zxid_cgi_rs_set
    __swig_getmethods__["rs"] = _zxid.zxid_cgi_rs_get
    if _newclass:rs = property(_zxid.zxid_cgi_rs_get, _zxid.zxid_cgi_rs_set)
    __swig_setmethods__["newnym"] = _zxid.zxid_cgi_newnym_set
    __swig_getmethods__["newnym"] = _zxid.zxid_cgi_newnym_get
    if _newclass:newnym = property(_zxid.zxid_cgi_newnym_get, _zxid.zxid_cgi_newnym_set)
    __swig_setmethods__["saml_art"] = _zxid.zxid_cgi_saml_art_set
    __swig_getmethods__["saml_art"] = _zxid.zxid_cgi_saml_art_get
    if _newclass:saml_art = property(_zxid.zxid_cgi_saml_art_get, _zxid.zxid_cgi_saml_art_set)
    __swig_setmethods__["saml_resp"] = _zxid.zxid_cgi_saml_resp_set
    __swig_getmethods__["saml_resp"] = _zxid.zxid_cgi_saml_resp_get
    if _newclass:saml_resp = property(_zxid.zxid_cgi_saml_resp_get, _zxid.zxid_cgi_saml_resp_set)
    __swig_setmethods__["saml_req"] = _zxid.zxid_cgi_saml_req_set
    __swig_getmethods__["saml_req"] = _zxid.zxid_cgi_saml_req_get
    if _newclass:saml_req = property(_zxid.zxid_cgi_saml_req_get, _zxid.zxid_cgi_saml_req_set)
    __swig_setmethods__["sigalg"] = _zxid.zxid_cgi_sigalg_set
    __swig_getmethods__["sigalg"] = _zxid.zxid_cgi_sigalg_get
    if _newclass:sigalg = property(_zxid.zxid_cgi_sigalg_get, _zxid.zxid_cgi_sigalg_set)
    __swig_setmethods__["sig"] = _zxid.zxid_cgi_sig_set
    __swig_getmethods__["sig"] = _zxid.zxid_cgi_sig_get
    if _newclass:sig = property(_zxid.zxid_cgi_sig_get, _zxid.zxid_cgi_sig_set)
    __swig_setmethods__["sigval"] = _zxid.zxid_cgi_sigval_set
    __swig_getmethods__["sigval"] = _zxid.zxid_cgi_sigval_get
    if _newclass:sigval = property(_zxid.zxid_cgi_sigval_get, _zxid.zxid_cgi_sigval_set)
    __swig_setmethods__["sigmsg"] = _zxid.zxid_cgi_sigmsg_set
    __swig_getmethods__["sigmsg"] = _zxid.zxid_cgi_sigmsg_get
    if _newclass:sigmsg = property(_zxid.zxid_cgi_sigmsg_get, _zxid.zxid_cgi_sigmsg_set)
    __swig_setmethods__["err"] = _zxid.zxid_cgi_err_set
    __swig_getmethods__["err"] = _zxid.zxid_cgi_err_get
    if _newclass:err = property(_zxid.zxid_cgi_err_get, _zxid.zxid_cgi_err_set)
    __swig_setmethods__["msg"] = _zxid.zxid_cgi_msg_set
    __swig_getmethods__["msg"] = _zxid.zxid_cgi_msg_get
    if _newclass:msg = property(_zxid.zxid_cgi_msg_get, _zxid.zxid_cgi_msg_set)
    __swig_setmethods__["dbg"] = _zxid.zxid_cgi_dbg_set
    __swig_getmethods__["dbg"] = _zxid.zxid_cgi_dbg_get
    if _newclass:dbg = property(_zxid.zxid_cgi_dbg_get, _zxid.zxid_cgi_dbg_set)
    __swig_setmethods__["idp_list"] = _zxid.zxid_cgi_idp_list_set
    __swig_getmethods__["idp_list"] = _zxid.zxid_cgi_idp_list_get
    if _newclass:idp_list = property(_zxid.zxid_cgi_idp_list_get, _zxid.zxid_cgi_idp_list_set)
    def __init__(self, *args): 
        this = _zxid.new_zxid_cgi(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _zxid.delete_zxid_cgi
    __del__ = lambda self : None;
zxid_cgi_swigregister = _zxid.zxid_cgi_swigregister
zxid_cgi_swigregister(zxid_cgi)

ZXID_SES_MAGIC = _zxid.ZXID_SES_MAGIC
class zxid_ses(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, zxid_ses, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, zxid_ses, name)
    __repr__ = _swig_repr
    __swig_setmethods__["magic"] = _zxid.zxid_ses_magic_set
    __swig_getmethods__["magic"] = _zxid.zxid_ses_magic_get
    if _newclass:magic = property(_zxid.zxid_ses_magic_get, _zxid.zxid_ses_magic_set)
    __swig_setmethods__["sid"] = _zxid.zxid_ses_sid_set
    __swig_getmethods__["sid"] = _zxid.zxid_ses_sid_get
    if _newclass:sid = property(_zxid.zxid_ses_sid_get, _zxid.zxid_ses_sid_set)
    __swig_setmethods__["nid"] = _zxid.zxid_ses_nid_set
    __swig_getmethods__["nid"] = _zxid.zxid_ses_nid_get
    if _newclass:nid = property(_zxid.zxid_ses_nid_get, _zxid.zxid_ses_nid_set)
    __swig_setmethods__["sesix"] = _zxid.zxid_ses_sesix_set
    __swig_getmethods__["sesix"] = _zxid.zxid_ses_sesix_get
    if _newclass:sesix = property(_zxid.zxid_ses_sesix_get, _zxid.zxid_ses_sesix_set)
    __swig_setmethods__["nidfmt"] = _zxid.zxid_ses_nidfmt_set
    __swig_getmethods__["nidfmt"] = _zxid.zxid_ses_nidfmt_get
    if _newclass:nidfmt = property(_zxid.zxid_ses_nidfmt_get, _zxid.zxid_ses_nidfmt_set)
    __swig_setmethods__["sigres"] = _zxid.zxid_ses_sigres_set
    __swig_getmethods__["sigres"] = _zxid.zxid_ses_sigres_get
    if _newclass:sigres = property(_zxid.zxid_ses_sigres_get, _zxid.zxid_ses_sigres_set)
    __swig_setmethods__["pad2"] = _zxid.zxid_ses_pad2_set
    __swig_getmethods__["pad2"] = _zxid.zxid_ses_pad2_get
    if _newclass:pad2 = property(_zxid.zxid_ses_pad2_get, _zxid.zxid_ses_pad2_set)
    __swig_setmethods__["pad3"] = _zxid.zxid_ses_pad3_set
    __swig_getmethods__["pad3"] = _zxid.zxid_ses_pad3_get
    if _newclass:pad3 = property(_zxid.zxid_ses_pad3_get, _zxid.zxid_ses_pad3_set)
    __swig_setmethods__["sso_a7n_path"] = _zxid.zxid_ses_sso_a7n_path_set
    __swig_getmethods__["sso_a7n_path"] = _zxid.zxid_ses_sso_a7n_path_get
    if _newclass:sso_a7n_path = property(_zxid.zxid_ses_sso_a7n_path_get, _zxid.zxid_ses_sso_a7n_path_set)
    __swig_setmethods__["setcookie"] = _zxid.zxid_ses_setcookie_set
    __swig_getmethods__["setcookie"] = _zxid.zxid_ses_setcookie_get
    if _newclass:setcookie = property(_zxid.zxid_ses_setcookie_get, _zxid.zxid_ses_setcookie_set)
    __swig_setmethods__["cookie"] = _zxid.zxid_ses_cookie_set
    __swig_getmethods__["cookie"] = _zxid.zxid_ses_cookie_get
    if _newclass:cookie = property(_zxid.zxid_ses_cookie_get, _zxid.zxid_ses_cookie_set)
    __swig_setmethods__["rs"] = _zxid.zxid_ses_rs_set
    __swig_getmethods__["rs"] = _zxid.zxid_ses_rs_get
    if _newclass:rs = property(_zxid.zxid_ses_rs_get, _zxid.zxid_ses_rs_set)
    __swig_setmethods__["nameid"] = _zxid.zxid_ses_nameid_set
    __swig_getmethods__["nameid"] = _zxid.zxid_ses_nameid_get
    if _newclass:nameid = property(_zxid.zxid_ses_nameid_get, _zxid.zxid_ses_nameid_set)
    __swig_setmethods__["a7n"] = _zxid.zxid_ses_a7n_set
    __swig_getmethods__["a7n"] = _zxid.zxid_ses_a7n_get
    if _newclass:a7n = property(_zxid.zxid_ses_a7n_get, _zxid.zxid_ses_a7n_set)
    __swig_setmethods__["a7n11"] = _zxid.zxid_ses_a7n11_set
    __swig_getmethods__["a7n11"] = _zxid.zxid_ses_a7n11_get
    if _newclass:a7n11 = property(_zxid.zxid_ses_a7n11_get, _zxid.zxid_ses_a7n11_set)
    __swig_setmethods__["a7n12"] = _zxid.zxid_ses_a7n12_set
    __swig_getmethods__["a7n12"] = _zxid.zxid_ses_a7n12_get
    if _newclass:a7n12 = property(_zxid.zxid_ses_a7n12_get, _zxid.zxid_ses_a7n12_set)
    __swig_setmethods__["sesbuf"] = _zxid.zxid_ses_sesbuf_set
    __swig_getmethods__["sesbuf"] = _zxid.zxid_ses_sesbuf_get
    if _newclass:sesbuf = property(_zxid.zxid_ses_sesbuf_get, _zxid.zxid_ses_sesbuf_set)
    __swig_setmethods__["sso_a7n_buf"] = _zxid.zxid_ses_sso_a7n_buf_set
    __swig_getmethods__["sso_a7n_buf"] = _zxid.zxid_ses_sso_a7n_buf_get
    if _newclass:sso_a7n_buf = property(_zxid.zxid_ses_sso_a7n_buf_get, _zxid.zxid_ses_sso_a7n_buf_set)
    def __init__(self, *args): 
        this = _zxid.new_zxid_ses(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _zxid.delete_zxid_ses
    __del__ = lambda self : None;
zxid_ses_swigregister = _zxid.zxid_ses_swigregister
zxid_ses_swigregister(zxid_ses)

ZXID_SES_DIR = _zxid.ZXID_SES_DIR
ZXID_USER_DIR = _zxid.ZXID_USER_DIR
class zxid_entity(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, zxid_entity, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, zxid_entity, name)
    __repr__ = _swig_repr
    __swig_setmethods__["n"] = _zxid.zxid_entity_n_set
    __swig_getmethods__["n"] = _zxid.zxid_entity_n_get
    if _newclass:n = property(_zxid.zxid_entity_n_get, _zxid.zxid_entity_n_set)
    __swig_setmethods__["n_cdc"] = _zxid.zxid_entity_n_cdc_set
    __swig_getmethods__["n_cdc"] = _zxid.zxid_entity_n_cdc_get
    if _newclass:n_cdc = property(_zxid.zxid_entity_n_cdc_get, _zxid.zxid_entity_n_cdc_set)
    __swig_setmethods__["eid_len"] = _zxid.zxid_entity_eid_len_set
    __swig_getmethods__["eid_len"] = _zxid.zxid_entity_eid_len_get
    if _newclass:eid_len = property(_zxid.zxid_entity_eid_len_get, _zxid.zxid_entity_eid_len_set)
    __swig_setmethods__["eid"] = _zxid.zxid_entity_eid_set
    __swig_getmethods__["eid"] = _zxid.zxid_entity_eid_get
    if _newclass:eid = property(_zxid.zxid_entity_eid_get, _zxid.zxid_entity_eid_set)
    __swig_setmethods__["sha1_name"] = _zxid.zxid_entity_sha1_name_set
    __swig_getmethods__["sha1_name"] = _zxid.zxid_entity_sha1_name_get
    if _newclass:sha1_name = property(_zxid.zxid_entity_sha1_name_get, _zxid.zxid_entity_sha1_name_set)
    __swig_setmethods__["tls_cert"] = _zxid.zxid_entity_tls_cert_set
    __swig_getmethods__["tls_cert"] = _zxid.zxid_entity_tls_cert_get
    if _newclass:tls_cert = property(_zxid.zxid_entity_tls_cert_get, _zxid.zxid_entity_tls_cert_set)
    __swig_setmethods__["sign_cert"] = _zxid.zxid_entity_sign_cert_set
    __swig_getmethods__["sign_cert"] = _zxid.zxid_entity_sign_cert_get
    if _newclass:sign_cert = property(_zxid.zxid_entity_sign_cert_get, _zxid.zxid_entity_sign_cert_set)
    __swig_setmethods__["enc_cert"] = _zxid.zxid_entity_enc_cert_set
    __swig_getmethods__["enc_cert"] = _zxid.zxid_entity_enc_cert_get
    if _newclass:enc_cert = property(_zxid.zxid_entity_enc_cert_get, _zxid.zxid_entity_enc_cert_set)
    __swig_setmethods__["ed"] = _zxid.zxid_entity_ed_set
    __swig_getmethods__["ed"] = _zxid.zxid_entity_ed_get
    if _newclass:ed = property(_zxid.zxid_entity_ed_get, _zxid.zxid_entity_ed_set)
    def __init__(self, *args): 
        this = _zxid.new_zxid_entity(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _zxid.delete_zxid_entity
    __del__ = lambda self : None;
zxid_entity_swigregister = _zxid.zxid_entity_swigregister
zxid_entity_swigregister(zxid_entity)

ZXID_AUTO_EXIT = _zxid.ZXID_AUTO_EXIT
ZXID_AUTO_REDIR = _zxid.ZXID_AUTO_REDIR
ZXID_AUTO_SOAPC = _zxid.ZXID_AUTO_SOAPC
ZXID_AUTO_SOAPH = _zxid.ZXID_AUTO_SOAPH
ZXID_AUTO_METAC = _zxid.ZXID_AUTO_METAC
ZXID_AUTO_METAH = _zxid.ZXID_AUTO_METAH
ZXID_AUTO_LOGINC = _zxid.ZXID_AUTO_LOGINC
ZXID_AUTO_LOGINH = _zxid.ZXID_AUTO_LOGINH
ZXID_AUTO_MGMTC = _zxid.ZXID_AUTO_MGMTC
ZXID_AUTO_MGMTH = _zxid.ZXID_AUTO_MGMTH
ZXID_AUTO_FORMF = _zxid.ZXID_AUTO_FORMF
ZXID_AUTO_FORMT = _zxid.ZXID_AUTO_FORMT
ZXID_AUTO_ALL = _zxid.ZXID_AUTO_ALL
ZXID_AUTO_DEBUG = _zxid.ZXID_AUTO_DEBUG
zxid_simple = _zxid.zxid_simple
zxid_idp_list = _zxid.zxid_idp_list
zxid_idp_select = _zxid.zxid_idp_select
zxid_fed_mgmt = _zxid.zxid_fed_mgmt
zxid_new_conf_to_cf = _zxid.zxid_new_conf_to_cf
zxid_simple_cf = _zxid.zxid_simple_cf
zxid_idp_list_cf = _zxid.zxid_idp_list_cf
zxid_idp_select_cf = _zxid.zxid_idp_select_cf
zxid_fed_mgmt_cf = _zxid.zxid_fed_mgmt_cf
zxid_conf_to_cf_len = _zxid.zxid_conf_to_cf_len
zxid_simple_len = _zxid.zxid_simple_len
zxid_idp_list_len = _zxid.zxid_idp_list_len
zxid_idp_select_len = _zxid.zxid_idp_select_len
zxid_fed_mgmt_len = _zxid.zxid_fed_mgmt_len
zxid_idp_select_zxstr_cf = _zxid.zxid_idp_select_zxstr_cf
zxid_ses_to_ldif = _zxid.zxid_ses_to_ldif
zxid_simple_render_ses = _zxid.zxid_simple_render_ses
zxid_simple_ses_active_cf = _zxid.zxid_simple_ses_active_cf
zxid_simple_no_ses_cf = _zxid.zxid_simple_no_ses_cf
class zxsig_ref(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, zxsig_ref, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, zxsig_ref, name)
    __repr__ = _swig_repr
    __swig_setmethods__["sref"] = _zxid.zxsig_ref_sref_set
    __swig_getmethods__["sref"] = _zxid.zxsig_ref_sref_get
    if _newclass:sref = property(_zxid.zxsig_ref_sref_get, _zxid.zxsig_ref_sref_set)
    __swig_setmethods__["blob"] = _zxid.zxsig_ref_blob_set
    __swig_getmethods__["blob"] = _zxid.zxsig_ref_blob_get
    if _newclass:blob = property(_zxid.zxsig_ref_blob_get, _zxid.zxsig_ref_blob_set)
    __swig_setmethods__["id"] = _zxid.zxsig_ref_id_set
    __swig_getmethods__["id"] = _zxid.zxsig_ref_id_get
    if _newclass:id = property(_zxid.zxsig_ref_id_get, _zxid.zxsig_ref_id_set)
    __swig_setmethods__["canon"] = _zxid.zxsig_ref_canon_set
    __swig_getmethods__["canon"] = _zxid.zxsig_ref_canon_get
    if _newclass:canon = property(_zxid.zxsig_ref_canon_get, _zxid.zxsig_ref_canon_set)
    def __init__(self, *args): 
        this = _zxid.new_zxsig_ref(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _zxid.delete_zxsig_ref
    __del__ = lambda self : None;
zxsig_ref_swigregister = _zxid.zxsig_ref_swigregister
zxsig_ref_swigregister(zxsig_ref)

ZXSIG_OK = _zxid.ZXSIG_OK
ZXSIG_BAD_DALGO = _zxid.ZXSIG_BAD_DALGO
ZXSIG_DIGEST_LEN = _zxid.ZXSIG_DIGEST_LEN
ZXSIG_BAD_DIGEST = _zxid.ZXSIG_BAD_DIGEST
ZXSIG_BAD_SALGO = _zxid.ZXSIG_BAD_SALGO
ZXSIG_BAD_CERT = _zxid.ZXSIG_BAD_CERT
ZXSIG_VFY_FAIL = _zxid.ZXSIG_VFY_FAIL
ZXSIG_NO_SIG = _zxid.ZXSIG_NO_SIG
ZXSIG_TIMEOUT = _zxid.ZXSIG_TIMEOUT
ZXSIG_AUDIENCE = _zxid.ZXSIG_AUDIENCE
zxsig_sign = _zxid.zxsig_sign
zxsig_validate = _zxid.zxsig_validate
zxsig_data_rsa_sha1 = _zxid.zxsig_data_rsa_sha1
zxsig_verify_data_rsa_sha1 = _zxid.zxsig_verify_data_rsa_sha1
zxenc_symkey_dec = _zxid.zxenc_symkey_dec
zxenc_privkey_dec = _zxid.zxenc_privkey_dec
zxenc_symkey_enc = _zxid.zxenc_symkey_enc
zxenc_pubkey_enc = _zxid.zxenc_pubkey_enc
ZXLOG_RELY_DIR = _zxid.ZXLOG_RELY_DIR
ZXLOG_ISSUE_DIR = _zxid.ZXLOG_ISSUE_DIR
ZXLOG_A7N_KIND = _zxid.ZXLOG_A7N_KIND
ZXLOG_MSG_KIND = _zxid.ZXLOG_MSG_KIND
zxlog_write_line = _zxid.zxlog_write_line
zxlog_path = _zxid.zxlog_path
zxlog_dup_check = _zxid.zxlog_dup_check
zxlog_blob = _zxid.zxlog_blob
zxlog = _zxid.zxlog
ZXID_COT_DIR = _zxid.ZXID_COT_DIR
ZXID_MAX_MD = _zxid.ZXID_MAX_MD
ZXID_MAX_SOAP = _zxid.ZXID_MAX_SOAP
ZXID_MAX_EID = _zxid.ZXID_MAX_EID
zxid_get_ent_from_file = _zxid.zxid_get_ent_from_file
zxid_get_ent_from_cache = _zxid.zxid_get_ent_from_cache
zxid_write_ent_to_cache = _zxid.zxid_write_ent_to_cache
zxid_parse_meta = _zxid.zxid_parse_meta
zxid_get_meta_ss = _zxid.zxid_get_meta_ss
zxid_get_meta = _zxid.zxid_get_meta
zxid_get_ent_ss = _zxid.zxid_get_ent_ss
zxid_get_ent = _zxid.zxid_get_ent
zxid_get_ent_by_succinct_id = _zxid.zxid_get_ent_by_succinct_id
zxid_get_ent_by_sha1_name = _zxid.zxid_get_ent_by_sha1_name
zxid_load_cot_cache = _zxid.zxid_load_cot_cache
zxid_key_info = _zxid.zxid_key_info
zxid_key_desc = _zxid.zxid_key_desc
zxid_slo_desc = _zxid.zxid_slo_desc
zxid_mni_desc = _zxid.zxid_mni_desc
zxid_ac_desc = _zxid.zxid_ac_desc
zxid_sp_sso_desc = _zxid.zxid_sp_sso_desc
zxid_sp_meta = _zxid.zxid_sp_meta
zxid_send_sp_meta = _zxid.zxid_send_sp_meta
zxid_my_entity_id = _zxid.zxid_my_entity_id
zxid_my_cdc_url = _zxid.zxid_my_cdc_url
zxid_my_issuer = _zxid.zxid_my_issuer
zxid_sha1_file = _zxid.zxid_sha1_file
zxid_extract_cert = _zxid.zxid_extract_cert
zxid_extract_private_key = _zxid.zxid_extract_private_key
zxid_read_cert = _zxid.zxid_read_cert
zxid_read_private_key = _zxid.zxid_read_private_key
zxid_set_opt = _zxid.zxid_set_opt
zxid_url_set = _zxid.zxid_url_set
zxid_init_conf = _zxid.zxid_init_conf
zxid_init_conf_ctx = _zxid.zxid_init_conf_ctx
zxid_new_conf = _zxid.zxid_new_conf
zxid_parse_conf_raw = _zxid.zxid_parse_conf_raw
zxid_parse_conf = _zxid.zxid_parse_conf
zxid_parse_cgi = _zxid.zxid_parse_cgi
zxid_new_cgi = _zxid.zxid_new_cgi
zxid_get_sid_from_cookie = _zxid.zxid_get_sid_from_cookie
zxid_fetch_ses = _zxid.zxid_fetch_ses
zxid_get_ses = _zxid.zxid_get_ses
zxid_put_ses = _zxid.zxid_put_ses
zxid_del_ses = _zxid.zxid_del_ses
zxid_get_ses_sso_a7n = _zxid.zxid_get_ses_sso_a7n
zxid_get_ses_idp = _zxid.zxid_get_ses_idp
zxid_find_ses = _zxid.zxid_find_ses
zxid_put_user = _zxid.zxid_put_user
zxid_get_user_nameid = _zxid.zxid_get_user_nameid
zxid_user_change_nameid = _zxid.zxid_user_change_nameid
zxid_soap_call_raw = _zxid.zxid_soap_call_raw
zxid_lecp_check = _zxid.zxid_lecp_check
zxid_cdc_read = _zxid.zxid_cdc_read
zxid_cdc_check = _zxid.zxid_cdc_check
zxid_soap_call_envelope = _zxid.zxid_soap_call_envelope
zxid_soap_call_hdr_body = _zxid.zxid_soap_call_hdr_body
zxid_soap_call_body = _zxid.zxid_soap_call_body
zxid_soap_cgi_resp_body = _zxid.zxid_soap_cgi_resp_body
zxid_saml2_redir_enc = _zxid.zxid_saml2_redir_enc
zxid_saml2_redir = _zxid.zxid_saml2_redir
zxid_saml2_redir_url = _zxid.zxid_saml2_redir_url
zxid_saml2_location = _zxid.zxid_saml2_location
zxid_saml2_resp_location = _zxid.zxid_saml2_resp_location
zxid_saml2_resp_redir = _zxid.zxid_saml2_resp_redir
zxid_saml_ok = _zxid.zxid_saml_ok
zxid_decrypt_nameid = _zxid.zxid_decrypt_nameid
zxid_decrypt_newnym = _zxid.zxid_decrypt_newnym
zxid_idp_loc_raw = _zxid.zxid_idp_loc_raw
zxid_idp_loc = _zxid.zxid_idp_loc
zxid_idp_soap = _zxid.zxid_idp_soap
zxid_pick_sso_profile = _zxid.zxid_pick_sso_profile
zxid_start_sso = _zxid.zxid_start_sso
zxid_start_sso_url = _zxid.zxid_start_sso_url
zxid_start_sso_location = _zxid.zxid_start_sso_location
zxid_sp_deref_art = _zxid.zxid_sp_deref_art
zxid_sp_sso_finalize = _zxid.zxid_sp_sso_finalize
zxid_saml2_map_nid_fmt = _zxid.zxid_saml2_map_nid_fmt
zxid_saml2_map_protocol_binding = _zxid.zxid_saml2_map_protocol_binding
zxid_saml2_map_authn_ctx = _zxid.zxid_saml2_map_authn_ctx
zxid_date_time = _zxid.zxid_date_time
zxid_mk_id = _zxid.zxid_mk_id
zxid_issuer = _zxid.zxid_issuer
zxid_sigres_map = _zxid.zxid_sigres_map
zxid_sp_slo_soap = _zxid.zxid_sp_slo_soap
zxid_sp_slo_redir = _zxid.zxid_sp_slo_redir
zxid_sp_slo_location = _zxid.zxid_sp_slo_location
zxid_sp_dispatch_location = _zxid.zxid_sp_dispatch_location
zxid_sp_dispatch = _zxid.zxid_sp_dispatch
zxid_sp_soap_dispatch = _zxid.zxid_sp_soap_dispatch
zxid_sp_soap_parse = _zxid.zxid_sp_soap_parse
zxid_sp_mni_soap = _zxid.zxid_sp_mni_soap
zxid_sp_mni_redir = _zxid.zxid_sp_mni_redir
zxid_sp_mni_location = _zxid.zxid_sp_mni_location
zxid_mni_do = _zxid.zxid_mni_do
zxid_mni_do_ss = _zxid.zxid_mni_do_ss
zxid_find_attribute = _zxid.zxid_find_attribute
zxid_mk_authn_req = _zxid.zxid_mk_authn_req
zxid_mk_art_deref = _zxid.zxid_mk_art_deref
zxid_mk_Status = _zxid.zxid_mk_Status
zxid_OK = _zxid.zxid_OK
zxid_mk_logout = _zxid.zxid_mk_logout
zxid_mk_logout_resp = _zxid.zxid_mk_logout_resp
zxid_mk_mni = _zxid.zxid_mk_mni
zxid_mk_mni_resp = _zxid.zxid_mk_mni_resp
zxid_mk_di_query = _zxid.zxid_mk_di_query
zxid_mk_addr = _zxid.zxid_mk_addr
zxid_mk_dap_select = _zxid.zxid_mk_dap_select
zxid_mk_dap_query_item = _zxid.zxid_mk_dap_query_item
zxid_mk_dap_testop = _zxid.zxid_mk_dap_testop
zxid_mk_dap_test_item = _zxid.zxid_mk_dap_test_item
zxid_mk_dap_resquery = _zxid.zxid_mk_dap_resquery
zxid_mk_dap_subscription = _zxid.zxid_mk_dap_subscription
zxid_mk_dap_query = _zxid.zxid_mk_dap_query
zxid_map_sec_mech = _zxid.zxid_map_sec_mech
zxid_wsc_call = _zxid.zxid_wsc_call
zxid_new_envf = _zxid.zxid_new_envf
zxid_callf = _zxid.zxid_callf
zxid_get_epr = _zxid.zxid_get_epr
zxid_find_epr = _zxid.zxid_find_epr
zxid_cache_epr = _zxid.zxid_cache_epr
zxid_snarf_eprs_from_ses = _zxid.zxid_snarf_eprs_from_ses
ZXID_DAP_SCOPE_BASE = _zxid.ZXID_DAP_SCOPE_BASE
ZXID_DAP_SCOPE_SINGLE = _zxid.ZXID_DAP_SCOPE_SINGLE
ZXID_DAP_SCOPE_SUBTREE = _zxid.ZXID_DAP_SCOPE_SUBTREE
ZXID_CDC_CHOICE_ALWAYS_FIRST = _zxid.ZXID_CDC_CHOICE_ALWAYS_FIRST
ZXID_CDC_CHOICE_ALWAYS_LAST = _zxid.ZXID_CDC_CHOICE_ALWAYS_LAST
ZXID_CDC_CHOICE_ALWAYS_ONLY = _zxid.ZXID_CDC_CHOICE_ALWAYS_ONLY
ZXID_CDC_CHOICE_UI_PREF = _zxid.ZXID_CDC_CHOICE_UI_PREF
ZXID_CDC_CHOICE_UI_NOPREF = _zxid.ZXID_CDC_CHOICE_UI_NOPREF
ZXID_CDC_CHOICE_UI_ONLY_CDC = _zxid.ZXID_CDC_CHOICE_UI_ONLY_CDC
ZXID_SAML2_ART = _zxid.ZXID_SAML2_ART
ZXID_SAML2_POST = _zxid.ZXID_SAML2_POST
ZXID_SAML2_PAOS = _zxid.ZXID_SAML2_PAOS
ZXID_SAML2_SOAP = _zxid.ZXID_SAML2_SOAP
ZXID_SAML2_POST_SIMPLE_SIGN = _zxid.ZXID_SAML2_POST_SIMPLE_SIGN
ZXID_SAML2_REDIR = _zxid.ZXID_SAML2_REDIR
ZXID_SAML2_URI = _zxid.ZXID_SAML2_URI
ZXID_SLO_SVC = _zxid.ZXID_SLO_SVC
ZXID_MNI_SVC = _zxid.ZXID_MNI_SVC
ZXID_SEC_MECH_NULL = _zxid.ZXID_SEC_MECH_NULL
ZXID_SEC_MECH_BEARER = _zxid.ZXID_SEC_MECH_BEARER
ZXID_SEC_MECH_SAML = _zxid.ZXID_SEC_MECH_SAML
ZXID_SEC_MECH_X509 = _zxid.ZXID_SEC_MECH_X509
ZXID_SEC_MECH_PEERS = _zxid.ZXID_SEC_MECH_PEERS
ZXID_FAIL = _zxid.ZXID_FAIL
ZXID_OK = _zxid.ZXID_OK
ZXID_REDIR_OK = _zxid.ZXID_REDIR_OK
ZXID_SSO_OK = _zxid.ZXID_SSO_OK
ZXID_TRUE = _zxid.ZXID_TRUE
ZXID_FALSE = _zxid.ZXID_FALSE
CRLF = _zxid.CRLF
CRLF2 = _zxid.CRLF2
base64_fancy_raw = _zxid.base64_fancy_raw
unbase64_raw = _zxid.unbase64_raw
sha1_safe_base64 = _zxid.sha1_safe_base64
zx_zlib_raw_deflate = _zxid.zx_zlib_raw_deflate
zx_zlib_raw_inflate = _zxid.zx_zlib_raw_inflate
zx_url_encode_len = _zxid.zx_url_encode_len
zx_url_encode_raw = _zxid.zx_url_encode_raw
zx_url_encode = _zxid.zx_url_encode
read_all = _zxid.read_all
name_from_path = _zxid.name_from_path
open_fd_from_path = _zxid.open_fd_from_path
read_all_fd = _zxid.read_all_fd
write_all_fd = _zxid.write_all_fd
write_all_path_fmt = _zxid.write_all_path_fmt
close_file = _zxid.close_file
class zxid_curl_ctx(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, zxid_curl_ctx, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, zxid_curl_ctx, name)
    __repr__ = _swig_repr
    __swig_setmethods__["p"] = _zxid.zxid_curl_ctx_p_set
    __swig_getmethods__["p"] = _zxid.zxid_curl_ctx_p_get
    if _newclass:p = property(_zxid.zxid_curl_ctx_p_get, _zxid.zxid_curl_ctx_p_set)
    __swig_setmethods__["lim"] = _zxid.zxid_curl_ctx_lim_set
    __swig_getmethods__["lim"] = _zxid.zxid_curl_ctx_lim_get
    if _newclass:lim = property(_zxid.zxid_curl_ctx_lim_get, _zxid.zxid_curl_ctx_lim_set)
    def __init__(self, *args): 
        this = _zxid.new_zxid_curl_ctx(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _zxid.delete_zxid_curl_ctx
    __del__ = lambda self : None;
zxid_curl_ctx_swigregister = _zxid.zxid_curl_ctx_swigregister
zxid_curl_ctx_swigregister(zxid_curl_ctx)
cvar = _zxid.cvar

zxid_curl_write_data = _zxid.zxid_curl_write_data
zxid_curl_read_data = _zxid.zxid_curl_read_data
zxid_version = _zxid.zxid_version
zxid_version_str = _zxid.zxid_version_str
SAML2_PROTO = _zxid.SAML2_PROTO
SAML2_VERSION = _zxid.SAML2_VERSION
SAML2_SC_SUCCESS = _zxid.SAML2_SC_SUCCESS
SAML2_SC_REQUESTER = _zxid.SAML2_SC_REQUESTER
SAML2_SC_RESPONDER = _zxid.SAML2_SC_RESPONDER
SAML2_SC_VERSION = _zxid.SAML2_SC_VERSION
SAML2_SC_AUTHNFAIL = _zxid.SAML2_SC_AUTHNFAIL
SAML2_SC_INVATTRNV = _zxid.SAML2_SC_INVATTRNV
SAML2_SC_INVNIDPOL = _zxid.SAML2_SC_INVNIDPOL
SAML2_SC_NOAUTNCTX = _zxid.SAML2_SC_NOAUTNCTX
SAML2_SC_NOAVALIDP = _zxid.SAML2_SC_NOAVALIDP
SAML2_SC_NOPASSIVE = _zxid.SAML2_SC_NOPASSIVE
SAML2_SC_NOSUPPIDP = _zxid.SAML2_SC_NOSUPPIDP
SAML2_SC_PARLOGOUT = _zxid.SAML2_SC_PARLOGOUT
SAML2_SC_PROXYCEXC = _zxid.SAML2_SC_PROXYCEXC
SAML2_SC_REQDENIED = _zxid.SAML2_SC_REQDENIED
SAML2_SC_REQUNSUPP = _zxid.SAML2_SC_REQUNSUPP
SAML2_SC_REQVERDEP = _zxid.SAML2_SC_REQVERDEP
SAML2_SC_REQVERHIG = _zxid.SAML2_SC_REQVERHIG
SAML2_SC_REQVERLOW = _zxid.SAML2_SC_REQVERLOW
SAML2_SC_RESONRECG = _zxid.SAML2_SC_RESONRECG
SAML2_SC_TOOMNYRES = _zxid.SAML2_SC_TOOMNYRES
SAML2_SC_UNKATTPRO = _zxid.SAML2_SC_UNKATTPRO
SAML2_SC_UNKPRNCPL = _zxid.SAML2_SC_UNKPRNCPL
SAML2_SC_UNSUPPBIN = _zxid.SAML2_SC_UNSUPPBIN
SAML_AUTHCTX_PASSWORDPROTECTED = _zxid.SAML_AUTHCTX_PASSWORDPROTECTED
SAML_AUTHCTX_PASSWORD = _zxid.SAML_AUTHCTX_PASSWORD
SAML_AUTHCTX_SSL_TLS_CERT = _zxid.SAML_AUTHCTX_SSL_TLS_CERT
SAML_AUTHCTX_PREVSESS = _zxid.SAML_AUTHCTX_PREVSESS
SAML_AUTHCTX_UNSPCFD = _zxid.SAML_AUTHCTX_UNSPCFD
SAML_AUTHCTX_INPROT = _zxid.SAML_AUTHCTX_INPROT
SAML2_UNSPECIFIED_NID_FMT = _zxid.SAML2_UNSPECIFIED_NID_FMT
SAML2_EMAILADDR_NID_FMT = _zxid.SAML2_EMAILADDR_NID_FMT
SAML2_X509_NID_FMT = _zxid.SAML2_X509_NID_FMT
SAML2_WINDOMAINQN_NID_FMT = _zxid.SAML2_WINDOMAINQN_NID_FMT
SAML2_KERBEROS_NID_FMT = _zxid.SAML2_KERBEROS_NID_FMT
SAML2_ENTITY_NID_FMT = _zxid.SAML2_ENTITY_NID_FMT
SAML2_PERSISTENT_NID_FMT = _zxid.SAML2_PERSISTENT_NID_FMT
SAML2_TRANSIENT_NID_FMT = _zxid.SAML2_TRANSIENT_NID_FMT
SAML2_SSO_BRWS = _zxid.SAML2_SSO_BRWS
SAML2_SSO_ECP = _zxid.SAML2_SSO_ECP
SAML2_SLO = _zxid.SAML2_SLO
SAML2_NIREG = _zxid.SAML2_NIREG
SAML2_NIMAP = _zxid.SAML2_NIMAP
SAML2_ARTIFACT = _zxid.SAML2_ARTIFACT
SAML2_QUERY = _zxid.SAML2_QUERY
SAML2_PAOS = _zxid.SAML2_PAOS
SAML2_SOAP = _zxid.SAML2_SOAP
SAML2_REDIR = _zxid.SAML2_REDIR
SAML2_ART = _zxid.SAML2_ART
SAML2_POST = _zxid.SAML2_POST
SAML2_POST_SIMPLE_SIGN = _zxid.SAML2_POST_SIMPLE_SIGN
SAML2_URI = _zxid.SAML2_URI
SAML2_AP_BASIC = _zxid.SAML2_AP_BASIC
SAML2_AP_X500 = _zxid.SAML2_AP_X500
SAML2_AP_UUID = _zxid.SAML2_AP_UUID
SAML2_AP_DCE = _zxid.SAML2_AP_DCE
SAML2_AP_XACML = _zxid.SAML2_AP_XACML
ATTRNAME_UNSPECIFIED = _zxid.ATTRNAME_UNSPECIFIED
ATTRNAME_BASIC = _zxid.ATTRNAME_BASIC
SOAP_ACTOR_NEXT = _zxid.SOAP_ACTOR_NEXT
SAML2_BEARER = _zxid.SAML2_BEARER
SAML2_SOAP_ACTION = _zxid.SAML2_SOAP_ACTION
ACTION_RW = _zxid.ACTION_RW
ACTION_RWN = _zxid.ACTION_RWN
ACTION_GHPP = _zxid.ACTION_GHPP
ACTION_UNIX = _zxid.ACTION_UNIX
PAOS_CONTENT = _zxid.PAOS_CONTENT


