/* generated file, do not edit! zx_ _ATTR
 * $Id$ */
#ifndef _zx__ATTR
#define _zx__ATTR
#define zx_Name_ATTR	0
#define zx_Value_ATTR	1
#define zx_Version_ATTR	2
#define zx_Namespace_ATTR	3
#define zx_NameFormat_ATTR	4
#define zx_SessionIndex_ATTR	5
#define zx_NameQualifier_ATTR	6
#define zx_case_ATTR	7
#define zx_AssertionID_ATTR	8
#define zx_AuthnInstant_ATTR	9
#define zx_AuthorityKind_ATTR	10
#define zx_SessionNotOnOrAfter_ATTR	11
#define zx_Issuer_ATTR	12
#define zx_sharing_ATTR	13
#define zx_IsPassive_ATTR	14
#define zx_AuthenticationMethod_ATTR	15
#define zx_AuthenticationInstant_ATTR	16
#define zx_IssueInstant_ATTR	17
#define zx_requiredChars_ATTR	18
#define zx_Method_ATTR	19
#define zx_AssertionConsumerServiceURL_ATTR	20
#define zx_AttributeName_ATTR	21
#define zx_AssertionConsumerServiceIndex_ATTR	22
#define zx_Target_ATTR	23
#define zx_DNSName_ATTR	24
#define zx_AttributeNamespace_ATTR	25
#define zx_Type_ATTR	26
#define zx_Nonce_ATTR	27
#define zx_Destination_ATTR	28
#define zx_consent_ATTR	29
#define zx_max_ATTR	30
#define zx_Algorithm_ATTR	31
#define zx_DNSAddress_ATTR	32
#define zx_AllowCreate_ATTR	33
#define zx_ID_ATTR	34
#define zx_MimeType_ATTR	35
#define zx_mechanism_ATTR	36
#define zx_AttributeConsumingServiceIndex_ATTR	37
#define zx_Reason_ATTR	38
#define zx_FriendlyName_ATTR	39
#define zx_Decision_ATTR	40
#define zx_RequestID_ATTR	41
#define zx_DeviceType_ATTR	42
#define zx_governingAgreementRef_ATTR	43
#define zx_DeviceInHand_ATTR	44
#define zx_min_ATTR	45
#define zx_medium_ATTR	46
#define zx_MajorVersion_ATTR	47
#define zx_duration_ATTR	48
#define zx_NotBefore_ATTR	49
#define zx_SeedLength_ATTR	50
#define zx_Consent_ATTR	51
#define zx_ReauthenticateOnOrAfter_ATTR	52
#define zx_Recipient_ATTR	53
#define zx_ForceAuthn_ATTR	54
#define zx_number_ATTR	55
#define zx_Id_ATTR	56
#define zx_excludedChars_ATTR	57
#define zx_SPNameQualifier_ATTR	58
#define zx_MinorVersion_ATTR	59
#define zx_Resource_ATTR	60
#define zx_Address_ATTR	61
#define zx_nym_ATTR	62
#define zx_SPProvidedID_ATTR	63
#define zx_Loc_ATTR	64
#define zx_ProtocolBinding_ATTR	65
#define zx_InResponseTo_ATTR	66
#define zx_Location_ATTR	67
#define zx_credentialLevel_ATTR	68
#define zx_Format_ATTR	69
#define zx_NotOnOrAfter_ATTR	70
#define zx_ZX_TOK_NOT_FOUND_ATTR	71
#define zx_ProviderID_ATTR	72
#define zx_ProviderName_ATTR	73
#define zx_URI_ATTR	74
#define zx_ResponseID_ATTR	75
#define zx_Binding_ATTR	76
#define zx_Encoding_ATTR	77
#define zx_Comparison_ATTR	78
#define zx_Count_ATTR	79
#define zx_IPAddress_ATTR	80
#define zx_ProxyCount_ATTR	81
#define zx_xmlns_ATTR	82
#endif
/* generated file, do not edit! zx_ _ELEM
 * $Id$ */
#ifndef _zx__ELEM
#define _zx__ELEM
#define zx_ds_Y_ELEM	0
#define zx_root_ELEM	1
#define zx_se_Header_ELEM	2
#define zx_ds_J_ELEM	3
#define zx_se_Fault_ELEM	4
#define zx_ds_Object_ELEM	5
#define zx_ds_Exponent_ELEM	6
#define zx_sa11_Condition_ELEM	7
#define zx_sa_Condition_ELEM	8
#define zx_ac_ZeroKnowledge_ELEM	9
#define zx_ff12_RegisterNameIdentifierRequest_ELEM	10
#define zx_sp11_Request_ELEM	11
#define zx_sa11_Evidence_ELEM	12
#define zx_sa_Evidence_ELEM	13
#define zx_ac_Extension_ELEM	14
#define zx_ff12_Extension_ELEM	15
#define zx_ac_OperationalProtection_ELEM	16
#define zx_xenc_ReferenceList_ELEM	17
#define zx_ac_WrittenConsent_ELEM	18
#define zx_sa11_Conditions_ELEM	19
#define zx_sa_Conditions_ELEM	20
#define zx_xenc_CipherValue_ELEM	21
#define zx_sp11_Response_ELEM	22
#define zx_sp_Response_ELEM	23
#define zx_ff12_RequestAuthnContext_ELEM	24
#define zx_xenc_CipherReference_ELEM	25
#define zx_sp_RequestedAuthnContext_ELEM	26
#define zx_ac_ResumeSession_ELEM	27
#define zx_sp_Extensions_ELEM	28
#define zx_sp11_AssertionArtifact_ELEM	29
#define zx_sp_AssertionIDRequest_ELEM	30
#define zx_ff12_Assertion_ELEM	31
#define zx_sa_Assertion_ELEM	32
#define zx_sa11_Assertion_ELEM	33
#define zx_ff12_RegisterNameIdentifierResponse_ELEM	34
#define zx_ac_Authenticator_ELEM	35
#define zx_ds_Reference_ELEM	36
#define zx_xenc_CipherData_ELEM	37
#define zx_sa11_Action_ELEM	38
#define zx_sa_Action_ELEM	39
#define zx_ff12_ForceAuthn_ELEM	40
#define zx_sa11_AuthorizationDecisionStatement_ELEM	41
#define zx_ff12_AuthnRequest_ELEM	42
#define zx_sp_AuthnRequest_ELEM	43
#define zx_ff12_AuthenticationStatement_ELEM	44
#define zx_sa11_AuthenticationStatement_ELEM	45
#define zx_xenc_CarriedKeyName_ELEM	46
#define zx_ff12_AuthnContext_ELEM	47
#define zx_sa_AuthnContext_ELEM	48
#define zx_sa_AudienceRestriction_ELEM	49
#define zx_ac_AuthenticationContextStatement_ELEM	50
#define zx_ff12_FederationTerminationNotification_ELEM	51
#define zx_sa11_Audience_ELEM	52
#define zx_sa_Audience_ELEM	53
#define zx_ac_WTLS_ELEM	54
#define zx_sa11_AssertionIDReference_ELEM	55
#define zx_ac_AsymmetricKeyAgreement_ELEM	56
#define zx_sa11_AudienceRestrictionCondition_ELEM	57
#define zx_ac_SecretKeyProtection_ELEM	58
#define zx_xenc_OAEPparams_ELEM	59
#define zx_ff12_Subject_ELEM	60
#define zx_sa_Subject_ELEM	61
#define zx_sa11_Subject_ELEM	62
#define zx_sp_Artifact_ELEM	63
#define zx_ds_Signature_ELEM	64
#define zx_ac_AsymmetricDecryption_ELEM	65
#define zx_sa11_Advice_ELEM	66
#define zx_sa_Advice_ELEM	67
#define zx_ff12_AuthnContextComparison_ELEM	68
#define zx_ff12_AuthnResponse_ELEM	69
#define zx_ds_SignatureValue_ELEM	70
#define zx_ac_ActivationLimit_ELEM	71
#define zx_sa11_SubjectStatement_ELEM	72
#define zx_se_Envelope_ELEM	73
#define zx_ds_SignatureProperties_ELEM	74
#define zx_ff12_AuthnRequestEnvelope_ELEM	75
#define zx_ff12_AuthnResponseEnvelope_ELEM	76
#define zx_ac_ActivationPin_ELEM	77
#define zx_se_Body_ELEM	78
#define zx_ff12_OldProvidedNameIdentifier_ELEM	79
#define zx_ds_RSAKeyValue_ELEM	80
#define zx_xenc_OriginatorKeyInfo_ELEM	81
#define zx_sa11_SubjectConfirmation_ELEM	82
#define zx_sa_SubjectConfirmation_ELEM	83
#define zx_ff12_RelayState_ELEM	84
#define zx_sp11_Status_ELEM	85
#define zx_sp_Status_ELEM	86
#define zx_ac_ActivationLimitSession_ELEM	87
#define zx_ac_ActivationLimitDuration_ELEM	88
#define zx_ff12_SPProvidedNameIdentifier_ELEM	89
#define zx_sp11_StatusCode_ELEM	90
#define zx_sp_StatusCode_ELEM	91
#define zx_sp11_StatusMessage_ELEM	92
#define zx_sp_StatusMessage_ELEM	93
#define zx_ac_GoverningAgreements_ELEM	94
#define zx_sp_ArtifactResolve_ELEM	95
#define zx_sp_ArtifactResponse_ELEM	96
#define zx_ff12_EncryptedNameIdentifier_ELEM	97
#define zx_sa_AuthnStatement_ELEM	98
#define zx_ff12_EncryptableNameIdentifier_ELEM	99
#define zx_ac_ActivationLimitUsages_ELEM	100
#define zx_sa_EncryptedAssertion_ELEM	101
#define zx_ac_Generation_ELEM	102
#define zx_sp11_AuthorizationDecisionQuery_ELEM	103
#define zx_sa11_ConfirmationMethod_ELEM	104
#define zx_sp11_AuthenticationQuery_ELEM	105
#define zx_sp11_Query_ELEM	106
#define zx_ds_DigestValue_ELEM	107
#define zx_ac_AuthenticatingAuthority_ELEM	108
#define zx_sa_AuthenticatingAuthority_ELEM	109
#define zx_ac_Token_ELEM	110
#define zx_ds_Q_ELEM	111
#define zx_ds_SignatureProperty_ELEM	112
#define zx_sa_EncryptedAttribute_ELEM	113
#define zx_xenc_EncryptionProperties_ELEM	114
#define zx_sp11_RespondWith_ELEM	115
#define zx_ff12_SessionIndex_ELEM	116
#define zx_sp_SessionIndex_ELEM	117
#define zx_sa_SubjectConfirmationData_ELEM	118
#define zx_sa11_SubjectConfirmationData_ELEM	119
#define zx_ds_RetrievalMethod_ELEM	120
#define zx_ds_G_ELEM	121
#define zx_ds_SPKIData_ELEM	122
#define zx_sa11_DoNotCacheCondition_ELEM	123
#define zx_sp_RequesterID_ELEM	124
#define zx_xenc_EncryptedData_ELEM	125
#define zx_ac_HTTP_ELEM	126
#define zx_sa_OneTimeUse_ELEM	127
#define zx_sp11_SubjectQuery_ELEM	128
#define zx_sp_SubjectQuery_ELEM	129
#define zx_xenc_DataReference_ELEM	130
#define zx_ff12_TargetNamespace_ELEM	131
#define zx_sa11_SubjectLocality_ELEM	132
#define zx_sa_SubjectLocality_ELEM	133
#define zx_sp_Terminate_ELEM	134
#define zx_ds_Seed_ELEM	135
#define zx_sa11_AuthorityBinding_ELEM	136
#define zx_ac_SecurityAudit_ELEM	137
#define zx_ac_AuthenticationMethod_ELEM	138
#define zx_sa_AuthzDecisionStatement_ELEM	139
#define zx_ds_SignatureMethod_ELEM	140
#define zx_ff12_AssertionConsumerServiceID_ELEM	141
#define zx_xenc_EncryptedKey_ELEM	142
#define zx_sa11_Statement_ELEM	143
#define zx_sa_Statement_ELEM	144
#define zx_ac_PrivateKeyProtection_ELEM	145
#define zx_xenc_EncryptionProperty_ELEM	146
#define zx_ff12_ProxyCount_ELEM	147
#define zx_ac_SwitchAudit_ELEM	148
#define zx_ff12_Scoping_ELEM	149
#define zx_sp_Scoping_ELEM	150
#define zx_ac_SharedSecretDynamicPlaintext_ELEM	151
#define zx_sp_AuthnQuery_ELEM	152
#define zx_xenc_RecipientKeyInfo_ELEM	153
#define zx_ds_SPKISexp_ELEM	154
#define zx_ac_Smartcard_ELEM	155
#define zx_sa_ProxyRestriction_ELEM	156
#define zx_ac_KeyActivation_ELEM	157
#define zx_ds_DSAKeyValue_ELEM	158
#define zx_ds_PGPData_ELEM	159
#define zx_ac_PhysicalVerification_ELEM	160
#define zx_ds_X509SerialNumber_ELEM	161
#define zx_xenc_KeySize_ELEM	162
#define zx_sa11_NameIdentifier_ELEM	163
#define zx_sp_NewID_ELEM	164
#define zx_ds_HMACOutputLength_ELEM	165
#define zx_ac_TimeSyncToken_ELEM	166
#define zx_ff12_LogoutRequest_ELEM	167
#define zx_sp_LogoutRequest_ELEM	168
#define zx_ac_SharedSecretChallengeResponse_ELEM	169
#define zx_ff12_ProtocolProfile_ELEM	170
#define zx_ff12_GetComplete_ELEM	171
#define zx_sp_GetComplete_ELEM	172
#define zx_ds_DigestMethod_ELEM	173
#define zx_xenc_KA_Nonce_ELEM	174
#define zx_se_faultactor_ELEM	175
#define zx_xenc_EncryptionMethod_ELEM	176
#define zx_ac_DeactivationCallCenter_ELEM	177
#define zx_ff12_NameIdentifierMappingRequest_ELEM	178
#define zx_se_faultcode_ELEM	179
#define zx_sp_NameIDMappingRequest_ELEM	180
#define zx_sa_EncryptedID_ELEM	181
#define zx_ff12_Loc_ELEM	182
#define zx_ds_X509IssuerName_ELEM	183
#define zx_ds_X509Certificate_ELEM	184
#define zx_sa_Issuer_ELEM	185
#define zx_ds_PGPKeyPacket_ELEM	186
#define zx_sa_AssertionIDRef_ELEM	187
#define zx_sa_AssertionURIRef_ELEM	188
#define zx_ds_PgenCounter_ELEM	189
#define zx_ds_CanonicalizationMethod_ELEM	190
#define zx_sp_AuthzDecisionQuery_ELEM	191
#define zx_ff12_LogoutResponse_ELEM	192
#define zx_sp_LogoutResponse_ELEM	193
#define zx_ds_Manifest_ELEM	194
#define zx_sp_NewEncryptedID_ELEM	195
#define zx_ds_SignedInfo_ELEM	196
#define zx_ff12_NameIdentifierMappingResponse_ELEM	197
#define zx_ac_PreviousSession_ELEM	198
#define zx_sp_NameIDMappingResponse_ELEM	199
#define zx_ac_TechnicalProtection_ELEM	200
#define zx_sp_ManageNameIDRequest_ELEM	201
#define zx_ac_IPSec_ELEM	202
#define zx_ff12_IDPList_ELEM	203
#define zx_sp_IDPList_ELEM	204
#define zx_ac_IPAddress_ELEM	205
#define zx_ff12_IDPEntries_ELEM	206
#define zx_ds_X509Data_ELEM	207
#define zx_sa_AuthnContextDeclRef_ELEM	208
#define zx_ff12_AuthnContextClassRef_ELEM	209
#define zx_sa_AuthnContextClassRef_ELEM	210
#define zx_ff12_AffiliationID_ELEM	211
#define zx_ff12_AuthnContextStatementRef_ELEM	212
#define zx_ac_MobileNetworkNoEncryption_ELEM	213
#define zx_sa_BaseID_ELEM	214
#define zx_ac_MobileNetworkRadioEncryption_ELEM	215
#define zx_xenc_AgreementMethod_ELEM	216
#define zx_ac_MobileNetworkEndToEndEncryption_ELEM	217
#define zx_ZX_TOK_NOT_FOUND_ELEM	218
#define zx_ac_SSL_ELEM	219
#define zx_sp_ManageNameIDResponse_ELEM	220
#define zx_ac_GoverningAgreementRef_ELEM	221
#define zx_ff12_AssertionConsumerServiceURL_ELEM	222
#define zx_ac_Alphabet_ELEM	223
#define zx_ff12_IsPassive_ELEM	224
#define zx_ac_KeyStorage_ELEM	225
#define zx_sp_NameIDPolicy_ELEM	226
#define zx_ff12_NameIDPolicy_ELEM	227
#define zx_ac_AuthenticatorTransportProtocol_ELEM	228
#define zx_sa_AuthnContextDecl_ELEM	229
#define zx_sa11_AttributeStatement_ELEM	230
#define zx_sa_AttributeStatement_ELEM	231
#define zx_sa11_AttributeDesignator_ELEM	232
#define zx_ds_XPath_ELEM	233
#define zx_ff12_ProviderName_ELEM	234
#define zx_ds_X509SubjectName_ELEM	235
#define zx_ff12_IDPEntry_ELEM	236
#define zx_sp_IDPEntry_ELEM	237
#define zx_sp11_StatusDetail_ELEM	238
#define zx_sp_StatusDetail_ELEM	239
#define zx_ds_MgmtData_ELEM	240
#define zx_sa11_Attribute_ELEM	241
#define zx_sa_Attribute_ELEM	242
#define zx_sa11_AttributeValue_ELEM	243
#define zx_sa_AttributeValue_ELEM	244
#define zx_se_faultstring_ELEM	245
#define zx_ff12_IDPProvidedNameIdentifier_ELEM	246
#define zx_ds_P_ELEM	247
#define zx_ds_KeyName_ELEM	248
#define zx_sa_NameID_ELEM	249
#define zx_ds_Modulus_ELEM	250
#define zx_ac_DigSig_ELEM	251
#define zx_ac_Password_ELEM	252
#define zx_ds_Transforms_ELEM	253
#define zx_xenc_Transforms_ELEM	254
#define zx_ds_PGPKeyID_ELEM	255
#define zx_ac_KeySharing_ELEM	256
#define zx_ac_Identification_ELEM	257
#define zx_sp11_AttributeQuery_ELEM	258
#define zx_sp_AttributeQuery_ELEM	259
#define zx_ff12_ProviderID_ELEM	260
#define zx_xenc_KeyReference_ELEM	261
#define zx_ac_PrincipalAuthenticationMechanism_ELEM	262
#define zx_ds_X509CRL_ELEM	263
#define zx_ds_X509IssuerSerial_ELEM	264
#define zx_ds_KeyValue_ELEM	265
#define zx_ds_Transform_ELEM	266
#define zx_ds_KeyInfo_ELEM	267
#define zx_ac_Length_ELEM	268
#define zx_sa_TestElem_ELEM	269
#define zx_se_detail_ELEM	270
#define zx_ds_X509SKI_ELEM	271
#endif
