/* generated file, do not edit! zxmd_ _ATTR
 * $Id$ */
#ifndef _zxmd__ATTR
#define _zxmd__ATTR
#define zxmd_ID_ATTR	0
#define zxmd_Name_ATTR	1
#define zxmd_xmlns_ATTR	2
#define zxmd_Target_ATTR	3
#define zxmd_DNSName_ATTR	4
#define zxmd_Decision_ATTR	5
#define zxmd_Namespace_ATTR	6
#define zxmd_NameFormat_ATTR	7
#define zxmd_Version_ATTR	8
#define zxmd_NameQualifier_ATTR	9
#define zxmd_isDefault_ATTR	10
#define zxmd_isRequired_ATTR	11
#define zxmd_IssueInstant_ATTR	12
#define zxmd_Resource_ATTR	13
#define zxmd_Recipient_ATTR	14
#define zxmd_index_ATTR	15
#define zxmd_SessionIndex_ATTR	16
#define zxmd_entityID_ATTR	17
#define zxmd_namespace_ATTR	18
#define zxmd_validUntil_ATTR	19
#define zxmd_ResponseLocation_ATTR	20
#define zxmd_InResponseTo_ATTR	21
#define zxmd_use_ATTR	22
#define zxmd_SessionNotOnOrAfter_ATTR	23
#define zxmd_Count_ATTR	24
#define zxmd_AuthnInstant_ATTR	25
#define zxmd_cacheDuration_ATTR	26
#define zxmd_NotBefore_ATTR	27
#define zxmd_WantAssertionsSigned_ATTR	28
#define zxmd_Format_ATTR	29
#define zxmd_NotOnOrAfter_ATTR	30
#define zxmd_WantAuthnRequestsSigned_ATTR	31
#define zxmd_AuthnRequestsSigned_ATTR	32
#define zxmd_Method_ATTR	33
#define zxmd_Id_ATTR	34
#define zxmd_MimeType_ATTR	35
#define zxmd_lang_ATTR	36
#define zxmd_Address_ATTR	37
#define zxmd_errorURL_ATTR	38
#define zxmd_Algorithm_ATTR	39
#define zxmd_SPProvidedID_ATTR	40
#define zxmd_affiliationOwnerID_ATTR	41
#define zxmd_Type_ATTR	42
#define zxmd_SPNameQualifier_ATTR	43
#define zxmd_contactType_ATTR	44
#define zxmd_FriendlyName_ATTR	45
#define zxmd_URI_ATTR	46
#define zxmd_Binding_ATTR	47
#define zxmd_ZX_TOK_NOT_FOUND_ATTR	48
#define zxmd_protocolSupportEnumeration_ATTR	49
#define zxmd_Location_ATTR	50
#define zxmd_Encoding_ATTR	51
#endif
/* generated file, do not edit! zxmd_ _ELEM
 * $Id$ */
#ifndef _zxmd__ELEM
#define _zxmd__ELEM
#define zxmd_ds_P_ELEM	0
#define zxmd_ds_XPath_ELEM	1
#define zxmd_sa_Statement_ELEM	2
#define zxmd_md_Extensions_ELEM	3
#define zxmd_ds_G_ELEM	4
#define zxmd_md_EmailAddress_ELEM	5
#define zxmd_md_GivenName_ELEM	6
#define zxmd_md_SurName_ELEM	7
#define zxmd_ds_Y_ELEM	8
#define zxmd_sa_Subject_ELEM	9
#define zxmd_ds_Signature_ELEM	10
#define zxmd_sa_Advice_ELEM	11
#define zxmd_sa_Audience_ELEM	12
#define zxmd_ds_Object_ELEM	13
#define zxmd_sa_AuthnContext_ELEM	14
#define zxmd_sa_AuthnStatement_ELEM	15
#define zxmd_xenc_OAEPparams_ELEM	16
#define zxmd_sa_ProxyRestriction_ELEM	17
#define zxmd_md_NameIDFormat_ELEM	18
#define zxmd_sa_Evidence_ELEM	19
#define zxmd_sa_AuthnContextDeclRef_ELEM	20
#define zxmd_sa_AuthnContextClassRef_ELEM	21
#define zxmd_sa_Action_ELEM	22
#define zxmd_sa_AuthzDecisionStatement_ELEM	23
#define zxmd_ds_Exponent_ELEM	24
#define zxmd_sa_Assertion_ELEM	25
#define zxmd_md_ArtifactResolutionService_ELEM	26
#define zxmd_md_AuthzService_ELEM	27
#define zxmd_root_ELEM	28
#define zxmd_md_NameIDMappingService_ELEM	29
#define zxmd_sa_NameID_ELEM	30
#define zxmd_md_AuthnQueryService_ELEM	31
#define zxmd_sa_AudienceRestriction_ELEM	32
#define zxmd_xenc_CipherReference_ELEM	33
#define zxmd_ds_SPKIData_ELEM	34
#define zxmd_ds_Reference_ELEM	35
#define zxmd_md_SPSSODescriptor_ELEM	36
#define zxmd_md_EntitiesDescriptor_ELEM	37
#define zxmd_ds_Seed_ELEM	38
#define zxmd_ds_PGPData_ELEM	39
#define zxmd_md_ContactPerson_ELEM	40
#define zxmd_ds_SignatureValue_ELEM	41
#define zxmd_ds_SignatureMethod_ELEM	42
#define zxmd_ds_PgenCounter_ELEM	43
#define zxmd_xenc_DataReference_ELEM	44
#define zxmd_sa_Attribute_ELEM	45
#define zxmd_xenc_AgreementMethod_ELEM	46
#define zxmd_ds_HMACOutputLength_ELEM	47
#define zxmd_ds_DigestMethod_ELEM	48
#define zxmd_ds_SPKISexp_ELEM	49
#define zxmd_md_AssertionConsumerService_ELEM	50
#define zxmd_sa_Conditions_ELEM	51
#define zxmd_md_OrganizationName_ELEM	52
#define zxmd_xenc_EncryptedData_ELEM	53
#define zxmd_sa_SubjectConfirmation_ELEM	54
#define zxmd_ds_Transforms_ELEM	55
#define zxmd_xenc_Transforms_ELEM	56
#define zxmd_md_ServiceName_ELEM	57
#define zxmd_md_OrganizationDisplayName_ELEM	58
#define zxmd_md_AffiliateMember_ELEM	59
#define zxmd_md_EntityDescriptor_ELEM	60
#define zxmd_md_Organization_ELEM	61
#define zxmd_md_ServiceDescription_ELEM	62
#define zxmd_sa_Condition_ELEM	63
#define zxmd_sa_OneTimeUse_ELEM	64
#define zxmd_sa_Issuer_ELEM	65
#define zxmd_xenc_KeySize_ELEM	66
#define zxmd_sa_SubjectConfirmationData_ELEM	67
#define zxmd_ds_X509IssuerName_ELEM	68
#define zxmd_xenc_EncryptionProperties_ELEM	69
#define zxmd_sa_BaseID_ELEM	70
#define zxmd_ds_Manifest_ELEM	71
#define zxmd_ds_SignedInfo_ELEM	72
#define zxmd_ds_DigestValue_ELEM	73
#define zxmd_ds_KeyName_ELEM	74
#define zxmd_xenc_KA_Nonce_ELEM	75
#define zxmd_ds_SignatureProperties_ELEM	76
#define zxmd_sa_AssertionURIRef_ELEM	77
#define zxmd_xenc_CipherValue_ELEM	78
#define zxmd_md_PDPDescriptor_ELEM	79
#define zxmd_xenc_CarriedKeyName_ELEM	80
#define zxmd_sa_SubjectLocality_ELEM	81
#define zxmd_md_IDPSSODescriptor_ELEM	82
#define zxmd_ds_X509SKI_ELEM	83
#define zxmd_ds_X509Data_ELEM	84
#define zxmd_sa_AttributeValue_ELEM	85
#define zxmd_ds_Modulus_ELEM	86
#define zxmd_sa_EncryptedAttribute_ELEM	87
#define zxmd_md_RoleDescriptor_ELEM	88
#define zxmd_md_AttributeConsumingService_ELEM	89
#define zxmd_md_EncryptionMethod_ELEM	90
#define zxmd_xenc_EncryptionMethod_ELEM	91
#define zxmd_ds_MgmtData_ELEM	92
#define zxmd_sa_AssertionIDRef_ELEM	93
#define zxmd_ds_X509SubjectName_ELEM	94
#define zxmd_md_AffiliationDescriptor_ELEM	95
#define zxmd_ds_PGPKeyID_ELEM	96
#define zxmd_md_AuthnAuthorityDescriptor_ELEM	97
#define zxmd_sa_AuthnContextDecl_ELEM	98
#define zxmd_sa_EncryptedAssertion_ELEM	99
#define zxmd_md_ManageNameIDService_ELEM	100
#define zxmd_md_AssertionIDRequestService_ELEM	101
#define zxmd_md_AttributeService_ELEM	102
#define zxmd_ds_CanonicalizationMethod_ELEM	103
#define zxmd_sa_AttributeStatement_ELEM	104
#define zxmd_md_SingleSignOnService_ELEM	105
#define zxmd_md_TelephoneNumber_ELEM	106
#define zxmd_md_Company_ELEM	107
#define zxmd_md_RequestedAttribute_ELEM	108
#define zxmd_ds_RetrievalMethod_ELEM	109
#define zxmd_ds_Q_ELEM	110
#define zxmd_xenc_EncryptionProperty_ELEM	111
#define zxmd_md_SingleLogoutService_ELEM	112
#define zxmd_xenc_CipherData_ELEM	113
#define zxmd_md_AttributeProfile_ELEM	114
#define zxmd_ds_KeyInfo_ELEM	115
#define zxmd_xenc_ReferenceList_ELEM	116
#define zxmd_md_OrganizationURL_ELEM	117
#define zxmd_md_AdditionalMetadataLocation_ELEM	118
#define zxmd_ds_SignatureProperty_ELEM	119
#define zxmd_ZX_TOK_NOT_FOUND_ELEM	120
#define zxmd_xenc_OriginatorKeyInfo_ELEM	121
#define zxmd_sa_TestElem_ELEM	122
#define zxmd_ds_X509CRL_ELEM	123
#define zxmd_ds_KeyValue_ELEM	124
#define zxmd_sa_AuthenticatingAuthority_ELEM	125
#define zxmd_xenc_RecipientKeyInfo_ELEM	126
#define zxmd_ds_Transform_ELEM	127
#define zxmd_sa_EncryptedID_ELEM	128
#define zxmd_xenc_KeyReference_ELEM	129
#define zxmd_ds_X509Certificate_ELEM	130
#define zxmd_ds_J_ELEM	131
#define zxmd_xenc_EncryptedKey_ELEM	132
#define zxmd_ds_DSAKeyValue_ELEM	133
#define zxmd_md_AttributeAuthorityDescriptor_ELEM	134
#define zxmd_ds_X509IssuerSerial_ELEM	135
#define zxmd_ds_PGPKeyPacket_ELEM	136
#define zxmd_md_KeyDescriptor_ELEM	137
#define zxmd_ds_RSAKeyValue_ELEM	138
#define zxmd_ds_X509SerialNumber_ELEM	139
#endif
