/* generated file, do not edit! zx_ _ATTR
 * $Id$ */
#ifndef _zx__ATTR
#define _zx__ATTR
#define zx_ID_ATTR	0
#define zx_Loc_ATTR	1
#define zx_Name_ATTR	2
#define zx_Count_ATTR	3
#define zx_Target_ATTR	4
#define zx_Consent_ATTR	5
#define zx_URI_ATTR	6
#define zx_Namespace_ATTR	7
#define zx_NameFormat_ATTR	8
#define zx_Reason_ATTR	9
#define zx_Version_ATTR	10
#define zx_NameQualifier_ATTR	11
#define zx_NotBefore_ATTR	12
#define zx_Comparison_ATTR	13
#define zx_Destination_ATTR	14
#define zx_SessionIndex_ATTR	15
#define zx_MimeType_ATTR	16
#define zx_Type_ATTR	17
#define zx_xmlns_ATTR	18
#define zx_Method_ATTR	19
#define zx_AuthnInstant_ATTR	20
#define zx_Resource_ATTR	21
#define zx_SessionNotOnOrAfter_ATTR	22
#define zx_FriendlyName_ATTR	23
#define zx_ZX_TOK_NOT_FOUND_ATTR	24
#define zx_Algorithm_ATTR	25
#define zx_ProtocolBinding_ATTR	26
#define zx_AllowCreate_ATTR	27
#define zx_AssertionConsumerServiceURL_ATTR	28
#define zx_AssertionConsumerServiceIndex_ATTR	29
#define zx_AttributeConsumingServiceIndex_ATTR	30
#define zx_Format_ATTR	31
#define zx_Id_ATTR	32
#define zx_Decision_ATTR	33
#define zx_Recipient_ATTR	34
#define zx_ProxyCount_ATTR	35
#define zx_InResponseTo_ATTR	36
#define zx_IsPassive_ATTR	37
#define zx_ForceAuthn_ATTR	38
#define zx_Address_ATTR	39
#define zx_Encoding_ATTR	40
#define zx_NotOnOrAfter_ATTR	41
#define zx_Value_ATTR	42
#define zx_SPProvidedID_ATTR	43
#define zx_ProviderID_ATTR	44
#define zx_ProviderName_ATTR	45
#define zx_IssueInstant_ATTR	46
#define zx_DNSName_ATTR	47
#define zx_SPNameQualifier_ATTR	48
#endif
/* generated file, do not edit! zx_ _ELEM
 * $Id$ */
#ifndef _zx__ELEM
#define _zx__ELEM
#define zx_ds_G_ELEM	0
#define zx_ds_Seed_ELEM	1
#define zx_se_Fault_ELEM	2
#define zx_sp_Status_ELEM	3
#define zx_ds_Signature_ELEM	4
#define zx_sp_StatusCode_ELEM	5
#define zx_ds_Y_ELEM	6
#define zx_sp_StatusMessage_ELEM	7
#define zx_ds_SignatureValue_ELEM	8
#define zx_ds_SignatureMethod_ELEM	9
#define zx_sa_Advice_ELEM	10
#define zx_sa_Subject_ELEM	11
#define zx_ds_SPKISexp_ELEM	12
#define zx_ds_SignatureProperties_ELEM	13
#define zx_ds_J_ELEM	14
#define zx_ds_SignatureProperty_ELEM	15
#define zx_ds_Exponent_ELEM	16
#define zx_sa_AuthnStatement_ELEM	17
#define zx_sp_Extensions_ELEM	18
#define zx_sp_SubjectQuery_ELEM	19
#define zx_sp_AssertionIDRequest_ELEM	20
#define zx_sa_SubjectLocality_ELEM	21
#define zx_ds_Q_ELEM	22
#define zx_sa_Audience_ELEM	23
#define zx_sa_Assertion_ELEM	24
#define zx_sa_Conditions_ELEM	25
#define zx_sa_Evidence_ELEM	26
#define zx_xenc_CarriedKeyName_ELEM	27
#define zx_sp_AuthnQuery_ELEM	28
#define zx_xenc_EncryptionMethod_ELEM	29
#define zx_xenc_EncryptedKey_ELEM	30
#define zx_sa_EncryptedAttribute_ELEM	31
#define zx_sa_SubjectConfirmation_ELEM	32
#define zx_xenc_EncryptionProperties_ELEM	33
#define zx_sa_Action_ELEM	34
#define zx_sa_AuthnContext_ELEM	35
#define zx_xenc_EncryptionProperty_ELEM	36
#define zx_sa_Condition_ELEM	37
#define zx_ds_XPath_ELEM	38
#define zx_ds_Object_ELEM	39
#define zx_sa_AuthenticatingAuthority_ELEM	40
#define zx_ds_X509IssuerName_ELEM	41
#define zx_ds_X509Certificate_ELEM	42
#define zx_ds_CanonicalizationMethod_ELEM	43
#define zx_sa_EncryptedAssertion_ELEM	44
#define zx_sa_AudienceRestriction_ELEM	45
#define zx_ds_DigestValue_ELEM	46
#define zx_ds_DigestMethod_ELEM	47
#define zx_xenc_DataReference_ELEM	48
#define zx_ds_Reference_ELEM	49
#define zx_ds_X509SubjectName_ELEM	50
#define zx_ds_DSAKeyValue_ELEM	51
#define zx_xenc_ReferenceList_ELEM	52
#define zx_root_ELEM	53
#define zx_ds_RetrievalMethod_ELEM	54
#define zx_ds_RSAKeyValue_ELEM	55
#define zx_sp_Artifact_ELEM	56
#define zx_se_Body_ELEM	57
#define zx_sp_NewID_ELEM	58
#define zx_sp_RequestedAuthnContext_ELEM	59
#define zx_sp_AuthnRequest_ELEM	60
#define zx_sp_Response_ELEM	61
#define zx_se_faultcode_ELEM	62
#define zx_sp_ArtifactResolve_ELEM	63
#define zx_sp_ArtifactResponse_ELEM	64
#define zx_sa_AuthzDecisionStatement_ELEM	65
#define zx_sp_AuthzDecisionQuery_ELEM	66
#define zx_sa_AssertionIDRef_ELEM	67
#define zx_sa_AssertionURIRef_ELEM	68
#define zx_sa_EncryptedID_ELEM	69
#define zx_sp_NameIDPolicy_ELEM	70
#define zx_sa_SubjectConfirmationData_ELEM	71
#define zx_sp_Terminate_ELEM	72
#define zx_sp_NameIDMappingRequest_ELEM	73
#define zx_sp_NameIDMappingResponse_ELEM	74
#define zx_ds_PGPKeyPacket_ELEM	75
#define zx_xenc_EncryptedData_ELEM	76
#define zx_sp_NewEncryptedID_ELEM	77
#define zx_ds_SignedInfo_ELEM	78
#define zx_ds_HMACOutputLength_ELEM	79
#define zx_sp_StatusDetail_ELEM	80
#define zx_xenc_KA_Nonce_ELEM	81
#define zx_xenc_CipherValue_ELEM	82
#define zx_xenc_KeySize_ELEM	83
#define zx_sa_Statement_ELEM	84
#define zx_xenc_CipherReference_ELEM	85
#define zx_sp_GetComplete_ELEM	86
#define zx_sp_Scoping_ELEM	87
#define zx_se_Envelope_ELEM	88
#define zx_xenc_OAEPparams_ELEM	89
#define zx_sp_SessionIndex_ELEM	90
#define zx_ds_Manifest_ELEM	91
#define zx_sa_AuthnContextDeclRef_ELEM	92
#define zx_sa_AuthnContextClassRef_ELEM	93
#define zx_sp_RequesterID_ELEM	94
#define zx_sp_IDPList_ELEM	95
#define zx_ds_SPKIData_ELEM	96
#define zx_xenc_AgreementMethod_ELEM	97
#define zx_ds_X509SerialNumber_ELEM	98
#define zx_ds_Modulus_ELEM	99
#define zx_sp_IDPEntry_ELEM	100
#define zx_sp_ManageNameIDRequest_ELEM	101
#define zx_sp_ManageNameIDResponse_ELEM	102
#define zx_sa_NameID_ELEM	103
#define zx_sp_LogoutRequest_ELEM	104
#define zx_sp_LogoutResponse_ELEM	105
#define zx_sa_Attribute_ELEM	106
#define zx_ds_Transforms_ELEM	107
#define zx_xenc_Transforms_ELEM	108
#define zx_sa_AuthnContextDecl_ELEM	109
#define zx_ds_PGPData_ELEM	110
#define zx_ds_PGPKeyID_ELEM	111
#define zx_sa_AttributeValue_ELEM	112
#define zx_ds_X509IssuerSerial_ELEM	113
#define zx_sa_AttributeStatement_ELEM	114
#define zx_sp_AttributeQuery_ELEM	115
#define zx_xenc_KeyReference_ELEM	116
#define zx_sa_OneTimeUse_ELEM	117
#define zx_ds_P_ELEM	118
#define zx_xenc_CipherData_ELEM	119
#define zx_se_faultstring_ELEM	120
#define zx_ds_X509Data_ELEM	121
#define zx_sa_ProxyRestriction_ELEM	122
#define zx_xenc_OriginatorKeyInfo_ELEM	123
#define zx_xenc_RecipientKeyInfo_ELEM	124
#define zx_ds_KeyValue_ELEM	125
#define zx_sa_BaseID_ELEM	126
#define zx_ZX_TOK_NOT_FOUND_ELEM	127
#define zx_se_detail_ELEM	128
#define zx_ds_KeyName_ELEM	129
#define zx_se_faultactor_ELEM	130
#define zx_se_Header_ELEM	131
#define zx_ds_X509CRL_ELEM	132
#define zx_ds_MgmtData_ELEM	133
#define zx_ds_KeyInfo_ELEM	134
#define zx_ds_Transform_ELEM	135
#define zx_ds_X509SKI_ELEM	136
#define zx_ds_PgenCounter_ELEM	137
#define zx_sa_Issuer_ELEM	138
#define zx_sa_TestElem_ELEM	139
#endif
