/* generated file, do not edit! zxwsf_ _ATTR
 * $Id$ */
#ifndef _zxwsf__ATTR
#define _zxwsf__ATTR
#define zxwsf_id_ATTR	0
#define zxwsf_uri_ATTR	1
#define zxwsf_redirect_ATTR	2
#define zxwsf_name_ATTR	3
#define zxwsf_redirectURL_ATTR	4
#define zxwsf_interact_ATTR	5
#define zxwsf_timestamp_ATTR	6
#define zxwsf_updateType_ATTR	7
#define zxwsf_descriptionIDRefs_ATTR	8
#define zxwsf_multiple_ATTR	9
#define zxwsf_link_ATTR	10
#define zxwsf_resultsType_ATTR	11
#define zxwsf_issueTo_ATTR	12
#define zxwsf_language_ATTR	13
#define zxwsf_messageID_ATTR	14
#define zxwsf_e_actor_ATTR	15
#define zxwsf_newEntryIDs_ATTR	16
#define zxwsf_version_ATTR	17
#define zxwsf_ref_ATTR	18
#define zxwsf_code_ATTR	19
#define zxwsf_title_ATTR	20
#define zxwsf_AssertionIssueInstant_ATTR	21
#define zxwsf_wsu_Id_ATTR	22
#define zxwsf_minChars_ATTR	23
#define zxwsf_e_mustUnderstand_ATTR	24
#define zxwsf_usage_ATTR	25
#define zxwsf_signed_ATTR	26
#define zxwsf_entryID_ATTR	27
#define zxwsf_moreLink_ATTR	28
#define zxwsf_type_ATTR	29
#define zxwsf_validUntil_ATTR	30
#define zxwsf_RelationshipType_ATTR	31
#define zxwsf_SessionIndex_ATTR	32
#define zxwsf_ZX_TOK_NOT_FOUND_ATTR	33
#define zxwsf_timeStamp_ATTR	34
#define zxwsf_confirmationURI_ATTR	35
#define zxwsf_format_ATTR	36
#define zxwsf_comment_ATTR	37
#define zxwsf_wantDSEPR_ATTR	38
#define zxwsf_value_ATTR	39
#define zxwsf_AuthenticationInstant_ATTR	40
#define zxwsf_EncodingType_ATTR	41
#define zxwsf_URI_ATTR	42
#define zxwsf_itemIDRef_ATTR	43
#define zxwsf_wsse_Usage_ATTR	44
#define zxwsf_ValueType_ATTR	45
#define zxwsf_xmlns_ATTR	46
#define zxwsf_svcMDID_ATTR	47
#define zxwsf_affiliationID_ATTR	48
#define zxwsf_Type_ATTR	49
#define zxwsf_maxInteractTime_ATTR	50
#define zxwsf_refToMessageID_ATTR	51
#define zxwsf_providerID_ATTR	52
#define zxwsf_maxChars_ATTR	53
#define zxwsf_reqID_ATTR	54
#define zxwsf_label_ATTR	55
#endif
/* generated file, do not edit! zxwsf_ _ELEM
 * $Id$ */
#ifndef _zxwsf__ELEM
#define _zxwsf__ELEM
#define zxwsf_a_To_ELEM	0
#define zxwsf_sec_Token_ELEM	1
#define zxwsf_b_Timeout_ELEM	2
#define zxwsf_is12_Text_ELEM	3
#define zxwsf_is_Text_ELEM	4
#define zxwsf_is12_Label_ELEM	5
#define zxwsf_is_Label_ELEM	6
#define zxwsf_wsu_Timestamp_ELEM	7
#define zxwsf_is12_Select_ELEM	8
#define zxwsf_is_Select_ELEM	9
#define zxwsf_is12_Item_ELEM	10
#define zxwsf_is_Item_ELEM	11
#define zxwsf_di_SvcMD_ELEM	12
#define zxwsf_di12_Status_ELEM	13
#define zxwsf_lu_Status_ELEM	14
#define zxwsf_is12_Status_ELEM	15
#define zxwsf_di_SvcMDID_ELEM	16
#define zxwsf_a_Metadata_ELEM	17
#define zxwsf_a_MessageID_ELEM	18
#define zxwsf_di_SvcMDQuery_ELEM	19
#define zxwsf_dise_Envelope_ELEM	20
#define zxwsf_e_Envelope_ELEM	21
#define zxwsf_root_ELEM	22
#define zxwsf_dise_detail_ELEM	23
#define zxwsf_e_detail_ELEM	24
#define zxwsf_di_SvcMDQueryResponse_ELEM	25
#define zxwsf_sec12_SessionSubject_ELEM	26
#define zxwsf_b_Sender_ELEM	27
#define zxwsf_di_SvcMDRegister_ELEM	28
#define zxwsf_di_SvcMDAssociationAdd_ELEM	29
#define zxwsf_di_SvcMDAssociationQuery_ELEM	30
#define zxwsf_di_SvcMDAssociationDelete_ELEM	31
#define zxwsf_b_InteractionService_ELEM	32
#define zxwsf_is12_InteractionService_ELEM	33
#define zxwsf_a_RelatesTo_ELEM	34
#define zxwsf_is12_InteractionStatement_ELEM	35
#define zxwsf_is_InteractionStatement_ELEM	36
#define zxwsf_di_SvcMDRegisterResponse_ELEM	37
#define zxwsf_di_SvcMDAssociationAddResponse_ELEM	38
#define zxwsf_wsse_Embedded_ELEM	39
#define zxwsf_di_SvcMDAssociationQueryResponse_ELEM	40
#define zxwsf_di_SvcMDAssociationDeleteResponse_ELEM	41
#define zxwsf_lu_TestResult_ELEM	42
#define zxwsf_sec12_Issuer_ELEM	43
#define zxwsf_is12_Inquiry_ELEM	44
#define zxwsf_is_Inquiry_ELEM	45
#define zxwsf_xenc_EncryptedData_ELEM	46
#define zxwsf_di12_EncryptedResourceID_ELEM	47
#define zxwsf_is12_EncryptedResourceID_ELEM	48
#define zxwsf_is12_Value_ELEM	49
#define zxwsf_is_Value_ELEM	50
#define zxwsf_di_SvcMDReplace_ELEM	51
#define zxwsf_is12_InteractionRequest_ELEM	52
#define zxwsf_is_InteractionRequest_ELEM	53
#define zxwsf_is12_InteractionResponse_ELEM	54
#define zxwsf_is_InteractionResponse_ELEM	55
#define zxwsf_a_RetryAfter_ELEM	56
#define zxwsf_di12_InsertEntry_ELEM	57
#define zxwsf_sec12_IssueInstant_ELEM	58
#define zxwsf_di12_Endpoint_ELEM	59
#define zxwsf_is12_Parameter_ELEM	60
#define zxwsf_is_Parameter_ELEM	61
#define zxwsf_di_SvcMDReplaceResponse_ELEM	62
#define zxwsf_di12_Modify_ELEM	63
#define zxwsf_di12_Extension_ELEM	64
#define zxwsf_lu_Extension_ELEM	65
#define zxwsf_is12_Extension_ELEM	66
#define zxwsf_a_ProblemIRI_ELEM	67
#define zxwsf_di12_ServiceType_ELEM	68
#define zxwsf_di_ServiceType_ELEM	69
#define zxwsf_a_EndpointReference_ELEM	70
#define zxwsf_b_EndpointUpdate_ELEM	71
#define zxwsf_di_EndpointContext_ELEM	72
#define zxwsf_sec12_ProxySubject_ELEM	73
#define zxwsf_wsse_Password_ELEM	74
#define zxwsf_ds_Signature_ELEM	75
#define zxwsf_di12_ResourceID_ELEM	76
#define zxwsf_is12_ResourceID_ELEM	77
#define zxwsf_sec_TokenPolicy_ELEM	78
#define zxwsf_wsu_Expires_ELEM	79
#define zxwsf_a_From_ELEM	80
#define zxwsf_di12_ResourceOffering_ELEM	81
#define zxwsf_b12_Consent_ELEM	82
#define zxwsf_b_Consent_ELEM	83
#define zxwsf_di12_Abstract_ELEM	84
#define zxwsf_di_Abstract_ELEM	85
#define zxwsf_di12_ServiceInstance_ELEM	86
#define zxwsf_sp_RequestedAuthnContext_ELEM	87
#define zxwsf_wsu_Created_ELEM	88
#define zxwsf_sec12_ResourceAccessStatement_ELEM	89
#define zxwsf_is12_Hint_ELEM	90
#define zxwsf_is_Hint_ELEM	91
#define zxwsf_di12_Query_ELEM	92
#define zxwsf_di_Query_ELEM	93
#define zxwsf_di_SvcMDDelete_ELEM	94
#define zxwsf_a_Address_ELEM	95
#define zxwsf_di_Address_ELEM	96
#define zxwsf_ZX_TOK_NOT_FOUND_ELEM	97
#define zxwsf_b_TargetIdentity_ELEM	98
#define zxwsf_di_RequestedService_ELEM	99
#define zxwsf_sec_TransitedProvider_ELEM	100
#define zxwsf_di12_QueryResponse_ELEM	101
#define zxwsf_di_QueryResponse_ELEM	102
#define zxwsf_sec12_SessionContext_ELEM	103
#define zxwsf_di12_RequestedServiceType_ELEM	104
#define zxwsf_sec_TransitedProviderPath_ELEM	105
#define zxwsf_a_ReplyTo_ELEM	106
#define zxwsf_b_Framework_ELEM	107
#define zxwsf_sbf_Framework_ELEM	108
#define zxwsf_di_Framework_ELEM	109
#define zxwsf_a_SoapAction_ELEM	110
#define zxwsf_di12_SoapAction_ELEM	111
#define zxwsf_dise_Header_ELEM	112
#define zxwsf_e_Header_ELEM	113
#define zxwsf_xenc_EncryptedKey_ELEM	114
#define zxwsf_sec12_SessionContextStatement_ELEM	115
#define zxwsf_dise_faultactor_ELEM	116
#define zxwsf_e_faultactor_ELEM	117
#define zxwsf_b12_Correlation_ELEM	118
#define zxwsf_is12_Confirm_ELEM	119
#define zxwsf_is_Confirm_ELEM	120
#define zxwsf_wsse_Security_ELEM	121
#define zxwsf_di12_ModifyResponse_ELEM	122
#define zxwsf_di12_Description_ELEM	123
#define zxwsf_di12_EncryptResourceID_ELEM	124
#define zxwsf_di12_AuthorizeRequester_ELEM	125
#define zxwsf_is12_Help_ELEM	126
#define zxwsf_is_Help_ELEM	127
#define zxwsf_di12_RemoveEntry_ELEM	128
#define zxwsf_sec12_NumberOfUses_ELEM	129
#define zxwsf_dise_faultcode_ELEM	130
#define zxwsf_e_faultcode_ELEM	131
#define zxwsf_di_SecurityContext_ELEM	132
#define zxwsf_dise_faultstring_ELEM	133
#define zxwsf_e_faultstring_ELEM	134
#define zxwsf_wsse_SecurityTokenReference_ELEM	135
#define zxwsf_b12_Provider_ELEM	136
#define zxwsf_di_SvcMDDeleteResponse_ELEM	137
#define zxwsf_di12_ProviderID_ELEM	138
#define zxwsf_sec12_ProviderID_ELEM	139
#define zxwsf_di_ProviderID_ELEM	140
#define zxwsf_a_Action_ELEM	141
#define zxwsf_di_Action_ELEM	142
#define zxwsf_di12_WsdlURI_ELEM	143
#define zxwsf_wsse_Username_ELEM	144
#define zxwsf_wsse_Reference_ELEM	145
#define zxwsf_di12_Option_ELEM	146
#define zxwsf_di_Option_ELEM	147
#define zxwsf_di12_Options_ELEM	148
#define zxwsf_di_Options_ELEM	149
#define zxwsf_wsse_UsernameToken_ELEM	150
#define zxwsf_wsse_TransformationParameters_ELEM	151
#define zxwsf_b_RedirectRequest_ELEM	152
#define zxwsf_is12_RedirectRequest_ELEM	153
#define zxwsf_b_SecurityMechID_ELEM	154
#define zxwsf_di_SecurityMechID_ELEM	155
#define zxwsf_di12_SecurityMechID_ELEM	156
#define zxwsf_b_UserInteraction_ELEM	157
#define zxwsf_is12_UserInteraction_ELEM	158
#define zxwsf_a_ProblemHeader_ELEM	159
#define zxwsf_di_Keys_ELEM	160
#define zxwsf_dise_Fault_ELEM	161
#define zxwsf_e_Fault_ELEM	162
#define zxwsf_a_FaultTo_ELEM	163
#define zxwsf_a_ProblemHeaderQName_ELEM	164
#define zxwsf_di_ServiceContext_ELEM	165
#define zxwsf_sec12_ProxyInfoConfirmationData_ELEM	166
#define zxwsf_dise_Body_ELEM	167
#define zxwsf_e_Body_ELEM	168
#define zxwsf_sa11_AssertionIDReference_ELEM	169
#define zxwsf_ds_KeyInfo_ELEM	170
#define zxwsf_sec12_ValidityRestrictionCondition_ELEM	171
#define zxwsf_a_ReferenceParameters_ELEM	172
#define zxwsf_di12_Credentials_ELEM	173
#define zxwsf_di12_CredentialRef_ELEM	174
#define zxwsf_di12_AuthenticateRequester_ELEM	175
#define zxwsf_wsse_KeyIdentifier_ELEM	176
#define zxwsf_wsse_BinarySecurityToken_ELEM	177
#define zxwsf_di12_AuthenticateSessionContext_ELEM	178
#define zxwsf_a_ProblemAction_ELEM	179
#define zxwsf_b_ApplicationEPR_ELEM	180
#define zxwsf_di12_ServiceNameRef_ELEM	181
#define zxwsf_wsse_Nonce_ELEM	182
#define zxwsf_ff12_RequestAuthnContext_ELEM	183
#define zxwsf_b12_UsageDirective_ELEM	184
#define zxwsf_b_UsageDirective_ELEM	185
#define zxwsf_md_KeyDescriptor_ELEM	186
#define zxwsf_b_CredentialsContext_ELEM	187
#define zxwsf_b12_ProcessingContext_ELEM	188
#define zxwsf_b_ProcessingContext_ELEM	189
#endif
