/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-ac.gperf  */
/* Computed positions: -k'5,$' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-ac.gperf"

/* c/zx-ac-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-ac-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 50
#define MIN_WORD_LENGTH 3
#define MAX_WORD_LENGTH 32
#define MIN_HASH_VALUE 3
#define MAX_HASH_VALUE 90
/* maximum key range = 88, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_ac_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 40,  0, 91, 91, 91,
       0, 91, 91, 50, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91,  0, 91, 20,
      30, 20,  5, 45,  0, 15, 91, 91, 40, 30,
       0, 91, 91, 91,  5,  5, 10, 91,  0, 15,
      91,  5, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91, 91, 91, 91, 91,
      91, 91, 91, 91, 91, 91
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[4]];
      /*FALLTHROUGH*/
      case 4:
      case 3:
        break;
    }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  3,  4,  5,  0,  0,  0,  9,  0,  0,  0, 13,
     0, 10,  6,  0,  8, 19, 20, 21, 22, 23, 14, 15, 21,  0,
    13, 19, 15, 21,  0, 13, 14, 20,  0, 22, 13, 19, 10, 11,
     0, 13,  9,  5,  0,  0, 23,  9, 20,  0,  0,  8,  4, 10,
     0,  0, 28,  0, 30,  0, 22, 13,  0, 25,  6,  0, 28, 29,
    20, 31,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0, 32,  0,
     0,  0,  0,  0,  0,  0, 30
  };

struct zx_el_tok zx_ac_el_tab[] =
  {
    {""}, {""}, {""},
#line 55 "c/zx-ac.gperf"
    {"SSL", sizeof(struct zx_ac_SSL_s)},
#line 37 "c/zx-ac.gperf"
    {"HTTP", sizeof(struct zx_ac_HTTP_s)},
#line 64 "c/zx-ac.gperf"
    {"Token", sizeof(struct zx_ac_Token_s)},
    {""}, {""}, {""},
#line 33 "c/zx-ac.gperf"
    {"Extension", sizeof(struct zx_ac_Extension_s)},
    {""}, {""}, {""},
#line 22 "c/zx-ac.gperf"
    {"ActivationPin", sizeof(struct zx_ac_ActivationPin_s)},
    {""},
#line 34 "c/zx-ac.gperf"
    {"Generation", sizeof(struct zx_ac_Generation_s)},
#line 44 "c/zx-ac.gperf"
    {"Length", sizeof(struct zx_ac_Length_s)},
    {""},
#line 23 "c/zx-ac.gperf"
    {"Alphabet", sizeof(struct zx_ac_Alphabet_s)},
#line 62 "c/zx-ac.gperf"
    {"TechnicalProtection", sizeof(struct zx_ac_TechnicalProtection_s)},
#line 53 "c/zx-ac.gperf"
    {"PrivateKeyProtection", sizeof(struct zx_ac_PrivateKeyProtection_s)},
#line 48 "c/zx-ac.gperf"
    {"OperationalProtection", sizeof(struct zx_ac_OperationalProtection_s)},
#line 20 "c/zx-ac.gperf"
    {"ActivationLimitSession", sizeof(struct zx_elem_s)},
#line 19 "c/zx-ac.gperf"
    {"ActivationLimitDuration", sizeof(struct zx_ac_ActivationLimitDuration_s)},
#line 40 "c/zx-ac.gperf"
    {"Identification", sizeof(struct zx_ac_Identification_s)},
#line 18 "c/zx-ac.gperf"
    {"ActivationLimit", sizeof(struct zx_ac_ActivationLimit_s)},
#line 21 "c/zx-ac.gperf"
    {"ActivationLimitUsages", sizeof(struct zx_ac_ActivationLimitUsages_s)},
    {""},
#line 57 "c/zx-ac.gperf"
    {"SecurityAudit", sizeof(struct zx_ac_SecurityAudit_s)},
#line 36 "c/zx-ac.gperf"
    {"GoverningAgreements", sizeof(struct zx_ac_GoverningAgreements_s)},
#line 51 "c/zx-ac.gperf"
    {"PreviousSession", sizeof(struct zx_ac_PreviousSession_s)},
#line 35 "c/zx-ac.gperf"
    {"GoverningAgreementRef", sizeof(struct zx_ac_GoverningAgreementRef_s)},
    {""},
#line 41 "c/zx-ac.gperf"
    {"KeyActivation", sizeof(struct zx_ac_KeyActivation_s)},
#line 66 "c/zx-ac.gperf"
    {"WrittenConsent", sizeof(struct zx_ac_WrittenConsent_s)},
#line 50 "c/zx-ac.gperf"
    {"PhysicalVerification", sizeof(struct zx_ac_PhysicalVerification_s)},
    {""},
#line 31 "c/zx-ac.gperf"
    {"DeactivationCallCenter", sizeof(struct zx_ac_DeactivationCallCenter_s)},
#line 29 "c/zx-ac.gperf"
    {"Authenticator", sizeof(struct zx_ac_Authenticator_s)},
#line 56 "c/zx-ac.gperf"
    {"SecretKeyProtection", sizeof(struct zx_ac_SecretKeyProtection_s)},
#line 43 "c/zx-ac.gperf"
    {"KeyStorage", sizeof(struct zx_ac_KeyStorage_s)},
#line 61 "c/zx-ac.gperf"
    {"SwitchAudit", sizeof(struct zx_ac_SwitchAudit_s)},
    {""},
#line 54 "c/zx-ac.gperf"
    {"ResumeSession", sizeof(struct zx_ac_ResumeSession_s)},
#line 38 "c/zx-ac.gperf"
    {"IPAddress", sizeof(struct zx_ac_IPAddress_s)},
#line 39 "c/zx-ac.gperf"
    {"IPSec", sizeof(struct zx_ac_IPSec_s)},
    {""}, {""},
#line 26 "c/zx-ac.gperf"
    {"AuthenticatingAuthority", sizeof(struct zx_ac_AuthenticatingAuthority_s)},
#line 60 "c/zx-ac.gperf"
    {"Smartcard", sizeof(struct zx_ac_Smartcard_s)},
#line 24 "c/zx-ac.gperf"
    {"AsymmetricDecryption", sizeof(struct zx_ac_AsymmetricDecryption_s)},
    {""}, {""},
#line 49 "c/zx-ac.gperf"
    {"Password", sizeof(struct zx_ac_Password_s)},
#line 65 "c/zx-ac.gperf"
    {"WTLS", sizeof(struct zx_ac_WTLS_s)},
#line 42 "c/zx-ac.gperf"
    {"KeySharing", sizeof(struct zx_ac_KeySharing_s)},
    {""}, {""},
#line 59 "c/zx-ac.gperf"
    {"SharedSecretDynamicPlaintext", sizeof(struct zx_ac_SharedSecretDynamicPlaintext_s)},
    {""},
#line 27 "c/zx-ac.gperf"
    {"AuthenticationContextStatement", sizeof(struct zx_ac_AuthenticationContextStatement_s)},
    {""},
#line 25 "c/zx-ac.gperf"
    {"AsymmetricKeyAgreement", sizeof(struct zx_ac_AsymmetricKeyAgreement_s)},
#line 63 "c/zx-ac.gperf"
    {"TimeSyncToken", sizeof(struct zx_ac_TimeSyncToken_s)},
    {""},
#line 46 "c/zx-ac.gperf"
    {"MobileNetworkNoEncryption", sizeof(struct zx_ac_MobileNetworkNoEncryption_s)},
#line 32 "c/zx-ac.gperf"
    {"DigSig", sizeof(struct zx_ac_DigSig_s)},
    {""},
#line 47 "c/zx-ac.gperf"
    {"MobileNetworkRadioEncryption", sizeof(struct zx_ac_MobileNetworkRadioEncryption_s)},
#line 58 "c/zx-ac.gperf"
    {"SharedSecretChallengeResponse", sizeof(struct zx_ac_SharedSecretChallengeResponse_s)},
#line 28 "c/zx-ac.gperf"
    {"AuthenticationMethod", sizeof(struct zx_ac_AuthenticationMethod_s)},
#line 45 "c/zx-ac.gperf"
    {"MobileNetworkEndToEndEncryption", sizeof(struct zx_ac_MobileNetworkEndToEndEncryption_s)},
    {""},
#line 67 "c/zx-ac.gperf"
    {"ZeroKnowledge", sizeof(struct zx_ac_ZeroKnowledge_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 52 "c/zx-ac.gperf"
    {"PrincipalAuthenticationMechanism", sizeof(struct zx_ac_PrincipalAuthenticationMechanism_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 30 "c/zx-ac.gperf"
    {"AuthenticatorTransportProtocol", sizeof(struct zx_ac_AuthenticatorTransportProtocol_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_ac_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_ac_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_ac_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_ac_el_tab[key];
          }
    }
  return 0;
}
#line 68 "c/zx-ac.gperf"

/* EOF */
