/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-b.gperf  */
/* Computed positions: -k'1' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-b.gperf"

/* c/zx-b-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-b-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 14
#define MIN_WORD_LENGTH 6
#define MAX_WORD_LENGTH 18
#define MIN_HASH_VALUE 7
#define MAX_HASH_VALUE 29
/* maximum key range = 23, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_b_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 14, 30,  0, 30, 15,
       0, 30, 30,  5, 30, 30, 30, 30, 30, 30,
       0, 30,  5, 10,  5,  0, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
      30, 30, 30, 30, 30, 30
    };
  return len + asso_values[(unsigned char)str[0]];
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  0,  0,  0,  7,  0,  9,  0,  0,  7,  0,
    14, 15,  6, 17, 18, 14, 15,  0,  0, 18, 14,  0,  0,  0,
    14, 14
  };

struct zx_el_tok zx_b_el_tab[] =
  {
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 19 "c/zx-b.gperf"
    {"Consent", sizeof(struct zx_b_Consent_s)},
    {""},
#line 22 "c/zx-b.gperf"
    {"Framework", sizeof(struct zx_b_Framework_s)},
    {""}, {""},
#line 29 "c/zx-b.gperf"
    {"Timeout", sizeof(struct zx_b_Timeout_s)},
    {""},
#line 30 "c/zx-b.gperf"
    {"UsageDirective", sizeof(struct zx_b_UsageDirective_s)},
#line 31 "c/zx-b.gperf"
    {"UserInteraction", sizeof(struct zx_b_UserInteraction_s)},
#line 27 "c/zx-b.gperf"
    {"Sender", sizeof(struct zx_b_Sender_s)},
#line 24 "c/zx-b.gperf"
    {"ProcessingContext", sizeof(struct zx_b_ProcessingContext_s)},
#line 20 "c/zx-b.gperf"
    {"CredentialsContext", sizeof(struct zx_b_CredentialsContext_s)},
#line 28 "c/zx-b.gperf"
    {"TargetIdentity", sizeof(struct zx_b_TargetIdentity_s)},
#line 25 "c/zx-b.gperf"
    {"RedirectRequest", sizeof(struct zx_b_RedirectRequest_s)},
    {""}, {""},
#line 23 "c/zx-b.gperf"
    {"InteractionService", sizeof(struct zx_b_InteractionService_s)},
#line 26 "c/zx-b.gperf"
    {"SecurityMechID", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 18 "c/zx-b.gperf"
    {"ApplicationEPR", sizeof(struct zx_b_ApplicationEPR_s)},
#line 21 "c/zx-b.gperf"
    {"EndpointUpdate", sizeof(struct zx_b_EndpointUpdate_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_b_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_b_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_b_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_b_el_tab[key];
          }
    }
  return 0;
}
#line 32 "c/zx-b.gperf"

/* EOF */
