/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-b12.gperf  */
/* Computed positions: -k'' */

#line 1 "c/zx-b12.gperf"

/* c/zx-b12-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-b12-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 5
#define MIN_WORD_LENGTH 7
#define MAX_WORD_LENGTH 17
#define MIN_HASH_VALUE 7
#define MAX_HASH_VALUE 17
/* maximum key range = 11, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
/*ARGSUSED*/
static unsigned int
zx_b12_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  return len;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  0,  0,  0,  7,  8,  0,  0, 11,  0,  0,
    14,  0,  0, 17
  };

struct zx_el_tok zx_b12_el_tab[] =
  {
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 18 "c/zx-b12.gperf"
    {"Consent", sizeof(struct zx_b12_Consent_s)},
#line 21 "c/zx-b12.gperf"
    {"Provider", sizeof(struct zx_b12_Provider_s)},
    {""}, {""},
#line 19 "c/zx-b12.gperf"
    {"Correlation", sizeof(struct zx_b12_Correlation_s)},
    {""}, {""},
#line 22 "c/zx-b12.gperf"
    {"UsageDirective", sizeof(struct zx_b12_UsageDirective_s)},
    {""}, {""},
#line 20 "c/zx-b12.gperf"
    {"ProcessingContext", sizeof(struct zx_b12_ProcessingContext_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_b12_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_b12_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_b12_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_b12_el_tab[key];
          }
    }
  return 0;
}
#line 23 "c/zx-b12.gperf"

/* EOF */
