/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-cb.gperf  */
/* Computed positions: -k'1,4' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-cb.gperf"

/* c/zx-cb-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-cb-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 38
#define MIN_WORD_LENGTH 2
#define MAX_WORD_LENGTH 19
#define MIN_HASH_VALUE 2
#define MAX_HASH_VALUE 59
/* maximum key range = 58, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_cb_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 30,  0, 25,  0, 40,
      60, 60, 60, 10, 60, 60, 60, 20,  5, 60,
      60, 20,  5, 15,  0,  0, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60,  0, 60, 60,
      15,  0, 60,  0, 60,  0, 60, 60, 60,  5,
      60,  0,  0, 60,  0,  0, 15, 25, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60, 60, 60, 60, 60,
      60, 60, 60, 60, 60, 60
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[3]];
      /*FALLTHROUGH*/
      case 3:
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

static unsigned char lengthtable[] =
  {
     0,  0,  2,  0,  4,  0,  6,  7,  0,  9, 10,  6,  7,  8,
    14, 10, 11, 12, 13, 14,  0,  6,  7,  8, 19,  5,  6, 12,
    13,  9,  0,  6, 12, 13, 14, 10,  6,  0,  0, 14,  0, 11,
     0,  0,  4,  0,  0,  0,  8,  9, 10,  0,  0,  0, 14,  0,
     0,  0,  0, 19
  };

struct zx_el_tok zx_cb_el_tab[] =
  {
    {""}, {""},
#line 19 "c/zx-cb.gperf"
    {"By", sizeof(struct zx_cb_By_s)},
    {""},
#line 25 "c/zx-cb.gperf"
    {"Data", sizeof(struct zx_cb_Data_s)},
    {""},
#line 26 "c/zx-cb.gperf"
    {"Delete", sizeof(struct zx_cb_Delete_s)},
#line 54 "c/zx-cb.gperf"
    {"Trigger", sizeof(struct zx_elem_s)},
    {""},
#line 55 "c/zx-cb.gperf"
    {"UsageType", sizeof(struct zx_cb_UsageType_s)},
#line 27 "c/zx-cb.gperf"
    {"DeleteItem", sizeof(struct zx_cb_DeleteItem_s)},
#line 39 "c/zx-cb.gperf"
    {"Notify", sizeof(struct zx_cb_Notify_s)},
#line 37 "c/zx-cb.gperf"
    {"NewData", sizeof(struct zx_cb_NewData_s)},
#line 42 "c/zx-cb.gperf"
    {"NotifyTo", sizeof(struct zx_cb_NotifyTo_s)},
#line 28 "c/zx-cb.gperf"
    {"DeleteResponse", sizeof(struct zx_cb_DeleteResponse_s)},
#line 49 "c/zx-cb.gperf"
    {"ResourceID", sizeof(struct zx_cb_ResourceID_s)},
#line 47 "c/zx-cb.gperf"
    {"ReportUsage", sizeof(struct zx_cb_ReportUsage_s)},
#line 38 "c/zx-cb.gperf"
    {"Notification", sizeof(struct zx_cb_Notification_s)},
#line 40 "c/zx-cb.gperf"
    {"NotifyAdminTo", sizeof(struct zx_cb_NotifyAdminTo_s)},
#line 41 "c/zx-cb.gperf"
    {"NotifyResponse", sizeof(struct zx_cb_NotifyResponse_s)},
    {""},
#line 51 "c/zx-cb.gperf"
    {"Select", sizeof(struct zx_elem_s)},
#line 46 "c/zx-cb.gperf"
    {"RefItem", sizeof(struct zx_cb_RefItem_s)},
#line 32 "c/zx-cb.gperf"
    {"ItemData", sizeof(struct zx_cb_ItemData_s)},
#line 48 "c/zx-cb.gperf"
    {"ReportUsageResponse", sizeof(struct zx_cb_ReportUsageResponse_s)},
#line 43 "c/zx-cb.gperf"
    {"Query", sizeof(struct zx_cb_Query_s)},
#line 35 "c/zx-cb.gperf"
    {"Modify", sizeof(struct zx_cb_Modify_s)},
#line 53 "c/zx-cb.gperf"
    {"Subscription", sizeof(struct zx_cb_Subscription_s)},
#line 33 "c/zx-cb.gperf"
    {"ItemSelection", sizeof(struct zx_cb_ItemSelection_s)},
#line 44 "c/zx-cb.gperf"
    {"QueryItem", sizeof(struct zx_cb_QueryItem_s)},
    {""},
#line 21 "c/zx-cb.gperf"
    {"Create", sizeof(struct zx_cb_Create_s)},
#line 34 "c/zx-cb.gperf"
    {"Modification", sizeof(struct zx_cb_Modification_s)},
#line 45 "c/zx-cb.gperf"
    {"QueryResponse", sizeof(struct zx_cb_QueryResponse_s)},
#line 36 "c/zx-cb.gperf"
    {"ModifyResponse", sizeof(struct zx_cb_ModifyResponse_s)},
#line 22 "c/zx-cb.gperf"
    {"CreateItem", sizeof(struct zx_cb_CreateItem_s)},
#line 52 "c/zx-cb.gperf"
    {"Status", sizeof(struct zx_cb_Status_s)},
    {""}, {""},
#line 23 "c/zx-cb.gperf"
    {"CreateResponse", sizeof(struct zx_cb_CreateResponse_s)},
    {""},
#line 18 "c/zx-cb.gperf"
    {"Aggregation", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 20 "c/zx-cb.gperf"
    {"Card", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 30 "c/zx-cb.gperf"
    {"Endpoint", sizeof(struct zx_elem_s)},
#line 31 "c/zx-cb.gperf"
    {"Extension", sizeof(struct zx_cb_Extension_s)},
#line 24 "c/zx-cb.gperf"
    {"Credential", sizeof(struct zx_cb_Credential_s)},
    {""}, {""}, {""},
#line 50 "c/zx-cb.gperf"
    {"SecurityMechID", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 29 "c/zx-cb.gperf"
    {"EncryptedResourceID", sizeof(struct zx_cb_EncryptedResourceID_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_cb_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_cb_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_cb_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_cb_el_tab[key];
          }
    }
  return 0;
}
#line 56 "c/zx-cb.gperf"

/* EOF */
