/* generated file, do not edit! zx_ _ATTR
 * $Id$ */
#ifndef _zx__ATTR
#define _zx__ATTR
#define zx_id_ATTR	0
#define zx_min_ATTR	1
#define zx_name_ATTR	2
#define zx_nym_ATTR	3
#define zx_title_ATTR	4
#define zx_number_ATTR	5
#define zx_duration_ATTR	6
#define zx_e_actor_ATTR	7
#define zx_Consent_ATTR	8
#define zx_redirect_ATTR	9
#define zx_namespace_ATTR	10
#define zx_Comparison_ATTR	11
#define zx_Address_ATTR	12
#define zx_interact_ATTR	13
#define zx_newEntryIDs_ATTR	14
#define zx_AuthnInstant_ATTR	15
#define zx_AttributeName_ATTR	16
#define zx_AuthnRequestsSigned_ATTR	17
#define zx_AuthenticationMethod_ATTR	18
#define zx_Id_ATTR	19
#define zx_wsu_Id_ATTR	20
#define zx_AttributeNamespace_ATTR	21
#define zx_code_ATTR	22
#define zx_maxInteractTime_ATTR	23
#define zx_AuthenticationInstant_ATTR	24
#define zx_descriptionIDRefs_ATTR	25
#define zx_contactType_ATTR	26
#define zx_consent_ATTR	27
#define zx_max_ATTR	28
#define zx_case_ATTR	29
#define zx_index_ATTR	30
#define zx_AssertionIssueInstant_ATTR	31
#define zx_comment_ATTR	32
#define zx_entityID_ATTR	33
#define zx_mechanism_ATTR	34
#define zx_Issuer_ATTR	35
#define zx_ReauthenticateOnOrAfter_ATTR	36
#define zx_messageID_ATTR	37
#define zx_Destination_ATTR	38
#define zx_IssueInstant_ATTR	39
#define zx_use_ATTR	40
#define zx_IPAddress_ATTR	41
#define zx_usage_ATTR	42
#define zx_format_ATTR	43
#define zx_IsPassive_ATTR	44
#define zx_AttributeConsumingServiceIndex_ATTR	45
#define zx_AssertionID_ATTR	46
#define zx_ID_ATTR	47
#define zx_uri_ATTR	48
#define zx_AssertionConsumerServiceIndex_ATTR	49
#define zx_updateType_ATTR	50
#define zx_medium_ATTR	51
#define zx_EncodingType_ATTR	52
#define zx_multiple_ATTR	53
#define zx_wantDSEPR_ATTR	54
#define zx_ForceAuthn_ATTR	55
#define zx_Format_ATTR	56
#define zx_FriendlyName_ATTR	57
#define zx_cacheDuration_ATTR	58
#define zx_link_ATTR	59
#define zx_Count_ATTR	60
#define zx_resultsType_ATTR	61
#define zx_issueTo_ATTR	62
#define zx_Decision_ATTR	63
#define zx_confirmationURI_ATTR	64
#define zx_AllowCreate_ATTR	65
#define zx_MinorVersion_ATTR	66
#define zx_AuthorityKind_ATTR	67
#define zx_type_ATTR	68
#define zx_WantAssertionsSigned_ATTR	69
#define zx_Reason_ATTR	70
#define zx_ProviderName_ATTR	71
#define zx_WantAuthnRequestsSigned_ATTR	72
#define zx_itemIDRef_ATTR	73
#define zx_version_ATTR	74
#define zx_Resource_ATTR	75
#define zx_isDefault_ATTR	76
#define zx_xmlns_ATTR	77
#define zx_RelationshipType_ATTR	78
#define zx_entryID_ATTR	79
#define zx_ref_ATTR	80
#define zx_SessionNotOnOrAfter_ATTR	81
#define zx_credentialLevel_ATTR	82
#define zx_Target_ATTR	83
#define zx_DNSName_ATTR	84
#define zx_requiredChars_ATTR	85
#define zx_timestamp_ATTR	86
#define zx_Nonce_ATTR	87
#define zx_ResponseLocation_ATTR	88
#define zx_SessionIndex_ATTR	89
#define zx_excludedChars_ATTR	90
#define zx_Name_ATTR	91
#define zx_isRequired_ATTR	92
#define zx_libertyPrincipalIdentifier_ATTR	93
#define zx_svcMDID_ATTR	94
#define zx_errorURL_ATTR	95
#define zx_NotBefore_ATTR	96
#define zx_DNSAddress_ATTR	97
#define zx_redirectURL_ATTR	98
#define zx_MajorVersion_ATTR	99
#define zx_language_ATTR	100
#define zx_ProviderID_ATTR	101
#define zx_signed_ATTR	102
#define zx_NotOnOrAfter_ATTR	103
#define zx_NameQualifier_ATTR	104
#define zx_Namespace_ATTR	105
#define zx_sharing_ATTR	106
#define zx_wsse_Usage_ATTR	107
#define zx_Version_ATTR	108
#define zx_moreLink_ATTR	109
#define zx_Algorithm_ATTR	110
#define zx_ResponseID_ATTR	111
#define zx_InResponseTo_ATTR	112
#define zx_minChars_ATTR	113
#define zx_RequestID_ATTR	114
#define zx_value_ATTR	115
#define zx_Method_ATTR	116
#define zx_Binding_ATTR	117
#define zx_Location_ATTR	118
#define zx_ProxyCount_ATTR	119
#define zx_AssertionConsumerServiceURL_ATTR	120
#define zx_affiliationID_ATTR	121
#define zx_Recipient_ATTR	122
#define zx_reqID_ATTR	123
#define zx_affiliationOwnerID_ATTR	124
#define zx_e_mustUnderstand_ATTR	125
#define zx_DeviceType_ATTR	126
#define zx_DeviceInHand_ATTR	127
#define zx_maxChars_ATTR	128
#define zx_refToMessageID_ATTR	129
#define zx_timeStamp_ATTR	130
#define zx_Loc_ATTR	131
#define zx_lang_ATTR	132
#define zx_MimeType_ATTR	133
#define zx_Type_ATTR	134
#define zx_Encoding_ATTR	135
#define zx_Value_ATTR	136
#define zx_ValueType_ATTR	137
#define zx_NameFormat_ATTR	138
#define zx_SPProvidedID_ATTR	139
#define zx_providerID_ATTR	140
#define zx_SPNameQualifier_ATTR	141
#define zx_URI_ATTR	142
#define zx_label_ATTR	143
#define zx_validUntil_ATTR	144
#define zx_protocolSupportEnumeration_ATTR	145
#define zx_ZX_TOK_NOT_FOUND_ATTR	146
#define zx_ProtocolBinding_ATTR	147
#define zx_governingAgreementRef_ATTR	148
#define zx_SeedLength_ATTR	149
#define zx__ATTR_MAX	150
#endif
/* generated file, do not edit! zx_ _ELEM
 * $Id$ */
#ifndef _zx__ELEM
#define _zx__ELEM
#define zx_ds_Y_ELEM	0
#define zx_ds_XPath_ELEM	1
#define zx_ds_J_ELEM	2
#define zx_ff12_Assertion_ELEM	3
#define zx_sa11_Assertion_ELEM	4
#define zx_sa_Assertion_ELEM	5
#define zx_is_Select_ELEM	6
#define zx_is12_Select_ELEM	7
#define zx_ac_Alphabet_ELEM	8
#define zx_root_ELEM	9
#define zx_sp_StatusCode_ELEM	10
#define zx_sp11_StatusCode_ELEM	11
#define zx_ff12_AuthnContext_ELEM	12
#define zx_sa_AuthnContext_ELEM	13
#define zx_di12_Abstract_ELEM	14
#define zx_di_Abstract_ELEM	15
#define zx_ds_SignedInfo_ELEM	16
#define zx_sa_Advice_ELEM	17
#define zx_sa11_Advice_ELEM	18
#define zx_sa11_Audience_ELEM	19
#define zx_sa_Audience_ELEM	20
#define zx_sa11_Statement_ELEM	21
#define zx_sa_Statement_ELEM	22
#define zx_a_Action_ELEM	23
#define zx_di_Action_ELEM	24
#define zx_sa11_Action_ELEM	25
#define zx_sa_Action_ELEM	26
#define zx_ff12_AuthnContextComparison_ELEM	27
#define zx_ac_ZeroKnowledge_ELEM	28
#define zx_sa_Attribute_ELEM	29
#define zx_sa11_Attribute_ELEM	30
#define zx_sp11_AssertionArtifact_ELEM	31
#define zx_sp_Artifact_ELEM	32
#define zx_ds_Signature_ELEM	33
#define zx_sp_ArtifactResolve_ELEM	34
#define zx_sp_ArtifactResponse_ELEM	35
#define zx_ff12_AuthnRequest_ELEM	36
#define zx_sp_AuthnRequest_ELEM	37
#define zx_sa_AudienceRestriction_ELEM	38
#define zx_ff12_AuthnRequestEnvelope_ELEM	39
#define zx_md_AuthnAuthorityDescriptor_ELEM	40
#define zx_md_ArtifactResolutionService_ELEM	41
#define zx_sa_AuthnContextDecl_ELEM	42
#define zx_md_AuthzService_ELEM	43
#define zx_sa11_AudienceRestrictionCondition_ELEM	44
#define zx_md_AttributeService_ELEM	45
#define zx_m20_SPDescriptor_ELEM	46
#define zx_ac_ActivationPin_ELEM	47
#define zx_sa_AuthnStatement_ELEM	48
#define zx_ac_ActivationLimit_ELEM	49
#define zx_m20_AffiliationDescriptor_ELEM	50
#define zx_md_AffiliationDescriptor_ELEM	51
#define zx_a_ReplyTo_ELEM	52
#define zx_sa_AttributeStatement_ELEM	53
#define zx_sa11_AttributeStatement_ELEM	54
#define zx_ac_ActivationLimitSession_ELEM	55
#define zx_ac_ActivationLimitDuration_ELEM	56
#define zx_ac_SharedSecretChallengeResponse_ELEM	57
#define zx_b_RedirectRequest_ELEM	58
#define zx_is12_RedirectRequest_ELEM	59
#define zx_ac_SharedSecretDynamicPlaintext_ELEM	60
#define zx_m20_AdditionalMetaLocation_ELEM	61
#define zx_md_AdditionalMetadataLocation_ELEM	62
#define zx_md_AttributeAuthorityDescriptor_ELEM	63
#define zx_ff12_AuthenticationStatement_ELEM	64
#define zx_sa11_AuthenticationStatement_ELEM	65
#define zx_b_ApplicationEPR_ELEM	66
#define zx_di12_AuthenticateSessionContext_ELEM	67
#define zx_sp_StatusDetail_ELEM	68
#define zx_sp11_StatusDetail_ELEM	69
#define zx_ac_Authenticator_ELEM	70
#define zx_is12_Hint_ELEM	71
#define zx_is_Hint_ELEM	72
#define zx_ac_AuthenticationContextStatement_ELEM	73
#define zx_b_InteractionService_ELEM	74
#define zx_is12_InteractionService_ELEM	75
#define zx_is_InteractionResponse_ELEM	76
#define zx_is12_InteractionResponse_ELEM	77
#define zx_a_RetryAfter_ELEM	78
#define zx_di12_AuthenticateRequester_ELEM	79
#define zx_sp11_Request_ELEM	80
#define zx_is_InteractionRequest_ELEM	81
#define zx_is12_InteractionRequest_ELEM	82
#define zx_is_InteractionStatement_ELEM	83
#define zx_is12_InteractionStatement_ELEM	84
#define zx_ac_SwitchAudit_ELEM	85
#define zx_md_AuthnQueryService_ELEM	86
#define zx_dise_Envelope_ELEM	87
#define zx_se_Envelope_ELEM	88
#define zx_e_Envelope_ELEM	89
#define zx_sa11_AssertionIDReference_ELEM	90
#define zx_ds_Q_ELEM	91
#define zx_ff12_Subject_ELEM	92
#define zx_sa11_Subject_ELEM	93
#define zx_sa_Subject_ELEM	94
#define zx_sp_AssertionIDRequest_ELEM	95
#define zx_ac_Extension_ELEM	96
#define zx_m20_Extension_ELEM	97
#define zx_lu_Extension_ELEM	98
#define zx_is12_Extension_ELEM	99
#define zx_ff12_Extension_ELEM	100
#define zx_di12_Extension_ELEM	101
#define zx_md_AssertionIDRequestService_ELEM	102
#define zx_sa_BaseID_ELEM	103
#define zx_ds_Exponent_ELEM	104
#define zx_sa_AttributeValue_ELEM	105
#define zx_sa11_AttributeValue_ELEM	106
#define zx_ac_AuthenticatorTransportProtocol_ELEM	107
#define zx_md_RequestedAttribute_ELEM	108
#define zx_ds_SignatureValue_ELEM	109
#define zx_ff12_RelayState_ELEM	110
#define zx_di_RequestedService_ELEM	111
#define zx_ff12_AffiliationID_ELEM	112
#define zx_di12_RequestedServiceType_ELEM	113
#define zx_sp_RequestedAuthnContext_ELEM	114
#define zx_xenc_DataReference_ELEM	115
#define zx_ff12_RequestAuthnContext_ELEM	116
#define zx_is12_Value_ELEM	117
#define zx_is_Value_ELEM	118
#define zx_ff12_AuthnResponse_ELEM	119
#define zx_ff12_RegisterNameIdentifierResponse_ELEM	120
#define zx_di12_Status_ELEM	121
#define zx_sp11_Status_ELEM	122
#define zx_sp_Status_ELEM	123
#define zx_lu_Status_ELEM	124
#define zx_is12_Status_ELEM	125
#define zx_ff12_RegisterNameIdentifierRequest_ELEM	126
#define zx_sa11_AuthorizationDecisionStatement_ELEM	127
#define zx_ff12_AuthnResponseEnvelope_ELEM	128
#define zx_m20_RegisterNameIdentifierProtocolProfile_ELEM	129
#define zx_sp11_StatusMessage_ELEM	130
#define zx_sp_StatusMessage_ELEM	131
#define zx_wsse_BinarySecurityToken_ELEM	132
#define zx_a_Address_ELEM	133
#define zx_di_Address_ELEM	134
#define zx_sa_EncryptedAttribute_ELEM	135
#define zx_sa11_AttributeDesignator_ELEM	136
#define zx_di12_RemoveEntry_ELEM	137
#define zx_sa_EncryptedAssertion_ELEM	138
#define zx_ac_Identification_ELEM	139
#define zx_di_Query_ELEM	140
#define zx_sp11_Query_ELEM	141
#define zx_di12_Query_ELEM	142
#define zx_sa_Issuer_ELEM	143
#define zx_sec12_Issuer_ELEM	144
#define zx_sp11_AuthenticationQuery_ELEM	145
#define zx_ac_AuthenticatingAuthority_ELEM	146
#define zx_sa_AuthenticatingAuthority_ELEM	147
#define zx_ac_WTLS_ELEM	148
#define zx_di_SecurityContext_ELEM	149
#define zx_wsse_SecurityTokenReference_ELEM	150
#define zx_sa11_SubjectStatement_ELEM	151
#define zx_di12_AuthorizeRequester_ELEM	152
#define zx_md_SingleLogoutService_ELEM	153
#define zx_ac_ActivationLimitUsages_ELEM	154
#define zx_ds_SPKIData_ELEM	155
#define zx_sp_AttributeQuery_ELEM	156
#define zx_sp11_AttributeQuery_ELEM	157
#define zx_sp_AuthnQuery_ELEM	158
#define zx_ds_DigestValue_ELEM	159
#define zx_m20_SingleLogoutProtocolProfile_ELEM	160
#define zx_md_SPSSODescriptor_ELEM	161
#define zx_di12_InsertEntry_ELEM	162
#define zx_di_QueryResponse_ELEM	163
#define zx_di12_QueryResponse_ELEM	164
#define zx_dise_Body_ELEM	165
#define zx_se_Body_ELEM	166
#define zx_e_Body_ELEM	167
#define zx_xenc_CipherReference_ELEM	168
#define zx_sec12_ValidityRestrictionCondition_ELEM	169
#define zx_md_SingleSignOnService_ELEM	170
#define zx_b_Sender_ELEM	171
#define zx_ds_Manifest_ELEM	172
#define zx_sa_AuthnContextDeclRef_ELEM	173
#define zx_ff12_AuthnContextClassRef_ELEM	174
#define zx_sa_AuthnContextClassRef_ELEM	175
#define zx_sa11_AuthorityBinding_ELEM	176
#define zx_m20_SingleSignOnProtocolProfile_ELEM	177
#define zx_sp_Response_ELEM	178
#define zx_sp11_Response_ELEM	179
#define zx_ff12_AuthnContextStatementRef_ELEM	180
#define zx_di12_ResourceID_ELEM	181
#define zx_is12_ResourceID_ELEM	182
#define zx_m20_AuthnRequestsSigned_ELEM	183
#define zx_a_SoapAction_ELEM	184
#define zx_di12_SoapAction_ELEM	185
#define zx_sp11_AuthorizationDecisionQuery_ELEM	186
#define zx_md_AssertionConsumerService_ELEM	187
#define zx_b12_Correlation_ELEM	188
#define zx_a_To_ELEM	189
#define zx_ac_ResumeSession_ELEM	190
#define zx_ac_Smartcard_ELEM	191
#define zx_ff12_EncryptableNameIdentifier_ELEM	192
#define zx_is_Inquiry_ELEM	193
#define zx_is12_Inquiry_ELEM	194
#define zx_ac_SecurityAudit_ELEM	195
#define zx_ac_Token_ELEM	196
#define zx_sec_Token_ELEM	197
#define zx_di_SvcMDDelete_ELEM	198
#define zx_b_Timeout_ELEM	199
#define zx_is_Text_ELEM	200
#define zx_is12_Text_ELEM	201
#define zx_ac_MobileNetworkNoEncryption_ELEM	202
#define zx_dise_detail_ELEM	203
#define zx_se_detail_ELEM	204
#define zx_e_detail_ELEM	205
#define zx_ac_MobileNetworkRadioEncryption_ELEM	206
#define zx_di_SvcMDDeleteResponse_ELEM	207
#define zx_m20_AffiliateMember_ELEM	208
#define zx_md_AffiliateMember_ELEM	209
#define zx_ac_MobileNetworkEndToEndEncryption_ELEM	210
#define zx_wsu_Expires_ELEM	211
#define zx_xenc_EncryptionProperty_ELEM	212
#define zx_md_AttributeConsumingService_ELEM	213
#define zx_wsse_Security_ELEM	214
#define zx_dise_faultactor_ELEM	215
#define zx_se_faultactor_ELEM	216
#define zx_e_faultactor_ELEM	217
#define zx_di12_WsdlURI_ELEM	218
#define zx_b_SecurityMechID_ELEM	219
#define zx_di_SecurityMechID_ELEM	220
#define zx_di12_SecurityMechID_ELEM	221
#define zx_ac_AuthenticationMethod_ELEM	222
#define zx_ac_DigSig_ELEM	223
#define zx_sp_SubjectQuery_ELEM	224
#define zx_sp11_SubjectQuery_ELEM	225
#define zx_xenc_EncryptedData_ELEM	226
#define zx_ds_Reference_ELEM	227
#define zx_wsse_Reference_ELEM	228
#define zx_ds_DigestMethod_ELEM	229
#define zx_di12_EncryptedResourceID_ELEM	230
#define zx_is12_EncryptedResourceID_ELEM	231
#define zx_ds_MgmtData_ELEM	232
#define zx_sec12_SessionSubject_ELEM	233
#define zx_m20_KeySize_ELEM	234
#define zx_xenc_KeySize_ELEM	235
#define zx_m20_EntitiesDescriptor_ELEM	236
#define zx_md_EntitiesDescriptor_ELEM	237
#define zx_md_ManageNameIDService_ELEM	238
#define zx_sp_ManageNameIDResponse_ELEM	239
#define zx_sp_RequesterID_ELEM	240
#define zx_sec12_ResourceAccessStatement_ELEM	241
#define zx_sp_ManageNameIDRequest_ELEM	242
#define zx_xenc_EncryptionProperties_ELEM	243
#define zx_dise_Header_ELEM	244
#define zx_se_Header_ELEM	245
#define zx_e_Header_ELEM	246
#define zx_sa_Evidence_ELEM	247
#define zx_sa11_Evidence_ELEM	248
#define zx_di_SvcMD_ELEM	249
#define zx_di12_Modify_ELEM	250
#define zx_di_SvcMDID_ELEM	251
#define zx_sa_AssertionIDRef_ELEM	252
#define zx_a_FaultTo_ELEM	253
#define zx_di12_Endpoint_ELEM	254
#define zx_dise_Fault_ELEM	255
#define zx_se_Fault_ELEM	256
#define zx_e_Fault_ELEM	257
#define zx_a_EndpointReference_ELEM	258
#define zx_di_SvcMDQueryResponse_ELEM	259
#define zx_di_EndpointContext_ELEM	260
#define zx_xenc_CipherValue_ELEM	261
#define zx_wsse_Username_ELEM	262
#define zx_md_RoleDescriptor_ELEM	263
#define zx_ac_IPSec_ELEM	264
#define zx_sa_EncryptedID_ELEM	265
#define zx_a_Metadata_ELEM	266
#define zx_lu_TestResult_ELEM	267
#define zx_ds_PgenCounter_ELEM	268
#define zx_wsse_UsernameToken_ELEM	269
#define zx_ff12_AssertionConsumerServiceID_ELEM	270
#define zx_sec12_IssueInstant_ELEM	271
#define zx_ff12_FederationTerminationNotification_ELEM	272
#define zx_a_RelatesTo_ELEM	273
#define zx_ac_KeyStorage_ELEM	274
#define zx_di12_Description_ELEM	275
#define zx_b_Consent_ELEM	276
#define zx_b12_Consent_ELEM	277
#define zx_sa11_DoNotCacheCondition_ELEM	278
#define zx_xenc_CipherData_ELEM	279
#define zx_md_AttributeProfile_ELEM	280
#define zx_xenc_KeyReference_ELEM	281
#define zx_m20_FederationTerminationNotificationProtocolProfile_ELEM	282
#define zx_sa_SubjectConfirmation_ELEM	283
#define zx_sa11_SubjectConfirmation_ELEM	284
#define zx_xenc_RecipientKeyInfo_ELEM	285
#define zx_ac_SecretKeyProtection_ELEM	286
#define zx_md_EncryptionMethod_ELEM	287
#define zx_m20_EncryptionMethod_ELEM	288
#define zx_xenc_EncryptionMethod_ELEM	289
#define zx_ds_KeyValue_ELEM	290
#define zx_ff12_ProtocolProfile_ELEM	291
#define zx_is_Parameter_ELEM	292
#define zx_is12_Parameter_ELEM	293
#define zx_ds_KeyInfo_ELEM	294
#define zx_ff12_Scoping_ELEM	295
#define zx_sp_Scoping_ELEM	296
#define zx_sec12_SessionContext_ELEM	297
#define zx_md_Extensions_ELEM	298
#define zx_sp_Extensions_ELEM	299
#define zx_md_IDPSSODescriptor_ELEM	300
#define zx_b_UserInteraction_ELEM	301
#define zx_is12_UserInteraction_ELEM	302
#define zx_sec12_SessionContextStatement_ELEM	303
#define zx_ac_WrittenConsent_ELEM	304
#define zx_ds_Modulus_ELEM	305
#define zx_ds_Seed_ELEM	306
#define zx_sp11_RespondWith_ELEM	307
#define zx_sa_SubjectConfirmationData_ELEM	308
#define zx_sa11_SubjectConfirmationData_ELEM	309
#define zx_sa_AuthzDecisionStatement_ELEM	310
#define zx_ff12_IDPEntry_ELEM	311
#define zx_sp_IDPEntry_ELEM	312
#define zx_m20_EntityDescriptor_ELEM	313
#define zx_md_EntityDescriptor_ELEM	314
#define zx_m20_SurName_ELEM	315
#define zx_md_SurName_ELEM	316
#define zx_sa11_Condition_ELEM	317
#define zx_sa_Condition_ELEM	318
#define zx_di_SvcMDQuery_ELEM	319
#define zx_ds_Object_ELEM	320
#define zx_di12_ModifyResponse_ELEM	321
#define zx_xenc_AgreementMethod_ELEM	322
#define zx_di12_EncryptResourceID_ELEM	323
#define zx_dise_faultcode_ELEM	324
#define zx_se_faultcode_ELEM	325
#define zx_e_faultcode_ELEM	326
#define zx_di12_ResourceOffering_ELEM	327
#define zx_m20_IDPDescriptor_ELEM	328
#define zx_ac_Generation_ELEM	329
#define zx_dise_faultstring_ELEM	330
#define zx_se_faultstring_ELEM	331
#define zx_e_faultstring_ELEM	332
#define zx_m20_SoapEndpoint_ELEM	333
#define zx_di12_Option_ELEM	334
#define zx_di_Option_ELEM	335
#define zx_ac_DeactivationCallCenter_ELEM	336
#define zx_ff12_NameIdentifierMappingResponse_ELEM	337
#define zx_ds_RSAKeyValue_ELEM	338
#define zx_ff12_NameIdentifierMappingRequest_ELEM	339
#define zx_sa11_NameIdentifier_ELEM	340
#define zx_ds_SignatureMethod_ELEM	341
#define zx_m20_NameIdentifierMappingProtocolProfile_ELEM	342
#define zx_ds_PGPData_ELEM	343
#define zx_m20_NameIdentifierMappingEncryptionProfile_ELEM	344
#define zx_wsu_Created_ELEM	345
#define zx_a_ProblemAction_ELEM	346
#define zx_ff12_IsPassive_ELEM	347
#define zx_ds_X509SerialNumber_ELEM	348
#define zx_ds_SignatureProperty_ELEM	349
#define zx_ff12_SPProvidedNameIdentifier_ELEM	350
#define zx_ff12_IDPProvidedNameIdentifier_ELEM	351
#define zx_di_SvcMDReplace_ELEM	352
#define zx_m20_EmailAddress_ELEM	353
#define zx_md_EmailAddress_ELEM	354
#define zx_ds_X509Data_ELEM	355
#define zx_ds_X509IssuerName_ELEM	356
#define zx_di_SvcMDReplaceResponse_ELEM	357
#define zx_ds_X509SKI_ELEM	358
#define zx_b_CredentialsContext_ELEM	359
#define zx_wsse_TransformationParameters_ELEM	360
#define zx_is_Help_ELEM	361
#define zx_is12_Help_ELEM	362
#define zx_ff12_TargetNamespace_ELEM	363
#define zx_ac_PhysicalVerification_ELEM	364
#define zx_sa_NameID_ELEM	365
#define zx_ds_CanonicalizationMethod_ELEM	366
#define zx_ds_DSAKeyValue_ELEM	367
#define zx_sp_AuthzDecisionQuery_ELEM	368
#define zx_ds_SignatureProperties_ELEM	369
#define zx_ac_OperationalProtection_ELEM	370
#define zx_ds_SPKISexp_ELEM	371
#define zx_ff12_IDPEntries_ELEM	372
#define zx_ds_X509IssuerSerial_ELEM	373
#define zx_m20_Company_ELEM	374
#define zx_md_Company_ELEM	375
#define zx_wsse_Embedded_ELEM	376
#define zx_ac_TimeSyncToken_ELEM	377
#define zx_sp_Terminate_ELEM	378
#define zx_ds_RetrievalMethod_ELEM	379
#define zx_sp_NameIDPolicy_ELEM	380
#define zx_ff12_NameIDPolicy_ELEM	381
#define zx_b_EndpointUpdate_ELEM	382
#define zx_ac_SSL_ELEM	383
#define zx_ds_HMACOutputLength_ELEM	384
#define zx_xenc_EncryptedKey_ELEM	385
#define zx_a_MessageID_ELEM	386
#define zx_ff12_ProxyCount_ELEM	387
#define zx_is12_Label_ELEM	388
#define zx_is_Label_ELEM	389
#define zx_ds_Transform_ELEM	390
#define zx_m20_OrganizationName_ELEM	391
#define zx_md_OrganizationName_ELEM	392
#define zx_m20_Organization_ELEM	393
#define zx_md_Organization_ELEM	394
#define zx_sa_AssertionURIRef_ELEM	395
#define zx_di_SvcMDRegisterResponse_ELEM	396
#define zx_m20_OrganizationDisplayName_ELEM	397
#define zx_md_OrganizationDisplayName_ELEM	398
#define zx_di_Keys_ELEM	399
#define zx_ac_AsymmetricDecryption_ELEM	400
#define zx_ac_AsymmetricKeyAgreement_ELEM	401
#define zx_ds_Transforms_ELEM	402
#define zx_xenc_Transforms_ELEM	403
#define zx_di_SvcMDRegister_ELEM	404
#define zx_ac_IPAddress_ELEM	405
#define zx_ff12_ForceAuthn_ELEM	406
#define zx_m20_ContactPerson_ELEM	407
#define zx_md_ContactPerson_ELEM	408
#define zx_ac_GoverningAgreements_ELEM	409
#define zx_di_Options_ELEM	410
#define zx_di12_Options_ELEM	411
#define zx_m20_AuthnServiceURL_ELEM	412
#define zx_di_ServiceContext_ELEM	413
#define zx_di12_ServiceInstance_ELEM	414
#define zx_ff12_EncryptedNameIdentifier_ELEM	415
#define zx_b_Framework_ELEM	416
#define zx_sbf_Framework_ELEM	417
#define zx_di_Framework_ELEM	418
#define zx_sec12_ProxySubject_ELEM	419
#define zx_md_ServiceDescription_ELEM	420
#define zx_ff12_LogoutRequest_ELEM	421
#define zx_sp_LogoutRequest_ELEM	422
#define zx_a_ProblemHeaderQName_ELEM	423
#define zx_sp_NewID_ELEM	424
#define zx_sec_TransitedProviderPath_ELEM	425
#define zx_ff12_SessionIndex_ELEM	426
#define zx_sp_SessionIndex_ELEM	427
#define zx_is_Item_ELEM	428
#define zx_is12_Item_ELEM	429
#define zx_ds_X509Certificate_ELEM	430
#define zx_di12_Credentials_ELEM	431
#define zx_a_ProblemHeader_ELEM	432
#define zx_sec_TransitedProvider_ELEM	433
#define zx_ff12_IDPList_ELEM	434
#define zx_sp_IDPList_ELEM	435
#define zx_ds_P_ELEM	436
#define zx_di_SvcMDAssociationDelete_ELEM	437
#define zx_wsse_KeyIdentifier_ELEM	438
#define zx_sa_ProxyRestriction_ELEM	439
#define zx_di_SvcMDAssociationAddResponse_ELEM	440
#define zx_m20_KeyDescriptor_ELEM	441
#define zx_md_KeyDescriptor_ELEM	442
#define zx_di_SvcMDAssociationQueryResponse_ELEM	443
#define zx_di_SvcMDAssociationDeleteResponse_ELEM	444
#define zx_xenc_OriginatorKeyInfo_ELEM	445
#define zx_xenc_CarriedKeyName_ELEM	446
#define zx_ac_KeyActivation_ELEM	447
#define zx_ac_TechnicalProtection_ELEM	448
#define zx_sec_TokenPolicy_ELEM	449
#define zx_wsse_Nonce_ELEM	450
#define zx_ac_GoverningAgreementRef_ELEM	451
#define zx_md_PDPDescriptor_ELEM	452
#define zx_md_NameIDMappingService_ELEM	453
#define zx_sp_NameIDMappingResponse_ELEM	454
#define zx_ac_PrincipalAuthenticationMechanism_ELEM	455
#define zx_sec12_ProxyTransitedStatement_ELEM	456
#define zx_m20_GivenName_ELEM	457
#define zx_md_GivenName_ELEM	458
#define zx_sp_NameIDMappingRequest_ELEM	459
#define zx_md_NameIDFormat_ELEM	460
#define zx_ff12_GetComplete_ELEM	461
#define zx_sp_GetComplete_ELEM	462
#define zx_ds_PGPKeyPacket_ELEM	463
#define zx_m20_RegisterNameIdentifierServiceURL_ELEM	464
#define zx_b12_Provider_ELEM	465
#define zx_m20_RegisterNameIdentifierServiceReturnURL_ELEM	466
#define zx_is_Confirm_ELEM	467
#define zx_is12_Confirm_ELEM	468
#define zx_di12_CredentialRef_ELEM	469
#define zx_ac_KeySharing_ELEM	470
#define zx_ac_Length_ELEM	471
#define zx_sa_Conditions_ELEM	472
#define zx_sa11_Conditions_ELEM	473
#define zx_ds_KeyName_ELEM	474
#define zx_xenc_KA_Nonce_ELEM	475
#define zx_m20_TelephoneNumber_ELEM	476
#define zx_md_TelephoneNumber_ELEM	477
#define zx_sa11_ConfirmationMethod_ELEM	478
#define zx_ff12_ProviderName_ELEM	479
#define zx_wsu_Timestamp_ELEM	480
#define zx_ff12_LogoutResponse_ELEM	481
#define zx_sp_LogoutResponse_ELEM	482
#define zx_di_SvcMDAssociationQuery_ELEM	483
#define zx_m20_SingleLogoutServiceURL_ELEM	484
#define zx_ac_HTTP_ELEM	485
#define zx_a_ProblemIRI_ELEM	486
#define zx_m20_SingleLogoutServiceReturnURL_ELEM	487
#define zx_sp_NewEncryptedID_ELEM	488
#define zx_b_TargetIdentity_ELEM	489
#define zx_ds_X509SubjectName_ELEM	490
#define zx_m20_SingleSignOnServiceURL_ELEM	491
#define zx_a_ReferenceParameters_ELEM	492
#define zx_ff12_Loc_ELEM	493
#define zx_b_UsageDirective_ELEM	494
#define zx_b12_UsageDirective_ELEM	495
#define zx_m20_AssertionConsumerServiceURL_ELEM	496
#define zx_ff12_AssertionConsumerServiceURL_ELEM	497
#define zx_b_ProcessingContext_ELEM	498
#define zx_b12_ProcessingContext_ELEM	499
#define zx_sa_TestElem_ELEM	500
#define zx_ac_PreviousSession_ELEM	501
#define zx_ZX_TOK_NOT_FOUND_ELEM	502
#define zx_ff12_OldProvidedNameIdentifier_ELEM	503
#define zx_ds_PGPKeyID_ELEM	504
#define zx_a_From_ELEM	505
#define zx_di12_ServiceType_ELEM	506
#define zx_di_ServiceType_ELEM	507
#define zx_ds_G_ELEM	508
#define zx_di_SvcMDAssociationAdd_ELEM	509
#define zx_xenc_ReferenceList_ELEM	510
#define zx_ac_Password_ELEM	511
#define zx_wsse_Password_ELEM	512
#define zx_di12_ProviderID_ELEM	513
#define zx_sec12_ProviderID_ELEM	514
#define zx_ff12_ProviderID_ELEM	515
#define zx_di_ProviderID_ELEM	516
#define zx_m20_FederationTerminationServiceURL_ELEM	517
#define zx_m20_FederationTerminationServiceReturnURL_ELEM	518
#define zx_ds_X509CRL_ELEM	519
#define zx_sec12_ProxyInfoConfirmationData_ELEM	520
#define zx_sa_SubjectLocality_ELEM	521
#define zx_sa11_SubjectLocality_ELEM	522
#define zx_md_ServiceName_ELEM	523
#define zx_sec12_NumberOfUses_ELEM	524
#define zx_sa_OneTimeUse_ELEM	525
#define zx_ac_PrivateKeyProtection_ELEM	526
#define zx_xenc_OAEPparams_ELEM	527
#define zx_m20_OrganizationURL_ELEM	528
#define zx_md_OrganizationURL_ELEM	529
#define zx_di12_ServiceNameRef_ELEM	530
#define zx__ELEM_MAX	531
#endif
