/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-cdm.gperf  */
/* Computed positions: -k'1,3-4' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-cdm.gperf"

/* c/zx-cdm-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-cdm-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 89
#define MIN_WORD_LENGTH 1
#define MAX_WORD_LENGTH 16
#define MIN_HASH_VALUE 2
#define MAX_HASH_VALUE 194
/* maximum key range = 193, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_cdm_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195,   0,   0,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195,   5,  55,   5,  35,  10,
       15,  90,  35,   5,  65,  15,   0,   5,  45,  35,
        0,  75, 110,  55,   0,  10,  35,  10,   0,  80,
       70, 195, 195, 195, 195, 195, 195, 195,  10, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195,   5, 195, 195, 195,   5, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195, 195, 195, 195,
      195, 195, 195, 195, 195, 195, 195
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[3]];
      /*FALLTHROUGH*/
      case 3:
        hval += asso_values[(unsigned char)str[2]+1];
      /*FALLTHROUGH*/
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

static unsigned char lengthtable[] =
  {
     0,  0,  2,  3,  4,  5,  6,  0,  3,  0, 10,  6,  0,  3,
     4,  5,  0,  2,  3,  4,  5,  0,  0,  3,  9,  5,  6,  0,
     0,  0,  5,  6,  0,  8,  4, 10,  6,  0,  3,  0,  5,  6,
     0,  3,  4,  5,  1,  0,  8,  4,  5, 16,  0,  8,  0,  0,
     6,  0,  3,  4,  5,  6,  0,  3,  4,  0,  6, 12,  8,  4,
     5,  6,  0,  3,  4,  5,  6,  0,  3,  4,  0,  0,  0,  3,
     4,  0,  0,  7,  3,  4,  0,  0,  0,  3,  4,  0,  6,  0,
     3,  0,  0,  6,  7,  8,  0,  0,  0,  7,  0,  0,  5,  0,
     0,  0,  0,  5,  0,  0,  0,  0,  5, 11,  7,  3,  0,  0,
     6,  0,  0,  4,  0,  6,  0,  8,  0,  0,  0,  0,  0, 14,
     5,  6,  0,  0,  4,  0,  0,  0,  0,  0,  0,  6,  7,  0,
     0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  5,  6,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4
  };

struct zx_el_tok zx_cdm_el_tab[] =
  {
    {""}, {""},
#line 96 "c/zx-cdm.gperf"
    {"TZ", sizeof(struct zx_cdm_TZ_s)},
#line 74 "c/zx-cdm.gperf"
    {"PCS", sizeof(struct zx_elem_s)},
#line 105 "c/zx-cdm.gperf"
    {"X400", sizeof(struct zx_elem_s)},
#line 76 "c/zx-cdm.gperf"
    {"PHOTO", sizeof(struct zx_cdm_PHOTO_s)},
#line 79 "c/zx-cdm.gperf"
    {"POSTAL", sizeof(struct zx_elem_s)},
    {""},
#line 93 "c/zx-cdm.gperf"
    {"TEL", sizeof(struct zx_cdm_TEL_s)},
    {""},
#line 56 "c/zx-cdm.gperf"
    {"LISTMEMBER", sizeof(struct zx_cdm_LISTMEMBER_s)},
#line 84 "c/zx-cdm.gperf"
    {"PUBLIC", sizeof(struct zx_elem_s)},
    {""},
#line 54 "c/zx-cdm.gperf"
    {"LAT", sizeof(struct zx_cdm_LAT_s)},
#line 28 "c/zx-cdm.gperf"
    {"CELL", sizeof(struct zx_elem_s)},
#line 94 "c/zx-cdm.gperf"
    {"TITLE", sizeof(struct zx_cdm_TITLE_s)},
    {""},
#line 43 "c/zx-cdm.gperf"
    {"FN", sizeof(struct zx_cdm_FN_s)},
#line 99 "c/zx-cdm.gperf"
    {"URL", sizeof(struct zx_cdm_URL_s)},
#line 48 "c/zx-cdm.gperf"
    {"INTL", sizeof(struct zx_elem_s)},
#line 53 "c/zx-cdm.gperf"
    {"LABEL", sizeof(struct zx_cdm_LABEL_s)},
    {""}, {""},
#line 97 "c/zx-cdm.gperf"
    {"UID", sizeof(struct zx_cdm_UID_s)},
#line 23 "c/zx-cdm.gperf"
    {"CALADRURI", sizeof(struct zx_cdm_CALADRURI_s)},
#line 106 "c/zx-cdm.gperf"
    {"vCard", sizeof(struct zx_cdm_vCard_s)},
#line 24 "c/zx-cdm.gperf"
    {"CALURI", sizeof(struct zx_cdm_CALURI_s)},
    {""}, {""}, {""},
#line 62 "c/zx-cdm.gperf"
    {"MODEM", sizeof(struct zx_elem_s)},
#line 37 "c/zx-cdm.gperf"
    {"EXTADR", sizeof(struct zx_cdm_EXTADR_s)},
    {""},
#line 47 "c/zx-cdm.gperf"
    {"INTERNET", sizeof(struct zx_elem_s)},
#line 80 "c/zx-cdm.gperf"
    {"PREF", sizeof(struct zx_elem_s)},
#line 27 "c/zx-cdm.gperf"
    {"CATEGORIES", sizeof(struct zx_cdm_CATEGORIES_s)},
#line 81 "c/zx-cdm.gperf"
    {"PREFIX", sizeof(struct zx_cdm_PREFIX_s)},
    {""},
#line 59 "c/zx-cdm.gperf"
    {"LON", sizeof(struct zx_cdm_LON_s)},
    {""},
#line 73 "c/zx-cdm.gperf"
    {"PCODE", sizeof(struct zx_cdm_PCODE_s)},
#line 83 "c/zx-cdm.gperf"
    {"PRODID", sizeof(struct zx_cdm_PRODID_s)},
    {""},
#line 63 "c/zx-cdm.gperf"
    {"MSG", sizeof(struct zx_elem_s)},
#line 33 "c/zx-cdm.gperf"
    {"DESC", sizeof(struct zx_cdm_DESC_s)},
#line 78 "c/zx-cdm.gperf"
    {"POBOX", sizeof(struct zx_cdm_POBOX_s)},
#line 64 "c/zx-cdm.gperf"
    {"N", sizeof(struct zx_cdm_N_s)},
    {""},
#line 57 "c/zx-cdm.gperf"
    {"LOCALITY", sizeof(struct zx_cdm_LOCALITY_s)},
#line 55 "c/zx-cdm.gperf"
    {"LINE", sizeof(struct zx_cdm_LINE_s)},
#line 71 "c/zx-cdm.gperf"
    {"PAGER", sizeof(struct zx_elem_s)},
#line 34 "c/zx-cdm.gperf"
    {"DISTRIBUTIONLIST", sizeof(struct zx_elem_s)},
    {""},
#line 75 "c/zx-cdm.gperf"
    {"PHONETIC", sizeof(struct zx_cdm_PHONETIC_s)},
    {""}, {""},
#line 61 "c/zx-cdm.gperf"
    {"MIDDLE", sizeof(struct zx_cdm_MIDDLE_s)},
    {""},
#line 20 "c/zx-cdm.gperf"
    {"BBS", sizeof(struct zx_elem_s)},
#line 31 "c/zx-cdm.gperf"
    {"CRED", sizeof(struct zx_cdm_CRED_s)},
#line 102 "c/zx-cdm.gperf"
    {"VIDEO", sizeof(struct zx_elem_s)},
#line 38 "c/zx-cdm.gperf"
    {"EXTVAL", sizeof(struct zx_cdm_EXTVAL_s)},
    {""},
#line 18 "c/zx-cdm.gperf"
    {"ADR", sizeof(struct zx_cdm_ADR_s)},
#line 49 "c/zx-cdm.gperf"
    {"ISDN", sizeof(struct zx_elem_s)},
    {""},
#line 72 "c/zx-cdm.gperf"
    {"PARCEL", sizeof(struct zx_elem_s)},
#line 30 "c/zx-cdm.gperf"
    {"CONFIDENTIAL", sizeof(struct zx_elem_s)},
#line 40 "c/zx-cdm.gperf"
    {"FAVORITE", sizeof(struct zx_elem_s)},
#line 66 "c/zx-cdm.gperf"
    {"NOTE", sizeof(struct zx_cdm_NOTE_s)},
#line 19 "c/zx-cdm.gperf"
    {"AGENT", sizeof(struct zx_cdm_AGENT_s)},
#line 39 "c/zx-cdm.gperf"
    {"FAMILY", sizeof(struct zx_cdm_FAMILY_s)},
    {""},
#line 68 "c/zx-cdm.gperf"
    {"ORG", sizeof(struct zx_cdm_ORG_s)},
#line 58 "c/zx-cdm.gperf"
    {"LOGO", sizeof(struct zx_cdm_LOGO_s)},
#line 36 "c/zx-cdm.gperf"
    {"EMAIL", sizeof(struct zx_cdm_EMAIL_s)},
#line 60 "c/zx-cdm.gperf"
    {"MAILER", sizeof(struct zx_cdm_MAILER_s)},
    {""},
#line 98 "c/zx-cdm.gperf"
    {"URI", sizeof(struct zx_cdm_URI_s)},
#line 88 "c/zx-cdm.gperf"
    {"SELF", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 35 "c/zx-cdm.gperf"
    {"DOM", sizeof(struct zx_elem_s)},
#line 104 "c/zx-cdm.gperf"
    {"WORK", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 70 "c/zx-cdm.gperf"
    {"ORGUNIT", sizeof(struct zx_cdm_ORGUNIT_s)},
#line 51 "c/zx-cdm.gperf"
    {"KEY", sizeof(struct zx_cdm_KEY_s)},
#line 95 "c/zx-cdm.gperf"
    {"TYPE", sizeof(struct zx_cdm_TYPE_s)},
    {""}, {""}, {""},
#line 44 "c/zx-cdm.gperf"
    {"GEO", sizeof(struct zx_cdm_GEO_s)},
#line 46 "c/zx-cdm.gperf"
    {"HOME", sizeof(struct zx_elem_s)},
    {""},
#line 25 "c/zx-cdm.gperf"
    {"CAPURI", sizeof(struct zx_cdm_CAPURI_s)},
    {""},
#line 41 "c/zx-cdm.gperf"
    {"FAX", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 26 "c/zx-cdm.gperf"
    {"CARDID", sizeof(struct zx_elem_s)},
#line 52 "c/zx-cdm.gperf"
    {"KEYWORD", sizeof(struct zx_cdm_KEYWORD_s)},
#line 65 "c/zx-cdm.gperf"
    {"NICKNAME", sizeof(struct zx_cdm_NICKNAME_s)},
    {""}, {""}, {""},
#line 82 "c/zx-cdm.gperf"
    {"PRIVATE", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 103 "c/zx-cdm.gperf"
    {"VOICE", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 45 "c/zx-cdm.gperf"
    {"GIVEN", sizeof(struct zx_cdm_GIVEN_s)},
    {""}, {""}, {""}, {""},
#line 29 "c/zx-cdm.gperf"
    {"CLASS", sizeof(struct zx_cdm_CLASS_s)},
#line 89 "c/zx-cdm.gperf"
    {"SORT_STRING", sizeof(struct zx_cdm_SORT_STRING_s)},
#line 69 "c/zx-cdm.gperf"
    {"ORGNAME", sizeof(struct zx_cdm_ORGNAME_s)},
#line 86 "c/zx-cdm.gperf"
    {"REV", sizeof(struct zx_cdm_REV_s)},
    {""}, {""},
#line 91 "c/zx-cdm.gperf"
    {"STREET", sizeof(struct zx_cdm_STREET_s)},
    {""}, {""},
#line 87 "c/zx-cdm.gperf"
    {"ROLE", sizeof(struct zx_cdm_ROLE_s)},
    {""},
#line 22 "c/zx-cdm.gperf"
    {"BINVAL", sizeof(struct zx_cdm_BINVAL_s)},
    {""},
#line 50 "c/zx-cdm.gperf"
    {"JABBERID", sizeof(struct zx_cdm_JABBERID_s)},
    {""}, {""}, {""}, {""}, {""},
#line 77 "c/zx-cdm.gperf"
    {"PHYSICALACCESS", sizeof(struct zx_cdm_PHYSICALACCESS_s)},
#line 90 "c/zx-cdm.gperf"
    {"SOUND", sizeof(struct zx_cdm_SOUND_s)},
#line 100 "c/zx-cdm.gperf"
    {"USERID", sizeof(struct zx_cdm_USERID_s)},
    {""}, {""},
#line 32 "c/zx-cdm.gperf"
    {"CTRY", sizeof(struct zx_cdm_CTRY_s)},
    {""}, {""}, {""}, {""}, {""}, {""},
#line 67 "c/zx-cdm.gperf"
    {"NUMBER", sizeof(struct zx_cdm_NUMBER_s)},
#line 101 "c/zx-cdm.gperf"
    {"VERSION", sizeof(struct zx_cdm_VERSION_s)},
    {""}, {""}, {""},
#line 85 "c/zx-cdm.gperf"
    {"REGION", sizeof(struct zx_cdm_REGION_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 42 "c/zx-cdm.gperf"
    {"FBURL", sizeof(struct zx_cdm_FBURL_s)},
#line 92 "c/zx-cdm.gperf"
    {"SUFFIX", sizeof(struct zx_cdm_SUFFIX_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 21 "c/zx-cdm.gperf"
    {"BDAY", sizeof(struct zx_cdm_BDAY_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_cdm_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_cdm_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_cdm_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_cdm_el_tab[key];
          }
    }
  return 0;
}
#line 107 "c/zx-cdm.gperf"

/* EOF */
