/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-demomed.gperf  */
/* Computed positions: -k'1,7' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-demomed.gperf"

/* c/zx-demomed-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-demomed-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 21
#define MIN_WORD_LENGTH 3
#define MAX_WORD_LENGTH 21
#define MIN_HASH_VALUE 4
#define MAX_HASH_VALUE 43
/* maximum key range = 40, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_demomed_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44,  0,  5, 44,
      44,  0, 44, 30, 44, 44, 44, 44,  5,  0,
      44, 44, 44, 15,  0, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44,  0, 44,
       5,  0, 44, 44, 44, 44, 44, 44, 44, 44,
      44,  5, 44, 44, 44, 44,  0, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
      44, 44, 44, 44, 44, 44
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[6]];
      /*FALLTHROUGH*/
      case 6:
      case 5:
      case 4:
      case 3:
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  4,  5,  6,  7,  3,  4,  0,  0,  7,  0,
     0, 10, 16, 17,  0,  0, 20, 21,  0,  0, 19, 20,  0,  0,
     0,  0, 15, 16,  0, 18, 19,  0,  0,  0,  8,  0, 10,  0,
     0,  8
  };

struct zx_el_tok zx_demomed_el_tab[] =
  {
    {""}, {""}, {""}, {""},
#line 37 "c/zx-demomed.gperf"
    {"Type", sizeof(struct zx_elem_s)},
#line 19 "c/zx-demomed.gperf"
    {"Count", sizeof(struct zx_elem_s)},
#line 29 "c/zx-demomed.gperf"
    {"Object", sizeof(struct zx_demomed_Object_s)},
#line 18 "c/zx-demomed.gperf"
    {"Comment", sizeof(struct zx_elem_s)},
#line 23 "c/zx-demomed.gperf"
    {"Dir", sizeof(struct zx_elem_s)},
#line 28 "c/zx-demomed.gperf"
    {"Name", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 20 "c/zx-demomed.gperf"
    {"Created", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 30 "c/zx-demomed.gperf"
    {"ObjectData", sizeof(struct zx_demomed_ObjectData_s)},
#line 26 "c/zx-demomed.gperf"
    {"GetObjectRequest", sizeof(struct zx_demomed_GetObjectRequest_s)},
#line 27 "c/zx-demomed.gperf"
    {"GetObjectResponse", sizeof(struct zx_demomed_GetObjectResponse_s)},
    {""}, {""},
#line 24 "c/zx-demomed.gperf"
    {"GetObjectListRequest", sizeof(struct zx_demomed_GetObjectListRequest_s)},
#line 25 "c/zx-demomed.gperf"
    {"GetObjectListResponse", sizeof(struct zx_demomed_GetObjectListResponse_s)},
    {""}, {""},
#line 21 "c/zx-demomed.gperf"
    {"DeleteObjectRequest", sizeof(struct zx_demomed_DeleteObjectRequest_s)},
#line 22 "c/zx-demomed.gperf"
    {"DeleteObjectResponse", sizeof(struct zx_demomed_DeleteObjectResponse_s)},
    {""}, {""}, {""}, {""},
#line 34 "c/zx-demomed.gperf"
    {"ObjectStoreInfo", sizeof(struct zx_demomed_ObjectStoreInfo_s)},
#line 33 "c/zx-demomed.gperf"
    {"ObjectSearchParm", sizeof(struct zx_demomed_ObjectSearchParm_s)},
    {""},
#line 35 "c/zx-demomed.gperf"
    {"StoreObjectRequest", sizeof(struct zx_demomed_StoreObjectRequest_s)},
#line 36 "c/zx-demomed.gperf"
    {"StoreObjectResponse", sizeof(struct zx_demomed_StoreObjectResponse_s)},
    {""}, {""}, {""},
#line 31 "c/zx-demomed.gperf"
    {"ObjectID", sizeof(struct zx_elem_s)},
    {""},
#line 32 "c/zx-demomed.gperf"
    {"ObjectInfo", sizeof(struct zx_demomed_ObjectInfo_s)},
    {""}, {""},
#line 38 "c/zx-demomed.gperf"
    {"objectID", sizeof(struct zx_elem_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_demomed_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_demomed_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_demomed_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_demomed_el_tab[key];
          }
    }
  return 0;
}
#line 39 "c/zx-demomed.gperf"

/* EOF */
