/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-ds.gperf  */
/* Computed positions: -k'1,5' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-ds.gperf"

/* c/zx-ds-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-ds-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 45
#define MIN_WORD_LENGTH 1
#define MAX_WORD_LENGTH 22
#define MIN_HASH_VALUE 1
#define MAX_HASH_VALUE 62
/* maximum key range = 62, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_ds_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 25,  5, 20,
      63, 60, 35,  5, 50, 25, 63, 15, 63,  5,
       0, 10, 20,  0,  0, 63, 63, 63,  5,  5,
      63, 63, 63, 63, 63, 63, 63,  0, 63,  5,
      63, 15, 15, 63,  0,  5, 63, 63,  0, 63,
      15, 63, 63, 63,  0, 25, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
      63, 63, 63, 63, 63, 63
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[4]];
      /*FALLTHROUGH*/
      case 4:
      case 3:
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

static unsigned char lengthtable[] =
  {
     0,  1,  0,  0,  4,  0,  1,  7,  8,  9,  5,  1,  7,  8,
    14, 15,  6, 17,  8, 19, 15, 16,  7,  8, 14, 10, 16, 12,
     8,  9,  0, 11,  7,  8,  9, 10, 11,  7,  8,  0, 15, 11,
    12,  8,  0, 15, 11,  7,  0,  0,  0,  1,  0,  0,  0,  0,
    16,  0,  0,  0,  0,  1, 22
  };

struct zx_el_tok zx_ds_el_tab[] =
  {
    {""},
#line 33 "c/zx-ds.gperf"
    {"P", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 44 "c/zx-ds.gperf"
    {"Seed", sizeof(struct zx_elem_s)},
    {""},
#line 62 "c/zx-ds.gperf"
    {"Y", sizeof(struct zx_elem_s)},
#line 34 "c/zx-ds.gperf"
    {"PGPData", sizeof(struct zx_ds_PGPData_s)},
#line 43 "c/zx-ds.gperf"
    {"SPKISexp", sizeof(struct zx_elem_s)},
#line 45 "c/zx-ds.gperf"
    {"Signature", sizeof(struct zx_ds_Signature_s)},
#line 61 "c/zx-ds.gperf"
    {"XPath", sizeof(struct zx_elem_s)},
#line 38 "c/zx-ds.gperf"
    {"Q", sizeof(struct zx_elem_s)},
#line 58 "c/zx-ds.gperf"
    {"X509SKI", sizeof(struct zx_elem_s)},
#line 42 "c/zx-ds.gperf"
    {"SPKIData", sizeof(struct zx_ds_SPKIData_s)},
#line 49 "c/zx-ds.gperf"
    {"SignatureValue", sizeof(struct zx_ds_SignatureValue_s)},
#line 46 "c/zx-ds.gperf"
    {"SignatureMethod", sizeof(struct zx_ds_SignatureMethod_s)},
#line 32 "c/zx-ds.gperf"
    {"Object", sizeof(struct zx_ds_Object_s)},
#line 48 "c/zx-ds.gperf"
    {"SignatureProperty", sizeof(struct zx_ds_SignatureProperty_s)},
#line 55 "c/zx-ds.gperf"
    {"X509Data", sizeof(struct zx_ds_X509Data_s)},
#line 47 "c/zx-ds.gperf"
    {"SignatureProperties", sizeof(struct zx_ds_SignatureProperties_s)},
#line 60 "c/zx-ds.gperf"
    {"X509SubjectName", sizeof(struct zx_elem_s)},
#line 59 "c/zx-ds.gperf"
    {"X509SerialNumber", sizeof(struct zx_elem_s)},
#line 31 "c/zx-ds.gperf"
    {"Modulus", sizeof(struct zx_elem_s)},
#line 35 "c/zx-ds.gperf"
    {"PGPKeyID", sizeof(struct zx_elem_s)},
#line 56 "c/zx-ds.gperf"
    {"X509IssuerName", sizeof(struct zx_elem_s)},
#line 50 "c/zx-ds.gperf"
    {"SignedInfo", sizeof(struct zx_ds_SignedInfo_s)},
#line 57 "c/zx-ds.gperf"
    {"X509IssuerSerial", sizeof(struct zx_ds_X509IssuerSerial_s)},
#line 36 "c/zx-ds.gperf"
    {"PGPKeyPacket", sizeof(struct zx_elem_s)},
#line 30 "c/zx-ds.gperf"
    {"MgmtData", sizeof(struct zx_elem_s)},
#line 40 "c/zx-ds.gperf"
    {"Reference", sizeof(struct zx_ds_Reference_s)},
    {""},
#line 19 "c/zx-ds.gperf"
    {"DSAKeyValue", sizeof(struct zx_ds_DSAKeyValue_s)},
#line 27 "c/zx-ds.gperf"
    {"KeyName", sizeof(struct zx_elem_s)},
#line 28 "c/zx-ds.gperf"
    {"KeyValue", sizeof(struct zx_ds_KeyValue_s)},
#line 51 "c/zx-ds.gperf"
    {"Transform", sizeof(struct zx_ds_Transform_s)},
#line 52 "c/zx-ds.gperf"
    {"Transforms", sizeof(struct zx_ds_Transforms_s)},
#line 37 "c/zx-ds.gperf"
    {"PgenCounter", sizeof(struct zx_elem_s)},
#line 53 "c/zx-ds.gperf"
    {"X509CRL", sizeof(struct zx_elem_s)},
#line 29 "c/zx-ds.gperf"
    {"Manifest", sizeof(struct zx_ds_Manifest_s)},
    {""},
#line 41 "c/zx-ds.gperf"
    {"RetrievalMethod", sizeof(struct zx_ds_RetrievalMethod_s)},
#line 21 "c/zx-ds.gperf"
    {"DigestValue", sizeof(struct zx_elem_s)},
#line 20 "c/zx-ds.gperf"
    {"DigestMethod", sizeof(struct zx_ds_DigestMethod_s)},
#line 22 "c/zx-ds.gperf"
    {"Exponent", sizeof(struct zx_elem_s)},
    {""},
#line 54 "c/zx-ds.gperf"
    {"X509Certificate", sizeof(struct zx_elem_s)},
#line 39 "c/zx-ds.gperf"
    {"RSAKeyValue", sizeof(struct zx_ds_RSAKeyValue_s)},
#line 26 "c/zx-ds.gperf"
    {"KeyInfo", sizeof(struct zx_ds_KeyInfo_s)},
    {""}, {""}, {""},
#line 25 "c/zx-ds.gperf"
    {"J", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 24 "c/zx-ds.gperf"
    {"HMACOutputLength", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 23 "c/zx-ds.gperf"
    {"G", sizeof(struct zx_elem_s)},
#line 18 "c/zx-ds.gperf"
    {"CanonicalizationMethod", sizeof(struct zx_ds_CanonicalizationMethod_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_ds_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_ds_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_ds_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_ds_el_tab[key];
          }
    }
  return 0;
}
#line 63 "c/zx-ds.gperf"

/* EOF */
