/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-di.gperf  */
/* Computed positions: -k'2,6' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-di.gperf"

/* c/zx-di-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-di-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 32
#define MIN_WORD_LENGTH 4
#define MAX_WORD_LENGTH 30
#define MIN_HASH_VALUE 4
#define MAX_HASH_VALUE 46
/* maximum key range = 43, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_di_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47,  0, 47, 47,  5, 47,
      47, 47, 47,  0, 47, 47, 47, 47, 47, 47,
      47, 10,  5, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47,  0,  0, 20,
       0,  0, 47, 47, 47,  0, 47, 47, 47, 47,
      20, 47, 10, 47, 30, 25, 47,  5,  0,  0,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
      47, 47, 47, 47, 47, 47
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[5]];
      /*FALLTHROUGH*/
      case 5:
      case 4:
      case 3:
      case 2:
        hval += asso_values[(unsigned char)str[1]];
        break;
    }
  return hval;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  4,  5,  0,  7,  8,  0,  5,  0,  0,  0,
    14, 15, 11, 12, 13, 19, 10, 21, 22, 13, 19, 20, 21, 27,
    18, 29, 30, 11,  7,  0, 14, 15,  6,  7,  0,  9, 10, 16,
     0,  0,  0,  0,  6
  };

struct zx_el_tok zx_di_el_tab[] =
  {
    {""}, {""}, {""}, {""},
#line 23 "c/zx-di.gperf"
    {"Keys", sizeof(struct zx_di_Keys_s)},
#line 34 "c/zx-di.gperf"
    {"SvcMD", sizeof(struct zx_di_SvcMD_s)},
    {""},
#line 43 "c/zx-di.gperf"
    {"SvcMDID", sizeof(struct zx_elem_s)},
#line 18 "c/zx-di.gperf"
    {"Abstract", sizeof(struct zx_elem_s)},
    {""},
#line 27 "c/zx-di.gperf"
    {"Query", sizeof(struct zx_di_Query_s)},
    {""}, {""}, {""},
#line 31 "c/zx-di.gperf"
    {"SecurityMechID", sizeof(struct zx_elem_s)},
#line 30 "c/zx-di.gperf"
    {"SecurityContext", sizeof(struct zx_di_SecurityContext_s)},
#line 41 "c/zx-di.gperf"
    {"SvcMDDelete", sizeof(struct zx_di_SvcMDDelete_s)},
#line 48 "c/zx-di.gperf"
    {"SvcMDReplace", sizeof(struct zx_di_SvcMDReplace_s)},
#line 46 "c/zx-di.gperf"
    {"SvcMDRegister", sizeof(struct zx_di_SvcMDRegister_s)},
#line 35 "c/zx-di.gperf"
    {"SvcMDAssociationAdd", sizeof(struct zx_di_SvcMDAssociationAdd_s)},
#line 44 "c/zx-di.gperf"
    {"SvcMDQuery", sizeof(struct zx_di_SvcMDQuery_s)},
#line 39 "c/zx-di.gperf"
    {"SvcMDAssociationQuery", sizeof(struct zx_di_SvcMDAssociationQuery_s)},
#line 37 "c/zx-di.gperf"
    {"SvcMDAssociationDelete", sizeof(struct zx_di_SvcMDAssociationDelete_s)},
#line 28 "c/zx-di.gperf"
    {"QueryResponse", sizeof(struct zx_di_QueryResponse_s)},
#line 42 "c/zx-di.gperf"
    {"SvcMDDeleteResponse", sizeof(struct zx_di_SvcMDDeleteResponse_s)},
#line 49 "c/zx-di.gperf"
    {"SvcMDReplaceResponse", sizeof(struct zx_di_SvcMDReplaceResponse_s)},
#line 47 "c/zx-di.gperf"
    {"SvcMDRegisterResponse", sizeof(struct zx_di_SvcMDRegisterResponse_s)},
#line 36 "c/zx-di.gperf"
    {"SvcMDAssociationAddResponse", sizeof(struct zx_di_SvcMDAssociationAddResponse_s)},
#line 45 "c/zx-di.gperf"
    {"SvcMDQueryResponse", sizeof(struct zx_di_SvcMDQueryResponse_s)},
#line 40 "c/zx-di.gperf"
    {"SvcMDAssociationQueryResponse", sizeof(struct zx_di_SvcMDAssociationQueryResponse_s)},
#line 38 "c/zx-di.gperf"
    {"SvcMDAssociationDeleteResponse", sizeof(struct zx_di_SvcMDAssociationDeleteResponse_s)},
#line 33 "c/zx-di.gperf"
    {"ServiceType", sizeof(struct zx_elem_s)},
#line 20 "c/zx-di.gperf"
    {"Address", sizeof(struct zx_elem_s)},
    {""},
#line 32 "c/zx-di.gperf"
    {"ServiceContext", sizeof(struct zx_di_ServiceContext_s)},
#line 21 "c/zx-di.gperf"
    {"EndpointContext", sizeof(struct zx_di_EndpointContext_s)},
#line 24 "c/zx-di.gperf"
    {"Option", sizeof(struct zx_elem_s)},
#line 25 "c/zx-di.gperf"
    {"Options", sizeof(struct zx_di_Options_s)},
    {""},
#line 22 "c/zx-di.gperf"
    {"Framework", sizeof(struct zx_di_Framework_s)},
#line 26 "c/zx-di.gperf"
    {"ProviderID", sizeof(struct zx_elem_s)},
#line 29 "c/zx-di.gperf"
    {"RequestedService", sizeof(struct zx_di_RequestedService_s)},
    {""}, {""}, {""}, {""},
#line 19 "c/zx-di.gperf"
    {"Action", sizeof(struct zx_elem_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_di_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_di_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_di_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_di_el_tab[key];
          }
    }
  return 0;
}
#line 50 "c/zx-di.gperf"

/* EOF */
