/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-di12.gperf  */
/* Computed positions: -k'6' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-di12.gperf"

/* c/zx-di12-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-di12-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 30
#define MIN_WORD_LENGTH 5
#define MAX_WORD_LENGTH 26
#define MIN_HASH_VALUE 5
#define MAX_HASH_VALUE 45
/* maximum key range = 41, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_di12_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46,  5, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46,  0, 46,  5,
       0,  3, 46, 46, 46, 21, 46, 46, 46, 46,
       0, 46,  5, 46, 20, 25, 30, 46, 46, 46,
      46,  3, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46, 46, 46, 46, 46,
      46, 46, 46, 46, 46, 46
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[5]];
      /*FALLTHROUGH*/
      case 5:
        break;
    }
  return hval;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  0,  5,  6,  7,  8,  6, 10, 11,  7, 13,
    11, 10, 11, 14, 13, 14, 15, 21, 17,  0, 19,  0, 26,  0,
     0,  8, 10,  6, 11,  0,  9, 14, 16,  0, 18,  0,  0, 11,
     0,  0,  0, 20
  };

struct zx_el_tok zx_di12_el_tab[] =
  {
    {""}, {""}, {""}, {""}, {""},
#line 35 "c/zx-di12.gperf"
    {"Query", sizeof(struct zx_di12_Query_s)},
#line 32 "c/zx-di12.gperf"
    {"Option", sizeof(struct zx_elem_s)},
#line 33 "c/zx-di12.gperf"
    {"Options", sizeof(struct zx_di12_Options_s)},
#line 18 "c/zx-di12.gperf"
    {"Abstract", sizeof(struct zx_elem_s)},
#line 30 "c/zx-di12.gperf"
    {"Modify", sizeof(struct zx_di12_Modify_s)},
#line 34 "c/zx-di12.gperf"
    {"ProviderID", sizeof(struct zx_elem_s)},
#line 23 "c/zx-di12.gperf"
    {"Credentials", sizeof(struct zx_di12_Credentials_s)},
#line 47 "c/zx-di12.gperf"
    {"WsdlURI", sizeof(struct zx_elem_s)},
#line 22 "c/zx-di12.gperf"
    {"CredentialRef", sizeof(struct zx_elem_s)},
#line 37 "c/zx-di12.gperf"
    {"RemoveEntry", sizeof(struct zx_di12_RemoveEntry_s)},
#line 45 "c/zx-di12.gperf"
    {"SoapAction", sizeof(struct zx_elem_s)},
#line 44 "c/zx-di12.gperf"
    {"ServiceType", sizeof(struct zx_elem_s)},
#line 31 "c/zx-di12.gperf"
    {"ModifyResponse", sizeof(struct zx_di12_ModifyResponse_s)},
#line 36 "c/zx-di12.gperf"
    {"QueryResponse", sizeof(struct zx_di12_QueryResponse_s)},
#line 43 "c/zx-di12.gperf"
    {"ServiceNameRef", sizeof(struct zx_elem_s)},
#line 42 "c/zx-di12.gperf"
    {"ServiceInstance", sizeof(struct zx_di12_ServiceInstance_s)},
#line 19 "c/zx-di12.gperf"
    {"AuthenticateRequester", sizeof(struct zx_di12_AuthenticateRequester_s)},
#line 25 "c/zx-di12.gperf"
    {"EncryptResourceID", sizeof(struct zx_di12_EncryptResourceID_s)},
    {""},
#line 26 "c/zx-di12.gperf"
    {"EncryptedResourceID", sizeof(struct zx_di12_EncryptedResourceID_s)},
    {""},
#line 20 "c/zx-di12.gperf"
    {"AuthenticateSessionContext", sizeof(struct zx_di12_AuthenticateSessionContext_s)},
    {""}, {""},
#line 27 "c/zx-di12.gperf"
    {"Endpoint", sizeof(struct zx_elem_s)},
#line 39 "c/zx-di12.gperf"
    {"ResourceID", sizeof(struct zx_di12_ResourceID_s)},
#line 46 "c/zx-di12.gperf"
    {"Status", sizeof(struct zx_di12_Status_s)},
#line 24 "c/zx-di12.gperf"
    {"Description", sizeof(struct zx_di12_Description_s)},
    {""},
#line 28 "c/zx-di12.gperf"
    {"Extension", sizeof(struct zx_di12_Extension_s)},
#line 41 "c/zx-di12.gperf"
    {"SecurityMechID", sizeof(struct zx_elem_s)},
#line 40 "c/zx-di12.gperf"
    {"ResourceOffering", sizeof(struct zx_di12_ResourceOffering_s)},
    {""},
#line 21 "c/zx-di12.gperf"
    {"AuthorizeRequester", sizeof(struct zx_di12_AuthorizeRequester_s)},
    {""}, {""},
#line 29 "c/zx-di12.gperf"
    {"InsertEntry", sizeof(struct zx_di12_InsertEntry_s)},
    {""}, {""}, {""},
#line 38 "c/zx-di12.gperf"
    {"RequestedServiceType", sizeof(struct zx_di12_RequestedServiceType_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_di12_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_di12_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_di12_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_di12_el_tab[key];
          }
    }
  return 0;
}
#line 48 "c/zx-di12.gperf"

/* EOF */
