/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-ecp.gperf  */
/* Computed positions: -k'' */

#line 1 "c/zx-ecp.gperf"

/* c/zx-ecp-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-ecp-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 3
#define MIN_WORD_LENGTH 7
#define MAX_WORD_LENGTH 10
#define MIN_HASH_VALUE 7
#define MAX_HASH_VALUE 10
/* maximum key range = 4, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
/*ARGSUSED*/
static unsigned int
zx_ecp_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  return len;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  0,  0,  0,  7,  8,  0, 10
  };

struct zx_el_tok zx_ecp_el_tab[] =
  {
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 19 "c/zx-ecp.gperf"
    {"Request", sizeof(struct zx_ecp_Request_s)},
#line 20 "c/zx-ecp.gperf"
    {"Response", sizeof(struct zx_ecp_Response_s)},
    {""},
#line 18 "c/zx-ecp.gperf"
    {"RelayState", sizeof(struct zx_ecp_RelayState_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_ecp_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_ecp_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_ecp_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_ecp_el_tab[key];
          }
    }
  return 0;
}
#line 21 "c/zx-ecp.gperf"

/* EOF */
