/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-gl.gperf  */
/* Computed positions: -k'1,4,6' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-gl.gperf"

/* c/zx-gl-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-gl-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 101
#define MIN_WORD_LENGTH 1
#define MAX_WORD_LENGTH 25
#define MIN_HASH_VALUE 1
#define MAX_HASH_VALUE 202
/* maximum key range = 202, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_gl_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203,  75,  45,   5,  40,  85,
      203,  45,   0,  55, 203, 203,  35,  10,   5, 203,
       55,  85,  15,  40,   0, 203, 203, 203,  20,  15,
        0, 203, 203, 203, 203,   0, 203,   0, 203,  75,
       80,   0,   0,   5,  15,   5, 203,   0,   0,  20,
       45,  95,  20, 203,   0,  15,  10,  75,  10, 203,
      203,  45, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203, 203, 203, 203, 203,
      203, 203, 203, 203, 203, 203
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[5]];
      /*FALLTHROUGH*/
      case 5:
      case 4:
        hval += asso_values[(unsigned char)str[3]];
      /*FALLTHROUGH*/
      case 3:
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

static unsigned char lengthtable[] =
  {
     0,  1,  0,  3,  4,  5,  1,  0,  0,  0,  0,  6,  7,  3,
     4, 10,  1,  7,  8, 14,  5,  1,  2,  0,  4,  0,  6, 12,
     8,  9,  0,  0, 12,  0,  9, 25,  1,  2,  3,  9,  5, 16,
     2,  0,  4, 10,  6,  0,  3,  0, 10,  0,  0,  8, 14, 10,
     6,  0,  0,  9, 10,  6,  7,  8, 14, 15,  6, 12, 13, 14,
    15,  6,  0,  8, 14, 10,  0,  7, 13,  4,  5,  6,  7,  8,
     4, 10, 11, 12, 13,  9,  5, 11, 12, 18,  0, 15,  0,  7,
     0,  9, 10, 11,  0,  8,  9,  5,  0,  0,  0,  9,  0,  0,
     7, 13, 14, 10,  0,  0,  8,  4, 10,  0,  0,  0, 19,  0,
    11,  0,  0,  0,  0,  0,  7,  0, 14,  0,  0,  0,  0,  0,
    10,  0,  0,  0,  0,  0,  0, 12,  0,  9,  0,  0,  0,  0,
     0, 15,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  9,  0,  0,  7
  };

struct zx_el_tok zx_gl_el_tab[] =
  {
    {""},
#line 83 "c/zx-gl.gperf"
    {"Z", sizeof(struct zx_elem_s)},
    {""},
#line 84 "c/zx-gl.gperf"
    {"alt", sizeof(struct zx_elem_s)},
#line 96 "c/zx-gl.gperf"
    {"esrk", sizeof(struct zx_gl_esrk_s)},
#line 86 "c/zx-gl.gperf"
    {"angle", sizeof(struct zx_elem_s)},
#line 21 "c/zx-gl.gperf"
    {"C", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 28 "c/zx-gl.gperf"
    {"Create", sizeof(struct zx_gl_Create_s)},
#line 80 "c/zx-gl.gperf"
    {"Trigger", sizeof(struct zx_gl_Trigger_s)},
#line 53 "c/zx-gl.gperf"
    {"MNC", sizeof(struct zx_elem_s)},
#line 118 "c/zx-gl.gperf"
    {"time", sizeof(struct zx_elem_s)},
#line 29 "c/zx-gl.gperf"
    {"CreateItem", sizeof(struct zx_gl_CreateItem_s)},
#line 82 "c/zx-gl.gperf"
    {"Y", sizeof(struct zx_elem_s)},
#line 97 "c/zx-gl.gperf"
    {"geoinfo", sizeof(struct zx_gl_geoinfo_s)},
#line 99 "c/zx-gl.gperf"
    {"inRadius", sizeof(struct zx_elem_s)},
#line 30 "c/zx-gl.gperf"
    {"CreateResponse", sizeof(struct zx_gl_CreateResponse_s)},
#line 115 "c/zx-gl.gperf"
    {"speed", sizeof(struct zx_elem_s)},
#line 81 "c/zx-gl.gperf"
    {"X", sizeof(struct zx_elem_s)},
#line 108 "c/zx-gl.gperf"
    {"pd", sizeof(struct zx_gl_pd_s)},
    {""},
#line 94 "c/zx-gl.gperf"
    {"eqop", sizeof(struct zx_gl_eqop_s)},
    {""},
#line 110 "c/zx-gl.gperf"
    {"radius", sizeof(struct zx_elem_s)},
#line 61 "c/zx-gl.gperf"
    {"Notification", sizeof(struct zx_gl_Notification_s)},
#line 111 "c/zx-gl.gperf"
    {"resp_req", sizeof(struct zx_gl_resp_req_s)},
#line 112 "c/zx-gl.gperf"
    {"semiMajor", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 54 "c/zx-gl.gperf"
    {"Modification", sizeof(struct zx_gl_Modification_s)},
    {""},
#line 113 "c/zx-gl.gperf"
    {"semiMinor", sizeof(struct zx_elem_s)},
#line 27 "c/zx-gl.gperf"
    {"CoordinateReferenceSystem", sizeof(struct zx_gl_CoordinateReferenceSystem_s)},
#line 47 "c/zx-gl.gperf"
    {"L", sizeof(struct zx_elem_s)},
#line 48 "c/zx-gl.gperf"
    {"LL", sizeof(struct zx_gl_LL_s)},
#line 50 "c/zx-gl.gperf"
    {"LSt", sizeof(struct zx_gl_LSt_s)},
#line 105 "c/zx-gl.gperf"
    {"ms_action", sizeof(struct zx_gl_ms_action_s)},
#line 114 "c/zx-gl.gperf"
    {"shape", sizeof(struct zx_gl_shape_s)},
#line 26 "c/zx-gl.gperf"
    {"ComparisonResult", sizeof(struct zx_gl_ComparisonResult_s)},
#line 77 "c/zx-gl.gperf"
    {"St", sizeof(struct zx_elem_s)},
    {""},
#line 32 "c/zx-gl.gperf"
    {"Data", sizeof(struct zx_gl_Data_s)},
#line 52 "c/zx-gl.gperf"
    {"LinearRing", sizeof(struct zx_gl_LinearRing_s)},
#line 33 "c/zx-gl.gperf"
    {"Delete", sizeof(struct zx_gl_Delete_s)},
    {""},
#line 20 "c/zx-gl.gperf"
    {"Box", sizeof(struct zx_gl_Box_s)},
    {""},
#line 34 "c/zx-gl.gperf"
    {"DeleteItem", sizeof(struct zx_gl_DeleteItem_s)},
    {""}, {""},
#line 103 "c/zx-gl.gperf"
    {"loc_type", sizeof(struct zx_gl_loc_type_s)},
#line 35 "c/zx-gl.gperf"
    {"DeleteResponse", sizeof(struct zx_gl_DeleteResponse_s)},
#line 51 "c/zx-gl.gperf"
    {"LineString", sizeof(struct zx_gl_LineString_s)},
#line 76 "c/zx-gl.gperf"
    {"Select", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 25 "c/zx-gl.gperf"
    {"CivilData", sizeof(struct zx_gl_CivilData_s)},
#line 22 "c/zx-gl.gperf"
    {"ChangeArea", sizeof(struct zx_gl_ChangeArea_s)},
#line 62 "c/zx-gl.gperf"
    {"Notify", sizeof(struct zx_gl_Notify_s)},
#line 60 "c/zx-gl.gperf"
    {"NewData", sizeof(struct zx_gl_NewData_s)},
#line 65 "c/zx-gl.gperf"
    {"NotifyTo", sizeof(struct zx_gl_NotifyTo_s)},
#line 49 "c/zx-gl.gperf"
    {"LPostalAddress", sizeof(struct zx_gl_LPostalAddress_s)},
#line 100 "c/zx-gl.gperf"
    {"innerBoundaryIs", sizeof(struct zx_gl_innerBoundaryIs_s)},
#line 55 "c/zx-gl.gperf"
    {"Modify", sizeof(struct zx_gl_Modify_s)},
#line 79 "c/zx-gl.gperf"
    {"Subscription", sizeof(struct zx_gl_Subscription_s)},
#line 63 "c/zx-gl.gperf"
    {"NotifyAdminTo", sizeof(struct zx_gl_NotifyAdminTo_s)},
#line 64 "c/zx-gl.gperf"
    {"NotifyResponse", sizeof(struct zx_gl_NotifyResponse_s)},
#line 57 "c/zx-gl.gperf"
    {"MultiLineString", sizeof(struct zx_gl_MultiLineString_s)},
#line 78 "c/zx-gl.gperf"
    {"Status", sizeof(struct zx_gl_Status_s)},
    {""},
#line 44 "c/zx-gl.gperf"
    {"Interval", sizeof(struct zx_elem_s)},
#line 56 "c/zx-gl.gperf"
    {"ModifyResponse", sizeof(struct zx_gl_ModifyResponse_s)},
#line 69 "c/zx-gl.gperf"
    {"PostalCode", sizeof(struct zx_elem_s)},
    {""},
#line 73 "c/zx-gl.gperf"
    {"RefItem", sizeof(struct zx_gl_RefItem_s)},
#line 68 "c/zx-gl.gperf"
    {"PostalAddress", sizeof(struct zx_elem_s)},
#line 88 "c/zx-gl.gperf"
    {"code", sizeof(struct zx_elem_s)},
#line 90 "c/zx-gl.gperf"
    {"coord", sizeof(struct zx_gl_coord_s)},
#line 102 "c/zx-gl.gperf"
    {"ll_acc", sizeof(struct zx_elem_s)},
#line 85 "c/zx-gl.gperf"
    {"alt_acc", sizeof(struct zx_elem_s)},
#line 45 "c/zx-gl.gperf"
    {"ItemData", sizeof(struct zx_gl_ItemData_s)},
#line 95 "c/zx-gl.gperf"
    {"esrd", sizeof(struct zx_gl_esrd_s)},
#line 58 "c/zx-gl.gperf"
    {"MultiPoint", sizeof(struct zx_gl_MultiPoint_s)},
#line 87 "c/zx-gl.gperf"
    {"angularUnit", sizeof(struct zx_elem_s)},
#line 59 "c/zx-gl.gperf"
    {"MultiPolygon", sizeof(struct zx_gl_MultiPolygon_s)},
#line 46 "c/zx-gl.gperf"
    {"ItemSelection", sizeof(struct zx_gl_ItemSelection_s)},
#line 117 "c/zx-gl.gperf"
    {"stopAngle", sizeof(struct zx_elem_s)},
#line 70 "c/zx-gl.gperf"
    {"Query", sizeof(struct zx_gl_Query_s)},
#line 18 "c/zx-gl.gperf"
    {"Aggregation", sizeof(struct zx_elem_s)},
#line 24 "c/zx-gl.gperf"
    {"CircularArea", sizeof(struct zx_gl_CircularArea_s)},
#line 40 "c/zx-gl.gperf"
    {"GeometryCollection", sizeof(struct zx_gl_GeometryCollection_s)},
    {""},
#line 23 "c/zx-gl.gperf"
    {"CircularArcArea", sizeof(struct zx_gl_CircularArcArea_s)},
    {""},
#line 98 "c/zx-gl.gperf"
    {"hor_acc", sizeof(struct zx_elem_s)},
    {""},
#line 91 "c/zx-gl.gperf"
    {"direction", sizeof(struct zx_elem_s)},
#line 116 "c/zx-gl.gperf"
    {"startAngle", sizeof(struct zx_elem_s)},
#line 41 "c/zx-gl.gperf"
    {"Granularity", sizeof(struct zx_elem_s)},
    {""},
#line 101 "c/zx-gl.gperf"
    {"lev_conf", sizeof(struct zx_elem_s)},
#line 89 "c/zx-gl.gperf"
    {"codeSpace", sizeof(struct zx_elem_s)},
#line 66 "c/zx-gl.gperf"
    {"Point", sizeof(struct zx_gl_Point_s)},
    {""}, {""}, {""},
#line 39 "c/zx-gl.gperf"
    {"Extension", sizeof(struct zx_gl_Extension_s)},
    {""}, {""},
#line 93 "c/zx-gl.gperf"
    {"edition", sizeof(struct zx_elem_s)},
#line 72 "c/zx-gl.gperf"
    {"QueryResponse", sizeof(struct zx_gl_QueryResponse_s)},
#line 36 "c/zx-gl.gperf"
    {"EllipticalArea", sizeof(struct zx_gl_EllipticalArea_s)},
#line 43 "c/zx-gl.gperf"
    {"Identifier", sizeof(struct zx_gl_Identifier_s)},
    {""}, {""},
#line 38 "c/zx-gl.gperf"
    {"Endpoint", sizeof(struct zx_elem_s)},
#line 109 "c/zx-gl.gperf"
    {"prio", sizeof(struct zx_gl_prio_s)},
#line 74 "c/zx-gl.gperf"
    {"ResourceID", sizeof(struct zx_gl_ResourceID_s)},
    {""}, {""}, {""},
#line 37 "c/zx-gl.gperf"
    {"EncryptedResourceID", sizeof(struct zx_gl_EncryptedResourceID_s)},
    {""},
#line 104 "c/zx-gl.gperf"
    {"max_loc_age", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""}, {""},
#line 42 "c/zx-gl.gperf"
    {"Heading", sizeof(struct zx_elem_s)},
    {""},
#line 75 "c/zx-gl.gperf"
    {"SecurityMechID", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""}, {""},
#line 31 "c/zx-gl.gperf"
    {"Credential", sizeof(struct zx_gl_Credential_s)},
    {""}, {""}, {""}, {""}, {""}, {""},
#line 92 "c/zx-gl.gperf"
    {"distanceUnit", sizeof(struct zx_elem_s)},
    {""},
#line 71 "c/zx-gl.gperf"
    {"QueryItem", sizeof(struct zx_gl_QueryItem_s)},
    {""}, {""}, {""}, {""}, {""},
#line 107 "c/zx-gl.gperf"
    {"outerBoundaryIs", sizeof(struct zx_gl_outerBoundaryIs_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""},
#line 19 "c/zx-gl.gperf"
    {"AreaComparison", sizeof(struct zx_gl_AreaComparison_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""},
#line 106 "c/zx-gl.gperf"
    {"outRadius", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 67 "c/zx-gl.gperf"
    {"Polygon", sizeof(struct zx_gl_Polygon_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_gl_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_gl_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_gl_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_gl_el_tab[key];
          }
    }
  return 0;
}
#line 119 "c/zx-gl.gperf"

/* EOF */
