/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-hrxml.gperf  */
/* Computed positions: -k'1,3-4,7-8,$' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-hrxml.gperf"

/* c/zx-hrxml-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-hrxml-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 402
#define MIN_WORD_LENGTH 2
#define MAX_WORD_LENGTH 31
#define MIN_HASH_VALUE 13
#define MAX_HASH_VALUE 1471
/* maximum key range = 1459, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_hrxml_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned short asso_values[] =
    {
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472,   50,  460,   40,  135,  295,
       125,  135,  133,  205,  100, 1472,  135,  340,  340,  210,
         0,   95,  105,   15,  495,   10,  425,  440,   10,   15,
        35, 1472, 1472, 1472, 1472, 1472, 1472,    0,  395,   25,
         0,    0,  365,   55,  185,   20,   80,  312,   75,  140,
         5,    0,  180,    5,    5,    5,    5,  105,  280,    5,
        35,  130,  365, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472, 1472,
      1472, 1472, 1472, 1472, 1472, 1472
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[7]];
      /*FALLTHROUGH*/
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      /*FALLTHROUGH*/
      case 6:
      case 5:
      case 4:
        hval += asso_values[(unsigned char)str[3]];
      /*FALLTHROUGH*/
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      /*FALLTHROUGH*/
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,
     0,  0,  6,  0,  0,  0,  0,  6,  0,  8,  0,  5,  0,  0,
     0,  4,  0,  6,  0,  0,  9,  0,  0,  0, 13,  0,  0,  0,
     0, 13,  4, 10, 16,  0,  0,  0,  0, 16,  0,  3,  4,  0,
     0, 22,  0,  9, 10,  0,  0,  0, 19,  5, 16,  0,  0, 19,
     0,  0, 17,  0, 14,  0, 11, 12, 13, 14, 15, 16,  7,  8,
     0, 15,  0,  0, 28,  0,  0,  0,  0, 13, 14, 20,  0, 12,
    13, 14, 15, 16,  0,  8,  0, 20,  0, 12,  0,  4,  0,  0,
     0, 18, 14,  0,  0,  0,  0,  0, 25,  0, 27, 28,  0, 10,
     0,  0, 18,  0,  0, 16,  0,  0,  4,  0,  0,  0,  0, 14,
     0,  0, 12,  0,  4, 20,  0, 17,  0,  9,  0,  0, 12,  0,
     4,  0,  0,  7, 13, 19, 15,  0,  0,  0,  0,  0,  0, 17,
     8,  9, 20,  0,  0,  0, 19, 15,  0,  0,  8,  0,  0,  0,
     0,  0,  4, 10,  6,  0,  0,  9, 10,  6, 12,  0, 19, 25,
     0,  7,  3,  0,  0,  6,  0,  0, 19, 30, 11,  2, 23, 14,
     0, 16,  0,  0, 19,  0, 11,  0,  8,  6, 10,  6,  0,  8,
     9, 20, 21, 12,  0,  9,  0, 16,  0, 18, 14,  0,  0,  7,
    18,  0, 20,  0,  0,  0,  0, 15,  6,  9,  0, 14, 15,  0,
     0,  5, 19,  0,  0,  9,  8, 19,  0,  0, 12,  0,  9, 20,
    11,  0,  0,  9,  0, 11,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  6,  0, 18,  0,  0,  0,  7, 13, 19, 15, 21,  0,  8,
     0, 15,  0,  7, 23,  9, 15, 13,  0,  0, 19,  0, 16,  0,
    13,  9, 15, 31,  0,  0, 19,  0, 18,  0,  0,  0,  5,  0,
     7,  0,  0,  0,  0,  7,  8,  0,  0, 11,  5, 13,  0, 20,
     0,  7,  0,  9, 10, 26,  0,  8,  0,  0,  9,  0,  0,  0,
    10,  0,  7,  8,  9,  5,  0,  5,  0,  0, 10,  0,  0,  0,
     0, 20, 11, 12,  8, 24, 10,  9, 12, 18, 19,  0,  0, 12,
    18,  0, 15, 16, 12, 18,  0, 15, 16, 17, 18, 14, 10, 16,
    17,  0,  0, 15,  0, 22, 20,  0,  0,  0,  0,  0,  0,  0,
    11,  0, 13,  9,  5, 11, 12,  8, 19,  0, 11,  0, 13, 24,
    25, 16, 12,  0, 19, 20, 21,  0,  8, 14,  5,  0,  0,  8,
     0, 15,  0,  7, 18, 19, 15,  0,  0, 13,  0,  0,  0,  0,
     0,  9, 10,  0,  0,  0,  0,  0, 19, 12,  0,  0, 15, 19,
    17, 18,  0,  0,  0, 22,  0, 19,  5, 31, 12, 13,  0,  5,
    11,  7, 13,  0,  0,  0, 22,  0,  4,  0,  0,  0,  8,  4,
    15,  0, 12,  0, 19,  0,  0,  0,  0,  0, 15, 16, 12,  0,
     9, 10,  0, 17,  0,  9,  0,  0,  7, 13, 19, 10,  0, 12,
    18,  0, 25, 21,  0, 13,  0,  0,  6,  7,  0,  0,  0, 11,
    12,  0, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12, 10,
     0, 17, 13, 19, 10, 11,  0,  0,  0, 10,  0, 17,  0,  0,
     0,  0,  0,  0,  9,  0, 16, 17,  8, 12, 15, 11, 17,  0,
    19,  0,  0, 17,  0,  9,  5, 11,  7,  0,  9, 30,  0,  0,
     0, 14,  0, 16,  0, 16,  0, 15,  0,  0,  0,  9,  0, 19,
     0,  0,  9, 10, 21,  0, 13, 14,  5,  6,  7,  0,  0,  0,
     0,  0,  8,  9,  0, 11,  0, 18,  0,  0,  0,  7,  0, 14,
    15,  6,  0,  0, 14, 10,  0,  7,  8, 12,  0,  0,  0,  0,
    14,  0, 16, 12, 23,  9, 20, 16, 22, 18,  0, 10, 16, 12,
    13,  0,  0,  0,  0,  8,  0,  0, 16,  0, 13,  0, 10,  0,
    22,  0,  9,  0,  0, 17,  0,  4, 15,  0,  0,  0,  0,  0,
     0, 12,  0,  0, 10,  0,  0,  0,  0, 10, 16,  0,  0,  0,
    15,  0,  0,  0,  0,  5,  0,  0,  0,  0, 10,  0,  7,  0,
     0, 15, 11, 12,  0,  0,  0, 11,  0,  0,  0,  0, 16,  0,
     0,  0, 15, 11,  7,  0,  0,  0,  0,  0,  0,  0,  5,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13,  0, 15,
     0,  0,  0,  0, 10,  6,  0,  0,  0,  0, 16,  0,  4,  0,
     8,  0, 10,  0, 12, 12,  0,  0,  0,  0,  0,  0, 12,  0,
     0,  0, 19,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  7,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,
    12,  0,  0,  0, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 17,  0,  0,
    20,  0,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  6,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  4,  0, 16,  0,  0,  0,
     0,  0,  0,  0,  0,  0, 16,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0, 14,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0, 16,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  9,  0, 13,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    15,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 17,  0,
     0,  0, 16,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0, 15,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13,  0,
     0, 16
  };

struct zx_el_tok zx_hrxml_el_tab[] =
  {
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""},
#line 396 "c/zx-hrxml.gperf"
    {"Use", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 260 "c/zx-hrxml.gperf"
    {"Patent", sizeof(struct zx_hrxml_Patent_s)},
    {""}, {""}, {""}, {""},
#line 398 "c/zx-hrxml.gperf"
    {"UserId", sizeof(struct zx_hrxml_UserId_s)},
    {""},
#line 397 "c/zx-hrxml.gperf"
    {"UserArea", sizeof(struct zx_hrxml_UserArea_s)},
    {""},
#line 340 "c/zx-hrxml.gperf"
    {"Score", sizeof(struct zx_hrxml_Score_s)},
    {""}, {""}, {""},
#line 418 "c/zx-hrxml.gperf"
    {"Year", sizeof(struct zx_elem_s)},
    {""},
#line 369 "c/zx-hrxml.gperf"
    {"Status", sizeof(struct zx_hrxml_Status_s)},
    {""}, {""},
#line 365 "c/zx-hrxml.gperf"
    {"StartDate", sizeof(struct zx_hrxml_StartDate_s)},
    {""}, {""}, {""},
#line 364 "c/zx-hrxml.gperf"
    {"StandardValue", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 283 "c/zx-hrxml.gperf"
    {"PositionTitle", sizeof(struct zx_elem_s)},
#line 394 "c/zx-hrxml.gperf"
    {"Unit", sizeof(struct zx_elem_s)},
#line 266 "c/zx-hrxml.gperf"
    {"Percentage", sizeof(struct zx_elem_s)},
#line 282 "c/zx-hrxml.gperf"
    {"PositionSchedule", sizeof(struct zx_hrxml_PositionSchedule_s)},
    {""}, {""}, {""}, {""},
#line 279 "c/zx-hrxml.gperf"
    {"PositionLocation", sizeof(struct zx_hrxml_PositionLocation_s)},
    {""},
#line 32 "c/zx-hrxml.gperf"
    {"Age", sizeof(struct zx_elem_s)},
#line 38 "c/zx-hrxml.gperf"
    {"Area", sizeof(struct zx_hrxml_Area_s)},
    {""}, {""},
#line 277 "c/zx-hrxml.gperf"
    {"PositionClassification", sizeof(struct zx_elem_s)},
    {""},
#line 59 "c/zx-hrxml.gperf"
    {"Candidate", sizeof(struct zx_hrxml_Candidate_s)},
#line 286 "c/zx-hrxml.gperf"
    {"PostalCode", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 334 "c/zx-hrxml.gperf"
    {"SEPPhysicalLocation", sizeof(struct zx_hrxml_SEPPhysicalLocation_s)},
#line 258 "c/zx-hrxml.gperf"
    {"Pager", sizeof(struct zx_hrxml_Pager_s)},
#line 60 "c/zx-hrxml.gperf"
    {"CandidateProfile", sizeof(struct zx_hrxml_CandidateProfile_s)},
    {""}, {""},
#line 61 "c/zx-hrxml.gperf"
    {"CandidateRecordInfo", sizeof(struct zx_hrxml_CandidateRecordInfo_s)},
    {""}, {""},
#line 62 "c/zx-hrxml.gperf"
    {"CandidateSupplier", sizeof(struct zx_hrxml_CandidateSupplier_s)},
    {""},
#line 82 "c/zx-hrxml.gperf"
    {"Considerations", sizeof(struct zx_hrxml_Considerations_s)},
    {""},
#line 41 "c/zx-hrxml.gperf"
    {"Association", sizeof(struct zx_hrxml_Association_s)},
#line 42 "c/zx-hrxml.gperf"
    {"Associations", sizeof(struct zx_hrxml_Associations_s)},
#line 285 "c/zx-hrxml.gperf"
    {"PostalAddress", sizeof(struct zx_hrxml_PostalAddress_s)},
#line 341 "c/zx-hrxml.gperf"
    {"SearchCriteria", sizeof(struct zx_hrxml_SearchCriteria_s)},
#line 33 "c/zx-hrxml.gperf"
    {"AlternateScript", sizeof(struct zx_hrxml_AlternateScript_s)},
#line 342 "c/zx-hrxml.gperf"
    {"SearchCriteriaId", sizeof(struct zx_hrxml_SearchCriteriaId_s)},
#line 40 "c/zx-hrxml.gperf"
    {"Article", sizeof(struct zx_hrxml_Article_s)},
#line 34 "c/zx-hrxml.gperf"
    {"Altitude", sizeof(struct zx_elem_s)},
    {""},
#line 343 "c/zx-hrxml.gperf"
    {"SearchCriterion", sizeof(struct zx_hrxml_SearchCriterion_s)},
    {""}, {""},
#line 363 "c/zx-hrxml.gperf"
    {"SpecifiedCompetencyReference", sizeof(struct zx_hrxml_SpecifiedCompetencyReference_s)},
    {""}, {""}, {""}, {""},
#line 361 "c/zx-hrxml.gperf"
    {"SpeakingEvent", sizeof(struct zx_hrxml_SpeakingEvent_s)},
#line 27 "c/zx-hrxml.gperf"
    {"AdditionalText", sizeof(struct zx_elem_s)},
#line 23 "c/zx-hrxml.gperf"
    {"AccommodationsNeeded", sizeof(struct zx_elem_s)},
    {""},
#line 274 "c/zx-hrxml.gperf"
    {"PersonalData", sizeof(struct zx_hrxml_PersonalData_s)},
#line 93 "c/zx-hrxml.gperf"
    {"CriterionName", sizeof(struct zx_elem_s)},
#line 94 "c/zx-hrxml.gperf"
    {"CriterionValue", sizeof(struct zx_elem_s)},
#line 281 "c/zx-hrxml.gperf"
    {"PositionPosting", sizeof(struct zx_hrxml_PositionPosting_s)},
#line 280 "c/zx-hrxml.gperf"
    {"PositionMatching", sizeof(struct zx_hrxml_PositionMatching_s)},
    {""},
#line 18 "c/zx-hrxml.gperf"
    {"Abstract", sizeof(struct zx_elem_s)},
    {""},
#line 368 "c/zx-hrxml.gperf"
    {"StartingCompensation", sizeof(struct zx_hrxml_StartingCompensation_s)},
    {""},
#line 349 "c/zx-hrxml.gperf"
    {"SearchString", sizeof(struct zx_elem_s)},
    {""},
#line 309 "c/zx-hrxml.gperf"
    {"Read", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 19 "c/zx-hrxml.gperf"
    {"AcademicCreditCode", sizeof(struct zx_elem_s)},
#line 24 "c/zx-hrxml.gperf"
    {"AccountingCode", sizeof(struct zx_hrxml_AccountingCode_s)},
    {""}, {""}, {""}, {""}, {""},
#line 21 "c/zx-hrxml.gperf"
    {"AcademicCreditHoursEarned", sizeof(struct zx_elem_s)},
    {""},
#line 22 "c/zx-hrxml.gperf"
    {"AcademicCreditHoursIncluded", sizeof(struct zx_elem_s)},
#line 20 "c/zx-hrxml.gperf"
    {"AcademicCreditHoursAttempted", sizeof(struct zx_elem_s)},
    {""},
#line 273 "c/zx-hrxml.gperf"
    {"PersonRole", sizeof(struct zx_hrxml_PersonRole_s)},
    {""}, {""},
#line 304 "c/zx-hrxml.gperf"
    {"QuestionAnswerPair", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 44 "c/zx-hrxml.gperf"
    {"AttendanceRating", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 305 "c/zx-hrxml.gperf"
    {"Race", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 348 "c/zx-hrxml.gperf"
    {"SearchResultId", sizeof(struct zx_hrxml_SearchResultId_s)},
    {""}, {""},
#line 346 "c/zx-hrxml.gperf"
    {"SearchResult", sizeof(struct zx_hrxml_SearchResult_s)},
    {""},
#line 97 "c/zx-hrxml.gperf"
    {"Date", sizeof(struct zx_elem_s)},
#line 345 "c/zx-hrxml.gperf"
    {"SearchRelevanceScore", sizeof(struct zx_hrxml_SearchRelevanceScore_s)},
    {""},
#line 347 "c/zx-hrxml.gperf"
    {"SearchResultCount", sizeof(struct zx_elem_s)},
    {""},
#line 120 "c/zx-hrxml.gperf"
    {"DressCode", sizeof(struct zx_hrxml_DressCode_s)},
    {""}, {""},
#line 66 "c/zx-hrxml.gperf"
    {"ChildrenInfo", sizeof(struct zx_hrxml_ChildrenInfo_s)},
    {""},
#line 203 "c/zx-hrxml.gperf"
    {"List", sizeof(struct zx_hrxml_List_s)},
    {""}, {""},
#line 112 "c/zx-hrxml.gperf"
    {"Details", sizeof(struct zx_hrxml_Details_s)},
#line 270 "c/zx-hrxml.gperf"
    {"PersonLegalId", sizeof(struct zx_hrxml_PersonLegalId_s)},
#line 208 "c/zx-hrxml.gperf"
    {"LowestPossibleValue", sizeof(struct zx_hrxml_LowestPossibleValue_s)},
#line 151 "c/zx-hrxml.gperf"
    {"FirstIssuedDate", sizeof(struct zx_hrxml_FirstIssuedDate_s)},
    {""}, {""}, {""}, {""}, {""}, {""},
#line 268 "c/zx-hrxml.gperf"
    {"PersonDescriptors", sizeof(struct zx_hrxml_PersonDescriptors_s)},
#line 193 "c/zx-hrxml.gperf"
    {"Latitude", sizeof(struct zx_hrxml_Latitude_s)},
#line 311 "c/zx-hrxml.gperf"
    {"Recipient", sizeof(struct zx_hrxml_Recipient_s)},
#line 35 "c/zx-hrxml.gperf"
    {"AltitudeMeanSeaLevel", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 312 "c/zx-hrxml.gperf"
    {"RecognitionAchieved", sizeof(struct zx_elem_s)},
#line 278 "c/zx-hrxml.gperf"
    {"PositionHistory", sizeof(struct zx_hrxml_PositionHistory_s)},
    {""}, {""},
#line 205 "c/zx-hrxml.gperf"
    {"Location", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""}, {""},
#line 331 "c/zx-hrxml.gperf"
    {"Role", sizeof(struct zx_elem_s)},
#line 372 "c/zx-hrxml.gperf"
    {"StringDate", sizeof(struct zx_elem_s)},
#line 332 "c/zx-hrxml.gperf"
    {"RoleId", sizeof(struct zx_hrxml_RoleId_s)},
    {""}, {""},
#line 367 "c/zx-hrxml.gperf"
    {"StartTime", sizeof(struct zx_elem_s)},
#line 155 "c/zx-hrxml.gperf"
    {"GenderCode", sizeof(struct zx_elem_s)},
#line 315 "c/zx-hrxml.gperf"
    {"Region", sizeof(struct zx_elem_s)},
#line 63 "c/zx-hrxml.gperf"
    {"CategoryCode", sizeof(struct zx_elem_s)},
    {""},
#line 267 "c/zx-hrxml.gperf"
    {"PermissionToContact", sizeof(struct zx_elem_s)},
#line 200 "c/zx-hrxml.gperf"
    {"LicensesAndCertifications", sizeof(struct zx_hrxml_LicensesAndCertifications_s)},
    {""},
#line 195 "c/zx-hrxml.gperf"
    {"LegalId", sizeof(struct zx_hrxml_LegalId_s)},
#line 150 "c/zx-hrxml.gperf"
    {"Fax", sizeof(struct zx_hrxml_Fax_s)},
    {""}, {""},
#line 101 "c/zx-hrxml.gperf"
    {"Degree", sizeof(struct zx_hrxml_Degree_s)},
    {""}, {""},
#line 64 "c/zx-hrxml.gperf"
    {"CategoryDescription", sizeof(struct zx_elem_s)},
#line 204 "c/zx-hrxml.gperf"
    {"LocalInstitutionClassification", sizeof(struct zx_hrxml_LocalInstitutionClassification_s)},
#line 28 "c/zx-hrxml.gperf"
    {"AddressLine", sizeof(struct zx_elem_s)},
#line 168 "c/zx-hrxml.gperf"
    {"Id", sizeof(struct zx_hrxml_Id_s)},
#line 318 "c/zx-hrxml.gperf"
    {"RelatedPositionPostings", sizeof(struct zx_hrxml_RelatedPositionPostings_s)},
#line 395 "c/zx-hrxml.gperf"
    {"UnitOrDivision", sizeof(struct zx_elem_s)},
    {""},
#line 196 "c/zx-hrxml.gperf"
    {"LegalIdentifiers", sizeof(struct zx_hrxml_LegalIdentifiers_s)},
    {""}, {""},
#line 43 "c/zx-hrxml.gperf"
    {"AttachmentReference", sizeof(struct zx_hrxml_AttachmentReference_s)},
    {""},
#line 116 "c/zx-hrxml.gperf"
    {"DistanceMax", sizeof(struct zx_hrxml_DistanceMax_s)},
    {""},
#line 319 "c/zx-hrxml.gperf"
    {"Religion", sizeof(struct zx_elem_s)},
#line 161 "c/zx-hrxml.gperf"
    {"Height", sizeof(struct zx_hrxml_Height_s)},
#line 320 "c/zx-hrxml.gperf"
    {"Relocation", sizeof(struct zx_hrxml_Relocation_s)},
#line 325 "c/zx-hrxml.gperf"
    {"Resume", sizeof(struct zx_hrxml_Resume_s)},
    {""},
#line 269 "c/zx-hrxml.gperf"
    {"PersonId", sizeof(struct zx_hrxml_PersonId_s)},
#line 419 "c/zx-hrxml.gperf"
    {"YearMonth", sizeof(struct zx_elem_s)},
#line 321 "c/zx-hrxml.gperf"
    {"RelocationAssistance", sizeof(struct zx_hrxml_RelocationAssistance_s)},
#line 362 "c/zx-hrxml.gperf"
    {"SpeakingEventsHistory", sizeof(struct zx_hrxml_SpeakingEventsHistory_s)},
#line 261 "c/zx-hrxml.gperf"
    {"PatentDetail", sizeof(struct zx_hrxml_PatentDetail_s)},
    {""},
#line 323 "c/zx-hrxml.gperf"
    {"Requested", sizeof(struct zx_elem_s)},
    {""},
#line 276 "c/zx-hrxml.gperf"
    {"PhysicalLocation", sizeof(struct zx_hrxml_PhysicalLocation_s)},
    {""},
#line 174 "c/zx-hrxml.gperf"
    {"InternetDomainName", sizeof(struct zx_hrxml_InternetDomainName_s)},
#line 303 "c/zx-hrxml.gperf"
    {"Qualifications", sizeof(struct zx_hrxml_Qualifications_s)},
    {""}, {""},
#line 65 "c/zx-hrxml.gperf"
    {"Chapter", sizeof(struct zx_elem_s)},
#line 176 "c/zx-hrxml.gperf"
    {"InternetWebAddress", sizeof(struct zx_elem_s)},
    {""},
#line 175 "c/zx-hrxml.gperf"
    {"InternetEmailAddress", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 114 "c/zx-hrxml.gperf"
    {"DischargeStatus", sizeof(struct zx_elem_s)},
#line 234 "c/zx-hrxml.gperf"
    {"Option", sizeof(struct zx_elem_s)},
#line 159 "c/zx-hrxml.gperf"
    {"HairColor", sizeof(struct zx_elem_s)},
    {""},
#line 113 "c/zx-hrxml.gperf"
    {"DisabilityInfo", sizeof(struct zx_hrxml_DisabilityInfo_s)},
#line 359 "c/zx-hrxml.gperf"
    {"SpatialLocation", sizeof(struct zx_hrxml_SpatialLocation_s)},
    {""}, {""},
#line 164 "c/zx-hrxml.gperf"
    {"Hours", sizeof(struct zx_elem_s)},
#line 374 "c/zx-hrxml.gperf"
    {"StructuredXMLResume", sizeof(struct zx_hrxml_StructuredXMLResume_s)},
    {""}, {""},
#line 160 "c/zx-hrxml.gperf"
    {"Headcount", sizeof(struct zx_elem_s)},
#line 190 "c/zx-hrxml.gperf"
    {"Language", sizeof(struct zx_hrxml_Language_s)},
#line 103 "c/zx-hrxml.gperf"
    {"DegreeConcentration", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 191 "c/zx-hrxml.gperf"
    {"LanguageCode", sizeof(struct zx_hrxml_LanguageCode_s)},
    {""},
#line 192 "c/zx-hrxml.gperf"
    {"Languages", sizeof(struct zx_hrxml_Languages_s)},
#line 158 "c/zx-hrxml.gperf"
    {"GoodStudentIndicator", sizeof(struct zx_elem_s)},
#line 67 "c/zx-hrxml.gperf"
    {"Citizenship", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 83 "c/zx-hrxml.gperf"
    {"ContactId", sizeof(struct zx_hrxml_ContactId_s)},
    {""},
#line 84 "c/zx-hrxml.gperf"
    {"ContactInfo", sizeof(struct zx_hrxml_ContactInfo_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 336 "c/zx-hrxml.gperf"
    {"School", sizeof(struct zx_hrxml_School_s)},
    {""},
#line 115 "c/zx-hrxml.gperf"
    {"DisciplinaryAction", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 238 "c/zx-hrxml.gperf"
    {"OrgSize", sizeof(struct zx_elem_s)},
#line 152 "c/zx-hrxml.gperf"
    {"FormattedName", sizeof(struct zx_elem_s)},
#line 194 "c/zx-hrxml.gperf"
    {"LegalClassification", sizeof(struct zx_hrxml_LegalClassification_s)},
#line 119 "c/zx-hrxml.gperf"
    {"DoingBusinessAs", sizeof(struct zx_hrxml_DoingBusinessAs_s)},
#line 327 "c/zx-hrxml.gperf"
    {"ResumeAdditionalItems", sizeof(struct zx_hrxml_ResumeAdditionalItems_s)},
    {""},
#line 275 "c/zx-hrxml.gperf"
    {"Physical", sizeof(struct zx_elem_s)},
    {""},
#line 153 "c/zx-hrxml.gperf"
    {"FormattedNumber", sizeof(struct zx_elem_s)},
    {""},
#line 156 "c/zx-hrxml.gperf"
    {"General", sizeof(struct zx_elem_s)},
#line 329 "c/zx-hrxml.gperf"
    {"RetirementOrSavingsPlan", sizeof(struct zx_elem_s)},
#line 324 "c/zx-hrxml.gperf"
    {"Residency", sizeof(struct zx_elem_s)},
#line 92 "c/zx-hrxml.gperf"
    {"CourseLevelCode", sizeof(struct zx_elem_s)},
#line 262 "c/zx-hrxml.gperf"
    {"PatentHistory", sizeof(struct zx_hrxml_PatentHistory_s)},
    {""}, {""},
#line 353 "c/zx-hrxml.gperf"
    {"SecurityCredentials", sizeof(struct zx_hrxml_SecurityCredentials_s)},
    {""},
#line 310 "c/zx-hrxml.gperf"
    {"ReasonForLeaving", sizeof(struct zx_elem_s)},
    {""},
#line 91 "c/zx-hrxml.gperf"
    {"CountryServed", sizeof(struct zx_elem_s)},
#line 207 "c/zx-hrxml.gperf"
    {"Longitude", sizeof(struct zx_hrxml_Longitude_s)},
#line 206 "c/zx-hrxml.gperf"
    {"LocationSummary", sizeof(struct zx_hrxml_LocationSummary_s)},
#line 154 "c/zx-hrxml.gperf"
    {"FormattedPublicationDescription", sizeof(struct zx_hrxml_FormattedPublicationDescription_s)},
    {""}, {""},
#line 290 "c/zx-hrxml.gperf"
    {"PrehireRemuneration", sizeof(struct zx_hrxml_PrehireRemuneration_s)},
    {""},
#line 163 "c/zx-hrxml.gperf"
    {"HorizontalAccuracy", sizeof(struct zx_hrxml_HorizontalAccuracy_s)},
    {""}, {""}, {""},
#line 181 "c/zx-hrxml.gperf"
    {"Issue", sizeof(struct zx_elem_s)},
    {""},
#line 36 "c/zx-hrxml.gperf"
    {"AnyDate", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 70 "c/zx-hrxml.gperf"
    {"Commute", sizeof(struct zx_hrxml_Commute_s)},
#line 333 "c/zx-hrxml.gperf"
    {"RoleName", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 90 "c/zx-hrxml.gperf"
    {"CountryCode", sizeof(struct zx_elem_s)},
#line 360 "c/zx-hrxml.gperf"
    {"Speak", sizeof(struct zx_elem_s)},
#line 356 "c/zx-hrxml.gperf"
    {"ServiceStatus", sizeof(struct zx_elem_s)},
    {""},
#line 102 "c/zx-hrxml.gperf"
    {"DegreeClassification", sizeof(struct zx_hrxml_DegreeClassification_s)},
    {""},
#line 123 "c/zx-hrxml.gperf"
    {"Edition", sizeof(struct zx_elem_s)},
    {""},
#line 197 "c/zx-hrxml.gperf"
    {"LegalName", sizeof(struct zx_elem_s)},
#line 104 "c/zx-hrxml.gperf"
    {"DegreeDate", sizeof(struct zx_hrxml_DegreeDate_s)},
#line 95 "c/zx-hrxml.gperf"
    {"CumulativeSummaryIndicator", sizeof(struct zx_elem_s)},
    {""},
#line 69 "c/zx-hrxml.gperf"
    {"Comments", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 366 "c/zx-hrxml.gperf"
    {"StartRank", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 141 "c/zx-hrxml.gperf"
    {"EvidenceId", sizeof(struct zx_hrxml_EvidenceId_s)},
    {""},
#line 212 "c/zx-hrxml.gperf"
    {"Measure", sizeof(struct zx_hrxml_Measure_s)},
#line 148 "c/zx-hrxml.gperf"
    {"EyeColor", sizeof(struct zx_elem_s)},
#line 173 "c/zx-hrxml.gperf"
    {"Insurance", sizeof(struct zx_hrxml_Insurance_s)},
#line 218 "c/zx-hrxml.gperf"
    {"Minor", sizeof(struct zx_elem_s)},
    {""},
#line 370 "c/zx-hrxml.gperf"
    {"Stock", sizeof(struct zx_hrxml_Stock_s)},
    {""}, {""},
#line 272 "c/zx-hrxml.gperf"
    {"PersonName", sizeof(struct zx_hrxml_PersonName_s)},
    {""}, {""}, {""}, {""},
#line 302 "c/zx-hrxml.gperf"
    {"QualificationSummary", sizeof(struct zx_elem_s)},
#line 111 "c/zx-hrxml.gperf"
    {"Description", sizeof(struct zx_hrxml_Description_s)},
#line 271 "c/zx-hrxml.gperf"
    {"PersonMember", sizeof(struct zx_hrxml_PersonMember_s)},
#line 177 "c/zx-hrxml.gperf"
    {"Interval", sizeof(struct zx_elem_s)},
#line 256 "c/zx-hrxml.gperf"
    {"OverallPerformanceRating", sizeof(struct zx_elem_s)},
#line 371 "c/zx-hrxml.gperf"
    {"StreetName", sizeof(struct zx_elem_s)},
#line 68 "c/zx-hrxml.gperf"
    {"ClassRank", sizeof(struct zx_hrxml_ClassRank_s)},
#line 246 "c/zx-hrxml.gperf"
    {"OriginalDate", sizeof(struct zx_hrxml_OriginalDate_s)},
#line 352 "c/zx-hrxml.gperf"
    {"SecurityCredential", sizeof(struct zx_hrxml_SecurityCredential_s)},
#line 322 "c/zx-hrxml.gperf"
    {"RemunerationPackage", sizeof(struct zx_hrxml_RemunerationPackage_s)},
    {""}, {""},
#line 77 "c/zx-hrxml.gperf"
    {"CompetencyId", sizeof(struct zx_hrxml_CompetencyId_s)},
#line 134 "c/zx-hrxml.gperf"
    {"EndingCompensation", sizeof(struct zx_hrxml_EndingCompensation_s)},
    {""},
#line 263 "c/zx-hrxml.gperf"
    {"PatentMilestone", sizeof(struct zx_hrxml_PatentMilestone_s)},
#line 227 "c/zx-hrxml.gperf"
    {"NonStandardValue", sizeof(struct zx_elem_s)},
#line 74 "c/zx-hrxml.gperf"
    {"Compensation", sizeof(struct zx_hrxml_Compensation_s)},
#line 76 "c/zx-hrxml.gperf"
    {"CompetencyEvidence", sizeof(struct zx_hrxml_CompetencyEvidence_s)},
    {""},
#line 109 "c/zx-hrxml.gperf"
    {"DeliveryAddress", sizeof(struct zx_hrxml_DeliveryAddress_s)},
#line 78 "c/zx-hrxml.gperf"
    {"CompetencyWeight", sizeof(struct zx_hrxml_CompetencyWeight_s)},
#line 288 "c/zx-hrxml.gperf"
    {"PreferredLanguage", sizeof(struct zx_hrxml_PreferredLanguage_s)},
#line 287 "c/zx-hrxml.gperf"
    {"PreferredGivenName", sizeof(struct zx_elem_s)},
#line 223 "c/zx-hrxml.gperf"
    {"MostRecentDate", sizeof(struct zx_hrxml_MostRecentDate_s)},
#line 375 "c/zx-hrxml.gperf"
    {"SupplierId", sizeof(struct zx_hrxml_SupplierId_s)},
#line 219 "c/zx-hrxml.gperf"
    {"MissionStatement", sizeof(struct zx_elem_s)},
#line 289 "c/zx-hrxml.gperf"
    {"PreferredPosition", sizeof(struct zx_hrxml_PreferredPosition_s)},
    {""}, {""},
#line 39 "c/zx-hrxml.gperf"
    {"AreaOfExpertise", sizeof(struct zx_elem_s)},
    {""},
#line 199 "c/zx-hrxml.gperf"
    {"LicenseOrCertification", sizeof(struct zx_hrxml_LicenseOrCertification_s)},
#line 162 "c/zx-hrxml.gperf"
    {"HighestPossibleValue", sizeof(struct zx_hrxml_HighestPossibleValue_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 86 "c/zx-hrxml.gperf"
    {"ContactName", sizeof(struct zx_hrxml_ContactName_s)},
    {""},
#line 85 "c/zx-hrxml.gperf"
    {"ContactMethod", sizeof(struct zx_hrxml_ContactMethod_s)},
#line 296 "c/zx-hrxml.gperf"
    {"ProgramId", sizeof(struct zx_hrxml_ProgramId_s)},
#line 357 "c/zx-hrxml.gperf"
    {"Shift", sizeof(struct zx_hrxml_Shift_s)},
#line 25 "c/zx-hrxml.gperf"
    {"Achievement", sizeof(struct zx_hrxml_Achievement_s)},
#line 26 "c/zx-hrxml.gperf"
    {"Achievements", sizeof(struct zx_hrxml_Achievements_s)},
#line 337 "c/zx-hrxml.gperf"
    {"SchoolId", sizeof(struct zx_hrxml_SchoolId_s)},
#line 316 "c/zx-hrxml.gperf"
    {"RelatedOrganization", sizeof(struct zx_hrxml_RelatedOrganization_s)},
    {""},
#line 250 "c/zx-hrxml.gperf"
    {"OtherHonors", sizeof(struct zx_hrxml_OtherHonors_s)},
    {""},
#line 247 "c/zx-hrxml.gperf"
    {"OtherBenefits", sizeof(struct zx_hrxml_OtherBenefits_s)},
#line 292 "c/zx-hrxml.gperf"
    {"ProfessionalAssociations", sizeof(struct zx_hrxml_ProfessionalAssociations_s)},
#line 317 "c/zx-hrxml.gperf"
    {"RelatedOrganizationalUnit", sizeof(struct zx_hrxml_RelatedOrganizationalUnit_s)},
#line 249 "c/zx-hrxml.gperf"
    {"OtherDescriptors", sizeof(struct zx_hrxml_OtherDescriptors_s)},
#line 330 "c/zx-hrxml.gperf"
    {"RevisionDate", sizeof(struct zx_elem_s)},
    {""},
#line 377 "c/zx-hrxml.gperf"
    {"SupportingMaterials", sizeof(struct zx_hrxml_SupportingMaterials_s)},
#line 326 "c/zx-hrxml.gperf"
    {"ResumeAdditionalItem", sizeof(struct zx_hrxml_ResumeAdditionalItem_s)},
#line 376 "c/zx-hrxml.gperf"
    {"SupportingInformation", sizeof(struct zx_elem_s)},
    {""},
#line 328 "c/zx-hrxml.gperf"
    {"ResumeId", sizeof(struct zx_elem_s)},
#line 79 "c/zx-hrxml.gperf"
    {"ConferenceDate", sizeof(struct zx_hrxml_ConferenceDate_s)},
#line 209 "c/zx-hrxml.gperf"
    {"Major", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 58 "c/zx-hrxml.gperf"
    {"Campaign", sizeof(struct zx_elem_s)},
    {""},
#line 81 "c/zx-hrxml.gperf"
    {"ConferencePaper", sizeof(struct zx_hrxml_ConferencePaper_s)},
    {""},
#line 132 "c/zx-hrxml.gperf"
    {"EndDate", sizeof(struct zx_hrxml_EndDate_s)},
#line 80 "c/zx-hrxml.gperf"
    {"ConferenceLocation", sizeof(struct zx_elem_s)},
#line 339 "c/zx-hrxml.gperf"
    {"SchoolOrInstitution", sizeof(struct zx_hrxml_SchoolOrInstitution_s)},
#line 291 "c/zx-hrxml.gperf"
    {"PrimaryLanguage", sizeof(struct zx_hrxml_PrimaryLanguage_s)},
    {""}, {""},
#line 284 "c/zx-hrxml.gperf"
    {"PostOfficeBox", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""}, {""},
#line 139 "c/zx-hrxml.gperf"
    {"EventName", sizeof(struct zx_elem_s)},
#line 407 "c/zx-hrxml.gperf"
    {"VisaStatus", sizeof(struct zx_hrxml_VisaStatus_s)},
    {""}, {""}, {""}, {""}, {""},
#line 344 "c/zx-hrxml.gperf"
    {"SearchRelevanceRank", sizeof(struct zx_elem_s)},
#line 171 "c/zx-hrxml.gperf"
    {"IndustryCode", sizeof(struct zx_hrxml_IndustryCode_s)},
    {""}, {""},
#line 293 "c/zx-hrxml.gperf"
    {"ProficencyLevel", sizeof(struct zx_elem_s)},
#line 308 "c/zx-hrxml.gperf"
    {"RankedSearchResults", sizeof(struct zx_hrxml_RankedSearchResults_s)},
#line 127 "c/zx-hrxml.gperf"
    {"EligibleForRehire", sizeof(struct zx_elem_s)},
#line 125 "c/zx-hrxml.gperf"
    {"EducationalMeasure", sizeof(struct zx_hrxml_EducationalMeasure_s)},
    {""}, {""}, {""},
#line 29 "c/zx-hrxml.gperf"
    {"AffiliatedOrganization", sizeof(struct zx_elem_s)},
    {""},
#line 172 "c/zx-hrxml.gperf"
    {"IndustryDescription", sizeof(struct zx_elem_s)},
#line 417 "c/zx-hrxml.gperf"
    {"Write", sizeof(struct zx_elem_s)},
#line 30 "c/zx-hrxml.gperf"
    {"AffirmativeActionPlanJobGroupId", sizeof(struct zx_hrxml_AffirmativeActionPlanJobGroupId_s)},
#line 228 "c/zx-hrxml.gperf"
    {"NonXMLResume", sizeof(struct zx_hrxml_NonXMLResume_s)},
#line 210 "c/zx-hrxml.gperf"
    {"MaritalStatus", sizeof(struct zx_elem_s)},
    {""},
#line 31 "c/zx-hrxml.gperf"
    {"Affix", sizeof(struct zx_hrxml_Affix_s)},
#line 373 "c/zx-hrxml.gperf"
    {"StringValue", sizeof(struct zx_hrxml_StringValue_s)},
#line 236 "c/zx-hrxml.gperf"
    {"OrgInfo", sizeof(struct zx_hrxml_OrgInfo_s)},
#line 411 "c/zx-hrxml.gperf"
    {"WhenAvailable", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 110 "c/zx-hrxml.gperf"
    {"DemographicDescriptors", sizeof(struct zx_hrxml_DemographicDescriptors_s)},
    {""},
#line 225 "c/zx-hrxml.gperf"
    {"Name", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 53 "c/zx-hrxml.gperf"
    {"Benefits", sizeof(struct zx_hrxml_Benefits_s)},
#line 183 "c/zx-hrxml.gperf"
    {"Item", sizeof(struct zx_elem_s)},
#line 297 "c/zx-hrxml.gperf"
    {"PublicationDate", sizeof(struct zx_hrxml_PublicationDate_s)},
    {""},
#line 403 "c/zx-hrxml.gperf"
    {"Verification", sizeof(struct zx_hrxml_Verification_s)},
    {""},
#line 299 "c/zx-hrxml.gperf"
    {"PublicationLanguage", sizeof(struct zx_hrxml_PublicationLanguage_s)},
    {""}, {""}, {""}, {""}, {""},
#line 180 "c/zx-hrxml.gperf"
    {"IsPublicCompany", sizeof(struct zx_elem_s)},
#line 46 "c/zx-hrxml.gperf"
    {"AvailabilityInfo", sizeof(struct zx_hrxml_AvailabilityInfo_s)},
#line 178 "c/zx-hrxml.gperf"
    {"InventorName", sizeof(struct zx_elem_s)},
    {""},
#line 179 "c/zx-hrxml.gperf"
    {"Inventors", sizeof(struct zx_hrxml_Inventors_s)},
#line 75 "c/zx-hrxml.gperf"
    {"Competency", sizeof(struct zx_hrxml_Competency_s)},
    {""},
#line 45 "c/zx-hrxml.gperf"
    {"AvailabilityDates", sizeof(struct zx_hrxml_AvailabilityDates_s)},
    {""},
#line 313 "c/zx-hrxml.gperf"
    {"Reference", sizeof(struct zx_hrxml_Reference_s)},
    {""}, {""},
#line 187 "c/zx-hrxml.gperf"
    {"JobPlan", sizeof(struct zx_elem_s)},
#line 213 "c/zx-hrxml.gperf"
    {"MeasureSystem", sizeof(struct zx_elem_s)},
#line 189 "c/zx-hrxml.gperf"
    {"JournalOrSerialName", sizeof(struct zx_elem_s)},
#line 314 "c/zx-hrxml.gperf"
    {"References", sizeof(struct zx_hrxml_References_s)},
    {""},
#line 72 "c/zx-hrxml.gperf"
    {"CompanyScale", sizeof(struct zx_elem_s)},
#line 146 "c/zx-hrxml.gperf"
    {"ExpatriateBenefits", sizeof(struct zx_hrxml_ExpatriateBenefits_s)},
    {""},
#line 147 "c/zx-hrxml.gperf"
    {"ExpatriateBenefitsOffered", sizeof(struct zx_elem_s)},
#line 145 "c/zx-hrxml.gperf"
    {"ExpatriateBenefitList", sizeof(struct zx_elem_s)},
    {""},
#line 354 "c/zx-hrxml.gperf"
    {"ServiceDetail", sizeof(struct zx_hrxml_ServiceDetail_s)},
    {""}, {""},
#line 410 "c/zx-hrxml.gperf"
    {"Weight", sizeof(struct zx_hrxml_Weight_s)},
#line 400 "c/zx-hrxml.gperf"
    {"ValidTo", sizeof(struct zx_hrxml_ValidTo_s)},
    {""}, {""}, {""},
#line 264 "c/zx-hrxml.gperf"
    {"PatentTitle", sizeof(struct zx_elem_s)},
#line 350 "c/zx-hrxml.gperf"
    {"SearchTarget", sizeof(struct zx_elem_s)},
    {""},
#line 100 "c/zx-hrxml.gperf"
    {"DatesOfService", sizeof(struct zx_hrxml_DatesOfService_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 307 "c/zx-hrxml.gperf"
    {"RankedResult", sizeof(struct zx_hrxml_RankedResult_s)},
#line 108 "c/zx-hrxml.gperf"
    {"DegreeName", sizeof(struct zx_hrxml_DegreeName_s)},
    {""},
#line 253 "c/zx-hrxml.gperf"
    {"OtherPayAmountMin", sizeof(struct zx_elem_s)},
#line 106 "c/zx-hrxml.gperf"
    {"DegreeMeasure", sizeof(struct zx_hrxml_DegreeMeasure_s)},
#line 254 "c/zx-hrxml.gperf"
    {"OtherPayCalculation", sizeof(struct zx_elem_s)},
#line 338 "c/zx-hrxml.gperf"
    {"SchoolName", sizeof(struct zx_elem_s)},
#line 105 "c/zx-hrxml.gperf"
    {"DegreeMajor", sizeof(struct zx_hrxml_DegreeMajor_s)},
    {""}, {""}, {""},
#line 55 "c/zx-hrxml.gperf"
    {"BirthPlace", sizeof(struct zx_elem_s)},
    {""},
#line 248 "c/zx-hrxml.gperf"
    {"OtherCompensation", sizeof(struct zx_hrxml_OtherCompensation_s)},
    {""}, {""}, {""}, {""}, {""}, {""},
#line 157 "c/zx-hrxml.gperf"
    {"GivenName", sizeof(struct zx_elem_s)},
    {""},
#line 182 "c/zx-hrxml.gperf"
    {"IssuingAuthority", sizeof(struct zx_hrxml_IssuingAuthority_s)},
#line 47 "c/zx-hrxml.gperf"
    {"BKZClassification", sizeof(struct zx_hrxml_BKZClassification_s)},
#line 143 "c/zx-hrxml.gperf"
    {"Exchange", sizeof(struct zx_elem_s)},
#line 202 "c/zx-hrxml.gperf"
    {"LinkToResume", sizeof(struct zx_elem_s)},
#line 130 "c/zx-hrxml.gperf"
    {"EmployerOrgName", sizeof(struct zx_elem_s)},
#line 107 "c/zx-hrxml.gperf"
    {"DegreeMinor", sizeof(struct zx_hrxml_DegreeMinor_s)},
#line 99 "c/zx-hrxml.gperf"
    {"DatesOfAttendance", sizeof(struct zx_hrxml_DatesOfAttendance_s)},
    {""},
#line 128 "c/zx-hrxml.gperf"
    {"EmployerContactInfo", sizeof(struct zx_hrxml_EmployerContactInfo_s)},
    {""}, {""},
#line 252 "c/zx-hrxml.gperf"
    {"OtherPayAmountMax", sizeof(struct zx_elem_s)},
    {""},
#line 294 "c/zx-hrxml.gperf"
    {"ProfileId", sizeof(struct zx_hrxml_ProfileId_s)},
#line 388 "c/zx-hrxml.gperf"
    {"Title", sizeof(struct zx_elem_s)},
#line 226 "c/zx-hrxml.gperf"
    {"Nationality", sizeof(struct zx_elem_s)},
#line 233 "c/zx-hrxml.gperf"
    {"Offered", sizeof(struct zx_elem_s)},
    {""},
#line 383 "c/zx-hrxml.gperf"
    {"Telephone", sizeof(struct zx_hrxml_Telephone_s)},
#line 166 "c/zx-hrxml.gperf"
    {"ISCEDInstitutionClassification", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 217 "c/zx-hrxml.gperf"
    {"MilitaryStatus", sizeof(struct zx_hrxml_MilitaryStatus_s)},
    {""},
#line 124 "c/zx-hrxml.gperf"
    {"EducationHistory", sizeof(struct zx_hrxml_EducationHistory_s)},
    {""},
#line 96 "c/zx-hrxml.gperf"
    {"CurrentOrEndRank", sizeof(struct zx_elem_s)},
    {""},
#line 211 "c/zx-hrxml.gperf"
    {"MatchedObjectId", sizeof(struct zx_hrxml_MatchedObjectId_s)},
    {""}, {""}, {""},
#line 232 "c/zx-hrxml.gperf"
    {"Objective", sizeof(struct zx_elem_s)},
    {""},
#line 259 "c/zx-hrxml.gperf"
    {"ParkingInstructions", sizeof(struct zx_hrxml_ParkingInstructions_s)},
    {""}, {""},
#line 87 "c/zx-hrxml.gperf"
    {"Copyright", sizeof(struct zx_hrxml_Copyright_s)},
#line 257 "c/zx-hrxml.gperf"
    {"PageNumber", sizeof(struct zx_elem_s)},
#line 54 "c/zx-hrxml.gperf"
    {"BiologicalDescriptors", sizeof(struct zx_hrxml_BiologicalDescriptors_s)},
    {""},
#line 89 "c/zx-hrxml.gperf"
    {"CopyrightText", sizeof(struct zx_elem_s)},
#line 88 "c/zx-hrxml.gperf"
    {"CopyrightDates", sizeof(struct zx_hrxml_CopyrightDates_s)},
#line 401 "c/zx-hrxml.gperf"
    {"Value", sizeof(struct zx_elem_s)},
#line 408 "c/zx-hrxml.gperf"
    {"Volume", sizeof(struct zx_elem_s)},
#line 237 "c/zx-hrxml.gperf"
    {"OrgName", sizeof(struct zx_hrxml_OrgName_s)},
    {""}, {""}, {""}, {""}, {""},
#line 221 "c/zx-hrxml.gperf"
    {"MonthDay", sizeof(struct zx_elem_s)},
#line 140 "c/zx-hrxml.gperf"
    {"EventType", sizeof(struct zx_elem_s)},
    {""},
#line 129 "c/zx-hrxml.gperf"
    {"EmployerOrg", sizeof(struct zx_hrxml_EmployerOrg_s)},
    {""},
#line 298 "c/zx-hrxml.gperf"
    {"PublicationHistory", sizeof(struct zx_hrxml_PublicationHistory_s)},
    {""}, {""}, {""},
#line 71 "c/zx-hrxml.gperf"
    {"Company", sizeof(struct zx_hrxml_Company_s)},
    {""},
#line 402 "c/zx-hrxml.gperf"
    {"ValueStatement", sizeof(struct zx_elem_s)},
#line 406 "c/zx-hrxml.gperf"
    {"VisaSponsorship", sizeof(struct zx_elem_s)},
#line 378 "c/zx-hrxml.gperf"
    {"Symbol", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 57 "c/zx-hrxml.gperf"
    {"BuildingNumber", sizeof(struct zx_elem_s)},
#line 149 "c/zx-hrxml.gperf"
    {"FamilyName", sizeof(struct zx_hrxml_FamilyName_s)},
    {""},
#line 169 "c/zx-hrxml.gperf"
    {"IdValue", sizeof(struct zx_hrxml_IdValue_s)},
#line 185 "c/zx-hrxml.gperf"
    {"JobGrade", sizeof(struct zx_elem_s)},
#line 306 "c/zx-hrxml.gperf"
    {"RankAchieved", sizeof(struct zx_hrxml_RankAchieved_s)},
    {""}, {""}, {""}, {""},
#line 240 "c/zx-hrxml.gperf"
    {"OrganizationId", sizeof(struct zx_hrxml_OrganizationId_s)},
    {""},
#line 241 "c/zx-hrxml.gperf"
    {"OrganizationName", sizeof(struct zx_elem_s)},
#line 239 "c/zx-hrxml.gperf"
    {"Organization", sizeof(struct zx_hrxml_Organization_s)},
#line 142 "c/zx-hrxml.gperf"
    {"ExcessiveValueIndicator", sizeof(struct zx_elem_s)},
#line 138 "c/zx-hrxml.gperf"
    {"Ethnicity", sizeof(struct zx_elem_s)},
#line 244 "c/zx-hrxml.gperf"
    {"OrganizationalUnitId", sizeof(struct zx_hrxml_OrganizationalUnitId_s)},
#line 242 "c/zx-hrxml.gperf"
    {"OrganizationUnit", sizeof(struct zx_hrxml_OrganizationUnit_s)},
#line 245 "c/zx-hrxml.gperf"
    {"OrganizationalUnitName", sizeof(struct zx_elem_s)},
#line 243 "c/zx-hrxml.gperf"
    {"OrganizationalUnit", sizeof(struct zx_hrxml_OrganizationalUnit_s)},
    {""},
#line 385 "c/zx-hrxml.gperf"
    {"TextResume", sizeof(struct zx_elem_s)},
#line 405 "c/zx-hrxml.gperf"
    {"VerticalAccuracy", sizeof(struct zx_hrxml_VerticalAccuracy_s)},
#line 117 "c/zx-hrxml.gperf"
    {"DistributeTo", sizeof(struct zx_hrxml_DistributeTo_s)},
#line 355 "c/zx-hrxml.gperf"
    {"ServiceNumber", sizeof(struct zx_hrxml_ServiceNumber_s)},
    {""}, {""}, {""}, {""},
#line 251 "c/zx-hrxml.gperf"
    {"OtherPay", sizeof(struct zx_hrxml_OtherPay_s)},
    {""}, {""},
#line 52 "c/zx-hrxml.gperf"
    {"BasePayAmountMin", sizeof(struct zx_elem_s)},
    {""},
#line 301 "c/zx-hrxml.gperf"
    {"PublisherName", sizeof(struct zx_elem_s)},
    {""},
#line 135 "c/zx-hrxml.gperf"
    {"EntityName", sizeof(struct zx_elem_s)},
    {""},
#line 118 "c/zx-hrxml.gperf"
    {"DistributionGuidelines", sizeof(struct zx_elem_s)},
    {""},
#line 399 "c/zx-hrxml.gperf"
    {"ValidFrom", sizeof(struct zx_hrxml_ValidFrom_s)},
    {""}, {""},
#line 300 "c/zx-hrxml.gperf"
    {"PublisherLocation", sizeof(struct zx_elem_s)},
    {""},
#line 393 "c/zx-hrxml.gperf"
    {"Type", sizeof(struct zx_elem_s)},
#line 222 "c/zx-hrxml.gperf"
    {"MonthDayOfBirth", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""}, {""}, {""},
#line 224 "c/zx-hrxml.gperf"
    {"Municipality", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 215 "c/zx-hrxml.gperf"
    {"MiddleName", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 121 "c/zx-hrxml.gperf"
    {"DunsNumber", sizeof(struct zx_hrxml_DunsNumber_s)},
#line 51 "c/zx-hrxml.gperf"
    {"BasePayAmountMax", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 335 "c/zx-hrxml.gperf"
    {"SafetyEquipment", sizeof(struct zx_hrxml_SafetyEquipment_s)},
    {""}, {""}, {""}, {""},
#line 48 "c/zx-hrxml.gperf"
    {"BKZId", sizeof(struct zx_hrxml_BKZId_s)},
    {""}, {""}, {""}, {""},
#line 37 "c/zx-hrxml.gperf"
    {"Applicable", sizeof(struct zx_elem_s)},
    {""},
#line 386 "c/zx-hrxml.gperf"
    {"TimeMax", sizeof(struct zx_hrxml_TimeMax_s)},
    {""}, {""},
#line 216 "c/zx-hrxml.gperf"
    {"MilitaryHistory", sizeof(struct zx_hrxml_MilitaryHistory_s)},
#line 295 "c/zx-hrxml.gperf"
    {"ProfileName", sizeof(struct zx_elem_s)},
#line 186 "c/zx-hrxml.gperf"
    {"JobLevelInfo", sizeof(struct zx_hrxml_JobLevelInfo_s)},
    {""}, {""}, {""},
#line 235 "c/zx-hrxml.gperf"
    {"OrgIndustry", sizeof(struct zx_hrxml_OrgIndustry_s)},
    {""}, {""}, {""}, {""},
#line 170 "c/zx-hrxml.gperf"
    {"IdentifyingMarks", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 351 "c/zx-hrxml.gperf"
    {"SearchTimeStamp", sizeof(struct zx_elem_s)},
#line 184 "c/zx-hrxml.gperf"
    {"JobCategory", sizeof(struct zx_hrxml_JobCategory_s)},
#line 50 "c/zx-hrxml.gperf"
    {"BasePay", sizeof(struct zx_hrxml_BasePay_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 380 "c/zx-hrxml.gperf"
    {"TaxId", sizeof(struct zx_hrxml_TaxId_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""},
#line 136 "c/zx-hrxml.gperf"
    {"EnvironmentId", sizeof(struct zx_hrxml_EnvironmentId_s)},
    {""},
#line 137 "c/zx-hrxml.gperf"
    {"EnvironmentName", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 358 "c/zx-hrxml.gperf"
    {"SourceType", sizeof(struct zx_hrxml_SourceType_s)},
#line 220 "c/zx-hrxml.gperf"
    {"Mobile", sizeof(struct zx_hrxml_Mobile_s)},
    {""}, {""}, {""}, {""},
#line 144 "c/zx-hrxml.gperf"
    {"ExecutiveSummary", sizeof(struct zx_elem_s)},
    {""},
#line 201 "c/zx-hrxml.gperf"
    {"Link", sizeof(struct zx_elem_s)},
    {""},
#line 412 "c/zx-hrxml.gperf"
    {"WorkSite", sizeof(struct zx_hrxml_WorkSite_s)},
    {""},
#line 414 "c/zx-hrxml.gperf"
    {"WorkSiteId", sizeof(struct zx_hrxml_WorkSiteId_s)},
    {""},
#line 415 "c/zx-hrxml.gperf"
    {"WorkSiteName", sizeof(struct zx_elem_s)},
#line 265 "c/zx-hrxml.gperf"
    {"PayTypeHours", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""}, {""}, {""},
#line 214 "c/zx-hrxml.gperf"
    {"MeasureValue", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 413 "c/zx-hrxml.gperf"
    {"WorkSiteEnvironment", sizeof(struct zx_hrxml_WorkSiteEnvironment_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""},
#line 133 "c/zx-hrxml.gperf"
    {"EndTime", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""},
#line 381 "c/zx-hrxml.gperf"
    {"TaxonomyId", sizeof(struct zx_hrxml_TaxonomyId_s)},
    {""},
#line 382 "c/zx-hrxml.gperf"
    {"TaxonomyName", sizeof(struct zx_hrxml_TaxonomyName_s)},
    {""}, {""}, {""},
#line 98 "c/zx-hrxml.gperf"
    {"DateOfBirth", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""},
#line 131 "c/zx-hrxml.gperf"
    {"EmploymentHistory", sizeof(struct zx_hrxml_EmploymentHistory_s)},
    {""}, {""},
#line 390 "c/zx-hrxml.gperf"
    {"TravelConsiderations", sizeof(struct zx_elem_s)},
    {""},
#line 49 "c/zx-hrxml.gperf"
    {"BKZName", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""},
#line 389 "c/zx-hrxml.gperf"
    {"Travel", sizeof(struct zx_hrxml_Travel_s)},
#line 409 "c/zx-hrxml.gperf"
    {"WebSite", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""},
#line 188 "c/zx-hrxml.gperf"
    {"JobStep", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 167 "c/zx-hrxml.gperf"
    {"ISSN", sizeof(struct zx_elem_s)},
    {""},
#line 404 "c/zx-hrxml.gperf"
    {"VerifyEmployment", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 255 "c/zx-hrxml.gperf"
    {"OtherPublication", sizeof(struct zx_hrxml_OtherPublication_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""},
#line 73 "c/zx-hrxml.gperf"
    {"CompanyVehicle", sizeof(struct zx_hrxml_CompanyVehicle_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""},
#line 231 "c/zx-hrxml.gperf"
    {"NumericValue", sizeof(struct zx_hrxml_NumericValue_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 391 "c/zx-hrxml.gperf"
    {"TravelDirections", sizeof(struct zx_hrxml_TravelDirections_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""},
#line 416 "c/zx-hrxml.gperf"
    {"WorkStyle", sizeof(struct zx_elem_s)},
    {""},
#line 126 "c/zx-hrxml.gperf"
    {"EffectiveDate", sizeof(struct zx_hrxml_EffectiveDate_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 384 "c/zx-hrxml.gperf"
    {"TermOfNotice", sizeof(struct zx_hrxml_TermOfNotice_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""},
#line 392 "c/zx-hrxml.gperf"
    {"TravelFrequency", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""},
#line 198 "c/zx-hrxml.gperf"
    {"LevelOfDisability", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 387 "c/zx-hrxml.gperf"
    {"TimeOffAllowance", sizeof(struct zx_hrxml_TimeOffAllowance_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""},
#line 56 "c/zx-hrxml.gperf"
    {"Book", sizeof(struct zx_hrxml_Book_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 122 "c/zx-hrxml.gperf"
    {"EEOCJobCategory", sizeof(struct zx_hrxml_EEOCJobCategory_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""},
#line 379 "c/zx-hrxml.gperf"
    {"TTYTDD", sizeof(struct zx_hrxml_TTYTDD_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""},
#line 165 "c/zx-hrxml.gperf"
    {"ISBN", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""},
#line 230 "c/zx-hrxml.gperf"
    {"NumberOfPages", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 229 "c/zx-hrxml.gperf"
    {"NumberOfChildren", sizeof(struct zx_elem_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_hrxml_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_hrxml_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_hrxml_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_hrxml_el_tab[key];
          }
    }
  return 0;
}
#line 420 "c/zx-hrxml.gperf"

/* EOF */
