/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-is.gperf  */
/* Computed positions: -k'3' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-is.gperf"

/* c/zx-is-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-is-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 13
#define MIN_WORD_LENGTH 4
#define MAX_WORD_LENGTH 20
#define MIN_HASH_VALUE 4
#define MAX_HASH_VALUE 24
/* maximum key range = 21, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_is_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25,  5, 25,
      25,  4, 25, 25, 25, 25, 25, 25,  0, 25,
       5, 25, 25,  0, 15, 25,  0, 25, 25, 25,
      10, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
      25, 25, 25, 25, 25, 25
    };
  return len + asso_values[(unsigned char)str[2]];
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  4,  5,  6,  7,  4,  4,  5,  0,  7,  0,
     4,  0,  0,  0, 18, 19, 20,  0,  0,  0,  9
  };

struct zx_el_tok zx_is_el_tab[] =
  {
    {""}, {""}, {""}, {""},
#line 19 "c/zx-is.gperf"
    {"Help", sizeof(struct zx_is_Help_s)},
#line 30 "c/zx-is.gperf"
    {"Value", sizeof(struct zx_elem_s)},
#line 28 "c/zx-is.gperf"
    {"Select", sizeof(struct zx_is_Select_s)},
#line 21 "c/zx-is.gperf"
    {"Inquiry", sizeof(struct zx_is_Inquiry_s)},
#line 25 "c/zx-is.gperf"
    {"Item", sizeof(struct zx_is_Item_s)},
#line 20 "c/zx-is.gperf"
    {"Hint", sizeof(struct zx_elem_s)},
#line 26 "c/zx-is.gperf"
    {"Label", sizeof(struct zx_elem_s)},
    {""},
#line 18 "c/zx-is.gperf"
    {"Confirm", sizeof(struct zx_is_Confirm_s)},
    {""},
#line 29 "c/zx-is.gperf"
    {"Text", sizeof(struct zx_is_Text_s)},
    {""}, {""}, {""},
#line 22 "c/zx-is.gperf"
    {"InteractionRequest", sizeof(struct zx_is_InteractionRequest_s)},
#line 23 "c/zx-is.gperf"
    {"InteractionResponse", sizeof(struct zx_is_InteractionResponse_s)},
#line 24 "c/zx-is.gperf"
    {"InteractionStatement", sizeof(struct zx_is_InteractionStatement_s)},
    {""}, {""}, {""},
#line 27 "c/zx-is.gperf"
    {"Parameter", sizeof(struct zx_is_Parameter_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_is_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_is_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_is_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_is_el_tab[key];
          }
    }
  return 0;
}
#line 31 "c/zx-is.gperf"

/* EOF */
