/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-idp.gperf  */
/* Computed positions: -k'1' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-idp.gperf"

/* c/zx-idp-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-idp-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 14
#define MIN_WORD_LENGTH 7
#define MAX_WORD_LENGTH 24
#define MIN_HASH_VALUE 7
#define MAX_HASH_VALUE 33
/* maximum key range = 27, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_idp_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34,  5, 34,  0, 34, 34,
      34,  0, 34, 34, 34, 34, 34,  0, 34, 34,
      15, 34, 34, 15, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
      34, 34, 34, 34, 34, 34
    };
  return len + asso_values[(unsigned char)str[0]];
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0, 12, 13,
     0, 15,  0, 17, 13,  0, 20, 21,  0, 23, 24, 10,  0, 12,
    23,  0,  0,  0,  0, 18
  };

struct zx_el_tok zx_idp_el_tab[] =
  {
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 28 "c/zx-idp.gperf"
    {"MEDInfo", sizeof(struct zx_idp_MEDInfo_s)},
    {""}, {""}, {""}, {""},
#line 23 "c/zx-idp.gperf"
    {"GetAssertion", sizeof(struct zx_idp_GetAssertion_s)},
#line 20 "c/zx-idp.gperf"
    {"CreatedStatus", sizeof(struct zx_idp_CreatedStatus_s)},
    {""},
#line 26 "c/zx-idp.gperf"
    {"GetProviderInfo", sizeof(struct zx_idp_GetProviderInfo_s)},
    {""},
#line 21 "c/zx-idp.gperf"
    {"CreatedStatusItem", sizeof(struct zx_idp_CreatedStatusItem_s)},
#line 18 "c/zx-idp.gperf"
    {"AssertionItem", sizeof(struct zx_idp_AssertionItem_s)},
    {""},
#line 24 "c/zx-idp.gperf"
    {"GetAssertionResponse", sizeof(struct zx_idp_GetAssertionResponse_s)},
#line 22 "c/zx-idp.gperf"
    {"CreatedStatusResponse", sizeof(struct zx_idp_CreatedStatusResponse_s)},
    {""},
#line 27 "c/zx-idp.gperf"
    {"GetProviderInfoResponse", sizeof(struct zx_idp_GetProviderInfoResponse_s)},
#line 25 "c/zx-idp.gperf"
    {"GetAssertionResponseItem", sizeof(struct zx_idp_GetAssertionResponseItem_s)},
#line 29 "c/zx-idp.gperf"
    {"ProviderID", sizeof(struct zx_elem_s)},
    {""},
#line 30 "c/zx-idp.gperf"
    {"ProviderInfo", sizeof(struct zx_idp_ProviderInfo_s)},
#line 19 "c/zx-idp.gperf"
    {"AuthnContextRestriction", sizeof(struct zx_idp_AuthnContextRestriction_s)},
    {""}, {""}, {""}, {""},
#line 31 "c/zx-idp.gperf"
    {"SubjectRestriction", sizeof(struct zx_idp_SubjectRestriction_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_idp_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_idp_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_idp_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_idp_el_tab[key];
          }
    }
  return 0;
}
#line 32 "c/zx-idp.gperf"

/* EOF */
