/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-lu.gperf  */
/* Computed positions: -k'' */

#line 1 "c/zx-lu.gperf"

/* c/zx-lu-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-lu-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 3
#define MIN_WORD_LENGTH 6
#define MAX_WORD_LENGTH 10
#define MIN_HASH_VALUE 6
#define MAX_HASH_VALUE 10
/* maximum key range = 5, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
/*ARGSUSED*/
static unsigned int
zx_lu_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  return len;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  0,  0,  6,  0,  0,  9, 10
  };

struct zx_el_tok zx_lu_el_tab[] =
  {
    {""}, {""}, {""}, {""}, {""}, {""},
#line 19 "c/zx-lu.gperf"
    {"Status", sizeof(struct zx_lu_Status_s)},
    {""}, {""},
#line 18 "c/zx-lu.gperf"
    {"Extension", sizeof(struct zx_lu_Extension_s)},
#line 20 "c/zx-lu.gperf"
    {"TestResult", sizeof(struct zx_lu_TestResult_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_lu_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_lu_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_lu_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_lu_el_tab[key];
          }
    }
  return 0;
}
#line 21 "c/zx-lu.gperf"

/* EOF */
