/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-md.gperf  */
/* Computed positions: -k'2,10' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-md.gperf"

/* c/zx-md-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-md-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 40
#define MIN_WORD_LENGTH 7
#define MAX_WORD_LENGTH 28
#define MIN_HASH_VALUE 7
#define MAX_HASH_VALUE 68
/* maximum key range = 62, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_md_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 20, 69,  5, 20, 69,
      69, 69, 69, 15, 69, 69, 69,  5, 20, 69,
       5, 69, 69, 20, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 15, 69,  0,
      15,  5, 25, 69, 69,  0, 69, 69, 10, 15,
       5,  0,  0, 69,  0, 15, 20, 10, 69, 69,
       0,  0, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69, 69, 69, 69, 69,
      69, 69, 69, 69, 69, 69
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[9]];
      /*FALLTHROUGH*/
      case 9:
      case 8:
      case 7:
      case 6:
      case 5:
      case 4:
      case 3:
      case 2:
        hval += asso_values[(unsigned char)str[1]];
        break;
    }
  return hval;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  0,  0,  0,  7,  0,  9,  0,  0, 12, 13,
    14, 15, 16,  7, 13, 19, 15, 16, 12, 23, 19, 10, 16, 17,
    18,  0, 25, 11, 12, 13, 24, 20, 16,  0, 18, 19, 15, 16,
    12, 18, 24, 15, 21,  0,  0,  0, 25, 26,  0,  0,  0, 25,
    16,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 28
  };

struct zx_el_tok zx_md_el_tab[] =
  {
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 31 "c/zx-md.gperf"
    {"Company", sizeof(struct zx_elem_s)},
    {""},
#line 38 "c/zx-md.gperf"
    {"GivenName", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 44 "c/zx-md.gperf"
    {"Organization", sizeof(struct zx_md_Organization_s)},
#line 32 "c/zx-md.gperf"
    {"ContactPerson", sizeof(struct zx_md_ContactPerson_s)},
#line 50 "c/zx-md.gperf"
    {"RoleDescriptor", sizeof(struct zx_md_RoleDescriptor_s)},
#line 47 "c/zx-md.gperf"
    {"OrganizationURL", sizeof(struct zx_md_OrganizationURL_s)},
#line 46 "c/zx-md.gperf"
    {"OrganizationName", sizeof(struct zx_md_OrganizationName_s)},
#line 56 "c/zx-md.gperf"
    {"SurName", sizeof(struct zx_elem_s)},
#line 40 "c/zx-md.gperf"
    {"KeyDescriptor", sizeof(struct zx_md_KeyDescriptor_s)},
#line 54 "c/zx-md.gperf"
    {"SingleLogoutService", sizeof(struct zx_md_SingleLogoutService_s)},
#line 51 "c/zx-md.gperf"
    {"SPSSODescriptor", sizeof(struct zx_md_SPSSODescriptor_s)},
#line 36 "c/zx-md.gperf"
    {"EntityDescriptor", sizeof(struct zx_md_EntityDescriptor_s)},
#line 30 "c/zx-md.gperf"
    {"AuthzService", sizeof(struct zx_md_AuthzService_s)},
#line 45 "c/zx-md.gperf"
    {"OrganizationDisplayName", sizeof(struct zx_md_OrganizationDisplayName_s)},
#line 55 "c/zx-md.gperf"
    {"SingleSignOnService", sizeof(struct zx_md_SingleSignOnService_s)},
#line 37 "c/zx-md.gperf"
    {"Extensions", sizeof(struct zx_md_Extensions_s)},
#line 34 "c/zx-md.gperf"
    {"EncryptionMethod", sizeof(struct zx_md_EncryptionMethod_s)},
#line 29 "c/zx-md.gperf"
    {"AuthnQueryService", sizeof(struct zx_md_AuthnQueryService_s)},
#line 35 "c/zx-md.gperf"
    {"EntitiesDescriptor", sizeof(struct zx_md_EntitiesDescriptor_s)},
    {""},
#line 21 "c/zx-md.gperf"
    {"ArtifactResolutionService", sizeof(struct zx_md_ArtifactResolutionService_s)},
#line 53 "c/zx-md.gperf"
    {"ServiceName", sizeof(struct zx_md_ServiceName_s)},
#line 33 "c/zx-md.gperf"
    {"EmailAddress", sizeof(struct zx_elem_s)},
#line 48 "c/zx-md.gperf"
    {"PDPDescriptor", sizeof(struct zx_md_PDPDescriptor_s)},
#line 28 "c/zx-md.gperf"
    {"AuthnAuthorityDescriptor", sizeof(struct zx_md_AuthnAuthorityDescriptor_s)},
#line 43 "c/zx-md.gperf"
    {"NameIDMappingService", sizeof(struct zx_md_NameIDMappingService_s)},
#line 39 "c/zx-md.gperf"
    {"IDPSSODescriptor", sizeof(struct zx_md_IDPSSODescriptor_s)},
    {""},
#line 52 "c/zx-md.gperf"
    {"ServiceDescription", sizeof(struct zx_md_ServiceDescription_s)},
#line 41 "c/zx-md.gperf"
    {"ManageNameIDService", sizeof(struct zx_md_ManageNameIDService_s)},
#line 57 "c/zx-md.gperf"
    {"TelephoneNumber", sizeof(struct zx_elem_s)},
#line 26 "c/zx-md.gperf"
    {"AttributeProfile", sizeof(struct zx_elem_s)},
#line 42 "c/zx-md.gperf"
    {"NameIDFormat", sizeof(struct zx_elem_s)},
#line 49 "c/zx-md.gperf"
    {"RequestedAttribute", sizeof(struct zx_md_RequestedAttribute_s)},
#line 22 "c/zx-md.gperf"
    {"AssertionConsumerService", sizeof(struct zx_md_AssertionConsumerService_s)},
#line 19 "c/zx-md.gperf"
    {"AffiliateMember", sizeof(struct zx_elem_s)},
#line 20 "c/zx-md.gperf"
    {"AffiliationDescriptor", sizeof(struct zx_md_AffiliationDescriptor_s)},
    {""}, {""}, {""},
#line 25 "c/zx-md.gperf"
    {"AttributeConsumingService", sizeof(struct zx_md_AttributeConsumingService_s)},
#line 18 "c/zx-md.gperf"
    {"AdditionalMetadataLocation", sizeof(struct zx_md_AdditionalMetadataLocation_s)},
    {""}, {""}, {""},
#line 23 "c/zx-md.gperf"
    {"AssertionIDRequestService", sizeof(struct zx_md_AssertionIDRequestService_s)},
#line 27 "c/zx-md.gperf"
    {"AttributeService", sizeof(struct zx_md_AttributeService_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""},
#line 24 "c/zx-md.gperf"
    {"AttributeAuthorityDescriptor", sizeof(struct zx_md_AttributeAuthorityDescriptor_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_md_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_md_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_md_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_md_el_tab[key];
          }
    }
  return 0;
}
#line 58 "c/zx-md.gperf"

/* EOF */
