/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-m20.gperf  */
/* Computed positions: -k'3,8' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-m20.gperf"

/* c/zx-m20-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-m20-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 38
#define MIN_WORD_LENGTH 7
#define MAX_WORD_LENGTH 48
#define MIN_HASH_VALUE 7
#define MAX_HASH_VALUE 83
/* maximum key range = 77, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_m20_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 25, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
       0, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84,  0, 84,  0,
       5,  0,  5,  0, 84, 10, 84, 84,  0, 15,
      30, 20, 30,  5,  0, 35,  5, 84,  0, 84,
      84, 20, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84, 84, 84, 84, 84,
      84, 84, 84, 84, 84, 84
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[7]];
      /*FALLTHROUGH*/
      case 7:
      case 6:
      case 5:
      case 4:
      case 3:
        hval += asso_values[(unsigned char)str[2]];
        break;
    }
  return hval;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0, 12, 13,
     0, 15, 16, 12,  0,  0, 15, 16,  7, 23,  9, 15, 16,  7,
     0, 19,  0, 21, 32, 13,  9,  0,  0, 37, 38,  0,  0,  0,
    12, 13,  0, 15, 31, 12,  0,  0,  0,  0, 37,  0,  0,  0,
     0, 22, 18,  0,  0,  0, 22, 48,  0,  0,  0, 27,  0,  0,
     0,  0, 22,  0,  0,  0,  0, 27, 28,  0,  0, 36, 27, 38
  };

struct zx_el_tok zx_m20_el_tab[] =
  {
    {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 54 "c/zx-m20.gperf"
    {"SurName", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 40 "c/zx-m20.gperf"
    {"Organization", sizeof(struct zx_m20_Organization_s)},
#line 35 "c/zx-m20.gperf"
    {"IDPDescriptor", sizeof(struct zx_m20_IDPDescriptor_s)},
    {""},
#line 43 "c/zx-m20.gperf"
    {"OrganizationURL", sizeof(struct zx_m20_OrganizationURL_s)},
#line 42 "c/zx-m20.gperf"
    {"OrganizationName", sizeof(struct zx_m20_OrganizationName_s)},
#line 26 "c/zx-m20.gperf"
    {"EmailAddress", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 23 "c/zx-m20.gperf"
    {"AuthnServiceURL", sizeof(struct zx_elem_s)},
#line 29 "c/zx-m20.gperf"
    {"EntityDescriptor", sizeof(struct zx_m20_EntityDescriptor_s)},
#line 24 "c/zx-m20.gperf"
    {"Company", sizeof(struct zx_elem_s)},
#line 41 "c/zx-m20.gperf"
    {"OrganizationDisplayName", sizeof(struct zx_m20_OrganizationDisplayName_s)},
#line 34 "c/zx-m20.gperf"
    {"GivenName", sizeof(struct zx_elem_s)},
#line 19 "c/zx-m20.gperf"
    {"AffiliateMember", sizeof(struct zx_elem_s)},
#line 27 "c/zx-m20.gperf"
    {"EncryptionMethod", sizeof(struct zx_elem_s)},
#line 37 "c/zx-m20.gperf"
    {"KeySize", sizeof(struct zx_elem_s)},
    {""},
#line 22 "c/zx-m20.gperf"
    {"AuthnRequestsSigned", sizeof(struct zx_elem_s)},
    {""},
#line 20 "c/zx-m20.gperf"
    {"AffiliationDescriptor", sizeof(struct zx_m20_AffiliationDescriptor_s)},
#line 46 "c/zx-m20.gperf"
    {"RegisterNameIdentifierServiceURL", sizeof(struct zx_elem_s)},
#line 36 "c/zx-m20.gperf"
    {"KeyDescriptor", sizeof(struct zx_m20_KeyDescriptor_s)},
#line 30 "c/zx-m20.gperf"
    {"Extension", sizeof(struct zx_m20_Extension_s)},
    {""}, {""},
#line 44 "c/zx-m20.gperf"
    {"RegisterNameIdentifierProtocolProfile", sizeof(struct zx_elem_s)},
#line 45 "c/zx-m20.gperf"
    {"RegisterNameIdentifierServiceReturnURL", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 53 "c/zx-m20.gperf"
    {"SoapEndpoint", sizeof(struct zx_elem_s)},
#line 25 "c/zx-m20.gperf"
    {"ContactPerson", sizeof(struct zx_m20_ContactPerson_s)},
    {""},
#line 55 "c/zx-m20.gperf"
    {"TelephoneNumber", sizeof(struct zx_elem_s)},
#line 33 "c/zx-m20.gperf"
    {"FederationTerminationServiceURL", sizeof(struct zx_elem_s)},
#line 47 "c/zx-m20.gperf"
    {"SPDescriptor", sizeof(struct zx_m20_SPDescriptor_s)},
    {""}, {""}, {""}, {""},
#line 32 "c/zx-m20.gperf"
    {"FederationTerminationServiceReturnURL", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 18 "c/zx-m20.gperf"
    {"AdditionalMetaLocation", sizeof(struct zx_m20_AdditionalMetaLocation_s)},
#line 28 "c/zx-m20.gperf"
    {"EntitiesDescriptor", sizeof(struct zx_m20_EntitiesDescriptor_s)},
    {""}, {""}, {""},
#line 52 "c/zx-m20.gperf"
    {"SingleSignOnServiceURL", sizeof(struct zx_elem_s)},
#line 31 "c/zx-m20.gperf"
    {"FederationTerminationNotificationProtocolProfile", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 51 "c/zx-m20.gperf"
    {"SingleSignOnProtocolProfile", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 50 "c/zx-m20.gperf"
    {"SingleLogoutServiceURL", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 48 "c/zx-m20.gperf"
    {"SingleLogoutProtocolProfile", sizeof(struct zx_elem_s)},
#line 49 "c/zx-m20.gperf"
    {"SingleLogoutServiceReturnURL", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 39 "c/zx-m20.gperf"
    {"NameIdentifierMappingProtocolProfile", sizeof(struct zx_elem_s)},
#line 21 "c/zx-m20.gperf"
    {"AssertionConsumerServiceURL", sizeof(struct zx_m20_AssertionConsumerServiceURL_s)},
#line 38 "c/zx-m20.gperf"
    {"NameIdentifierMappingEncryptionProfile", sizeof(struct zx_elem_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_m20_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_m20_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_m20_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_m20_el_tab[key];
          }
    }
  return 0;
}
#line 56 "c/zx-m20.gperf"

/* EOF */
