/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-ps.gperf  */
/* Computed positions: -k'1,5' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-ps.gperf"

/* c/zx-ps-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-ps-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 45
#define MIN_WORD_LENGTH 3
#define MAX_WORD_LENGTH 28
#define MIN_HASH_VALUE 3
#define MAX_HASH_VALUE 67
/* maximum key range = 65, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_ps_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 10, 68, 20,  0,  0,
      20,  5, 68,  0, 68, 68, 15, 68,  0, 45,
      15, 10,  0, 40,  0, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68,  0,
       0, 68, 30,  0, 68, 68, 68, 68, 68,  5,
      68, 15,  5, 68, 68, 68, 68, 15, 68,  0,
      68, 68, 10, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[4]+1];
      /*FALLTHROUGH*/
      case 4:
      case 3:
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  3,  0,  0,  6,  0,  8,  0,  0,  6, 12,  0,
    14,  0, 11, 12, 13, 19, 20, 21, 22, 23, 24, 20, 21, 27,
    28, 24, 25, 11, 17, 18, 19, 20, 21, 22, 23, 19, 20, 16,
    17,  0, 14,  0, 21, 22,  0, 14,  0,  6, 12,  8,  9,  0,
     6,  0,  0,  0, 20, 21,  0,  0,  0,  0,  0, 17
  };

struct zx_el_tok zx_ps_el_tab[] =
  {
    {""}, {""}, {""},
#line 59 "c/zx-ps.gperf"
    {"Tag", sizeof(struct zx_ps_Tag_s)},
    {""}, {""},
#line 35 "c/zx-ps.gperf"
    {"Notify", sizeof(struct zx_ps_Notify_s)},
    {""},
#line 31 "c/zx-ps.gperf"
    {"ItemData", sizeof(struct zx_ps_ItemData_s)},
    {""}, {""},
#line 54 "c/zx-ps.gperf"
    {"Result", sizeof(struct zx_elem_s)},
#line 34 "c/zx-ps.gperf"
    {"Notification", sizeof(struct zx_ps_Notification_s)},
    {""},
#line 36 "c/zx-ps.gperf"
    {"NotifyResponse", sizeof(struct zx_ps_NotifyResponse_s)},
    {""},
#line 27 "c/zx-ps.gperf"
    {"DisplayName", sizeof(struct zx_ps_DisplayName_s)},
#line 52 "c/zx-ps.gperf"
    {"ResolveInput", sizeof(struct zx_ps_ResolveInput_s)},
#line 53 "c/zx-ps.gperf"
    {"ResolveOutput", sizeof(struct zx_ps_ResolveOutput_s)},
#line 46 "c/zx-ps.gperf"
    {"RemoveEntityRequest", sizeof(struct zx_ps_RemoveEntityRequest_s)},
#line 47 "c/zx-ps.gperf"
    {"RemoveEntityResponse", sizeof(struct zx_ps_RemoveEntityResponse_s)},
#line 61 "c/zx-ps.gperf"
    {"TestMembershipRequest", sizeof(struct zx_ps_TestMembershipRequest_s)},
#line 62 "c/zx-ps.gperf"
    {"TestMembershipResponse", sizeof(struct zx_ps_TestMembershipResponse_s)},
#line 44 "c/zx-ps.gperf"
    {"RemoveCollectionRequest", sizeof(struct zx_ps_RemoveCollectionRequest_s)},
#line 45 "c/zx-ps.gperf"
    {"RemoveCollectionResponse", sizeof(struct zx_ps_RemoveCollectionResponse_s)},
#line 29 "c/zx-ps.gperf"
    {"GetObjectInfoRequest", sizeof(struct zx_ps_GetObjectInfoRequest_s)},
#line 30 "c/zx-ps.gperf"
    {"GetObjectInfoResponse", sizeof(struct zx_ps_GetObjectInfoResponse_s)},
#line 48 "c/zx-ps.gperf"
    {"RemoveFromCollectionRequest", sizeof(struct zx_ps_RemoveFromCollectionRequest_s)},
#line 49 "c/zx-ps.gperf"
    {"RemoveFromCollectionResponse", sizeof(struct zx_ps_RemoveFromCollectionResponse_s)},
#line 50 "c/zx-ps.gperf"
    {"ResolveIdentifierRequest", sizeof(struct zx_ps_ResolveIdentifierRequest_s)},
#line 51 "c/zx-ps.gperf"
    {"ResolveIdentifierResponse", sizeof(struct zx_ps_ResolveIdentifierResponse_s)},
#line 43 "c/zx-ps.gperf"
    {"QueryString", sizeof(struct zx_elem_s)},
#line 40 "c/zx-ps.gperf"
    {"PStoSPRedirectURL", sizeof(struct zx_elem_s)},
#line 32 "c/zx-ps.gperf"
    {"ListMembersRequest", sizeof(struct zx_ps_ListMembersRequest_s)},
#line 33 "c/zx-ps.gperf"
    {"ListMembersResponse", sizeof(struct zx_ps_ListMembersResponse_s)},
#line 18 "c/zx-ps.gperf"
    {"AddCollectionRequest", sizeof(struct zx_ps_AddCollectionRequest_s)},
#line 19 "c/zx-ps.gperf"
    {"AddCollectionResponse", sizeof(struct zx_ps_AddCollectionResponse_s)},
#line 24 "c/zx-ps.gperf"
    {"AddToCollectionRequest", sizeof(struct zx_ps_AddToCollectionRequest_s)},
#line 25 "c/zx-ps.gperf"
    {"AddToCollectionResponse", sizeof(struct zx_ps_AddToCollectionResponse_s)},
#line 41 "c/zx-ps.gperf"
    {"QueryObjectsRequest", sizeof(struct zx_ps_QueryObjectsRequest_s)},
#line 42 "c/zx-ps.gperf"
    {"QueryObjectsResponse", sizeof(struct zx_ps_QueryObjectsResponse_s)},
#line 20 "c/zx-ps.gperf"
    {"AddEntityRequest", sizeof(struct zx_ps_AddEntityRequest_s)},
#line 21 "c/zx-ps.gperf"
    {"AddEntityResponse", sizeof(struct zx_ps_AddEntityResponse_s)},
    {""},
#line 60 "c/zx-ps.gperf"
    {"TargetObjectID", sizeof(struct zx_elem_s)},
    {""},
#line 22 "c/zx-ps.gperf"
    {"AddKnownEntityRequest", sizeof(struct zx_ps_AddKnownEntityRequest_s)},
#line 23 "c/zx-ps.gperf"
    {"AddKnownEntityResponse", sizeof(struct zx_ps_AddKnownEntityResponse_s)},
    {""},
#line 26 "c/zx-ps.gperf"
    {"CreatePSObject", sizeof(struct zx_ps_CreatePSObject_s)},
    {""},
#line 37 "c/zx-ps.gperf"
    {"Object", sizeof(struct zx_ps_Object_s)},
#line 58 "c/zx-ps.gperf"
    {"Subscription", sizeof(struct zx_ps_Subscription_s)},
#line 38 "c/zx-ps.gperf"
    {"ObjectID", sizeof(struct zx_elem_s)},
#line 39 "c/zx-ps.gperf"
    {"ObjectRef", sizeof(struct zx_elem_s)},
    {""},
#line 28 "c/zx-ps.gperf"
    {"Filter", sizeof(struct zx_elem_s)},
    {""}, {""}, {""},
#line 56 "c/zx-ps.gperf"
    {"SetObjectInfoRequest", sizeof(struct zx_ps_SetObjectInfoRequest_s)},
#line 57 "c/zx-ps.gperf"
    {"SetObjectInfoResponse", sizeof(struct zx_ps_SetObjectInfoResponse_s)},
    {""}, {""}, {""}, {""}, {""},
#line 55 "c/zx-ps.gperf"
    {"SPtoPSRedirectURL", sizeof(struct zx_elem_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_ps_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_ps_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_ps_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_ps_el_tab[key];
          }
    }
  return 0;
}
#line 63 "c/zx-ps.gperf"

/* EOF */
