/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-prov.gperf  */
/* Computed positions: -k'3,5,8' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-prov.gperf"

/* c/zx-prov-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-prov-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 61
#define MIN_WORD_LENGTH 4
#define MAX_WORD_LENGTH 32
#define MIN_HASH_VALUE 4
#define MAX_HASH_VALUE 82
/* maximum key range = 79, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_prov_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 40, 83, 20, 15,  0,
      83, 10, 83, 15, 83, 83, 83, 83, 83, 83,
      35, 83,  0, 15, 83, 30, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 20, 40, 83,
      25,  5, 55,  5, 10,  5, 83,  0,  0, 83,
       0, 15, 30, 83,  1, 15,  0, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83, 83, 83, 83, 83,
      83, 83, 83, 83, 83, 83
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[7]];
      /*FALLTHROUGH*/
      case 7:
      case 6:
      case 5:
        hval += asso_values[(unsigned char)str[4]];
      /*FALLTHROUGH*/
      case 4:
      case 3:
        hval += asso_values[(unsigned char)str[2]];
        break;
    }
  return hval;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  4,  0,  0,  7,  0,  9, 10,  0,  7, 12,
     9, 10,  0, 17,  0,  4,  0, 11, 17, 18, 14, 20, 11,  7,
     8, 24,  5, 11, 12, 28, 19, 10, 16, 32,  0, 19, 15, 11,
    12,  8, 14,  0, 11, 12, 23, 19, 10, 11, 12, 18, 19, 10,
    16, 22,  8,  9, 20,  0, 12, 18,  0,  0,  0, 17,  8,  9,
    10,  0, 12, 13, 14,  0, 16, 17, 18,  0,  0,  0, 11
  };

struct zx_el_tok zx_prov_el_tab[] =
  {
    {""}, {""}, {""}, {""},
#line 71 "c/zx-prov.gperf"
    {"Poll", sizeof(struct zx_prov_Poll_s)},
    {""}, {""},
#line 44 "c/zx-prov.gperf"
    {"PMEInfo", sizeof(struct zx_prov_PMEInfo_s)},
    {""},
#line 38 "c/zx-prov.gperf"
    {"PMEEnable", sizeof(struct zx_prov_PMEEnable_s)},
#line 40 "c/zx-prov.gperf"
    {"PMEEnabled", sizeof(struct zx_elem_s)},
    {""},
#line 47 "c/zx-prov.gperf"
    {"PMESize", sizeof(struct zx_elem_s)},
#line 31 "c/zx-prov.gperf"
    {"PMECreatorID", sizeof(struct zx_elem_s)},
#line 32 "c/zx-prov.gperf"
    {"PMEDelete", sizeof(struct zx_prov_PMEDelete_s)},
#line 41 "c/zx-prov.gperf"
    {"PMEGetInfo", sizeof(struct zx_prov_PMEGetInfo_s)},
    {""},
#line 39 "c/zx-prov.gperf"
    {"PMEEnableResponse", sizeof(struct zx_prov_PMEEnableResponse_s)},
    {""},
#line 58 "c/zx-prov.gperf"
    {"PMID", sizeof(struct zx_prov_PMID_s)},
    {""},
#line 53 "c/zx-prov.gperf"
    {"PMEngineRef", sizeof(struct zx_elem_s)},
#line 33 "c/zx-prov.gperf"
    {"PMEDeleteResponse", sizeof(struct zx_prov_PMEDeleteResponse_s)},
#line 42 "c/zx-prov.gperf"
    {"PMEGetInfoResponse", sizeof(struct zx_prov_PMEGetInfoResponse_s)},
#line 52 "c/zx-prov.gperf"
    {"PMEWhenEnabled", sizeof(struct zx_elem_s)},
#line 61 "c/zx-prov.gperf"
    {"PMRegisterDescriptor", sizeof(struct zx_prov_PMRegisterDescriptor_s)},
#line 36 "c/zx-prov.gperf"
    {"PMEDownload", sizeof(struct zx_prov_PMEDownload_s)},
#line 43 "c/zx-prov.gperf"
    {"PMEHash", sizeof(struct zx_prov_PMEHash_s)},
#line 27 "c/zx-prov.gperf"
    {"PMDelete", sizeof(struct zx_prov_PMDelete_s)},
#line 62 "c/zx-prov.gperf"
    {"PMRegisterDescriptorItem", sizeof(struct zx_prov_PMRegisterDescriptorItem_s)},
#line 75 "c/zx-prov.gperf"
    {"State", sizeof(struct zx_prov_State_s)},
#line 45 "c/zx-prov.gperf"
    {"PMERegister", sizeof(struct zx_prov_PMERegister_s)},
#line 28 "c/zx-prov.gperf"
    {"PMDeleteItem", sizeof(struct zx_prov_PMDeleteItem_s)},
#line 63 "c/zx-prov.gperf"
    {"PMRegisterDescriptorResponse", sizeof(struct zx_prov_PMRegisterDescriptorResponse_s)},
#line 37 "c/zx-prov.gperf"
    {"PMEDownloadResponse", sizeof(struct zx_prov_PMEDownloadResponse_s)},
#line 19 "c/zx-prov.gperf"
    {"EngineData", sizeof(struct zx_elem_s)},
#line 29 "c/zx-prov.gperf"
    {"PMDeleteResponse", sizeof(struct zx_prov_PMDeleteResponse_s)},
#line 64 "c/zx-prov.gperf"
    {"PMRegisterDescriptorResponseItem", sizeof(struct zx_prov_PMRegisterDescriptorResponseItem_s)},
    {""},
#line 46 "c/zx-prov.gperf"
    {"PMERegisterResponse", sizeof(struct zx_prov_PMERegisterResponse_s)},
#line 54 "c/zx-prov.gperf"
    {"PMGetDescriptor", sizeof(struct zx_prov_PMGetDescriptor_s)},
#line 56 "c/zx-prov.gperf"
    {"PMGetStatus", sizeof(struct zx_prov_PMGetStatus_s)},
#line 72 "c/zx-prov.gperf"
    {"PollResponse", sizeof(struct zx_prov_PollResponse_s)},
#line 60 "c/zx-prov.gperf"
    {"PMRTData", sizeof(struct zx_elem_s)},
#line 51 "c/zx-prov.gperf"
    {"PMEWhenCreated", sizeof(struct zx_elem_s)},
    {""},
#line 65 "c/zx-prov.gperf"
    {"PMSetStatus", sizeof(struct zx_prov_PMSetStatus_s)},
#line 30 "c/zx-prov.gperf"
    {"PMDescriptor", sizeof(struct zx_prov_PMDescriptor_s)},
#line 55 "c/zx-prov.gperf"
    {"PMGetDescriptorResponse", sizeof(struct zx_prov_PMGetDescriptorResponse_s)},
#line 57 "c/zx-prov.gperf"
    {"PMGetStatusResponse", sizeof(struct zx_prov_PMGetStatusResponse_s)},
#line 59 "c/zx-prov.gperf"
    {"PMInitData", sizeof(struct zx_elem_s)},
#line 18 "c/zx-prov.gperf"
    {"CallbackEPR", sizeof(struct zx_prov_CallbackEPR_s)},
#line 24 "c/zx-prov.gperf"
    {"PMDeactivate", sizeof(struct zx_prov_PMDeactivate_s)},
#line 73 "c/zx-prov.gperf"
    {"ProvisioningHandle", sizeof(struct zx_prov_ProvisioningHandle_s)},
#line 66 "c/zx-prov.gperf"
    {"PMSetStatusResponse", sizeof(struct zx_prov_PMSetStatusResponse_s)},
#line 34 "c/zx-prov.gperf"
    {"PMEDisable", sizeof(struct zx_prov_PMEDisable_s)},
#line 25 "c/zx-prov.gperf"
    {"PMDeactivateItem", sizeof(struct zx_prov_PMDeactivateItem_s)},
#line 74 "c/zx-prov.gperf"
    {"ProvisioningServiceEPR", sizeof(struct zx_prov_ProvisioningServiceEPR_s)},
#line 67 "c/zx-prov.gperf"
    {"PMStatus", sizeof(struct zx_prov_PMStatus_s)},
#line 48 "c/zx-prov.gperf"
    {"PMEUpload", sizeof(struct zx_prov_PMEUpload_s)},
#line 26 "c/zx-prov.gperf"
    {"PMDeactivateResponse", sizeof(struct zx_prov_PMDeactivateResponse_s)},
    {""},
#line 49 "c/zx-prov.gperf"
    {"PMEUploadMax", sizeof(struct zx_elem_s)},
#line 35 "c/zx-prov.gperf"
    {"PMEDisableResponse", sizeof(struct zx_prov_PMEDisableResponse_s)},
    {""}, {""}, {""},
#line 50 "c/zx-prov.gperf"
    {"PMEUploadResponse", sizeof(struct zx_prov_PMEUploadResponse_s)},
#line 68 "c/zx-prov.gperf"
    {"PMUpdate", sizeof(struct zx_prov_PMUpdate_s)},
#line 76 "c/zx-prov.gperf"
    {"UpdateEPR", sizeof(struct zx_prov_UpdateEPR_s)},
#line 20 "c/zx-prov.gperf"
    {"PMActivate", sizeof(struct zx_prov_PMActivate_s)},
    {""},
#line 69 "c/zx-prov.gperf"
    {"PMUpdateItem", sizeof(struct zx_prov_PMUpdateItem_s)},
#line 77 "c/zx-prov.gperf"
    {"UpdateEPRItem", sizeof(struct zx_prov_UpdateEPRItem_s)},
#line 21 "c/zx-prov.gperf"
    {"PMActivateItem", sizeof(struct zx_prov_PMActivateItem_s)},
    {""},
#line 70 "c/zx-prov.gperf"
    {"PMUpdateResponse", sizeof(struct zx_prov_PMUpdateResponse_s)},
#line 78 "c/zx-prov.gperf"
    {"UpdateEPRResponse", sizeof(struct zx_prov_UpdateEPRResponse_s)},
#line 22 "c/zx-prov.gperf"
    {"PMActivateResponse", sizeof(struct zx_prov_PMActivateResponse_s)},
    {""}, {""}, {""},
#line 23 "c/zx-prov.gperf"
    {"PMDArtifact", sizeof(struct zx_elem_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_prov_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_prov_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_prov_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_prov_el_tab[key];
          }
    }
  return 0;
}
#line 79 "c/zx-prov.gperf"

/* EOF */
