/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-sa.gperf  */
/* Computed positions: -k'3,$' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-sa.gperf"

/* c/zx-sa-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-sa-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 34
#define MIN_WORD_LENGTH 6
#define MAX_WORD_LENGTH 23
#define MIN_HASH_VALUE 6
#define MAX_HASH_VALUE 93
/* maximum key range = 88, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_sa_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94,  0, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 45, 25, 10,
      30, 25,  5, 94, 94,  0, 94, 94, 30, 20,
       0, 25, 94, 94, 20, 10,  0, 94,  0, 94,
      94,  0, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94, 94, 94, 94, 94,
      94, 94, 94, 94, 94, 94
    };
  return len + asso_values[(unsigned char)str[2]] + asso_values[(unsigned char)str[len - 1]];
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  0,  0,  6,  0,  0,  9,  0,  0, 12,  0,
    14,  0,  6,  0, 18,  9, 10, 11, 22, 23, 19, 20,  6,  0,
    18, 14, 15,  6,  7,  8,  9,  0,  6,  0,  8, 14, 15, 16,
     0,  0, 19,  0, 16,  0,  0, 19,  0,  0,  0, 18,  9,  0,
     0,  0,  0,  0, 10,  0,  0,  8,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0, 23
  };

struct zx_el_tok zx_sa_el_tab[] =
  {
    {""}, {""}, {""}, {""}, {""}, {""},
#line 18 "c/zx-sa.gperf"
    {"Action", sizeof(struct zx_sa_Action_s)},
    {""}, {""},
#line 36 "c/zx-sa.gperf"
    {"Condition", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 29 "c/zx-sa.gperf"
    {"AuthnContext", sizeof(struct zx_sa_AuthnContext_s)},
    {""},
#line 33 "c/zx-sa.gperf"
    {"AuthnStatement", sizeof(struct zx_sa_AuthnStatement_s)},
    {""},
#line 35 "c/zx-sa.gperf"
    {"BaseID", sizeof(struct zx_sa_BaseID_s)},
    {""},
#line 24 "c/zx-sa.gperf"
    {"AttributeStatement", sizeof(struct zx_sa_AttributeStatement_s)},
#line 20 "c/zx-sa.gperf"
    {"Assertion", sizeof(struct zx_sa_Assertion_s)},
#line 37 "c/zx-sa.gperf"
    {"Conditions", sizeof(struct zx_sa_Conditions_s)},
#line 40 "c/zx-sa.gperf"
    {"EncryptedID", sizeof(struct zx_sa_EncryptedID_s)},
#line 34 "c/zx-sa.gperf"
    {"AuthzDecisionStatement", sizeof(struct zx_sa_AuthzDecisionStatement_s)},
#line 28 "c/zx-sa.gperf"
    {"AuthenticatingAuthority", sizeof(struct zx_elem_s)},
#line 32 "c/zx-sa.gperf"
    {"AuthnContextDeclRef", sizeof(struct zx_elem_s)},
#line 30 "c/zx-sa.gperf"
    {"AuthnContextClassRef", sizeof(struct zx_elem_s)},
#line 43 "c/zx-sa.gperf"
    {"NameID", sizeof(struct zx_sa_NameID_s)},
    {""},
#line 38 "c/zx-sa.gperf"
    {"EncryptedAssertion", sizeof(struct zx_sa_EncryptedAssertion_s)},
#line 21 "c/zx-sa.gperf"
    {"AssertionIDRef", sizeof(struct zx_elem_s)},
#line 22 "c/zx-sa.gperf"
    {"AssertionURIRef", sizeof(struct zx_elem_s)},
#line 19 "c/zx-sa.gperf"
    {"Advice", sizeof(struct zx_sa_Advice_s)},
#line 47 "c/zx-sa.gperf"
    {"Subject", sizeof(struct zx_sa_Subject_s)},
#line 41 "c/zx-sa.gperf"
    {"Evidence", sizeof(struct zx_sa_Evidence_s)},
#line 23 "c/zx-sa.gperf"
    {"Attribute", sizeof(struct zx_sa_Attribute_s)},
    {""},
#line 42 "c/zx-sa.gperf"
    {"Issuer", sizeof(struct zx_sa_Issuer_s)},
    {""},
#line 51 "c/zx-sa.gperf"
    {"TestElem", sizeof(struct zx_sa_TestElem_s)},
#line 25 "c/zx-sa.gperf"
    {"AttributeValue", sizeof(struct zx_sa_AttributeValue_s)},
#line 50 "c/zx-sa.gperf"
    {"SubjectLocality", sizeof(struct zx_sa_SubjectLocality_s)},
#line 45 "c/zx-sa.gperf"
    {"ProxyRestriction", sizeof(struct zx_sa_ProxyRestriction_s)},
    {""}, {""},
#line 48 "c/zx-sa.gperf"
    {"SubjectConfirmation", sizeof(struct zx_sa_SubjectConfirmation_s)},
    {""},
#line 31 "c/zx-sa.gperf"
    {"AuthnContextDecl", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 27 "c/zx-sa.gperf"
    {"AudienceRestriction", sizeof(struct zx_sa_AudienceRestriction_s)},
    {""}, {""}, {""},
#line 39 "c/zx-sa.gperf"
    {"EncryptedAttribute", sizeof(struct zx_sa_EncryptedAttribute_s)},
#line 46 "c/zx-sa.gperf"
    {"Statement", sizeof(struct zx_sa_Statement_s)},
    {""}, {""}, {""}, {""}, {""},
#line 44 "c/zx-sa.gperf"
    {"OneTimeUse", sizeof(struct zx_sa_OneTimeUse_s)},
    {""}, {""},
#line 26 "c/zx-sa.gperf"
    {"Audience", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""},
#line 49 "c/zx-sa.gperf"
    {"SubjectConfirmationData", sizeof(struct zx_sa_SubjectConfirmationData_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_sa_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_sa_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_sa_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_sa_el_tab[key];
          }
    }
  return 0;
}
#line 52 "c/zx-sa.gperf"

/* EOF */
