/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-sa11.gperf  */
/* Computed positions: -k'3' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-sa11.gperf"

/* c/zx-sa11-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-sa11-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 25
#define MIN_WORD_LENGTH 6
#define MAX_WORD_LENGTH 30
#define MIN_HASH_VALUE 6
#define MAX_HASH_VALUE 44
/* maximum key range = 39, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_sa11_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 25, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45,  8,  5, 45,
       5, 45, 45, 45, 45,  0, 45, 45, 45, 25,
      25, 45, 45, 45, 45, 20,  0, 45,  5, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
      45, 45, 45, 45, 45, 45
    };
  return len + asso_values[(unsigned char)str[2]];
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  0,  0,  6,  0,  8,  9,  0,  6,  7,  8,
    14,  0, 16,  9, 18, 19, 15, 16,  0, 23, 19,  0,  0,  0,
    23,  9, 30,  0,  0, 28,  9, 10,  0,  0,  0, 14, 20,  0,
     0, 18, 19
  };

struct zx_el_tok zx_sa11_el_tab[] =
  {
    {""}, {""}, {""}, {""}, {""}, {""},
#line 18 "c/zx-sa11.gperf"
    {"Action", sizeof(struct zx_sa11_Action_s)},
    {""},
#line 35 "c/zx-sa11.gperf"
    {"Evidence", sizeof(struct zx_sa11_Evidence_s)},
#line 22 "c/zx-sa11.gperf"
    {"Attribute", sizeof(struct zx_sa11_Attribute_s)},
    {""},
#line 19 "c/zx-sa11.gperf"
    {"Advice", sizeof(struct zx_sa11_Advice_s)},
#line 38 "c/zx-sa11.gperf"
    {"Subject", sizeof(struct zx_sa11_Subject_s)},
#line 26 "c/zx-sa11.gperf"
    {"Audience", sizeof(struct zx_elem_s)},
#line 25 "c/zx-sa11.gperf"
    {"AttributeValue", sizeof(struct zx_sa11_AttributeValue_s)},
    {""},
#line 29 "c/zx-sa11.gperf"
    {"AuthorityBinding", sizeof(struct zx_sa11_AuthorityBinding_s)},
#line 37 "c/zx-sa11.gperf"
    {"Statement", sizeof(struct zx_elem_s)},
#line 24 "c/zx-sa11.gperf"
    {"AttributeStatement", sizeof(struct zx_sa11_AttributeStatement_s)},
#line 23 "c/zx-sa11.gperf"
    {"AttributeDesignator", sizeof(struct zx_sa11_AttributeDesignator_s)},
#line 41 "c/zx-sa11.gperf"
    {"SubjectLocality", sizeof(struct zx_sa11_SubjectLocality_s)},
#line 42 "c/zx-sa11.gperf"
    {"SubjectStatement", sizeof(struct zx_sa11_SubjectStatement_s)},
    {""},
#line 28 "c/zx-sa11.gperf"
    {"AuthenticationStatement", sizeof(struct zx_sa11_AuthenticationStatement_s)},
#line 39 "c/zx-sa11.gperf"
    {"SubjectConfirmation", sizeof(struct zx_sa11_SubjectConfirmation_s)},
    {""}, {""}, {""},
#line 40 "c/zx-sa11.gperf"
    {"SubjectConfirmationData", sizeof(struct zx_elem_s)},
#line 20 "c/zx-sa11.gperf"
    {"Assertion", sizeof(struct zx_sa11_Assertion_s)},
#line 30 "c/zx-sa11.gperf"
    {"AuthorizationDecisionStatement", sizeof(struct zx_sa11_AuthorizationDecisionStatement_s)},
    {""}, {""},
#line 27 "c/zx-sa11.gperf"
    {"AudienceRestrictionCondition", sizeof(struct zx_sa11_AudienceRestrictionCondition_s)},
#line 31 "c/zx-sa11.gperf"
    {"Condition", sizeof(struct zx_elem_s)},
#line 32 "c/zx-sa11.gperf"
    {"Conditions", sizeof(struct zx_sa11_Conditions_s)},
    {""}, {""}, {""},
#line 36 "c/zx-sa11.gperf"
    {"NameIdentifier", sizeof(struct zx_sa11_NameIdentifier_s)},
#line 21 "c/zx-sa11.gperf"
    {"AssertionIDReference", sizeof(struct zx_elem_s)},
    {""}, {""},
#line 33 "c/zx-sa11.gperf"
    {"ConfirmationMethod", sizeof(struct zx_elem_s)},
#line 34 "c/zx-sa11.gperf"
    {"DoNotCacheCondition", sizeof(struct zx_sa11_DoNotCacheCondition_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_sa11_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_sa11_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_sa11_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_sa11_el_tab[key];
          }
    }
  return 0;
}
#line 43 "c/zx-sa11.gperf"

/* EOF */
