/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-sec.gperf  */
/* Computed positions: -k'' */

#line 1 "c/zx-sec.gperf"

/* c/zx-sec-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-sec-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 4
#define MIN_WORD_LENGTH 5
#define MAX_WORD_LENGTH 21
#define MIN_HASH_VALUE 5
#define MAX_HASH_VALUE 21
/* maximum key range = 17, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
/*ARGSUSED*/
static unsigned int
zx_sec_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  return len;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0, 11,  0,  0,
     0,  0,  0, 17,  0,  0,  0, 21
  };

struct zx_el_tok zx_sec_el_tab[] =
  {
    {""}, {""}, {""}, {""}, {""},
#line 18 "c/zx-sec.gperf"
    {"Token", sizeof(struct zx_sec_Token_s)},
    {""}, {""}, {""}, {""}, {""},
#line 19 "c/zx-sec.gperf"
    {"TokenPolicy", sizeof(struct zx_sec_TokenPolicy_s)},
    {""}, {""}, {""}, {""}, {""},
#line 20 "c/zx-sec.gperf"
    {"TransitedProvider", sizeof(struct zx_sec_TransitedProvider_s)},
    {""}, {""}, {""},
#line 21 "c/zx-sec.gperf"
    {"TransitedProviderPath", sizeof(struct zx_sec_TransitedProviderPath_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_sec_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_sec_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_sec_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_sec_el_tab[key];
          }
    }
  return 0;
}
#line 22 "c/zx-sec.gperf"

/* EOF */
