/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-sp.gperf  */
/* Computed positions: -k'4' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-sp.gperf"

/* c/zx-sp-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-sp-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 32
#define MIN_WORD_LENGTH 5
#define MAX_WORD_LENGTH 21
#define MIN_HASH_VALUE 5
#define MAX_HASH_VALUE 49
/* maximum key range = 45, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_sp_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50,  5, 50, 35,
      50, 50, 50,  0, 50, 50, 30, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 20, 50, 50,
      50,  5, 50, 50, 20, 20, 15, 50, 50,  0,
      50,  5,  0, 50,  0, 10,  0,  0, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
      50, 50, 50, 50, 50, 50
    };
  return len + asso_values[(unsigned char)str[3]];
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10, 11, 12, 13,
    14, 10, 11, 12, 13, 14,  0, 21, 12, 18,  0, 20, 21, 12,
     8,  0, 10,  0, 12,  0,  0, 15, 16,  7, 18, 19, 20,  0,
     0,  8,  0,  0,  0,  0,  0, 14
  };

struct zx_el_tok zx_sp_el_tab[] =
  {
    {""}, {""}, {""}, {""}, {""},
#line 38 "c/zx-sp.gperf"
    {"NewID", sizeof(struct zx_elem_s)},
#line 44 "c/zx-sp.gperf"
    {"Status", sizeof(struct zx_sp_Status_s)},
#line 42 "c/zx-sp.gperf"
    {"Scoping", sizeof(struct zx_sp_Scoping_s)},
#line 41 "c/zx-sp.gperf"
    {"Response", sizeof(struct zx_sp_Response_s)},
#line 49 "c/zx-sp.gperf"
    {"Terminate", sizeof(struct zx_elem_s)},
#line 45 "c/zx-sp.gperf"
    {"StatusCode", sizeof(struct zx_sp_StatusCode_s)},
#line 40 "c/zx-sp.gperf"
    {"RequesterID", sizeof(struct zx_elem_s)},
#line 46 "c/zx-sp.gperf"
    {"StatusDetail", sizeof(struct zx_sp_StatusDetail_s)},
#line 47 "c/zx-sp.gperf"
    {"StatusMessage", sizeof(struct zx_elem_s)},
#line 22 "c/zx-sp.gperf"
    {"AttributeQuery", sizeof(struct zx_sp_AttributeQuery_s)},
#line 26 "c/zx-sp.gperf"
    {"Extensions", sizeof(struct zx_sp_Extensions_s)},
#line 27 "c/zx-sp.gperf"
    {"GetComplete", sizeof(struct zx_elem_s)},
#line 36 "c/zx-sp.gperf"
    {"NameIDPolicy", sizeof(struct zx_sp_NameIDPolicy_s)},
#line 30 "c/zx-sp.gperf"
    {"LogoutRequest", sizeof(struct zx_sp_LogoutRequest_s)},
#line 31 "c/zx-sp.gperf"
    {"LogoutResponse", sizeof(struct zx_sp_LogoutResponse_s)},
    {""},
#line 39 "c/zx-sp.gperf"
    {"RequestedAuthnContext", sizeof(struct zx_sp_RequestedAuthnContext_s)},
#line 43 "c/zx-sp.gperf"
    {"SessionIndex", sizeof(struct zx_elem_s)},
#line 21 "c/zx-sp.gperf"
    {"AssertionIDRequest", sizeof(struct zx_sp_AssertionIDRequest_s)},
    {""},
#line 34 "c/zx-sp.gperf"
    {"NameIDMappingRequest", sizeof(struct zx_sp_NameIDMappingRequest_s)},
#line 35 "c/zx-sp.gperf"
    {"NameIDMappingResponse", sizeof(struct zx_sp_NameIDMappingResponse_s)},
#line 48 "c/zx-sp.gperf"
    {"SubjectQuery", sizeof(struct zx_sp_SubjectQuery_s)},
#line 18 "c/zx-sp.gperf"
    {"Artifact", sizeof(struct zx_elem_s)},
    {""},
#line 23 "c/zx-sp.gperf"
    {"AuthnQuery", sizeof(struct zx_sp_AuthnQuery_s)},
    {""},
#line 24 "c/zx-sp.gperf"
    {"AuthnRequest", sizeof(struct zx_sp_AuthnRequest_s)},
    {""}, {""},
#line 19 "c/zx-sp.gperf"
    {"ArtifactResolve", sizeof(struct zx_sp_ArtifactResolve_s)},
#line 20 "c/zx-sp.gperf"
    {"ArtifactResponse", sizeof(struct zx_sp_ArtifactResponse_s)},
#line 29 "c/zx-sp.gperf"
    {"IDPList", sizeof(struct zx_sp_IDPList_s)},
#line 25 "c/zx-sp.gperf"
    {"AuthzDecisionQuery", sizeof(struct zx_sp_AuthzDecisionQuery_s)},
#line 32 "c/zx-sp.gperf"
    {"ManageNameIDRequest", sizeof(struct zx_sp_ManageNameIDRequest_s)},
#line 33 "c/zx-sp.gperf"
    {"ManageNameIDResponse", sizeof(struct zx_sp_ManageNameIDResponse_s)},
    {""}, {""},
#line 28 "c/zx-sp.gperf"
    {"IDPEntry", sizeof(struct zx_sp_IDPEntry_s)},
    {""}, {""}, {""}, {""}, {""},
#line 37 "c/zx-sp.gperf"
    {"NewEncryptedID", sizeof(struct zx_sp_NewEncryptedID_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_sp_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_sp_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_sp_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_sp_el_tab[key];
          }
    }
  return 0;
}
#line 50 "c/zx-sp.gperf"

/* EOF */
