/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-shps.gperf  */
/* Computed positions: -k'1,8' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-shps.gperf"

/* c/zx-shps-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-shps-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 36
#define MIN_WORD_LENGTH 4
#define MAX_WORD_LENGTH 23
#define MIN_HASH_VALUE 4
#define MAX_HASH_VALUE 50
/* maximum key range = 47, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_shps_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 15, 25, 51,
      51, 15, 20,  0, 51, 51, 51, 51, 51, 51,
       0,  5,  0,  0, 51, 15, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 10, 51, 10, 51,  0, 51, 10, 51, 51,
      51, 51,  0, 51,  0, 25, 25,  5,  0, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
      51, 51, 51, 51, 51, 51
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[7]];
      /*FALLTHROUGH*/
      case 7:
      case 6:
      case 5:
      case 4:
      case 3:
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  4,  0,  6,  0,  8,  0,  5, 11, 12, 13,
     9, 15, 16, 17, 13, 19, 20,  6, 17, 23, 14, 15, 16, 17,
    18,  9, 15,  6,  0, 13, 14, 10, 11, 17, 23, 14,  0, 21,
     0, 13,  0,  0,  0,  0,  0, 14, 10
  };

struct zx_el_tok zx_shps_el_tab[] =
  {
    {""}, {""}, {""}, {""},
#line 31 "c/zx-shps.gperf"
    {"Poll", sizeof(struct zx_shps_Poll_s)},
    {""},
#line 25 "c/zx-shps.gperf"
    {"Invoke", sizeof(struct zx_elem_s)},
    {""},
#line 41 "c/zx-shps.gperf"
    {"Register", sizeof(struct zx_shps_Register_s)},
    {""},
#line 37 "c/zx-shps.gperf"
    {"Query", sizeof(struct zx_shps_Query_s)},
#line 33 "c/zx-shps.gperf"
    {"ProxyInvoke", sizeof(struct zx_shps_ProxyInvoke_s)},
#line 32 "c/zx-shps.gperf"
    {"PollResponse", sizeof(struct zx_shps_PollResponse_s)},
#line 47 "c/zx-shps.gperf"
    {"ServiceStatus", sizeof(struct zx_elem_s)},
#line 48 "c/zx-shps.gperf"
    {"SetStatus", sizeof(struct zx_shps_SetStatus_s)},
#line 34 "c/zx-shps.gperf"
    {"ProxyInvokeItem", sizeof(struct zx_shps_ProxyInvokeItem_s)},
#line 42 "c/zx-shps.gperf"
    {"RegisterResponse", sizeof(struct zx_shps_RegisterResponse_s)},
#line 24 "c/zx-shps.gperf"
    {"InvocationContext", sizeof(struct zx_shps_InvocationContext_s)},
#line 49 "c/zx-shps.gperf"
    {"SetStatusItem", sizeof(struct zx_shps_SetStatusItem_s)},
#line 35 "c/zx-shps.gperf"
    {"ProxyInvokeResponse", sizeof(struct zx_shps_ProxyInvokeResponse_s)},
#line 43 "c/zx-shps.gperf"
    {"RegisterResponseItem", sizeof(struct zx_shps_RegisterResponseItem_s)},
#line 51 "c/zx-shps.gperf"
    {"Update", sizeof(struct zx_shps_Update_s)},
#line 50 "c/zx-shps.gperf"
    {"SetStatusResponse", sizeof(struct zx_shps_SetStatusResponse_s)},
#line 36 "c/zx-shps.gperf"
    {"ProxyInvokeResponseItem", sizeof(struct zx_shps_ProxyInvokeResponseItem_s)},
#line 27 "c/zx-shps.gperf"
    {"InvokeResponse", sizeof(struct zx_shps_InvokeResponse_s)},
#line 45 "c/zx-shps.gperf"
    {"ResponseHeaders", sizeof(struct zx_elem_s)},
#line 30 "c/zx-shps.gperf"
    {"InvokingProvider", sizeof(struct zx_elem_s)},
#line 29 "c/zx-shps.gperf"
    {"InvokingPrincipal", sizeof(struct zx_elem_s)},
#line 28 "c/zx-shps.gperf"
    {"InvokeResponseItem", sizeof(struct zx_shps_InvokeResponseItem_s)},
#line 21 "c/zx-shps.gperf"
    {"GetStatus", sizeof(struct zx_shps_GetStatus_s)},
#line 38 "c/zx-shps.gperf"
    {"QueryRegistered", sizeof(struct zx_shps_QueryRegistered_s)},
#line 19 "c/zx-shps.gperf"
    {"Delete", sizeof(struct zx_shps_Delete_s)},
    {""},
#line 46 "c/zx-shps.gperf"
    {"ServiceHandle", sizeof(struct zx_elem_s)},
#line 44 "c/zx-shps.gperf"
    {"RequestHeaders", sizeof(struct zx_elem_s)},
#line 26 "c/zx-shps.gperf"
    {"InvokeItem", sizeof(struct zx_shps_InvokeItem_s)},
#line 18 "c/zx-shps.gperf"
    {"CallbackEPR", sizeof(struct zx_shps_CallbackEPR_s)},
#line 22 "c/zx-shps.gperf"
    {"GetStatusResponse", sizeof(struct zx_shps_GetStatusResponse_s)},
#line 39 "c/zx-shps.gperf"
    {"QueryRegisteredResponse", sizeof(struct zx_shps_QueryRegisteredResponse_s)},
#line 53 "c/zx-shps.gperf"
    {"UpdateResponse", sizeof(struct zx_shps_UpdateResponse_s)},
    {""},
#line 23 "c/zx-shps.gperf"
    {"GetStatusResponseItem", sizeof(struct zx_shps_GetStatusResponseItem_s)},
    {""},
#line 40 "c/zx-shps.gperf"
    {"QueryResponse", sizeof(struct zx_shps_QueryResponse_s)},
    {""}, {""}, {""}, {""}, {""},
#line 20 "c/zx-shps.gperf"
    {"DeleteResponse", sizeof(struct zx_shps_DeleteResponse_s)},
#line 52 "c/zx-shps.gperf"
    {"UpdateItem", sizeof(struct zx_shps_UpdateItem_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_shps_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_shps_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_shps_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_shps_el_tab[key];
          }
    }
  return 0;
}
#line 54 "c/zx-shps.gperf"

/* EOF */
