/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-wst.gperf  */
/* Computed positions: -k'4,8' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-wst.gperf"

/* c/zx-wst-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-wst-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 49
#define MIN_WORD_LENGTH 4
#define MAX_WORD_LENGTH 38
#define MIN_HASH_VALUE 4
#define MAX_HASH_VALUE 71
/* maximum key range = 68, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_wst_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 30,
      72, 72, 72, 72, 72, 55, 72, 72, 72, 72,
      72, 72, 72,  5, 45, 72, 72, 40, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 25, 15, 10,
      15,  0,  5,  5, 25, 10, 72, 72, 40, 20,
       5,  5,  5, 72,  0, 40, 15,  0, 72,  5,
       0, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
      72, 72, 72, 72, 72, 72
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[7]];
      /*FALLTHROUGH*/
      case 7:
      case 6:
      case 5:
      case 4:
        hval += asso_values[(unsigned char)str[3]];
        break;
    }
  return hval;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  4,  0,  6,  7,  8,  0, 10, 11,  7,  8,
     9, 10,  6, 12,  0, 19, 10,  6, 22, 18, 14, 20, 26,  7,
    28, 19, 15, 11, 12, 28,  0, 30, 11, 12,  8, 14,  0, 11,
    12, 38,  0,  0,  6, 12, 13,  0,  0, 11,  7, 18,  9, 25,
    11,  0, 13,  0, 15,  6,  0,  0,  0,  0, 21,  0,  0,  0,
     0, 16
  };

struct zx_el_tok zx_wst_el_tab[] =
  {
    {""}, {""}, {""}, {""},
#line 27 "c/zx-wst.gperf"
    {"Code", sizeof(struct zx_elem_s)},
    {""},
#line 37 "c/zx-wst.gperf"
    {"Issuer", sizeof(struct zx_wst_Issuer_s)},
#line 34 "c/zx-wst.gperf"
    {"Entropy", sizeof(struct zx_wst_Entropy_s)},
#line 41 "c/zx-wst.gperf"
    {"Lifetime", sizeof(struct zx_wst_Lifetime_s)},
    {""},
#line 30 "c/zx-wst.gperf"
    {"DelegateTo", sizeof(struct zx_wst_DelegateTo_s)},
#line 48 "c/zx-wst.gperf"
    {"RenewTarget", sizeof(struct zx_wst_RenewTarget_s)},
#line 39 "c/zx-wst.gperf"
    {"KeySize", sizeof(struct zx_elem_s)},
#line 49 "c/zx-wst.gperf"
    {"Renewing", sizeof(struct zx_wst_Renewing_s)},
#line 64 "c/zx-wst.gperf"
    {"TokenType", sizeof(struct zx_elem_s)},
#line 42 "c/zx-wst.gperf"
    {"OnBehalfOf", sizeof(struct zx_wst_OnBehalfOf_s)},
#line 26 "c/zx-wst.gperf"
    {"Claims", sizeof(struct zx_wst_Claims_s)},
#line 36 "c/zx-wst.gperf"
    {"IssuedTokens", sizeof(struct zx_wst_IssuedTokens_s)},
    {""},
#line 56 "c/zx-wst.gperf"
    {"RequestedProofToken", sizeof(struct zx_wst_RequestedProofToken_s)},
#line 32 "c/zx-wst.gperf"
    {"Encryption", sizeof(struct zx_wst_Encryption_s)},
#line 63 "c/zx-wst.gperf"
    {"Status", sizeof(struct zx_wst_Status_s)},
#line 57 "c/zx-wst.gperf"
    {"RequestedSecurityToken", sizeof(struct zx_wst_RequestedSecurityToken_s)},
#line 62 "c/zx-wst.gperf"
    {"SignatureAlgorithm", sizeof(struct zx_elem_s)},
#line 66 "c/zx-wst.gperf"
    {"ValidateTarget", sizeof(struct zx_wst_ValidateTarget_s)},
#line 50 "c/zx-wst.gperf"
    {"RequestSecurityToken", sizeof(struct zx_wst_RequestSecurityToken_s)},
#line 55 "c/zx-wst.gperf"
    {"RequestedAttachedReference", sizeof(struct zx_wst_RequestedAttachedReference_s)},
#line 45 "c/zx-wst.gperf"
    {"Primary", sizeof(struct zx_wst_Primary_s)},
#line 58 "c/zx-wst.gperf"
    {"RequestedUnattachedReference", sizeof(struct zx_wst_RequestedUnattachedReference_s)},
#line 33 "c/zx-wst.gperf"
    {"EncryptionAlgorithm", sizeof(struct zx_elem_s)},
#line 46 "c/zx-wst.gperf"
    {"ProofEncryption", sizeof(struct zx_wst_ProofEncryption_s)},
#line 43 "c/zx-wst.gperf"
    {"Participant", sizeof(struct zx_wst_Participant_s)},
#line 44 "c/zx-wst.gperf"
    {"Participants", sizeof(struct zx_wst_Participants_s)},
#line 52 "c/zx-wst.gperf"
    {"RequestSecurityTokenResponse", sizeof(struct zx_wst_RequestSecurityTokenResponse_s)},
    {""},
#line 51 "c/zx-wst.gperf"
    {"RequestSecurityTokenCollection", sizeof(struct zx_wst_RequestSecurityTokenCollection_s)},
#line 29 "c/zx-wst.gperf"
    {"Delegatable", sizeof(struct zx_elem_s)},
#line 22 "c/zx-wst.gperf"
    {"BinarySecret", sizeof(struct zx_wst_BinarySecret_s)},
#line 61 "c/zx-wst.gperf"
    {"SignWith", sizeof(struct zx_elem_s)},
#line 21 "c/zx-wst.gperf"
    {"BinaryExchange", sizeof(struct zx_wst_BinaryExchange_s)},
    {""},
#line 35 "c/zx-wst.gperf"
    {"Forwardable", sizeof(struct zx_elem_s)},
#line 28 "c/zx-wst.gperf"
    {"CombinedHash", sizeof(struct zx_elem_s)},
#line 53 "c/zx-wst.gperf"
    {"RequestSecurityTokenResponseCollection", sizeof(struct zx_wst_RequestSecurityTokenResponseCollection_s)},
    {""}, {""},
#line 47 "c/zx-wst.gperf"
    {"Reason", sizeof(struct zx_elem_s)},
#line 23 "c/zx-wst.gperf"
    {"CancelTarget", sizeof(struct zx_wst_CancelTarget_s)},
#line 20 "c/zx-wst.gperf"
    {"Authenticator", sizeof(struct zx_wst_Authenticator_s)},
    {""}, {""},
#line 31 "c/zx-wst.gperf"
    {"EncryptWith", sizeof(struct zx_elem_s)},
#line 40 "c/zx-wst.gperf"
    {"KeyType", sizeof(struct zx_elem_s)},
#line 19 "c/zx-wst.gperf"
    {"AuthenticationType", sizeof(struct zx_elem_s)},
#line 25 "c/zx-wst.gperf"
    {"Challenge", sizeof(struct zx_elem_s)},
#line 24 "c/zx-wst.gperf"
    {"CanonicalizationAlgorithm", sizeof(struct zx_elem_s)},
#line 54 "c/zx-wst.gperf"
    {"RequestType", sizeof(struct zx_elem_s)},
    {""},
#line 59 "c/zx-wst.gperf"
    {"SignChallenge", sizeof(struct zx_wst_SignChallenge_s)},
    {""},
#line 18 "c/zx-wst.gperf"
    {"AllowPostdating", sizeof(struct zx_elem_s)},
#line 65 "c/zx-wst.gperf"
    {"UseKey", sizeof(struct zx_wst_UseKey_s)},
    {""}, {""}, {""}, {""},
#line 60 "c/zx-wst.gperf"
    {"SignChallengeResponse", sizeof(struct zx_wst_SignChallengeResponse_s)},
    {""}, {""}, {""}, {""},
#line 38 "c/zx-wst.gperf"
    {"KeyExchangeToken", sizeof(struct zx_wst_KeyExchangeToken_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_wst_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_wst_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_wst_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_wst_el_tab[key];
          }
    }
  return 0;
}
#line 67 "c/zx-wst.gperf"

/* EOF */
