/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-wsp.gperf  */
/* Computed positions: -k'' */

#line 1 "c/zx-wsp.gperf"

/* c/zx-wsp-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-wsp-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 6
#define MIN_WORD_LENGTH 3
#define MAX_WORD_LENGTH 16
#define MIN_HASH_VALUE 3
#define MAX_HASH_VALUE 16
/* maximum key range = 14, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
/*ARGSUSED*/
static unsigned int
zx_wsp_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  return len;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  3,  0,  0,  6,  0,  0,  9, 10,  0,  0,  0,
     0, 15, 16
  };

struct zx_el_tok zx_wsp_el_tab[] =
  {
    {""}, {""}, {""},
#line 18 "c/zx-wsp.gperf"
    {"All", sizeof(struct zx_wsp_All_s)},
    {""}, {""},
#line 21 "c/zx-wsp.gperf"
    {"Policy", sizeof(struct zx_wsp_Policy_s)},
    {""}, {""},
#line 19 "c/zx-wsp.gperf"
    {"AppliesTo", sizeof(struct zx_wsp_AppliesTo_s)},
#line 20 "c/zx-wsp.gperf"
    {"ExactlyOne", sizeof(struct zx_wsp_ExactlyOne_s)},
    {""}, {""}, {""}, {""},
#line 23 "c/zx-wsp.gperf"
    {"PolicyReference", sizeof(struct zx_wsp_PolicyReference_s)},
#line 22 "c/zx-wsp.gperf"
    {"PolicyAttachment", sizeof(struct zx_wsp_PolicyAttachment_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_wsp_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_wsp_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_wsp_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_wsp_el_tab[key];
          }
    }
  return 0;
}
#line 24 "c/zx-wsp.gperf"

/* EOF */
