/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-xenc.gperf  */
/* Computed positions: -k'1' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-xenc.gperf"

/* c/zx-xenc-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-xenc-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 19
#define MIN_WORD_LENGTH 7
#define MAX_WORD_LENGTH 20
#define MIN_HASH_VALUE 10
#define MAX_HASH_VALUE 35
/* maximum key range = 26, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_xenc_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 20, 36,  0, 20,  0,
      36, 36, 36, 36, 36, 15, 36, 36, 36, 15,
      36, 36, 15, 36, 20, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
      36, 36, 36, 36, 36, 36
    };
  return len + asso_values[(unsigned char)str[0]];
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 11, 12, 13,
    14, 15, 16,  0, 18,  0, 20,  0,  7,  8,  0, 10,  0, 12,
    13,  0, 10, 16, 17, 13,  0, 15
  };

struct zx_el_tok zx_xenc_el_tab[] =
  {
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""},
#line 20 "c/zx-xenc.gperf"
    {"CipherData", sizeof(struct zx_xenc_CipherData_s)},
#line 22 "c/zx-xenc.gperf"
    {"CipherValue", sizeof(struct zx_elem_s)},
#line 25 "c/zx-xenc.gperf"
    {"EncryptedKey", sizeof(struct zx_xenc_EncryptedKey_s)},
#line 24 "c/zx-xenc.gperf"
    {"EncryptedData", sizeof(struct zx_xenc_EncryptedData_s)},
#line 19 "c/zx-xenc.gperf"
    {"CarriedKeyName", sizeof(struct zx_elem_s)},
#line 21 "c/zx-xenc.gperf"
    {"CipherReference", sizeof(struct zx_xenc_CipherReference_s)},
#line 26 "c/zx-xenc.gperf"
    {"EncryptionMethod", sizeof(struct zx_xenc_EncryptionMethod_s)},
    {""},
#line 28 "c/zx-xenc.gperf"
    {"EncryptionProperty", sizeof(struct zx_xenc_EncryptionProperty_s)},
    {""},
#line 27 "c/zx-xenc.gperf"
    {"EncryptionProperties", sizeof(struct zx_xenc_EncryptionProperties_s)},
    {""},
#line 31 "c/zx-xenc.gperf"
    {"KeySize", sizeof(struct zx_elem_s)},
#line 29 "c/zx-xenc.gperf"
    {"KA_Nonce", sizeof(struct zx_elem_s)},
    {""},
#line 32 "c/zx-xenc.gperf"
    {"OAEPparams", sizeof(struct zx_elem_s)},
    {""},
#line 30 "c/zx-xenc.gperf"
    {"KeyReference", sizeof(struct zx_xenc_KeyReference_s)},
#line 35 "c/zx-xenc.gperf"
    {"ReferenceList", sizeof(struct zx_xenc_ReferenceList_s)},
    {""},
#line 36 "c/zx-xenc.gperf"
    {"Transforms", sizeof(struct zx_xenc_Transforms_s)},
#line 34 "c/zx-xenc.gperf"
    {"RecipientKeyInfo", sizeof(struct zx_xenc_RecipientKeyInfo_s)},
#line 33 "c/zx-xenc.gperf"
    {"OriginatorKeyInfo", sizeof(struct zx_xenc_OriginatorKeyInfo_s)},
#line 23 "c/zx-xenc.gperf"
    {"DataReference", sizeof(struct zx_xenc_DataReference_s)},
    {""},
#line 18 "c/zx-xenc.gperf"
    {"AgreementMethod", sizeof(struct zx_xenc_AgreementMethod_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_xenc_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_xenc_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_xenc_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_xenc_el_tab[key];
          }
    }
  return 0;
}
#line 37 "c/zx-xenc.gperf"

/* EOF */
