/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-xasacd1.gperf  */
/* Computed positions: -k'' */

#line 1 "c/zx-xasacd1.gperf"

/* c/zx-xasacd1-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-xasacd1-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 3
#define MIN_WORD_LENGTH 18
#define MAX_WORD_LENGTH 27
#define MIN_HASH_VALUE 18
#define MAX_HASH_VALUE 27
/* maximum key range = 10, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
/*ARGSUSED*/
static unsigned int
zx_xasacd1_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  return len;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0, 18,  0, 20,  0,  0,  0,  0,  0,  0, 27
  };

struct zx_el_tok zx_xasacd1_el_tab[] =
  {
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
    {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
#line 18 "c/zx-xasacd1.gperf"
    {"ReferencedPolicies", sizeof(struct zx_xasacd1_ReferencedPolicies_s)},
    {""},
#line 20 "c/zx-xasacd1.gperf"
    {"XACMLPolicyStatement", sizeof(struct zx_xasacd1_XACMLPolicyStatement_s)},
    {""}, {""}, {""}, {""}, {""}, {""},
#line 19 "c/zx-xasacd1.gperf"
    {"XACMLAuthzDecisionStatement", sizeof(struct zx_xasacd1_XACMLAuthzDecisionStatement_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_xasacd1_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_xasacd1_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_xasacd1_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_xasacd1_el_tab[key];
          }
    }
  return 0;
}
#line 21 "c/zx-xasacd1.gperf"

/* EOF */
