/* C code produced by gperf version 3.0.1 */
/* Command-line: gperf -l c/zx-xa.gperf  */
/* Computed positions: -k'1,7' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "c/zx-xa.gperf"

/* c/zx-xa-elems.gperf - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
#include "zx.h"
#include "c/zx-ns.h"
#include "c/zx-xa-data.h"
#include <string.h>

#define TOTAL_KEYWORDS 42
#define MIN_WORD_LENGTH 4
#define MAX_WORD_LENGTH 30
#define MIN_HASH_VALUE 4
#define MAX_HASH_VALUE 67
/* maximum key range = 64, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
zx_xa_hash (str, len)
     register const char *str;
     register unsigned int len;
{
  static unsigned char asso_values[] =
    {
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68,  5, 68,  5, 20, 15,
      10, 68, 68, 50, 68, 68, 68, 30, 68,  5,
       0, 68,  0,  0, 15, 68, 20, 68, 30, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68,  5,
      68, 20, 68, 68, 68, 25, 68, 68, 15, 35,
      10,  5,  0, 68, 68, 35,  0,  0, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68
    };
  register int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[6]];
      /*FALLTHROUGH*/
      case 6:
      case 5:
      case 4:
      case 3:
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

static unsigned char lengthtable[] =
  {
     0,  0,  0,  0,  4,  0,  6,  7,  8,  9,  5,  6, 12,  8,
     9, 10, 11, 17, 13, 14, 20,  6, 17,  8, 19,  0, 26, 27,
     0, 24,  0, 11, 27,  0, 14, 25, 11, 12,  0,  9,  0, 16,
    17, 18,  0,  0, 11,  7,  0,  0,  0,  0, 17, 18,  0, 30,
     0, 22,  0,  0, 10,  0, 12,  0,  0,  0,  0, 17
  };

struct zx_el_tok zx_xa_el_tab[] =
  {
    {""}, {""}, {""}, {""},
#line 50 "c/zx-xa.gperf"
    {"Rule", sizeof(struct zx_xa_Rule_s)},
    {""},
#line 38 "c/zx-xa.gperf"
    {"Policy", sizeof(struct zx_xa_Policy_s)},
#line 52 "c/zx-xa.gperf"
    {"Subject", sizeof(struct zx_xa_Subject_s)},
#line 55 "c/zx-xa.gperf"
    {"Subjects", sizeof(struct zx_xa_Subjects_s)},
#line 42 "c/zx-xa.gperf"
    {"PolicySet", sizeof(struct zx_xa_PolicySet_s)},
#line 22 "c/zx-xa.gperf"
    {"Apply", sizeof(struct zx_xa_Apply_s)},
#line 18 "c/zx-xa.gperf"
    {"Action", sizeof(struct zx_xa_Action_s)},
#line 54 "c/zx-xa.gperf"
    {"SubjectMatch", sizeof(struct zx_xa_SubjectMatch_s)},
#line 46 "c/zx-xa.gperf"
    {"Resource", sizeof(struct zx_xa_Resource_s)},
#line 49 "c/zx-xa.gperf"
    {"Resources", sizeof(struct zx_xa_Resources_s)},
#line 36 "c/zx-xa.gperf"
    {"Obligation", sizeof(struct zx_xa_Obligation_s)},
#line 37 "c/zx-xa.gperf"
    {"Obligations", sizeof(struct zx_xa_Obligations_s)},
#line 44 "c/zx-xa.gperf"
    {"PolicySetDefaults", sizeof(struct zx_xa_PolicySetDefaults_s)},
#line 48 "c/zx-xa.gperf"
    {"ResourceMatch", sizeof(struct zx_xa_ResourceMatch_s)},
#line 25 "c/zx-xa.gperf"
    {"AttributeValue", sizeof(struct zx_xa_AttributeValue_s)},
#line 45 "c/zx-xa.gperf"
    {"PolicySetIdReference", sizeof(struct zx_xa_PolicySetIdReference_s)},
#line 56 "c/zx-xa.gperf"
    {"Target", sizeof(struct zx_xa_Target_s)},
#line 24 "c/zx-xa.gperf"
    {"AttributeSelector", sizeof(struct zx_xa_AttributeSelector_s)},
#line 35 "c/zx-xa.gperf"
    {"Function", sizeof(struct zx_xa_Function_s)},
#line 23 "c/zx-xa.gperf"
    {"AttributeAssignment", sizeof(struct zx_xa_AttributeAssignment_s)},
    {""},
#line 53 "c/zx-xa.gperf"
    {"SubjectAttributeDesignator", sizeof(struct zx_xa_SubjectAttributeDesignator_s)},
#line 43 "c/zx-xa.gperf"
    {"PolicySetCombinerParameters", sizeof(struct zx_xa_PolicySetCombinerParameters_s)},
    {""},
#line 39 "c/zx-xa.gperf"
    {"PolicyCombinerParameters", sizeof(struct zx_xa_PolicyCombinerParameters_s)},
    {""},
#line 29 "c/zx-xa.gperf"
    {"Description", sizeof(struct zx_elem_s)},
#line 47 "c/zx-xa.gperf"
    {"ResourceAttributeDesignator", sizeof(struct zx_xa_ResourceAttributeDesignator_s)},
    {""},
#line 40 "c/zx-xa.gperf"
    {"PolicyDefaults", sizeof(struct zx_xa_PolicyDefaults_s)},
#line 19 "c/zx-xa.gperf"
    {"ActionAttributeDesignator", sizeof(struct zx_xa_ActionAttributeDesignator_s)},
#line 30 "c/zx-xa.gperf"
    {"Environment", sizeof(struct zx_xa_Environment_s)},
#line 33 "c/zx-xa.gperf"
    {"Environments", sizeof(struct zx_xa_Environments_s)},
    {""},
#line 28 "c/zx-xa.gperf"
    {"Condition", sizeof(struct zx_xa_Condition_s)},
    {""},
#line 32 "c/zx-xa.gperf"
    {"EnvironmentMatch", sizeof(struct zx_xa_EnvironmentMatch_s)},
#line 26 "c/zx-xa.gperf"
    {"CombinerParameter", sizeof(struct zx_xa_CombinerParameter_s)},
#line 27 "c/zx-xa.gperf"
    {"CombinerParameters", sizeof(struct zx_xa_CombinerParameters_s)},
    {""}, {""},
#line 20 "c/zx-xa.gperf"
    {"ActionMatch", sizeof(struct zx_xa_ActionMatch_s)},
#line 21 "c/zx-xa.gperf"
    {"Actions", sizeof(struct zx_xa_Actions_s)},
    {""}, {""}, {""}, {""},
#line 58 "c/zx-xa.gperf"
    {"VariableReference", sizeof(struct zx_xa_VariableReference_s)},
#line 57 "c/zx-xa.gperf"
    {"VariableDefinition", sizeof(struct zx_xa_VariableDefinition_s)},
    {""},
#line 31 "c/zx-xa.gperf"
    {"EnvironmentAttributeDesignator", sizeof(struct zx_xa_EnvironmentAttributeDesignator_s)},
    {""},
#line 51 "c/zx-xa.gperf"
    {"RuleCombinerParameters", sizeof(struct zx_xa_RuleCombinerParameters_s)},
    {""}, {""},
#line 34 "c/zx-xa.gperf"
    {"Expression", sizeof(struct zx_elem_s)},
    {""},
#line 59 "c/zx-xa.gperf"
    {"XPathVersion", sizeof(struct zx_elem_s)},
    {""}, {""}, {""}, {""},
#line 41 "c/zx-xa.gperf"
    {"PolicyIdReference", sizeof(struct zx_xa_PolicyIdReference_s)}
  };

#ifdef __GNUC__
__inline
#endif
struct zx_el_tok *
zx_xa_elem2tok (str, len)
     register const char *str;
     register unsigned int len;
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = zx_xa_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = zx_xa_el_tab[key].name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return &zx_xa_el_tab[key];
          }
    }
  return 0;
}
#line 60 "c/zx-xa.gperf"

/* EOF */
