/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zxidjava;

public class zx_ctx {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected zx_ctx(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(zx_ctx obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      zxidjniJNI.delete_zx_ctx(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setBase(String value) {
    zxidjniJNI.zx_ctx_base_set(swigCPtr, value);
  }

  public String getBase() {
    return zxidjniJNI.zx_ctx_base_get(swigCPtr);
  }

  public void setP(String value) {
    zxidjniJNI.zx_ctx_p_set(swigCPtr, value);
  }

  public String getP() {
    return zxidjniJNI.zx_ctx_p_get(swigCPtr);
  }

  public void setLim(String value) {
    zxidjniJNI.zx_ctx_lim_set(swigCPtr, value);
  }

  public String getLim() {
    return zxidjniJNI.zx_ctx_lim_get(swigCPtr);
  }

  public void setNs_tab(zx_ns_s value) {
    zxidjniJNI.zx_ctx_ns_tab_set(swigCPtr, zx_ns_s.getCPtr(value));
  }

  public zx_ns_s getNs_tab() {
    long cPtr = zxidjniJNI.zx_ctx_ns_tab_get(swigCPtr);
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

  public void setUnknown_ns(zx_ns_s value) {
    zxidjniJNI.zx_ctx_unknown_ns_set(swigCPtr, zx_ns_s.getCPtr(value));
  }

  public zx_ns_s getUnknown_ns() {
    long cPtr = zxidjniJNI.zx_ctx_unknown_ns_get(swigCPtr);
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

  public void setGuard_seen_n(zx_ns_s value) {
    zxidjniJNI.zx_ctx_guard_seen_n_set(swigCPtr, zx_ns_s.getCPtr(value));
  }

  public zx_ns_s getGuard_seen_n() {
    long cPtr = zxidjniJNI.zx_ctx_guard_seen_n_get(swigCPtr);
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

  public void setGuard_seen_p(zx_ns_s value) {
    zxidjniJNI.zx_ctx_guard_seen_p_set(swigCPtr, zx_ns_s.getCPtr(value));
  }

  public zx_ns_s getGuard_seen_p() {
    long cPtr = zxidjniJNI.zx_ctx_guard_seen_p_get(swigCPtr);
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

  public void setExclude_sig(SWIGTYPE_p_void value) {
    zxidjniJNI.zx_ctx_exclude_sig_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getExclude_sig() {
    long cPtr = zxidjniJNI.zx_ctx_exclude_sig_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setInc_ns_len(zx_ns_s value) {
    zxidjniJNI.zx_ctx_inc_ns_len_set(swigCPtr, zx_ns_s.getCPtr(value));
  }

  public zx_ns_s getInc_ns_len() {
    long cPtr = zxidjniJNI.zx_ctx_inc_ns_len_get(swigCPtr);
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

  public void setInc_ns(zx_ns_s value) {
    zxidjniJNI.zx_ctx_inc_ns_set(swigCPtr, zx_ns_s.getCPtr(value));
  }

  public zx_ns_s getInc_ns() {
    long cPtr = zxidjniJNI.zx_ctx_inc_ns_get(swigCPtr);
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

  public void setMalloc_func(SWIGTYPE_p_f_size_t__p_void value) {
    zxidjniJNI.zx_ctx_malloc_func_set(swigCPtr, SWIGTYPE_p_f_size_t__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_size_t__p_void getMalloc_func() {
    long cPtr = zxidjniJNI.zx_ctx_malloc_func_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_size_t__p_void(cPtr, false);
  }

  public void setRealloc_func(SWIGTYPE_p_f_p_void_size_t__p_void value) {
    zxidjniJNI.zx_ctx_realloc_func_set(swigCPtr, SWIGTYPE_p_f_p_void_size_t__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_size_t__p_void getRealloc_func() {
    long cPtr = zxidjniJNI.zx_ctx_realloc_func_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_size_t__p_void(cPtr, false);
  }

  public void setFree_func(SWIGTYPE_p_f_p_void__void value) {
    zxidjniJNI.zx_ctx_free_func_set(swigCPtr, SWIGTYPE_p_f_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void__void getFree_func() {
    long cPtr = zxidjniJNI.zx_ctx_free_func_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__void(cPtr, false);
  }

  public zx_ctx() {
    this(zxidjniJNI.new_zx_ctx(), true);
  }

}
