/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zxidjava;

public class zx_tok {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected zx_tok(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(zx_tok obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      zxidjniJNI.delete_zx_tok(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setName(String value) {
    zxidjniJNI.zx_tok_name_set(swigCPtr, value);
  }

  public String getName() {
    return zxidjniJNI.zx_tok_name_get(swigCPtr);
  }

  public void setPrefix(String value) {
    zxidjniJNI.zx_tok_prefix_set(swigCPtr, value);
  }

  public String getPrefix() {
    return zxidjniJNI.zx_tok_prefix_get(swigCPtr);
  }

  public void setNs(zx_ns_s value) {
    zxidjniJNI.zx_tok_ns_set(swigCPtr, zx_ns_s.getCPtr(value));
  }

  public zx_ns_s getNs() {
    long cPtr = zxidjniJNI.zx_tok_ns_get(swigCPtr);
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

  public zx_tok() {
    this(zxidjniJNI.new_zx_tok(), true);
  }

}
