/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zxidjava;

public class zxidjni implements zxidjniConstants {
  public static zx_elem_s zx_new_simple_elem(zx_ctx c, zx_str ss) {
    long cPtr = zxidjniJNI.zx_new_simple_elem(zx_ctx.getCPtr(c), zx_str.getCPtr(ss));
    return (cPtr == 0) ? null : new zx_elem_s(cPtr, false);
  }

  public static zx_elem_s zx_ref_len_simple_elem(zx_ctx c, int len) {
    long cPtr = zxidjniJNI.zx_ref_len_simple_elem(zx_ctx.getCPtr(c), len);
    return (cPtr == 0) ? null : new zx_elem_s(cPtr, false);
  }

  public static zx_elem_s zx_ref_simple_elem(zx_ctx c, String s) {
    long cPtr = zxidjniJNI.zx_ref_simple_elem(zx_ctx.getCPtr(c), s);
    return (cPtr == 0) ? null : new zx_elem_s(cPtr, false);
  }

  public static zx_elem_s zx_dup_len_simple_elem(zx_ctx c, int len) {
    long cPtr = zxidjniJNI.zx_dup_len_simple_elem(zx_ctx.getCPtr(c), len);
    return (cPtr == 0) ? null : new zx_elem_s(cPtr, false);
  }

  public static zx_elem_s zx_dup_simple_elem(zx_ctx c, String s) {
    long cPtr = zxidjniJNI.zx_dup_simple_elem(zx_ctx.getCPtr(c), s);
    return (cPtr == 0) ? null : new zx_elem_s(cPtr, false);
  }

  public static zx_str zx_ref_str(zx_ctx c, String s) {
    long cPtr = zxidjniJNI.zx_ref_str(zx_ctx.getCPtr(c), s);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str zx_ref_len_str(zx_ctx c, int len) {
    long cPtr = zxidjniJNI.zx_ref_len_str(zx_ctx.getCPtr(c), len);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str zx_dup_str(zx_ctx c, String s) {
    long cPtr = zxidjniJNI.zx_dup_str(zx_ctx.getCPtr(c), s);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str zx_dup_len_str(zx_ctx c, int len) {
    long cPtr = zxidjniJNI.zx_dup_len_str(zx_ctx.getCPtr(c), len);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str zx_strf(zx_ctx c, String f) {
    long cPtr = zxidjniJNI.zx_strf(zx_ctx.getCPtr(c), f);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static void zx_str_free(zx_ctx c, zx_str ss) {
    zxidjniJNI.zx_str_free(zx_ctx.getCPtr(c), zx_str.getCPtr(ss));
  }

  public static String zx_str_to_c(zx_ctx c, zx_str ss) {
    return zxidjniJNI.zx_str_to_c(zx_ctx.getCPtr(c), zx_str.getCPtr(ss));
  }

  public static void zx_str_conv(zx_str ss, SWIGTYPE_p_int out_len, SWIGTYPE_p_p_char out_s) {
    zxidjniJNI.zx_str_conv(zx_str.getCPtr(ss), SWIGTYPE_p_int.getCPtr(out_len), SWIGTYPE_p_p_char.getCPtr(out_s));
  }

  public static int zx_str_ends_in(zx_str ss, int len, String suffix) {
    return zxidjniJNI.zx_str_ends_in(zx_str.getCPtr(ss), len, suffix);
  }

  public static String zx_memmem(String haystack, int haystack_len, String needle, int needle_len) {
    return zxidjniJNI.zx_memmem(haystack, haystack_len, needle, needle_len);
  }

  public static SWIGTYPE_p_void zx_alloc(zx_ctx c, int size) {
    long cPtr = zxidjniJNI.zx_alloc(zx_ctx.getCPtr(c), size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void zx_zalloc(zx_ctx c, int size) {
    long cPtr = zxidjniJNI.zx_zalloc(zx_ctx.getCPtr(c), size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void zx_free(zx_ctx c, SWIGTYPE_p_void p) {
    long cPtr = zxidjniJNI.zx_free(zx_ctx.getCPtr(c), SWIGTYPE_p_void.getCPtr(p));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static String zx_dup_cstr(zx_ctx c, String str) {
    return zxidjniJNI.zx_dup_cstr(zx_ctx.getCPtr(c), str);
  }

  public static void zx_fix_any_elem_dec(zx_ctx c, zx_any_elem_s x, String nam, int namlen) {
    zxidjniJNI.zx_fix_any_elem_dec(zx_ctx.getCPtr(c), zx_any_elem_s.getCPtr(x), nam, namlen);
  }

  public static zx_ns_s zx_locate_ns_by_prefix(zx_ctx c, int len, String prefix) {
    long cPtr = zxidjniJNI.zx_locate_ns_by_prefix(zx_ctx.getCPtr(c), len, prefix);
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

  public static int zx_is_ns_prefix(zx_ns_s ns, int len, String prefix) {
    return zxidjniJNI.zx_is_ns_prefix(zx_ns_s.getCPtr(ns), len, prefix);
  }

  public static zx_ns_s zx_prefix_seen(zx_ctx c, int len, String prefix) {
    long cPtr = zxidjniJNI.zx_prefix_seen(zx_ctx.getCPtr(c), len, prefix);
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

  public static zx_ns_s zx_prefix_seen_whine(zx_ctx c, int len, String prefix, String logkey) {
    long cPtr = zxidjniJNI.zx_prefix_seen_whine(zx_ctx.getCPtr(c), len, prefix, logkey);
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

  public static zx_ns_s zx_scan_xmlns(zx_ctx c) {
    long cPtr = zxidjniJNI.zx_scan_xmlns(zx_ctx.getCPtr(c));
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

  public static void zx_pop_seen(zx_ns_s ns) {
    zxidjniJNI.zx_pop_seen(zx_ns_s.getCPtr(ns));
  }

  public static zx_tok zx_tok_by_ns(zx_tok zt, zx_tok lim, int len, String name, zx_ns_s ns) {
    long cPtr = zxidjniJNI.zx_tok_by_ns(zx_tok.getCPtr(zt), zx_tok.getCPtr(lim), len, name, zx_ns_s.getCPtr(ns));
    return (cPtr == 0) ? null : new zx_tok(cPtr, false);
  }

  public static int zx_len_xmlns_if_not_seen(zx_ctx c, zx_ns_s ns, SWIGTYPE_p_p_zx_ns_s pop_seen) {
    return zxidjniJNI.zx_len_xmlns_if_not_seen(zx_ctx.getCPtr(c), zx_ns_s.getCPtr(ns), SWIGTYPE_p_p_zx_ns_s.getCPtr(pop_seen));
  }

  public static String zx_enc_xmlns_if_not_seen(zx_ctx c, String p, zx_ns_s ns, SWIGTYPE_p_p_zx_ns_s pop_seen) {
    return zxidjniJNI.zx_enc_xmlns_if_not_seen(zx_ctx.getCPtr(c), p, zx_ns_s.getCPtr(ns), SWIGTYPE_p_p_zx_ns_s.getCPtr(pop_seen));
  }

  public static void zx_add_xmlns_if_not_seen(zx_ctx c, zx_ns_s ns, SWIGTYPE_p_p_zx_ns_s pop_seen) {
    zxidjniJNI.zx_add_xmlns_if_not_seen(zx_ctx.getCPtr(c), zx_ns_s.getCPtr(ns), SWIGTYPE_p_p_zx_ns_s.getCPtr(pop_seen));
  }

  public static String zx_enc_seen(String p, zx_ns_s ns) {
    return zxidjniJNI.zx_enc_seen(p, zx_ns_s.getCPtr(ns));
  }

  public static int zx_len_so_common(zx_ctx c, zx_elem_s x) {
    return zxidjniJNI.zx_len_so_common(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(x));
  }

  public static int zx_len_wo_common(zx_ctx c, zx_elem_s x) {
    return zxidjniJNI.zx_len_wo_common(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(x));
  }

  public static String zx_enc_unknown_attrs(String p, zx_any_attr_s aa) {
    return zxidjniJNI.zx_enc_unknown_attrs(p, zx_any_attr_s.getCPtr(aa));
  }

  public static String zx_enc_so_unknown_elems_and_content(zx_ctx c, String p, zx_elem_s x) {
    return zxidjniJNI.zx_enc_so_unknown_elems_and_content(zx_ctx.getCPtr(c), p, zx_elem_s.getCPtr(x));
  }

  public static zx_str zx_easy_enc_common(zx_ctx c, String p, String buf, int len) {
    long cPtr = zxidjniJNI.zx_easy_enc_common(zx_ctx.getCPtr(c), p, buf, len);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int zx_attr_so_len(zx_str attr, int name_size) {
    return zxidjniJNI.zx_attr_so_len(zx_str.getCPtr(attr), name_size);
  }

  public static String zx_attr_so_enc(String p, zx_str attr, String name, int name_len) {
    return zxidjniJNI.zx_attr_so_enc(p, zx_str.getCPtr(attr), name, name_len);
  }

  public static int zx_attr_wo_len(zx_str attr, int name_size) {
    return zxidjniJNI.zx_attr_wo_len(zx_str.getCPtr(attr), name_size);
  }

  public static String zx_attr_wo_enc(String p, zx_str attr, String name, int name_len) {
    return zxidjniJNI.zx_attr_wo_enc(p, zx_str.getCPtr(attr), name, name_len);
  }

  public static void zx_dup_attr(zx_ctx c, zx_str attr) {
    zxidjniJNI.zx_dup_attr(zx_ctx.getCPtr(c), zx_str.getCPtr(attr));
  }

  public static void zx_free_attr(zx_ctx c, zx_str attr, int free_strs) {
    zxidjniJNI.zx_free_attr(zx_ctx.getCPtr(c), zx_str.getCPtr(attr), free_strs);
  }

  public static zx_str zx_clone_attr(zx_ctx c, zx_str attr) {
    long cPtr = zxidjniJNI.zx_clone_attr(zx_ctx.getCPtr(c), zx_str.getCPtr(attr));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static void zx_free_elem_common(zx_ctx c, zx_elem_s x, int free_strs) {
    zxidjniJNI.zx_free_elem_common(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(x), free_strs);
  }

  public static zx_elem_s zx_clone_elem_common(zx_ctx c, zx_elem_s x, int size, int dup_strs) {
    long cPtr = zxidjniJNI.zx_clone_elem_common(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(x), size, dup_strs);
    return (cPtr == 0) ? null : new zx_elem_s(cPtr, false);
  }

  public static void zx_dup_strs_common(zx_ctx c, zx_elem_s x) {
    zxidjniJNI.zx_dup_strs_common(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(x));
  }

  public static int zx_walk_so_unknown_attributes(zx_ctx c, zx_elem_s x, SWIGTYPE_p_void ctx, SWIGTYPE_p_f_p_struct_zx_node_s_p_void__int callback) {
    return zxidjniJNI.zx_walk_so_unknown_attributes(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(x), SWIGTYPE_p_void.getCPtr(ctx), SWIGTYPE_p_f_p_struct_zx_node_s_p_void__int.getCPtr(callback));
  }

  public static int zx_walk_so_unknown_elems_and_content(zx_ctx c, zx_elem_s x, SWIGTYPE_p_void ctx, SWIGTYPE_p_f_p_struct_zx_node_s_p_void__int callback) {
    return zxidjniJNI.zx_walk_so_unknown_elems_and_content(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(x), SWIGTYPE_p_void.getCPtr(ctx), SWIGTYPE_p_f_p_struct_zx_node_s_p_void__int.getCPtr(callback));
  }

  public static zx_elem_s zx_deep_clone_simple_elems(zx_ctx c, zx_elem_s x, int dup_strs) {
    long cPtr = zxidjniJNI.zx_deep_clone_simple_elems(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(x), dup_strs);
    return (cPtr == 0) ? null : new zx_elem_s(cPtr, false);
  }

  public static int zx_walk_so_simple_elems(zx_ctx c, zx_elem_s se, SWIGTYPE_p_void ctx, SWIGTYPE_p_f_p_struct_zx_node_s_p_void__int callback) {
    return zxidjniJNI.zx_walk_so_simple_elems(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(se), SWIGTYPE_p_void.getCPtr(ctx), SWIGTYPE_p_f_p_struct_zx_node_s_p_void__int.getCPtr(callback));
  }

  public static void zx_free_simple_elems(zx_ctx c, zx_elem_s se, int free_strs) {
    zxidjniJNI.zx_free_simple_elems(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(se), free_strs);
  }

  public static void zx_dup_strs_simple_elems(zx_ctx c, zx_elem_s se) {
    zxidjniJNI.zx_dup_strs_simple_elems(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(se));
  }

  public static void zx_prepare_dec_ctx(zx_ctx c, zx_ns_s ns_tab, String start, String lim) {
    zxidjniJNI.zx_prepare_dec_ctx(zx_ctx.getCPtr(c), zx_ns_s.getCPtr(ns_tab), start, lim);
  }

  public static String simple(String conf, String qs, int auto_flags) {
    return zxidjniJNI.zxid_simple(conf, qs, auto_flags);
  }

  public static String idp_list(String conf, int auto_flags) {
    return zxidjniJNI.zxid_idp_list(conf, auto_flags);
  }

  public static String idp_select(String conf, int auto_flags) {
    return zxidjniJNI.zxid_idp_select(conf, auto_flags);
  }

  public static String fed_mgmt(String conf, String sid, int auto_flags) {
    return zxidjniJNI.zxid_fed_mgmt(conf, sid, auto_flags);
  }

  public static zxid_conf new_conf_to_cf(String conf) {
    long cPtr = zxidjniJNI.zxid_new_conf_to_cf(conf);
    return (cPtr == 0) ? null : new zxid_conf(cPtr, false);
  }

  public static String simple_cf(zxid_conf cf, int qs_len, String qs, SWIGTYPE_p_int res_len, int auto_flags) {
    return zxidjniJNI.zxid_simple_cf(zxid_conf.getCPtr(cf), qs_len, qs, SWIGTYPE_p_int.getCPtr(res_len), auto_flags);
  }

  public static String idp_list_cf(zxid_conf cf, SWIGTYPE_p_int res_len, int auto_flags) {
    return zxidjniJNI.zxid_idp_list_cf(zxid_conf.getCPtr(cf), SWIGTYPE_p_int.getCPtr(res_len), auto_flags);
  }

  public static String idp_select_cf(zxid_conf cf, SWIGTYPE_p_int res_len, int auto_flags) {
    return zxidjniJNI.zxid_idp_select_cf(zxid_conf.getCPtr(cf), SWIGTYPE_p_int.getCPtr(res_len), auto_flags);
  }

  public static String fed_mgmt_cf(zxid_conf cf, SWIGTYPE_p_int res_len, int sid_len, String sid, int auto_flags) {
    return zxidjniJNI.zxid_fed_mgmt_cf(zxid_conf.getCPtr(cf), SWIGTYPE_p_int.getCPtr(res_len), sid_len, sid, auto_flags);
  }

  public static int conf_to_cf_len(zxid_conf cf, int conf_len, String conf) {
    return zxidjniJNI.zxid_conf_to_cf_len(zxid_conf.getCPtr(cf), conf_len, conf);
  }

  public static String simple_len(int conf_len, String conf, int qs_len, String qs, SWIGTYPE_p_int res_len, int auto_flags) {
    return zxidjniJNI.zxid_simple_len(conf_len, conf, qs_len, qs, SWIGTYPE_p_int.getCPtr(res_len), auto_flags);
  }

  public static String idp_list_len(int conf_len, String conf, SWIGTYPE_p_int res_len, int auto_flags) {
    return zxidjniJNI.zxid_idp_list_len(conf_len, conf, SWIGTYPE_p_int.getCPtr(res_len), auto_flags);
  }

  public static String idp_select_len(int conf_len, String conf, SWIGTYPE_p_int res_len, int auto_flags) {
    return zxidjniJNI.zxid_idp_select_len(conf_len, conf, SWIGTYPE_p_int.getCPtr(res_len), auto_flags);
  }

  public static String fed_mgmt_len(int conf_len, String conf, SWIGTYPE_p_int res_len, String sid, int auto_flags) {
    return zxidjniJNI.zxid_fed_mgmt_len(conf_len, conf, SWIGTYPE_p_int.getCPtr(res_len), sid, auto_flags);
  }

  public static zx_str idp_select_zxstr_cf(zxid_conf cf, int auto_flags) {
    long cPtr = zxidjniJNI.zxid_idp_select_zxstr_cf(zxid_conf.getCPtr(cf), auto_flags);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str ses_to_ldif(zxid_conf cf, zxid_ses ses) {
    long cPtr = zxidjniJNI.zxid_ses_to_ldif(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int zxsig_validate(zx_ctx c, SWIGTYPE_p_X509 cert, SWIGTYPE_p_zx_ds_Signature_s sig, int n, zxsig_ref refs) {
    return zxidjniJNI.zxsig_validate(zx_ctx.getCPtr(c), SWIGTYPE_p_X509.getCPtr(cert), SWIGTYPE_p_zx_ds_Signature_s.getCPtr(sig), n, zxsig_ref.getCPtr(refs));
  }

  public static int zx_report_openssl_error(String logkey) {
    return zxidjniJNI.zx_report_openssl_error(logkey);
  }

  public static int zxsig_data_rsa_sha1(zx_ctx c, int len, String d, SWIGTYPE_p_p_char sig, SWIGTYPE_p_RSA priv_key, String lk) {
    return zxidjniJNI.zxsig_data_rsa_sha1(zx_ctx.getCPtr(c), len, d, SWIGTYPE_p_p_char.getCPtr(sig), SWIGTYPE_p_RSA.getCPtr(priv_key), lk);
  }

  public static int zxsig_verify_data_rsa_sha1(int len, String data, int siglen, String sig, SWIGTYPE_p_X509 cert, String lk) {
    return zxidjniJNI.zxsig_verify_data_rsa_sha1(len, data, siglen, sig, SWIGTYPE_p_X509.getCPtr(cert), lk);
  }

  public static void zxlog_write_line(zxid_conf cf, String c_path, int encflags, int n, String logbuf) {
    zxidjniJNI.zxlog_write_line(zxid_conf.getCPtr(cf), c_path, encflags, n, logbuf);
  }

  public static zx_str zxlog_path(zxid_conf cf, zx_str entid, zx_str objid, String dir, String kind, int create_dirs) {
    long cPtr = zxidjniJNI.zxlog_path(zxid_conf.getCPtr(cf), zx_str.getCPtr(entid), zx_str.getCPtr(objid), dir, kind, create_dirs);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int zxlog_dup_check(zxid_conf cf, zx_str path, String logkey) {
    return zxidjniJNI.zxlog_dup_check(zxid_conf.getCPtr(cf), zx_str.getCPtr(path), logkey);
  }

  public static int zxlog_blob(zxid_conf cf, int logflag, zx_str path, zx_str blob) {
    return zxidjniJNI.zxlog_blob(zxid_conf.getCPtr(cf), logflag, zx_str.getCPtr(path), zx_str.getCPtr(blob));
  }

  public static zxid_entity get_ent_from_file(zxid_conf cf, String sha1_name) {
    long cPtr = zxidjniJNI.zxid_get_ent_from_file(zxid_conf.getCPtr(cf), sha1_name);
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity get_ent_from_cache(zxid_conf cf, zx_str eid) {
    long cPtr = zxidjniJNI.zxid_get_ent_from_cache(zxid_conf.getCPtr(cf), zx_str.getCPtr(eid));
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static int write_ent_to_cache(zxid_conf cf, zxid_entity ent) {
    return zxidjniJNI.zxid_write_ent_to_cache(zxid_conf.getCPtr(cf), zxid_entity.getCPtr(ent));
  }

  public static zxid_entity parse_meta(zxid_conf cf, SWIGTYPE_p_p_char md, String lim) {
    long cPtr = zxidjniJNI.zxid_parse_meta(zxid_conf.getCPtr(cf), SWIGTYPE_p_p_char.getCPtr(md), lim);
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity get_meta_ss(zxid_conf cf, zx_str url) {
    long cPtr = zxidjniJNI.zxid_get_meta_ss(zxid_conf.getCPtr(cf), zx_str.getCPtr(url));
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity get_meta(zxid_conf cf, String url) {
    long cPtr = zxidjniJNI.zxid_get_meta(zxid_conf.getCPtr(cf), url);
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity get_ent_ss(zxid_conf cf, zx_str eid) {
    long cPtr = zxidjniJNI.zxid_get_ent_ss(zxid_conf.getCPtr(cf), zx_str.getCPtr(eid));
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity get_ent(zxid_conf cf, String eid) {
    long cPtr = zxidjniJNI.zxid_get_ent(zxid_conf.getCPtr(cf), eid);
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity get_ent_by_succinct_id(zxid_conf cf, String raw_succinct_id) {
    long cPtr = zxidjniJNI.zxid_get_ent_by_succinct_id(zxid_conf.getCPtr(cf), raw_succinct_id);
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity get_ent_by_sha1_name(zxid_conf cf, String sha1_name) {
    long cPtr = zxidjniJNI.zxid_get_ent_by_sha1_name(zxid_conf.getCPtr(cf), sha1_name);
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity load_cot_cache(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_load_cot_cache(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static SWIGTYPE_p_zx_md_KeyDescriptor_s key_desc(zxid_conf cf, String use, SWIGTYPE_p_X509 cert) {
    long cPtr = zxidjniJNI.zxid_key_desc(zxid_conf.getCPtr(cf), use, SWIGTYPE_p_X509.getCPtr(cert));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_md_KeyDescriptor_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_md_SingleLogoutService_s slo_desc(zxid_conf cf, String binding, String loc, String resp_loc) {
    long cPtr = zxidjniJNI.zxid_slo_desc(zxid_conf.getCPtr(cf), binding, loc, resp_loc);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_md_SingleLogoutService_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_md_ManageNameIDService_s nireg_desc(zxid_conf cf, String binding, String loc, String resp_loc) {
    long cPtr = zxidjniJNI.zxid_nireg_desc(zxid_conf.getCPtr(cf), binding, loc, resp_loc);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_md_ManageNameIDService_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_md_AssertionConsumerService_s ac_desc(zxid_conf cf, String binding, String loc, String index) {
    long cPtr = zxidjniJNI.zxid_ac_desc(zxid_conf.getCPtr(cf), binding, loc, index);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_md_AssertionConsumerService_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_md_SPSSODescriptor_s sp_sso_desc(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_sp_sso_desc(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_md_SPSSODescriptor_s(cPtr, false);
  }

  public static zx_str sp_meta(zxid_conf cf, zxid_cgi cgi) {
    long cPtr = zxidjniJNI.zxid_sp_meta(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int send_sp_meta(zxid_conf cf, zxid_cgi cgi) {
    return zxidjniJNI.zxid_send_sp_meta(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
  }

  public static zx_str my_entity_id(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_my_entity_id(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str my_cdc_url(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_my_cdc_url(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sa_Issuer_s my_issuer(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_my_issuer(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_Issuer_s(cPtr, false);
  }

  public static void sha1_file(zxid_conf cf, String name, String sha1) {
    zxidjniJNI.zxid_sha1_file(zxid_conf.getCPtr(cf), name, sha1);
  }

  public static SWIGTYPE_p_X509 extract_cert(String buf, String name) {
    long cPtr = zxidjniJNI.zxid_extract_cert(buf, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_X509(cPtr, false);
  }

  public static SWIGTYPE_p_RSA extract_private_key(String buf, String name) {
    long cPtr = zxidjniJNI.zxid_extract_private_key(buf, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_RSA(cPtr, false);
  }

  public static SWIGTYPE_p_X509 read_cert(zxid_conf cf, String name) {
    long cPtr = zxidjniJNI.zxid_read_cert(zxid_conf.getCPtr(cf), name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_X509(cPtr, false);
  }

  public static SWIGTYPE_p_RSA read_private_key(zxid_conf cf, String name) {
    long cPtr = zxidjniJNI.zxid_read_private_key(zxid_conf.getCPtr(cf), name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_RSA(cPtr, false);
  }

  public static int set_opt(zxid_conf cf, int which, int val) {
    return zxidjniJNI.zxid_set_opt(zxid_conf.getCPtr(cf), which, val);
  }

  public static void url_set(zxid_conf cf, String url) {
    zxidjniJNI.zxid_url_set(zxid_conf.getCPtr(cf), url);
  }

  public static int init_conf(zxid_conf cf, String conf_dir) {
    return zxidjniJNI.zxid_init_conf(zxid_conf.getCPtr(cf), conf_dir);
  }

  public static zxid_conf init_conf_ctx(zxid_conf cf, String zxid_path) {
    long cPtr = zxidjniJNI.zxid_init_conf_ctx(zxid_conf.getCPtr(cf), zxid_path);
    return (cPtr == 0) ? null : new zxid_conf(cPtr, false);
  }

  public static zxid_conf new_conf(String zxid_path) {
    long cPtr = zxidjniJNI.zxid_new_conf(zxid_path);
    return (cPtr == 0) ? null : new zxid_conf(cPtr, false);
  }

  public static int parse_conf_raw(zxid_conf cf, int qs_len, String qs) {
    return zxidjniJNI.zxid_parse_conf_raw(zxid_conf.getCPtr(cf), qs_len, qs);
  }

  public static int parse_conf(zxid_conf cf, String qs) {
    return zxidjniJNI.zxid_parse_conf(zxid_conf.getCPtr(cf), qs);
  }

  public static int parse_cgi(zxid_cgi cgi, String qs) {
    return zxidjniJNI.zxid_parse_cgi(zxid_cgi.getCPtr(cgi), qs);
  }

  public static zxid_cgi new_cgi(zxid_conf cf, String qs) {
    long cPtr = zxidjniJNI.zxid_new_cgi(zxid_conf.getCPtr(cf), qs);
    return (cPtr == 0) ? null : new zxid_cgi(cPtr, false);
  }

  public static zxid_ses fetch_ses(zxid_conf cf, String sid) {
    long cPtr = zxidjniJNI.zxid_fetch_ses(zxid_conf.getCPtr(cf), sid);
    return (cPtr == 0) ? null : new zxid_ses(cPtr, false);
  }

  public static int get_ses(zxid_conf cf, zxid_ses ses, String sid) {
    return zxidjniJNI.zxid_get_ses(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), sid);
  }

  public static int put_ses(zxid_conf cf, zxid_ses ses) {
    return zxidjniJNI.zxid_put_ses(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses));
  }

  public static int del_ses(zxid_conf cf, zxid_ses ses) {
    return zxidjniJNI.zxid_del_ses(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses));
  }

  public static int get_ses_sso_a7n(zxid_conf cf, zxid_ses ses) {
    return zxidjniJNI.zxid_get_ses_sso_a7n(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses));
  }

  public static zx_str lecp_check(zxid_conf cf, zxid_cgi cgi) {
    long cPtr = zxidjniJNI.zxid_lecp_check(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int cdc_read(zxid_conf cf, zxid_cgi cgi) {
    return zxidjniJNI.zxid_cdc_read(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
  }

  public static int cdc_check(zxid_conf cf, zxid_cgi cgi) {
    return zxidjniJNI.zxid_cdc_check(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
  }

  public static SWIGTYPE_p_zx_root_s soap_call_envelope(zxid_conf cf, zx_str url, SWIGTYPE_p_zx_e_Envelope_s env) {
    long cPtr = zxidjniJNI.zxid_soap_call_envelope(zxid_conf.getCPtr(cf), zx_str.getCPtr(url), SWIGTYPE_p_zx_e_Envelope_s.getCPtr(env));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_root_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_root_s soap_call_hdr_body(zxid_conf cf, zx_str url, SWIGTYPE_p_zx_e_Header_s hdr, SWIGTYPE_p_zx_e_Body_s body) {
    long cPtr = zxidjniJNI.zxid_soap_call_hdr_body(zxid_conf.getCPtr(cf), zx_str.getCPtr(url), SWIGTYPE_p_zx_e_Header_s.getCPtr(hdr), SWIGTYPE_p_zx_e_Body_s.getCPtr(body));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_root_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_root_s soap_call_body(zxid_conf cf, zx_str url, SWIGTYPE_p_zx_e_Body_s body) {
    long cPtr = zxidjniJNI.zxid_soap_call_body(zxid_conf.getCPtr(cf), zx_str.getCPtr(url), SWIGTYPE_p_zx_e_Body_s.getCPtr(body));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_root_s(cPtr, false);
  }

  public static int soap_cgi_resp_body(zxid_conf cf, SWIGTYPE_p_zx_e_Body_s body) {
    return zxidjniJNI.zxid_soap_cgi_resp_body(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_e_Body_s.getCPtr(body));
  }

  public static zx_str idp_loc_raw(zxid_conf cf, zxid_cgi cgi, SWIGTYPE_p_zx_sa_Issuer_s Issuer, int svc_type, String binding, int req) {
    long cPtr = zxidjniJNI.zxid_idp_loc_raw(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), SWIGTYPE_p_zx_sa_Issuer_s.getCPtr(Issuer), svc_type, binding, req);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str idp_loc(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, int svc_type, String binding) {
    long cPtr = zxidjniJNI.zxid_idp_loc(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), svc_type, binding);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static SWIGTYPE_p_zx_root_s idp_soap(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, int svc_type, SWIGTYPE_p_zx_e_Body_s body) {
    long cPtr = zxidjniJNI.zxid_idp_soap(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), svc_type, SWIGTYPE_p_zx_e_Body_s.getCPtr(body));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_root_s(cPtr, false);
  }

  public static zx_str saml2_redir_enc(zxid_conf cf, zx_str pay_load) {
    long cPtr = zxidjniJNI.zxid_saml2_redir_enc(zxid_conf.getCPtr(cf), zx_str.getCPtr(pay_load));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int saml2_redir(zxid_conf cf, zx_str loc, zx_str rs) {
    return zxidjniJNI.zxid_saml2_redir(zxid_conf.getCPtr(cf), zx_str.getCPtr(loc), zx_str.getCPtr(rs));
  }

  public static zx_str saml2_redir_url(zxid_conf cf, zx_str loc, zx_str rs) {
    long cPtr = zxidjniJNI.zxid_saml2_redir_url(zxid_conf.getCPtr(cf), zx_str.getCPtr(loc), zx_str.getCPtr(rs));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str saml2_location(zxid_conf cf, zx_str loc, zx_str rs) {
    long cPtr = zxidjniJNI.zxid_saml2_location(zxid_conf.getCPtr(cf), zx_str.getCPtr(loc), zx_str.getCPtr(rs));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int saml2_resp_redir(zxid_conf cf, zx_str loc, zx_str rs) {
    return zxidjniJNI.zxid_saml2_resp_redir(zxid_conf.getCPtr(cf), zx_str.getCPtr(loc), zx_str.getCPtr(rs));
  }

  public static zx_str saml2_resp_location(zxid_conf cf, zx_str loc, zx_str rs) {
    long cPtr = zxidjniJNI.zxid_saml2_resp_location(zxid_conf.getCPtr(cf), zx_str.getCPtr(loc), zx_str.getCPtr(rs));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int saml_ok(zxid_conf cf, zxid_cgi cgi, SWIGTYPE_p_zx_sp_Status_s st, String what) {
    return zxidjniJNI.zxid_saml_ok(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), SWIGTYPE_p_zx_sp_Status_s.getCPtr(st), what);
  }

  public static int pick_sso_profile(zxid_conf cf, zxid_cgi cgi, zxid_entity idp_met) {
    return zxidjniJNI.zxid_pick_sso_profile(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_entity.getCPtr(idp_met));
  }

  public static int start_sso(zxid_conf cf, zxid_cgi cgi) {
    return zxidjniJNI.zxid_start_sso(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
  }

  public static zx_str start_sso_url(zxid_conf cf, zxid_cgi cgi) {
    long cPtr = zxidjniJNI.zxid_start_sso_url(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str start_sso_location(zxid_conf cf, zxid_cgi cgi) {
    long cPtr = zxidjniJNI.zxid_start_sso_location(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int sp_deref_art(zxid_conf cf, zxid_cgi cgi, zxid_ses ses) {
    return zxidjniJNI.zxid_sp_deref_art(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses));
  }

  public static int sp_sso_finalize(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, SWIGTYPE_p_zx_sa_Assertion_s a7n) {
    return zxidjniJNI.zxid_sp_sso_finalize(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), SWIGTYPE_p_zx_sa_Assertion_s.getCPtr(a7n));
  }

  public static String saml2_map_nid_fmt(String f) {
    return zxidjniJNI.zxid_saml2_map_nid_fmt(f);
  }

  public static String saml2_map_protocol_binding(String b) {
    return zxidjniJNI.zxid_saml2_map_protocol_binding(b);
  }

  public static String saml2_map_authn_ctx(String c) {
    return zxidjniJNI.zxid_saml2_map_authn_ctx(c);
  }

  public static zx_str date_time(zxid_conf cf, SWIGTYPE_p_time_t secs) {
    long cPtr = zxidjniJNI.zxid_date_time(zxid_conf.getCPtr(cf), SWIGTYPE_p_time_t.getCPtr(secs));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str mk_id(zxid_conf cf, String prefix, int bits) {
    long cPtr = zxidjniJNI.zxid_mk_id(zxid_conf.getCPtr(cf), prefix, bits);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sa_Issuer_s issuer(zxid_conf cf, zx_str nameid, String affiliation) {
    long cPtr = zxidjniJNI.zxid_issuer(zxid_conf.getCPtr(cf), zx_str.getCPtr(nameid), affiliation);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_Issuer_s(cPtr, false);
  }

  public static int sp_slo_soap(zxid_conf cf, zxid_cgi cgi, zxid_ses ses) {
    return zxidjniJNI.zxid_sp_slo_soap(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses));
  }

  public static int sp_slo_redir(zxid_conf cf, zxid_cgi cgi, zxid_ses ses) {
    return zxidjniJNI.zxid_sp_slo_redir(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses));
  }

  public static zx_str sp_slo_location(zxid_conf cf, zxid_cgi cgi, zxid_ses ses) {
    long cPtr = zxidjniJNI.zxid_sp_slo_location(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int sp_nireg_soap(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, zx_str new_nym) {
    return zxidjniJNI.zxid_sp_nireg_soap(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), zx_str.getCPtr(new_nym));
  }

  public static int sp_nireg_redir(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, zx_str new_nym) {
    return zxidjniJNI.zxid_sp_nireg_redir(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), zx_str.getCPtr(new_nym));
  }

  public static zx_str sp_nireg_location(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, zx_str new_nym) {
    long cPtr = zxidjniJNI.zxid_sp_nireg_location(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), zx_str.getCPtr(new_nym));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str sp_dispatch_location(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, String msg) {
    long cPtr = zxidjniJNI.zxid_sp_dispatch_location(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), msg);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int sp_dispatch(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, String msg) {
    return zxidjniJNI.zxid_sp_dispatch(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), msg);
  }

  public static int sp_soap_dispatch(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, SWIGTYPE_p_zx_root_s r) {
    return zxidjniJNI.zxid_sp_soap_dispatch(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), SWIGTYPE_p_zx_root_s.getCPtr(r));
  }

  public static int sp_soap_parse(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, int len, String buf) {
    return zxidjniJNI.zxid_sp_soap_parse(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), len, buf);
  }

  public static SWIGTYPE_p_zx_sa_Attribute_s find_attribute(SWIGTYPE_p_zx_sa_Assertion_s a7n, int nfmt_len, String nfmt, int name_len, String name, int friendly_len, String friendly, int n) {
    long cPtr = zxidjniJNI.zxid_find_attribute(SWIGTYPE_p_zx_sa_Assertion_s.getCPtr(a7n), nfmt_len, nfmt, name_len, name, friendly_len, friendly, n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_Attribute_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_AuthnRequest_s mk_authn_req(zxid_conf cf, zxid_cgi cgi) {
    long cPtr = zxidjniJNI.zxid_mk_authn_req(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_AuthnRequest_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_ArtifactResolve_s mk_art_deref(zxid_conf cf, zxid_entity idp_meta, String artifact) {
    long cPtr = zxidjniJNI.zxid_mk_art_deref(zxid_conf.getCPtr(cf), zxid_entity.getCPtr(idp_meta), artifact);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_ArtifactResolve_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_Status_s mk_Status(zxid_conf cf, String sc1, String sc2, String msg) {
    long cPtr = zxidjniJNI.zxid_mk_Status(zxid_conf.getCPtr(cf), sc1, sc2, msg);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_Status_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_Status_s OK(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_OK(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_Status_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_LogoutRequest_s mk_logout(zxid_conf cf, SWIGTYPE_p_zx_sa_NameID_s nid, zx_str ses_ix) {
    long cPtr = zxidjniJNI.zxid_mk_logout(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_sa_NameID_s.getCPtr(nid), zx_str.getCPtr(ses_ix));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_LogoutRequest_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_LogoutResponse_s mk_logout_resp(zxid_conf cf, SWIGTYPE_p_zx_sp_Status_s st, zx_str req_id) {
    long cPtr = zxidjniJNI.zxid_mk_logout_resp(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_sp_Status_s.getCPtr(st), zx_str.getCPtr(req_id));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_LogoutResponse_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_ManageNameIDRequest_s mk_nireg(zxid_conf cf, SWIGTYPE_p_zx_sa_NameID_s nid, zx_str new_nym) {
    long cPtr = zxidjniJNI.zxid_mk_nireg(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_sa_NameID_s.getCPtr(nid), zx_str.getCPtr(new_nym));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_ManageNameIDRequest_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_ManageNameIDResponse_s mk_nireg_resp(zxid_conf cf, SWIGTYPE_p_zx_sp_Status_s st, zx_str req_id) {
    long cPtr = zxidjniJNI.zxid_mk_nireg_resp(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_sp_Status_s.getCPtr(st), zx_str.getCPtr(req_id));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_ManageNameIDResponse_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_di_Query_s mk_di_query(zxid_conf cf, String svc_type) {
    long cPtr = zxidjniJNI.zxid_mk_di_query(zxid_conf.getCPtr(cf), svc_type);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_di_Query_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_a_Address_s mk_addr(zxid_conf cf, zx_str url) {
    long cPtr = zxidjniJNI.zxid_mk_addr(zxid_conf.getCPtr(cf), zx_str.getCPtr(url));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_a_Address_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_dap_Select_s mk_dap_select(zxid_conf cf, String dn, String filter, String attributes, int deref_aliases, int scope, int sizelimit, int timelimit, int typesonly) {
    long cPtr = zxidjniJNI.zxid_mk_dap_select(zxid_conf.getCPtr(cf), dn, filter, attributes, deref_aliases, scope, sizelimit, timelimit, typesonly);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_dap_Select_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_dap_QueryItem_s mk_dap_query_item(zxid_conf cf, SWIGTYPE_p_zx_dap_Select_s sel, String objtype, String predef, String sort, String changed_since, int incl_common_attrs, int offset, int count, String setreq, String setid, String contingent_itemidref) {
    long cPtr = zxidjniJNI.zxid_mk_dap_query_item(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_dap_Select_s.getCPtr(sel), objtype, predef, sort, changed_since, incl_common_attrs, offset, count, setreq, setid, contingent_itemidref);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_dap_QueryItem_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_dap_TestOp_s mk_dap_testop(zxid_conf cf, String dn, String filter, String attributes, int deref_aliases, int scope, int sizelimit, int timelimit, int typesonly) {
    long cPtr = zxidjniJNI.zxid_mk_dap_testop(zxid_conf.getCPtr(cf), dn, filter, attributes, deref_aliases, scope, sizelimit, timelimit, typesonly);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_dap_TestOp_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_dap_TestItem_s mk_dap_test_item(zxid_conf cf, SWIGTYPE_p_zx_dap_TestOp_s top, String objtype, String predef) {
    long cPtr = zxidjniJNI.zxid_mk_dap_test_item(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_dap_TestOp_s.getCPtr(top), objtype, predef);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_dap_TestItem_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_dap_ResultQuery_s mk_dap_resquery(zxid_conf cf, SWIGTYPE_p_zx_dap_Select_s sel, String objtype, String predef, String sort, String changed_since, int incl_common_attr, String contingent_itemidref) {
    long cPtr = zxidjniJNI.zxid_mk_dap_resquery(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_dap_Select_s.getCPtr(sel), objtype, predef, sort, changed_since, incl_common_attr, contingent_itemidref);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_dap_ResultQuery_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_dap_Subscription_s mk_dap_subscription(zxid_conf cf, String subsID, String itemidref, SWIGTYPE_p_zx_dap_ResultQuery_s rq, String aggreg, String trig, String starts, String expires, int incl_data, String admin_notif, String notify_ref) {
    long cPtr = zxidjniJNI.zxid_mk_dap_subscription(zxid_conf.getCPtr(cf), subsID, itemidref, SWIGTYPE_p_zx_dap_ResultQuery_s.getCPtr(rq), aggreg, trig, starts, expires, incl_data, admin_notif, notify_ref);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_dap_Subscription_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_dap_Query_s mk_dap_query(zxid_conf cf, SWIGTYPE_p_zx_dap_TestItem_s tis, SWIGTYPE_p_zx_dap_QueryItem_s qis, SWIGTYPE_p_zx_dap_Subscription_s subs) {
    long cPtr = zxidjniJNI.zxid_mk_dap_query(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_dap_TestItem_s.getCPtr(tis), SWIGTYPE_p_zx_dap_QueryItem_s.getCPtr(qis), SWIGTYPE_p_zx_dap_Subscription_s.getCPtr(subs));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_dap_Query_s(cPtr, false);
  }

  public static int map_sec_mech(SWIGTYPE_p_zx_a_EndpointReference_s epr) {
    return zxidjniJNI.zxid_map_sec_mech(SWIGTYPE_p_zx_a_EndpointReference_s.getCPtr(epr));
  }

  public static SWIGTYPE_p_zx_e_Envelope_s wsc_call(zxid_conf cf, zxid_ses ses, SWIGTYPE_p_zx_a_EndpointReference_s epr, SWIGTYPE_p_zx_e_Envelope_s env) {
    long cPtr = zxidjniJNI.zxid_wsc_call(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), SWIGTYPE_p_zx_a_EndpointReference_s.getCPtr(epr), SWIGTYPE_p_zx_e_Envelope_s.getCPtr(env));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_e_Envelope_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_e_Envelope_s vzxid_new_envf(zxid_conf cf, String body_f, SWIGTYPE_p_va_list ap) {
    long cPtr = zxidjniJNI.vzxid_new_envf(zxid_conf.getCPtr(cf), body_f, SWIGTYPE_p_va_list.getCPtr(ap));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_e_Envelope_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_e_Envelope_s new_envf(zxid_conf cf, String body_f) {
    long cPtr = zxidjniJNI.zxid_new_envf(zxid_conf.getCPtr(cf), body_f);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_e_Envelope_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_e_Envelope_s callf(zxid_conf cf, zxid_ses ses, String svctype, String body_f) {
    long cPtr = zxidjniJNI.zxid_callf(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), svctype, body_f);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_e_Envelope_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_a_EndpointReference_s get_epr(zxid_conf cf, zxid_ses ses, String svc, int n) {
    long cPtr = zxidjniJNI.zxid_get_epr(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), svc, n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_a_EndpointReference_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_a_EndpointReference_s find_epr(zxid_conf cf, zxid_ses ses, String svc, int n) {
    long cPtr = zxidjniJNI.zxid_find_epr(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), svc, n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_a_EndpointReference_s(cPtr, false);
  }

  public static int cache_epr(zxid_conf cf, zxid_ses ses, SWIGTYPE_p_zx_a_EndpointReference_s epr) {
    return zxidjniJNI.zxid_cache_epr(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), SWIGTYPE_p_zx_a_EndpointReference_s.getCPtr(epr));
  }

  public static int snarf_eprs_from_ses(zxid_conf cf, zxid_ses ses) {
    return zxidjniJNI.zxid_snarf_eprs_from_ses(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses));
  }

  public static void setStd_basis_64(String value) {
    zxidjniJNI.std_basis_64_set(value);
  }

  public static String getStd_basis_64() {
    return zxidjniJNI.std_basis_64_get();
  }

  public static void setSafe_basis_64(String value) {
    zxidjniJNI.safe_basis_64_set(value);
  }

  public static String getSafe_basis_64() {
    return zxidjniJNI.safe_basis_64_get();
  }

  public static void setZx_std_index_64(SWIGTYPE_p_unsigned_char value) {
    zxidjniJNI.zx_std_index_64_set(SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public static SWIGTYPE_p_unsigned_char getZx_std_index_64() {
    long cPtr = zxidjniJNI.zx_std_index_64_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static String base64_fancy_raw(String p, int len, String r, String basis_64, int line_len, int eol_len, String eol, char eq_pad) {
    return zxidjniJNI.base64_fancy_raw(p, len, r, basis_64, line_len, eol_len, eol, eq_pad);
  }

  public static String unbase64_raw(String p, String lim, String r, String index_64) {
    return zxidjniJNI.unbase64_raw(p, lim, r, index_64);
  }

  public static String sha1_safe_base64(String out_buf, int len, String data) {
    return zxidjniJNI.sha1_safe_base64(out_buf, len, data);
  }

  public static String zx_zlib_raw_deflate(zx_ctx c, int in_len, String in, SWIGTYPE_p_int out_len) {
    return zxidjniJNI.zx_zlib_raw_deflate(zx_ctx.getCPtr(c), in_len, in, SWIGTYPE_p_int.getCPtr(out_len));
  }

  public static String zx_zlib_raw_inflate(zx_ctx c, int in_len, String in, SWIGTYPE_p_int out_len) {
    return zxidjniJNI.zx_zlib_raw_inflate(zx_ctx.getCPtr(c), in_len, in, SWIGTYPE_p_int.getCPtr(out_len));
  }

  public static int zx_url_encode_len(int in_len, String in) {
    return zxidjniJNI.zx_url_encode_len(in_len, in);
  }

  public static void zx_url_encode_raw(int in_len, String in, String out) {
    zxidjniJNI.zx_url_encode_raw(in_len, in, out);
  }

  public static String zx_url_encode(zx_ctx c, int in_len, String in, SWIGTYPE_p_int out_len) {
    return zxidjniJNI.zx_url_encode(zx_ctx.getCPtr(c), in_len, in, SWIGTYPE_p_int.getCPtr(out_len));
  }

  public static int read_all(int maxlen, String buf, String logkey, String name_fmt) {
    return zxidjniJNI.read_all(maxlen, buf, logkey, name_fmt);
  }

  public static int vname_from_path(String buf, int buf_len, String name_fmt, SWIGTYPE_p_va_list ap) {
    return zxidjniJNI.vname_from_path(buf, buf_len, name_fmt, SWIGTYPE_p_va_list.getCPtr(ap));
  }

  public static int name_from_path(String buf, int buf_len, String name_fmt) {
    return zxidjniJNI.name_from_path(buf, buf_len, name_fmt);
  }

  public static int open_fd_from_path(int flags, int mode, String logkey, String name_fmt) {
    return zxidjniJNI.open_fd_from_path(flags, mode, logkey, name_fmt);
  }

  public static int read_all_fd(int fd, String p, int want, SWIGTYPE_p_int got_all) {
    return zxidjniJNI.read_all_fd(fd, p, want, SWIGTYPE_p_int.getCPtr(got_all));
  }

  public static int write_all_fd(int fd, String p, int pending) {
    return zxidjniJNI.write_all_fd(fd, p, pending);
  }

  public static long curl_write_data(SWIGTYPE_p_void buffer, long size, long nmemb, SWIGTYPE_p_void userp) {
    return zxidjniJNI.zxid_curl_write_data(SWIGTYPE_p_void.getCPtr(buffer), size, nmemb, SWIGTYPE_p_void.getCPtr(userp));
  }

  public static long curl_read_data(SWIGTYPE_p_void buffer, long size, long nmemb, SWIGTYPE_p_void userp) {
    return zxidjniJNI.zxid_curl_read_data(SWIGTYPE_p_void.getCPtr(buffer), size, nmemb, SWIGTYPE_p_void.getCPtr(userp));
  }

  public static int version() {
    return zxidjniJNI.zxid_version();
  }

  public static String version_str() {
    return zxidjniJNI.zxid_version_str();
  }

  public static void setZx_ns_tab(zx_ns_s value) {
    zxidjniJNI.zx_ns_tab_set(zx_ns_s.getCPtr(value));
  }

  public static zx_ns_s getZx_ns_tab() {
    long cPtr = zxidjniJNI.zx_ns_tab_get();
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

}
