/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zxidjava;

public class zxid_attr {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected zxid_attr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(zxid_attr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      zxidjniJNI.delete_zxid_attr(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setN(zxid_attr value) {
    zxidjniJNI.zxid_attr_n_set(swigCPtr, zxid_attr.getCPtr(value));
  }

  public zxid_attr getN() {
    long cPtr = zxidjniJNI.zxid_attr_n_get(swigCPtr);
    return (cPtr == 0) ? null : new zxid_attr(cPtr, false);
  }

  public void setNv(zxid_attr value) {
    zxidjniJNI.zxid_attr_nv_set(swigCPtr, zxid_attr.getCPtr(value));
  }

  public zxid_attr getNv() {
    long cPtr = zxidjniJNI.zxid_attr_nv_get(swigCPtr);
    return (cPtr == 0) ? null : new zxid_attr(cPtr, false);
  }

  public void setName(String value) {
    zxidjniJNI.zxid_attr_name_set(swigCPtr, value);
  }

  public String getName() {
    return zxidjniJNI.zxid_attr_name_get(swigCPtr);
  }

  public void setVal(String value) {
    zxidjniJNI.zxid_attr_val_set(swigCPtr, value);
  }

  public String getVal() {
    return zxidjniJNI.zxid_attr_val_get(swigCPtr);
  }

  public void setMap_val(zx_str value) {
    zxidjniJNI.zxid_attr_map_val_set(swigCPtr, zx_str.getCPtr(value));
  }

  public zx_str getMap_val() {
    long cPtr = zxidjniJNI.zxid_attr_map_val_get(swigCPtr);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public void setOrig(SWIGTYPE_p_zx_sa_Attribute_s value) {
    zxidjniJNI.zxid_attr_orig_set(swigCPtr, SWIGTYPE_p_zx_sa_Attribute_s.getCPtr(value));
  }

  public SWIGTYPE_p_zx_sa_Attribute_s getOrig() {
    long cPtr = zxidjniJNI.zxid_attr_orig_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_Attribute_s(cPtr, false);
  }

  public void setIssuer(zx_str value) {
    zxidjniJNI.zxid_attr_issuer_set(swigCPtr, zx_str.getCPtr(value));
  }

  public zx_str getIssuer() {
    long cPtr = zxidjniJNI.zxid_attr_issuer_get(swigCPtr);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public zxid_attr() {
    this(zxidjniJNI.new_zxid_attr(), true);
  }

}
