/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zxidjava;

public class zxid_cstr_list {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected zxid_cstr_list(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(zxid_cstr_list obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      zxidjniJNI.delete_zxid_cstr_list(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setN(zxid_cstr_list value) {
    zxidjniJNI.zxid_cstr_list_n_set(swigCPtr, zxid_cstr_list.getCPtr(value));
  }

  public zxid_cstr_list getN() {
    long cPtr = zxidjniJNI.zxid_cstr_list_n_get(swigCPtr);
    return (cPtr == 0) ? null : new zxid_cstr_list(cPtr, false);
  }

  public void setS(String value) {
    zxidjniJNI.zxid_cstr_list_s_set(swigCPtr, value);
  }

  public String getS() {
    return zxidjniJNI.zxid_cstr_list_s_get(swigCPtr);
  }

  public zxid_cstr_list() {
    this(zxidjniJNI.new_zxid_cstr_list(), true);
  }

}
