/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zxidjava;

public class zxid_atsrc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected zxid_atsrc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(zxid_atsrc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      zxidjniJNI.delete_zxid_atsrc(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setN(zxid_atsrc value) {
    zxidjniJNI.zxid_atsrc_n_set(swigCPtr, zxid_atsrc.getCPtr(value));
  }

  public zxid_atsrc getN() {
    long cPtr = zxidjniJNI.zxid_atsrc_n_get(swigCPtr);
    return (cPtr == 0) ? null : new zxid_atsrc(cPtr, false);
  }

  public void setAt(zxid_attr value) {
    zxidjniJNI.zxid_atsrc_at_set(swigCPtr, zxid_attr.getCPtr(value));
  }

  public zxid_attr getAt() {
    long cPtr = zxidjniJNI.zxid_atsrc_at_get(swigCPtr);
    return (cPtr == 0) ? null : new zxid_attr(cPtr, false);
  }

  public void setNs(String value) {
    zxidjniJNI.zxid_atsrc_ns_set(swigCPtr, value);
  }

  public String getNs() {
    return zxidjniJNI.zxid_atsrc_ns_get(swigCPtr);
  }

  public void setWeight(String value) {
    zxidjniJNI.zxid_atsrc_weight_set(swigCPtr, value);
  }

  public String getWeight() {
    return zxidjniJNI.zxid_atsrc_weight_get(swigCPtr);
  }

  public void setUrl(String value) {
    zxidjniJNI.zxid_atsrc_url_set(swigCPtr, value);
  }

  public String getUrl() {
    return zxidjniJNI.zxid_atsrc_url_get(swigCPtr);
  }

  public void setAapml(String value) {
    zxidjniJNI.zxid_atsrc_aapml_set(swigCPtr, value);
  }

  public String getAapml() {
    return zxidjniJNI.zxid_atsrc_aapml_get(swigCPtr);
  }

  public void setOtherlim(String value) {
    zxidjniJNI.zxid_atsrc_otherlim_set(swigCPtr, value);
  }

  public String getOtherlim() {
    return zxidjniJNI.zxid_atsrc_otherlim_get(swigCPtr);
  }

  public void setExt(String value) {
    zxidjniJNI.zxid_atsrc_ext_set(swigCPtr, value);
  }

  public String getExt() {
    return zxidjniJNI.zxid_atsrc_ext_get(swigCPtr);
  }

  public zxid_atsrc() {
    this(zxidjniJNI.new_zxid_atsrc(), true);
  }

}
