/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zxidjava;

public class zxid_entity {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected zxid_entity(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(zxid_entity obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      zxidjniJNI.delete_zxid_entity(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setN(zxid_entity value) {
    zxidjniJNI.zxid_entity_n_set(swigCPtr, zxid_entity.getCPtr(value));
  }

  public zxid_entity getN() {
    long cPtr = zxidjniJNI.zxid_entity_n_get(swigCPtr);
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public void setEid_len(int value) {
    zxidjniJNI.zxid_entity_eid_len_set(swigCPtr, value);
  }

  public int getEid_len() {
    return zxidjniJNI.zxid_entity_eid_len_get(swigCPtr);
  }

  public void setEid(String value) {
    zxidjniJNI.zxid_entity_eid_set(swigCPtr, value);
  }

  public String getEid() {
    return zxidjniJNI.zxid_entity_eid_get(swigCPtr);
  }

  public void setSha1_name(String value) {
    zxidjniJNI.zxid_entity_sha1_name_set(swigCPtr, value);
  }

  public String getSha1_name() {
    return zxidjniJNI.zxid_entity_sha1_name_get(swigCPtr);
  }

  public void setTls_cert(SWIGTYPE_p_X509 value) {
    zxidjniJNI.zxid_entity_tls_cert_set(swigCPtr, SWIGTYPE_p_X509.getCPtr(value));
  }

  public SWIGTYPE_p_X509 getTls_cert() {
    long cPtr = zxidjniJNI.zxid_entity_tls_cert_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_X509(cPtr, false);
  }

  public void setSign_cert(SWIGTYPE_p_X509 value) {
    zxidjniJNI.zxid_entity_sign_cert_set(swigCPtr, SWIGTYPE_p_X509.getCPtr(value));
  }

  public SWIGTYPE_p_X509 getSign_cert() {
    long cPtr = zxidjniJNI.zxid_entity_sign_cert_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_X509(cPtr, false);
  }

  public void setEnc_cert(SWIGTYPE_p_X509 value) {
    zxidjniJNI.zxid_entity_enc_cert_set(swigCPtr, SWIGTYPE_p_X509.getCPtr(value));
  }

  public SWIGTYPE_p_X509 getEnc_cert() {
    long cPtr = zxidjniJNI.zxid_entity_enc_cert_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_X509(cPtr, false);
  }

  public void setEd(SWIGTYPE_p_zx_md_EntityDescriptor_s value) {
    zxidjniJNI.zxid_entity_ed_set(swigCPtr, SWIGTYPE_p_zx_md_EntityDescriptor_s.getCPtr(value));
  }

  public SWIGTYPE_p_zx_md_EntityDescriptor_s getEd() {
    long cPtr = zxidjniJNI.zxid_entity_ed_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_md_EntityDescriptor_s(cPtr, false);
  }

  public zxid_entity() {
    this(zxidjniJNI.new_zxid_entity(), true);
  }

}
