/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zxidjava;

public class zxidjni implements zxidjniConstants {
  public static zx_elem_s zx_new_simple_elem(zx_ctx c, zx_str ss) {
    long cPtr = zxidjniJNI.zx_new_simple_elem(zx_ctx.getCPtr(c), zx_str.getCPtr(ss));
    return (cPtr == 0) ? null : new zx_elem_s(cPtr, false);
  }

  public static zx_elem_s zx_ref_len_simple_elem(zx_ctx c, int len) {
    long cPtr = zxidjniJNI.zx_ref_len_simple_elem(zx_ctx.getCPtr(c), len);
    return (cPtr == 0) ? null : new zx_elem_s(cPtr, false);
  }

  public static zx_elem_s zx_ref_simple_elem(zx_ctx c, String s) {
    long cPtr = zxidjniJNI.zx_ref_simple_elem(zx_ctx.getCPtr(c), s);
    return (cPtr == 0) ? null : new zx_elem_s(cPtr, false);
  }

  public static zx_elem_s zx_dup_len_simple_elem(zx_ctx c, int len) {
    long cPtr = zxidjniJNI.zx_dup_len_simple_elem(zx_ctx.getCPtr(c), len);
    return (cPtr == 0) ? null : new zx_elem_s(cPtr, false);
  }

  public static zx_elem_s zx_dup_simple_elem(zx_ctx c, String s) {
    long cPtr = zxidjniJNI.zx_dup_simple_elem(zx_ctx.getCPtr(c), s);
    return (cPtr == 0) ? null : new zx_elem_s(cPtr, false);
  }

  public static zx_str zx_ref_str(zx_ctx c, String s) {
    long cPtr = zxidjniJNI.zx_ref_str(zx_ctx.getCPtr(c), s);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str zx_ref_len_str(zx_ctx c, int len) {
    long cPtr = zxidjniJNI.zx_ref_len_str(zx_ctx.getCPtr(c), len);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str zx_new_len_str(zx_ctx c, int len) {
    long cPtr = zxidjniJNI.zx_new_len_str(zx_ctx.getCPtr(c), len);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str zx_dup_str(zx_ctx c, String s) {
    long cPtr = zxidjniJNI.zx_dup_str(zx_ctx.getCPtr(c), s);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str zx_dup_len_str(zx_ctx c, int len) {
    long cPtr = zxidjniJNI.zx_dup_len_str(zx_ctx.getCPtr(c), len);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static String zx_alloc_sprintf(zx_ctx c, SWIGTYPE_p_int retlen, String f) {
    return zxidjniJNI.zx_alloc_sprintf(zx_ctx.getCPtr(c), SWIGTYPE_p_int.getCPtr(retlen), f);
  }

  public static zx_str zx_strf(zx_ctx c, String f) {
    long cPtr = zxidjniJNI.zx_strf(zx_ctx.getCPtr(c), f);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static void zx_str_free(zx_ctx c, zx_str ss) {
    zxidjniJNI.zx_str_free(zx_ctx.getCPtr(c), zx_str.getCPtr(ss));
  }

  public static String zx_str_to_c(zx_ctx c, zx_str ss) {
    return zxidjniJNI.zx_str_to_c(zx_ctx.getCPtr(c), zx_str.getCPtr(ss));
  }

  public static void zx_str_conv(zx_str ss, SWIGTYPE_p_int out_len, SWIGTYPE_p_p_char out_s) {
    zxidjniJNI.zx_str_conv(zx_str.getCPtr(ss), SWIGTYPE_p_int.getCPtr(out_len), SWIGTYPE_p_p_char.getCPtr(out_s));
  }

  public static int zx_str_ends_in(zx_str ss, int len, String suffix) {
    return zxidjniJNI.zx_str_ends_in(zx_str.getCPtr(ss), len, suffix);
  }

  public static String zx_memmem(String haystack, int haystack_len, String needle, int needle_len) {
    return zxidjniJNI.zx_memmem(haystack, haystack_len, needle, needle_len);
  }

  public static SWIGTYPE_p_void zx_alloc(zx_ctx c, int size) {
    long cPtr = zxidjniJNI.zx_alloc(zx_ctx.getCPtr(c), size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void zx_zalloc(zx_ctx c, int size) {
    long cPtr = zxidjniJNI.zx_zalloc(zx_ctx.getCPtr(c), size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void zx_free(zx_ctx c, SWIGTYPE_p_void p) {
    long cPtr = zxidjniJNI.zx_free(zx_ctx.getCPtr(c), SWIGTYPE_p_void.getCPtr(p));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static String zx_dup_cstr(zx_ctx c, String str) {
    return zxidjniJNI.zx_dup_cstr(zx_ctx.getCPtr(c), str);
  }

  public static void zx_reset_ctx(zx_ctx ctx) {
    zxidjniJNI.zx_reset_ctx(zx_ctx.getCPtr(ctx));
  }

  public static zx_ctx zx_init_ctx() {
    long cPtr = zxidjniJNI.zx_init_ctx();
    return (cPtr == 0) ? null : new zx_ctx(cPtr, false);
  }

  public static int zx_date_time_to_secs(String dt) {
    return zxidjniJNI.zx_date_time_to_secs(dt);
  }

  public static int write2_or_append_lock_c_path(String c_path, int len1, String data1, int len2, String data2, String which, int seeky, int flag) {
    return zxidjniJNI.write2_or_append_lock_c_path(c_path, len1, data1, len2, data2, which, seeky, flag);
  }

  public static int zx_report_openssl_error(String logkey) {
    return zxidjniJNI.zx_report_openssl_error(logkey);
  }

  public static void zx_fix_any_elem_dec(zx_ctx c, zx_any_elem_s x, String nam, int namlen) {
    zxidjniJNI.zx_fix_any_elem_dec(zx_ctx.getCPtr(c), zx_any_elem_s.getCPtr(x), nam, namlen);
  }

  public static zx_ns_s zx_locate_ns_by_prefix(zx_ctx c, int len, String prefix) {
    long cPtr = zxidjniJNI.zx_locate_ns_by_prefix(zx_ctx.getCPtr(c), len, prefix);
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

  public static int zx_is_ns_prefix(zx_ns_s ns, int len, String prefix) {
    return zxidjniJNI.zx_is_ns_prefix(zx_ns_s.getCPtr(ns), len, prefix);
  }

  public static zx_ns_s zx_prefix_seen(zx_ctx c, int len, String prefix) {
    long cPtr = zxidjniJNI.zx_prefix_seen(zx_ctx.getCPtr(c), len, prefix);
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

  public static zx_ns_s zx_prefix_seen_whine(zx_ctx c, int len, String prefix, String logkey, int mk_dummy_ns) {
    long cPtr = zxidjniJNI.zx_prefix_seen_whine(zx_ctx.getCPtr(c), len, prefix, logkey, mk_dummy_ns);
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

  public static zx_ns_s zx_scan_xmlns(zx_ctx c) {
    long cPtr = zxidjniJNI.zx_scan_xmlns(zx_ctx.getCPtr(c));
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

  public static void zx_pop_seen(zx_ns_s ns) {
    zxidjniJNI.zx_pop_seen(zx_ns_s.getCPtr(ns));
  }

  public static zx_str zx_raw_cipher(zx_ctx c, String algo, int encp, zx_str key, int len, int iv_len, String iv) {
    long cPtr = zxidjniJNI.zx_raw_cipher(zx_ctx.getCPtr(c), algo, encp, zx_str.getCPtr(key), len, iv_len, iv);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str zx_rsa_pub_enc(zx_ctx c, zx_str plain, SWIGTYPE_p_p_void rsa_pkey, int pad) {
    long cPtr = zxidjniJNI.zx_rsa_pub_enc(zx_ctx.getCPtr(c), zx_str.getCPtr(plain), SWIGTYPE_p_p_void.getCPtr(rsa_pkey), pad);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str zx_rsa_pub_dec(zx_ctx c, zx_str ciphered, SWIGTYPE_p_p_void rsa_pkey, int pad) {
    long cPtr = zxidjniJNI.zx_rsa_pub_dec(zx_ctx.getCPtr(c), zx_str.getCPtr(ciphered), SWIGTYPE_p_p_void.getCPtr(rsa_pkey), pad);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str zx_rsa_priv_dec(zx_ctx c, zx_str ciphered, SWIGTYPE_p_p_void rsa_pkey, int pad) {
    long cPtr = zxidjniJNI.zx_rsa_priv_dec(zx_ctx.getCPtr(c), zx_str.getCPtr(ciphered), SWIGTYPE_p_p_void.getCPtr(rsa_pkey), pad);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str zx_rsa_priv_enc(zx_ctx c, zx_str plain, SWIGTYPE_p_p_void rsa_pkey, int pad) {
    long cPtr = zxidjniJNI.zx_rsa_priv_enc(zx_ctx.getCPtr(c), zx_str.getCPtr(plain), SWIGTYPE_p_p_void.getCPtr(rsa_pkey), pad);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static SWIGTYPE_p_p_void zx_get_rsa_pub_from_cert(SWIGTYPE_p_X509 cert, String logkey) {
    long cPtr = zxidjniJNI.zx_get_rsa_pub_from_cert(SWIGTYPE_p_X509.getCPtr(cert), logkey);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public static void zx_rand(String buf, int n_bytes) {
    zxidjniJNI.zx_rand(buf, n_bytes);
  }

  public static String zx_md5_crypt(String pw, String salt, String buf) {
    return zxidjniJNI.zx_md5_crypt(pw, salt, buf);
  }

  public static zx_tok zx_tok_by_ns(zx_tok zt, zx_tok lim, int len, String name, zx_ns_s ns) {
    long cPtr = zxidjniJNI.zx_tok_by_ns(zx_tok.getCPtr(zt), zx_tok.getCPtr(lim), len, name, zx_ns_s.getCPtr(ns));
    return (cPtr == 0) ? null : new zx_tok(cPtr, false);
  }

  public static int zx_len_xmlns_if_not_seen(zx_ctx c, zx_ns_s ns, SWIGTYPE_p_p_zx_ns_s pop_seen) {
    return zxidjniJNI.zx_len_xmlns_if_not_seen(zx_ctx.getCPtr(c), zx_ns_s.getCPtr(ns), SWIGTYPE_p_p_zx_ns_s.getCPtr(pop_seen));
  }

  public static String zx_enc_xmlns_if_not_seen(zx_ctx c, String p, zx_ns_s ns, SWIGTYPE_p_p_zx_ns_s pop_seen) {
    return zxidjniJNI.zx_enc_xmlns_if_not_seen(zx_ctx.getCPtr(c), p, zx_ns_s.getCPtr(ns), SWIGTYPE_p_p_zx_ns_s.getCPtr(pop_seen));
  }

  public static void zx_add_xmlns_if_not_seen(zx_ctx c, zx_ns_s ns, SWIGTYPE_p_p_zx_ns_s pop_seen) {
    zxidjniJNI.zx_add_xmlns_if_not_seen(zx_ctx.getCPtr(c), zx_ns_s.getCPtr(ns), SWIGTYPE_p_p_zx_ns_s.getCPtr(pop_seen));
  }

  public static String zx_enc_seen(String p, zx_ns_s ns) {
    return zxidjniJNI.zx_enc_seen(p, zx_ns_s.getCPtr(ns));
  }

  public static int zx_len_so_common(zx_ctx c, zx_elem_s x) {
    return zxidjniJNI.zx_len_so_common(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(x));
  }

  public static int zx_len_wo_common(zx_ctx c, zx_elem_s x) {
    return zxidjniJNI.zx_len_wo_common(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(x));
  }

  public static String zx_enc_unknown_attrs(String p, zx_any_attr_s aa) {
    return zxidjniJNI.zx_enc_unknown_attrs(p, zx_any_attr_s.getCPtr(aa));
  }

  public static String zx_enc_so_unknown_elems_and_content(zx_ctx c, String p, zx_elem_s x) {
    return zxidjniJNI.zx_enc_so_unknown_elems_and_content(zx_ctx.getCPtr(c), p, zx_elem_s.getCPtr(x));
  }

  public static zx_str zx_easy_enc_common(zx_ctx c, String p, String buf, int len) {
    long cPtr = zxidjniJNI.zx_easy_enc_common(zx_ctx.getCPtr(c), p, buf, len);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int zx_attr_so_len(zx_str attr, int name_size) {
    return zxidjniJNI.zx_attr_so_len(zx_str.getCPtr(attr), name_size);
  }

  public static String zx_attr_so_enc(String p, zx_str attr, String name, int name_len) {
    return zxidjniJNI.zx_attr_so_enc(p, zx_str.getCPtr(attr), name, name_len);
  }

  public static int zx_attr_wo_len(zx_str attr, int name_size) {
    return zxidjniJNI.zx_attr_wo_len(zx_str.getCPtr(attr), name_size);
  }

  public static String zx_attr_wo_enc(String p, zx_str attr, String name, int name_len) {
    return zxidjniJNI.zx_attr_wo_enc(p, zx_str.getCPtr(attr), name, name_len);
  }

  public static void zx_free_attr(zx_ctx c, zx_str attr, int free_strs) {
    zxidjniJNI.zx_free_attr(zx_ctx.getCPtr(c), zx_str.getCPtr(attr), free_strs);
  }

  public static void zx_free_elem_common(zx_ctx c, zx_elem_s x, int free_strs) {
    zxidjniJNI.zx_free_elem_common(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(x), free_strs);
  }

  public static void zx_free_simple_elems(zx_ctx c, zx_elem_s se, int free_strs) {
    zxidjniJNI.zx_free_simple_elems(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(se), free_strs);
  }

  public static void zx_prepare_dec_ctx(zx_ctx c, zx_ns_s ns_tab, String start, String lim) {
    zxidjniJNI.zx_prepare_dec_ctx(zx_ctx.getCPtr(c), zx_ns_s.getCPtr(ns_tab), start, lim);
  }

  public static int zx_scan_data(zx_ctx c, zx_elem_s el) {
    return zxidjniJNI.zx_scan_data(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(el));
  }

  public static int zx_scan_pi_or_comment(zx_ctx c) {
    return zxidjniJNI.zx_scan_pi_or_comment(zx_ctx.getCPtr(c));
  }

  public static zx_str zx_dec_unknown_attr(zx_ctx c, zx_elem_s el, String name, String data, int tok, int ctx_tok) {
    long cPtr = zxidjniJNI.zx_dec_unknown_attr(zx_ctx.getCPtr(c), zx_elem_s.getCPtr(el), name, data, tok, ctx_tok);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static String zx_dec_attr_val(zx_ctx c, SWIGTYPE_p_p_char name) {
    return zxidjniJNI.zx_dec_attr_val(zx_ctx.getCPtr(c), SWIGTYPE_p_p_char.getCPtr(name));
  }

  public static void zx_xml_parse_err(zx_ctx c, char quote, String func, String msg) {
    zxidjniJNI.zx_xml_parse_err(zx_ctx.getCPtr(c), quote, func, msg);
  }

  public static int zx_len_inc_ns(zx_ctx c, SWIGTYPE_p_p_zx_ns_s pop_seenp) {
    return zxidjniJNI.zx_len_inc_ns(zx_ctx.getCPtr(c), SWIGTYPE_p_p_zx_ns_s.getCPtr(pop_seenp));
  }

  public static void zx_add_inc_ns(zx_ctx c, SWIGTYPE_p_p_zx_ns_s pop_seenp) {
    zxidjniJNI.zx_add_inc_ns(zx_ctx.getCPtr(c), SWIGTYPE_p_p_zx_ns_s.getCPtr(pop_seenp));
  }

  public static String zx_enc_inc_ns(zx_ctx c, String p, SWIGTYPE_p_p_zx_ns_s pop_seenp) {
    return zxidjniJNI.zx_enc_inc_ns(zx_ctx.getCPtr(c), p, SWIGTYPE_p_p_zx_ns_s.getCPtr(pop_seenp));
  }

  public static String simple(String conf, String qs, int auto_flags) {
    return zxidjniJNI.zxid_simple(conf, qs, auto_flags);
  }

  public static String idp_list(String conf, int auto_flags) {
    return zxidjniJNI.zxid_idp_list(conf, auto_flags);
  }

  public static String idp_select(String conf, int auto_flags) {
    return zxidjniJNI.zxid_idp_select(conf, auto_flags);
  }

  public static String fed_mgmt(String conf, String sid, int auto_flags) {
    return zxidjniJNI.zxid_fed_mgmt(conf, sid, auto_flags);
  }

  public static zxid_conf new_conf_to_cf(String conf) {
    long cPtr = zxidjniJNI.zxid_new_conf_to_cf(conf);
    return (cPtr == 0) ? null : new zxid_conf(cPtr, false);
  }

  public static String simple_cf(zxid_conf cf, int qs_len, String qs, SWIGTYPE_p_int res_len, int auto_flags) {
    return zxidjniJNI.zxid_simple_cf(zxid_conf.getCPtr(cf), qs_len, qs, SWIGTYPE_p_int.getCPtr(res_len), auto_flags);
  }

  public static String idp_list_cf(zxid_conf cf, SWIGTYPE_p_int res_len, int auto_flags) {
    return zxidjniJNI.zxid_idp_list_cf(zxid_conf.getCPtr(cf), SWIGTYPE_p_int.getCPtr(res_len), auto_flags);
  }

  public static String idp_select_cf(zxid_conf cf, SWIGTYPE_p_int res_len, int auto_flags) {
    return zxidjniJNI.zxid_idp_select_cf(zxid_conf.getCPtr(cf), SWIGTYPE_p_int.getCPtr(res_len), auto_flags);
  }

  public static String fed_mgmt_cf(zxid_conf cf, SWIGTYPE_p_int res_len, int sid_len, String sid, int auto_flags) {
    return zxidjniJNI.zxid_fed_mgmt_cf(zxid_conf.getCPtr(cf), SWIGTYPE_p_int.getCPtr(res_len), sid_len, sid, auto_flags);
  }

  public static int conf_to_cf_len(zxid_conf cf, int conf_len, String conf) {
    return zxidjniJNI.zxid_conf_to_cf_len(zxid_conf.getCPtr(cf), conf_len, conf);
  }

  public static String simple_len(int conf_len, String conf, int qs_len, String qs, SWIGTYPE_p_int res_len, int auto_flags) {
    return zxidjniJNI.zxid_simple_len(conf_len, conf, qs_len, qs, SWIGTYPE_p_int.getCPtr(res_len), auto_flags);
  }

  public static String idp_list_len(int conf_len, String conf, SWIGTYPE_p_int res_len, int auto_flags) {
    return zxidjniJNI.zxid_idp_list_len(conf_len, conf, SWIGTYPE_p_int.getCPtr(res_len), auto_flags);
  }

  public static String idp_select_len(int conf_len, String conf, SWIGTYPE_p_int res_len, int auto_flags) {
    return zxidjniJNI.zxid_idp_select_len(conf_len, conf, SWIGTYPE_p_int.getCPtr(res_len), auto_flags);
  }

  public static String fed_mgmt_len(int conf_len, String conf, SWIGTYPE_p_int res_len, String sid, int auto_flags) {
    return zxidjniJNI.zxid_fed_mgmt_len(conf_len, conf, SWIGTYPE_p_int.getCPtr(res_len), sid, auto_flags);
  }

  public static zx_str idp_select_zxstr_cf(zxid_conf cf, int auto_flags) {
    long cPtr = zxidjniJNI.zxid_idp_select_zxstr_cf(zxid_conf.getCPtr(cf), auto_flags);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static String simple_ab_pep(zxid_conf cf, zxid_ses ses, SWIGTYPE_p_int res_len, int auto_flags) {
    return zxidjniJNI.zxid_simple_ab_pep(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), SWIGTYPE_p_int.getCPtr(res_len), auto_flags);
  }

  public static String simple_ses_active_cf(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, SWIGTYPE_p_int res_len, int auto_flags) {
    return zxidjniJNI.zxid_simple_ses_active_cf(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), SWIGTYPE_p_int.getCPtr(res_len), auto_flags);
  }

  public static String simple_no_ses_cf(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, SWIGTYPE_p_int res_len, int auto_flags) {
    return zxidjniJNI.zxid_simple_no_ses_cf(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), SWIGTYPE_p_int.getCPtr(res_len), auto_flags);
  }

  public static SWIGTYPE_p_zx_ds_Signature_s zxsig_sign(zx_ctx c, int n, zxsig_ref sref, SWIGTYPE_p_X509 cert, SWIGTYPE_p_p_void priv_key) {
    long cPtr = zxidjniJNI.zxsig_sign(zx_ctx.getCPtr(c), n, zxsig_ref.getCPtr(sref), SWIGTYPE_p_X509.getCPtr(cert), SWIGTYPE_p_p_void.getCPtr(priv_key));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_ds_Signature_s(cPtr, false);
  }

  public static int zxsig_validate(zx_ctx c, SWIGTYPE_p_X509 cert, SWIGTYPE_p_zx_ds_Signature_s sig, int n, zxsig_ref refs) {
    return zxidjniJNI.zxsig_validate(zx_ctx.getCPtr(c), SWIGTYPE_p_X509.getCPtr(cert), SWIGTYPE_p_zx_ds_Signature_s.getCPtr(sig), n, zxsig_ref.getCPtr(refs));
  }

  public static int zxsig_data_rsa_sha1(zx_ctx c, int len, String d, SWIGTYPE_p_p_char sig, SWIGTYPE_p_p_void priv_key, String lk) {
    return zxidjniJNI.zxsig_data_rsa_sha1(zx_ctx.getCPtr(c), len, d, SWIGTYPE_p_p_char.getCPtr(sig), SWIGTYPE_p_p_void.getCPtr(priv_key), lk);
  }

  public static int zxsig_verify_data_rsa_sha1(int len, String data, int siglen, String sig, SWIGTYPE_p_X509 cert, String lk) {
    return zxidjniJNI.zxsig_verify_data_rsa_sha1(len, data, siglen, sig, SWIGTYPE_p_X509.getCPtr(cert), lk);
  }

  public static zx_str zxenc_symkey_dec(zxid_conf cf, SWIGTYPE_p_zx_xenc_EncryptedData_s ed, zx_str symkey) {
    long cPtr = zxidjniJNI.zxenc_symkey_dec(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_xenc_EncryptedData_s.getCPtr(ed), zx_str.getCPtr(symkey));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str zxenc_privkey_dec(zxid_conf cf, SWIGTYPE_p_zx_xenc_EncryptedData_s ed, SWIGTYPE_p_zx_xenc_EncryptedKey_s ek) {
    long cPtr = zxidjniJNI.zxenc_privkey_dec(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_xenc_EncryptedData_s.getCPtr(ed), SWIGTYPE_p_zx_xenc_EncryptedKey_s.getCPtr(ek));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static SWIGTYPE_p_zx_xenc_EncryptedData_s zxenc_symkey_enc(zxid_conf cf, zx_str data, zx_str ed_id, zx_str symkey, zx_str symkey_id) {
    long cPtr = zxidjniJNI.zxenc_symkey_enc(zxid_conf.getCPtr(cf), zx_str.getCPtr(data), zx_str.getCPtr(ed_id), zx_str.getCPtr(symkey), zx_str.getCPtr(symkey_id));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_xenc_EncryptedData_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_xenc_EncryptedData_s zxenc_pubkey_enc(zxid_conf cf, zx_str data, SWIGTYPE_p_p_zx_xenc_EncryptedKey_s ekp, SWIGTYPE_p_X509 cert, String idsuffix) {
    long cPtr = zxidjniJNI.zxenc_pubkey_enc(zxid_conf.getCPtr(cf), zx_str.getCPtr(data), SWIGTYPE_p_p_zx_xenc_EncryptedKey_s.getCPtr(ekp), SWIGTYPE_p_X509.getCPtr(cert), idsuffix);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_xenc_EncryptedData_s(cPtr, false);
  }

  public static void zxlog_write_line(zxid_conf cf, String c_path, int encflags, int n, String logbuf) {
    zxidjniJNI.zxlog_write_line(zxid_conf.getCPtr(cf), c_path, encflags, n, logbuf);
  }

  public static zx_str zxlog_path(zxid_conf cf, zx_str entid, zx_str objid, String dir, String kind, int create_dirs) {
    long cPtr = zxidjniJNI.zxlog_path(zxid_conf.getCPtr(cf), zx_str.getCPtr(entid), zx_str.getCPtr(objid), dir, kind, create_dirs);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int zxlog_dup_check(zxid_conf cf, zx_str path, String logkey) {
    return zxidjniJNI.zxlog_dup_check(zxid_conf.getCPtr(cf), zx_str.getCPtr(path), logkey);
  }

  public static int zxlog_blob(zxid_conf cf, int logflag, zx_str path, zx_str blob, String lk) {
    return zxidjniJNI.zxlog_blob(zxid_conf.getCPtr(cf), logflag, zx_str.getCPtr(path), zx_str.getCPtr(blob), lk);
  }

  public static int zxlog(zxid_conf cf, SWIGTYPE_p_timeval ourts, SWIGTYPE_p_timeval srcts, String ipport, zx_str entid, zx_str msgid, zx_str a7nid, zx_str nid, String sigval, String res, String op, String arg, String fmt) {
    return zxidjniJNI.zxlog(zxid_conf.getCPtr(cf), SWIGTYPE_p_timeval.getCPtr(ourts), SWIGTYPE_p_timeval.getCPtr(srcts), ipport, zx_str.getCPtr(entid), zx_str.getCPtr(msgid), zx_str.getCPtr(a7nid), zx_str.getCPtr(nid), sigval, res, op, arg, fmt);
  }

  public static zxid_entity get_ent_from_file(zxid_conf cf, String sha1_name) {
    long cPtr = zxidjniJNI.zxid_get_ent_from_file(zxid_conf.getCPtr(cf), sha1_name);
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity get_ent_from_cache(zxid_conf cf, zx_str eid) {
    long cPtr = zxidjniJNI.zxid_get_ent_from_cache(zxid_conf.getCPtr(cf), zx_str.getCPtr(eid));
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static int write_ent_to_cache(zxid_conf cf, zxid_entity ent) {
    return zxidjniJNI.zxid_write_ent_to_cache(zxid_conf.getCPtr(cf), zxid_entity.getCPtr(ent));
  }

  public static zxid_entity parse_meta(zxid_conf cf, SWIGTYPE_p_p_char md, String lim) {
    long cPtr = zxidjniJNI.zxid_parse_meta(zxid_conf.getCPtr(cf), SWIGTYPE_p_p_char.getCPtr(md), lim);
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity get_meta_ss(zxid_conf cf, zx_str url) {
    long cPtr = zxidjniJNI.zxid_get_meta_ss(zxid_conf.getCPtr(cf), zx_str.getCPtr(url));
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity get_meta(zxid_conf cf, String url) {
    long cPtr = zxidjniJNI.zxid_get_meta(zxid_conf.getCPtr(cf), url);
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity get_ent_ss(zxid_conf cf, zx_str eid) {
    long cPtr = zxidjniJNI.zxid_get_ent_ss(zxid_conf.getCPtr(cf), zx_str.getCPtr(eid));
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity get_ent(zxid_conf cf, String eid) {
    long cPtr = zxidjniJNI.zxid_get_ent(zxid_conf.getCPtr(cf), eid);
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity get_ent_by_succinct_id(zxid_conf cf, String raw_succinct_id) {
    long cPtr = zxidjniJNI.zxid_get_ent_by_succinct_id(zxid_conf.getCPtr(cf), raw_succinct_id);
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity get_ent_by_sha1_name(zxid_conf cf, String sha1_name) {
    long cPtr = zxidjniJNI.zxid_get_ent_by_sha1_name(zxid_conf.getCPtr(cf), sha1_name);
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static zxid_entity load_cot_cache(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_load_cot_cache(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static SWIGTYPE_p_zx_ds_KeyInfo_s key_info(zxid_conf cf, SWIGTYPE_p_X509 x) {
    long cPtr = zxidjniJNI.zxid_key_info(zxid_conf.getCPtr(cf), SWIGTYPE_p_X509.getCPtr(x));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_ds_KeyInfo_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_md_KeyDescriptor_s key_desc(zxid_conf cf, String use, SWIGTYPE_p_X509 cert) {
    long cPtr = zxidjniJNI.zxid_key_desc(zxid_conf.getCPtr(cf), use, SWIGTYPE_p_X509.getCPtr(cert));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_md_KeyDescriptor_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_md_ArtifactResolutionService_s ar_desc(zxid_conf cf, String binding, String loc, String resp_loc) {
    long cPtr = zxidjniJNI.zxid_ar_desc(zxid_conf.getCPtr(cf), binding, loc, resp_loc);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_md_ArtifactResolutionService_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_md_SingleSignOnService_s sso_desc(zxid_conf cf, String binding, String loc, String resp_loc) {
    long cPtr = zxidjniJNI.zxid_sso_desc(zxid_conf.getCPtr(cf), binding, loc, resp_loc);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_md_SingleSignOnService_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_md_SingleLogoutService_s slo_desc(zxid_conf cf, String binding, String loc, String resp_loc) {
    long cPtr = zxidjniJNI.zxid_slo_desc(zxid_conf.getCPtr(cf), binding, loc, resp_loc);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_md_SingleLogoutService_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_md_ManageNameIDService_s mni_desc(zxid_conf cf, String binding, String loc, String resp_loc) {
    long cPtr = zxidjniJNI.zxid_mni_desc(zxid_conf.getCPtr(cf), binding, loc, resp_loc);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_md_ManageNameIDService_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_md_AssertionConsumerService_s ac_desc(zxid_conf cf, String binding, String loc, String index) {
    long cPtr = zxidjniJNI.zxid_ac_desc(zxid_conf.getCPtr(cf), binding, loc, index);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_md_AssertionConsumerService_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_md_IDPSSODescriptor_s idp_sso_desc(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_idp_sso_desc(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_md_IDPSSODescriptor_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_md_SPSSODescriptor_s sp_sso_desc(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_sp_sso_desc(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_md_SPSSODescriptor_s(cPtr, false);
  }

  public static zx_str sp_meta(zxid_conf cf, zxid_cgi cgi) {
    long cPtr = zxidjniJNI.zxid_sp_meta(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int send_sp_meta(zxid_conf cf, zxid_cgi cgi) {
    return zxidjniJNI.zxid_send_sp_meta(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
  }

  public static zx_str sp_carml(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_sp_carml(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str my_entity_id(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_my_entity_id(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str my_cdc_url(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_my_cdc_url(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sa_Issuer_s my_issuer(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_my_issuer(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_Issuer_s(cPtr, false);
  }

  public static void sha1_file(zxid_conf cf, String name, String sha1) {
    zxidjniJNI.zxid_sha1_file(zxid_conf.getCPtr(cf), name, sha1);
  }

  public static SWIGTYPE_p_X509 extract_cert(String buf, String name) {
    long cPtr = zxidjniJNI.zxid_extract_cert(buf, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_X509(cPtr, false);
  }

  public static SWIGTYPE_p_p_void extract_private_key(String buf, String name) {
    long cPtr = zxidjniJNI.zxid_extract_private_key(buf, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_X509 read_cert(zxid_conf cf, String name) {
    long cPtr = zxidjniJNI.zxid_read_cert(zxid_conf.getCPtr(cf), name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_X509(cPtr, false);
  }

  public static SWIGTYPE_p_p_void read_private_key(zxid_conf cf, String name) {
    long cPtr = zxidjniJNI.zxid_read_private_key(zxid_conf.getCPtr(cf), name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public static int set_opt(zxid_conf cf, int which, int val) {
    return zxidjniJNI.zxid_set_opt(zxid_conf.getCPtr(cf), which, val);
  }

  public static void url_set(zxid_conf cf, String url) {
    zxidjniJNI.zxid_url_set(zxid_conf.getCPtr(cf), url);
  }

  public static int init_conf(zxid_conf cf, String conf_dir) {
    return zxidjniJNI.zxid_init_conf(zxid_conf.getCPtr(cf), conf_dir);
  }

  public static zxid_conf init_conf_ctx(zxid_conf cf, String zxid_path) {
    long cPtr = zxidjniJNI.zxid_init_conf_ctx(zxid_conf.getCPtr(cf), zxid_path);
    return (cPtr == 0) ? null : new zxid_conf(cPtr, false);
  }

  public static zxid_conf new_conf(String zxid_path) {
    long cPtr = zxidjniJNI.zxid_new_conf(zxid_path);
    return (cPtr == 0) ? null : new zxid_conf(cPtr, false);
  }

  public static int parse_conf_raw(zxid_conf cf, int qs_len, String qs) {
    return zxidjniJNI.zxid_parse_conf_raw(zxid_conf.getCPtr(cf), qs_len, qs);
  }

  public static int parse_conf(zxid_conf cf, String qs) {
    return zxidjniJNI.zxid_parse_conf(zxid_conf.getCPtr(cf), qs);
  }

  public static int mk_self_sig_cert(zxid_conf cf, int buflen, String buf, String lk, String name) {
    return zxidjniJNI.zxid_mk_self_sig_cert(zxid_conf.getCPtr(cf), buflen, buf, lk, name);
  }

  public static zxid_map load_map(zxid_conf cf, zxid_map map, String v) {
    long cPtr = zxidjniJNI.zxid_load_map(zxid_conf.getCPtr(cf), zxid_map.getCPtr(map), v);
    return (cPtr == 0) ? null : new zxid_map(cPtr, false);
  }

  public static zxid_need load_need(zxid_conf cf, zxid_need need, String v) {
    long cPtr = zxidjniJNI.zxid_load_need(zxid_conf.getCPtr(cf), zxid_need.getCPtr(need), v);
    return (cPtr == 0) ? null : new zxid_need(cPtr, false);
  }

  public static zxid_atsrc load_atsrc(zxid_conf cf, zxid_atsrc atsrc, String v) {
    long cPtr = zxidjniJNI.zxid_load_atsrc(zxid_conf.getCPtr(cf), zxid_atsrc.getCPtr(atsrc), v);
    return (cPtr == 0) ? null : new zxid_atsrc(cPtr, false);
  }

  public static zxid_attr new_at(zxid_conf cf, zxid_attr at, int name_len, String name, int val_len, String val, String lk) {
    long cPtr = zxidjniJNI.zxid_new_at(zxid_conf.getCPtr(cf), zxid_attr.getCPtr(at), name_len, name, val_len, val, lk);
    return (cPtr == 0) ? null : new zxid_attr(cPtr, false);
  }

  public static zxid_cstr_list load_cstr_list(zxid_conf cf, zxid_cstr_list lst, String v) {
    long cPtr = zxidjniJNI.zxid_load_cstr_list(zxid_conf.getCPtr(cf), zxid_cstr_list.getCPtr(lst), v);
    return (cPtr == 0) ? null : new zxid_cstr_list(cPtr, false);
  }

  public static zxid_need is_needed(zxid_need need, String name) {
    long cPtr = zxidjniJNI.zxid_is_needed(zxid_need.getCPtr(need), name);
    return (cPtr == 0) ? null : new zxid_need(cPtr, false);
  }

  public static zxid_map find_map(zxid_map map, String name) {
    long cPtr = zxidjniJNI.zxid_find_map(zxid_map.getCPtr(map), name);
    return (cPtr == 0) ? null : new zxid_map(cPtr, false);
  }

  public static zxid_cstr_list find_cstr_list(zxid_cstr_list lst, String name) {
    long cPtr = zxidjniJNI.zxid_find_cstr_list(zxid_cstr_list.getCPtr(lst), name);
    return (cPtr == 0) ? null : new zxid_cstr_list(cPtr, false);
  }

  public static zxid_attr find_at(zxid_attr pool, String name) {
    long cPtr = zxidjniJNI.zxid_find_at(zxid_attr.getCPtr(pool), name);
    return (cPtr == 0) ? null : new zxid_attr(cPtr, false);
  }

  public static int parse_cgi(zxid_cgi cgi, String qs) {
    return zxidjniJNI.zxid_parse_cgi(zxid_cgi.getCPtr(cgi), qs);
  }

  public static zxid_cgi new_cgi(zxid_conf cf, String qs) {
    long cPtr = zxidjniJNI.zxid_new_cgi(zxid_conf.getCPtr(cf), qs);
    return (cPtr == 0) ? null : new zxid_cgi(cPtr, false);
  }

  public static void get_sid_from_cookie(zxid_conf cf, zxid_cgi cgi, String cookie) {
    zxidjniJNI.zxid_get_sid_from_cookie(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), cookie);
  }

  public static zxid_ses alloc_ses(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_alloc_ses(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new zxid_ses(cPtr, false);
  }

  public static zxid_ses fetch_ses(zxid_conf cf, String sid) {
    long cPtr = zxidjniJNI.zxid_fetch_ses(zxid_conf.getCPtr(cf), sid);
    return (cPtr == 0) ? null : new zxid_ses(cPtr, false);
  }

  public static int get_ses(zxid_conf cf, zxid_ses ses, String sid) {
    return zxidjniJNI.zxid_get_ses(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), sid);
  }

  public static int put_ses(zxid_conf cf, zxid_ses ses) {
    return zxidjniJNI.zxid_put_ses(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses));
  }

  public static int del_ses(zxid_conf cf, zxid_ses ses) {
    return zxidjniJNI.zxid_del_ses(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses));
  }

  public static int get_ses_sso_a7n(zxid_conf cf, zxid_ses ses) {
    return zxidjniJNI.zxid_get_ses_sso_a7n(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses));
  }

  public static zxid_entity get_ses_idp(zxid_conf cf, zxid_ses ses) {
    long cPtr = zxidjniJNI.zxid_get_ses_idp(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses));
    return (cPtr == 0) ? null : new zxid_entity(cPtr, false);
  }

  public static int find_ses(zxid_conf cf, zxid_ses ses, zx_str ses_ix, zx_str nid) {
    return zxidjniJNI.zxid_find_ses(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), zx_str.getCPtr(ses_ix), zx_str.getCPtr(nid));
  }

  public static zx_str pool_to_ldif(zxid_conf cf, zxid_attr pool) {
    long cPtr = zxidjniJNI.zxid_pool_to_ldif(zxid_conf.getCPtr(cf), zxid_attr.getCPtr(pool));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str pool_to_json(zxid_conf cf, zxid_attr pool) {
    long cPtr = zxidjniJNI.zxid_pool_to_json(zxid_conf.getCPtr(cf), zxid_attr.getCPtr(pool));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str pool_to_qs(zxid_conf cf, zxid_attr pool) {
    long cPtr = zxidjniJNI.zxid_pool_to_qs(zxid_conf.getCPtr(cf), zxid_attr.getCPtr(pool));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static void ses_to_pool(zxid_conf cf, zxid_ses ses) {
    zxidjniJNI.zxid_ses_to_pool(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses));
  }

  public static void add_attr_to_pool(zxid_conf cf, zxid_ses ses, String at_name, zx_str val) {
    zxidjniJNI.zxid_add_attr_to_pool(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), at_name, zx_str.getCPtr(val));
  }

  public static int add_qs_to_pool(zxid_conf cf, zxid_ses ses, String qs, int apply_map) {
    return zxidjniJNI.zxid_add_qs_to_pool(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), qs, apply_map);
  }

  public static SWIGTYPE_p_zx_sa_NameID_s parse_mni(zxid_conf cf, String buf, SWIGTYPE_p_p_char pmniptr) {
    long cPtr = zxidjniJNI.zxid_parse_mni(zxid_conf.getCPtr(cf), buf, SWIGTYPE_p_p_char.getCPtr(pmniptr));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_NameID_s(cPtr, false);
  }

  public static int put_user(zxid_conf cf, zx_str nidfmt, zx_str idpent, zx_str spqual, zx_str idpnid, String mniptr) {
    return zxidjniJNI.zxid_put_user(zxid_conf.getCPtr(cf), zx_str.getCPtr(nidfmt), zx_str.getCPtr(idpent), zx_str.getCPtr(spqual), zx_str.getCPtr(idpnid), mniptr);
  }

  public static SWIGTYPE_p_zx_sa_NameID_s get_user_nameid(zxid_conf cf, SWIGTYPE_p_zx_sa_NameID_s oldnid) {
    long cPtr = zxidjniJNI.zxid_get_user_nameid(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_sa_NameID_s.getCPtr(oldnid));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_NameID_s(cPtr, false);
  }

  public static void user_change_nameid(zxid_conf cf, SWIGTYPE_p_zx_sa_NameID_s oldnid, zx_str newnym) {
    zxidjniJNI.zxid_user_change_nameid(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_sa_NameID_s.getCPtr(oldnid), zx_str.getCPtr(newnym));
  }

  public static int pw_authn(zxid_conf cf, zxid_cgi cgi, zxid_ses ses) {
    return zxidjniJNI.zxid_pw_authn(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses));
  }

  public static int version() {
    return zxidjniJNI.zxid_version();
  }

  public static String version_str() {
    return zxidjniJNI.zxid_version_str();
  }

  public static zx_str date_time(zxid_conf cf, SWIGTYPE_p_time_t secs) {
    long cPtr = zxidjniJNI.zxid_date_time(zxid_conf.getCPtr(cf), SWIGTYPE_p_time_t.getCPtr(secs));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str mk_id(zxid_conf cf, String prefix, int bits) {
    long cPtr = zxidjniJNI.zxid_mk_id(zxid_conf.getCPtr(cf), prefix, bits);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static SWIGTYPE_p_zx_root_s soap_call_raw(zxid_conf cf, zx_str url, zx_str data) {
    long cPtr = zxidjniJNI.zxid_soap_call_raw(zxid_conf.getCPtr(cf), zx_str.getCPtr(url), zx_str.getCPtr(data));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_root_s(cPtr, false);
  }

  public static zx_str lecp_check(zxid_conf cf, zxid_cgi cgi) {
    long cPtr = zxidjniJNI.zxid_lecp_check(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int cdc_read(zxid_conf cf, zxid_cgi cgi) {
    return zxidjniJNI.zxid_cdc_read(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
  }

  public static int cdc_check(zxid_conf cf, zxid_cgi cgi) {
    return zxidjniJNI.zxid_cdc_check(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
  }

  public static SWIGTYPE_p_zx_root_s soap_call_envelope(zxid_conf cf, zx_str url, SWIGTYPE_p_zx_e_Envelope_s env) {
    long cPtr = zxidjniJNI.zxid_soap_call_envelope(zxid_conf.getCPtr(cf), zx_str.getCPtr(url), SWIGTYPE_p_zx_e_Envelope_s.getCPtr(env));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_root_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_root_s soap_call_hdr_body(zxid_conf cf, zx_str url, SWIGTYPE_p_zx_e_Header_s hdr, SWIGTYPE_p_zx_e_Body_s body) {
    long cPtr = zxidjniJNI.zxid_soap_call_hdr_body(zxid_conf.getCPtr(cf), zx_str.getCPtr(url), SWIGTYPE_p_zx_e_Header_s.getCPtr(hdr), SWIGTYPE_p_zx_e_Body_s.getCPtr(body));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_root_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_root_s soap_call_body(zxid_conf cf, zx_str url, SWIGTYPE_p_zx_e_Body_s body) {
    long cPtr = zxidjniJNI.zxid_soap_call_body(zxid_conf.getCPtr(cf), zx_str.getCPtr(url), SWIGTYPE_p_zx_e_Body_s.getCPtr(body));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_root_s(cPtr, false);
  }

  public static int soap_cgi_resp_body(zxid_conf cf, SWIGTYPE_p_zx_e_Body_s body) {
    return zxidjniJNI.zxid_soap_cgi_resp_body(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_e_Body_s.getCPtr(body));
  }

  public static zx_str saml2_post_enc(zxid_conf cf, String field, zx_str payload, String relay_state, int sign, zx_str action_url) {
    long cPtr = zxidjniJNI.zxid_saml2_post_enc(zxid_conf.getCPtr(cf), field, zx_str.getCPtr(payload), relay_state, sign, zx_str.getCPtr(action_url));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str saml2_redir_enc(zxid_conf cf, String cgivar, zx_str pay_load, String relay_state) {
    long cPtr = zxidjniJNI.zxid_saml2_redir_enc(zxid_conf.getCPtr(cf), cgivar, zx_str.getCPtr(pay_load), relay_state);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str saml2_redir_url(zxid_conf cf, zx_str loc, zx_str pay_load, String relay_state) {
    long cPtr = zxidjniJNI.zxid_saml2_redir_url(zxid_conf.getCPtr(cf), zx_str.getCPtr(loc), zx_str.getCPtr(pay_load), relay_state);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str saml2_redir(zxid_conf cf, zx_str loc, zx_str pay_load, String relay_state) {
    long cPtr = zxidjniJNI.zxid_saml2_redir(zxid_conf.getCPtr(cf), zx_str.getCPtr(loc), zx_str.getCPtr(pay_load), relay_state);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str saml2_resp_redir(zxid_conf cf, zx_str loc, zx_str pay_load, String relay_state) {
    long cPtr = zxidjniJNI.zxid_saml2_resp_redir(zxid_conf.getCPtr(cf), zx_str.getCPtr(loc), zx_str.getCPtr(pay_load), relay_state);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int saml_ok(zxid_conf cf, zxid_cgi cgi, SWIGTYPE_p_zx_sp_Status_s st, String what) {
    return zxidjniJNI.zxid_saml_ok(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), SWIGTYPE_p_zx_sp_Status_s.getCPtr(st), what);
  }

  public static SWIGTYPE_p_zx_sa_NameID_s decrypt_nameid(zxid_conf cf, SWIGTYPE_p_zx_sa_NameID_s nid, SWIGTYPE_p_zx_sa_EncryptedID_s encid) {
    long cPtr = zxidjniJNI.zxid_decrypt_nameid(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_sa_NameID_s.getCPtr(nid), SWIGTYPE_p_zx_sa_EncryptedID_s.getCPtr(encid));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_NameID_s(cPtr, false);
  }

  public static zx_str decrypt_newnym(zxid_conf cf, zx_str newnym, SWIGTYPE_p_zx_sp_NewEncryptedID_s encid) {
    long cPtr = zxidjniJNI.zxid_decrypt_newnym(zxid_conf.getCPtr(cf), zx_str.getCPtr(newnym), SWIGTYPE_p_zx_sp_NewEncryptedID_s.getCPtr(encid));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int chk_sig(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, zx_elem_s elem, SWIGTYPE_p_zx_ds_Signature_s sig, SWIGTYPE_p_zx_sa_Issuer_s issue_ent, String lk) {
    return zxidjniJNI.zxid_chk_sig(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), zx_elem_s.getCPtr(elem), SWIGTYPE_p_zx_ds_Signature_s.getCPtr(sig), SWIGTYPE_p_zx_sa_Issuer_s.getCPtr(issue_ent), lk);
  }

  public static zx_str map_val(zxid_conf cf, zxid_map map, zx_str val) {
    long cPtr = zxidjniJNI.zxid_map_val(zxid_conf.getCPtr(cf), zxid_map.getCPtr(map), zx_str.getCPtr(val));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str idp_loc_raw(zxid_conf cf, zxid_cgi cgi, zxid_entity idp_meta, int svc_type, String binding, int req) {
    long cPtr = zxidjniJNI.zxid_idp_loc_raw(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_entity.getCPtr(idp_meta), svc_type, binding, req);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str idp_loc(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, zxid_entity idp_meta, int svc_type, String binding) {
    long cPtr = zxidjniJNI.zxid_idp_loc(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), zxid_entity.getCPtr(idp_meta), svc_type, binding);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static SWIGTYPE_p_zx_root_s idp_soap(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, zxid_entity idp_meta, int svc_type, SWIGTYPE_p_zx_e_Body_s body) {
    long cPtr = zxidjniJNI.zxid_idp_soap(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), zxid_entity.getCPtr(idp_meta), svc_type, SWIGTYPE_p_zx_e_Body_s.getCPtr(body));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_root_s(cPtr, false);
  }

  public static zx_str sp_loc_by_index_raw(zxid_conf cf, zxid_cgi cgi, zxid_entity sp_meta, int svc_type, zx_str ix, SWIGTYPE_p_int binding) {
    long cPtr = zxidjniJNI.zxid_sp_loc_by_index_raw(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_entity.getCPtr(sp_meta), svc_type, zx_str.getCPtr(ix), SWIGTYPE_p_int.getCPtr(binding));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str sp_loc_raw(zxid_conf cf, zxid_cgi cgi, zxid_entity sp_meta, int svc_type, String binding, int req) {
    long cPtr = zxidjniJNI.zxid_sp_loc_raw(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_entity.getCPtr(sp_meta), svc_type, binding, req);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str sp_loc(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, zxid_entity sp_meta, int svc_type, String binding) {
    long cPtr = zxidjniJNI.zxid_sp_loc(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), zxid_entity.getCPtr(sp_meta), svc_type, binding);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static SWIGTYPE_p_zx_root_s sp_soap(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, zxid_entity sp_meta, int svc_type, SWIGTYPE_p_zx_e_Body_s body) {
    long cPtr = zxidjniJNI.zxid_sp_soap(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), zxid_entity.getCPtr(sp_meta), svc_type, SWIGTYPE_p_zx_e_Body_s.getCPtr(body));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_root_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_root_s decode_redir_or_post(zxid_conf cf, zxid_cgi cgi, zxid_ses ses) {
    long cPtr = zxidjniJNI.zxid_decode_redir_or_post(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_root_s(cPtr, false);
  }

  public static zx_str sp_dispatch(zxid_conf cf, zxid_cgi cgi, zxid_ses ses) {
    long cPtr = zxidjniJNI.zxid_sp_dispatch(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int sp_soap_dispatch(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, SWIGTYPE_p_zx_root_s r) {
    return zxidjniJNI.zxid_sp_soap_dispatch(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), SWIGTYPE_p_zx_root_s.getCPtr(r));
  }

  public static int sp_soap_parse(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, int len, String buf) {
    return zxidjniJNI.zxid_sp_soap_parse(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), len, buf);
  }

  public static zx_str idp_dispatch(zxid_conf cf, zxid_cgi cgi, zxid_ses ses) {
    long cPtr = zxidjniJNI.zxid_idp_dispatch(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int idp_soap_dispatch(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, SWIGTYPE_p_zx_root_s r) {
    return zxidjniJNI.zxid_idp_soap_dispatch(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), SWIGTYPE_p_zx_root_s.getCPtr(r));
  }

  public static int idp_soap_parse(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, int len, String buf) {
    return zxidjniJNI.zxid_idp_soap_parse(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), len, buf);
  }

  public static SWIGTYPE_p_zx_sa_Attribute_s add_ldif_attributes(zxid_conf cf, SWIGTYPE_p_zx_sa_Attribute_s prev, int len, String p, String lk) {
    long cPtr = zxidjniJNI.zxid_add_ldif_attributes(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_sa_Attribute_s.getCPtr(prev), len, p, lk);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_Attribute_s(cPtr, false);
  }

  public static zx_str idp_sso(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, SWIGTYPE_p_zx_sp_AuthnRequest_s ar) {
    long cPtr = zxidjniJNI.zxid_idp_sso(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), SWIGTYPE_p_zx_sp_AuthnRequest_s.getCPtr(ar));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int pick_sso_profile(zxid_conf cf, zxid_cgi cgi, zxid_entity idp_met) {
    return zxidjniJNI.zxid_pick_sso_profile(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_entity.getCPtr(idp_met));
  }

  public static int start_sso(zxid_conf cf, zxid_cgi cgi) {
    return zxidjniJNI.zxid_start_sso(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
  }

  public static zx_str start_sso_url(zxid_conf cf, zxid_cgi cgi) {
    long cPtr = zxidjniJNI.zxid_start_sso_url(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str start_sso_location(zxid_conf cf, zxid_cgi cgi) {
    long cPtr = zxidjniJNI.zxid_start_sso_location(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int sp_deref_art(zxid_conf cf, zxid_cgi cgi, zxid_ses ses) {
    return zxidjniJNI.zxid_sp_deref_art(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses));
  }

  public static int sp_sso_finalize(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, SWIGTYPE_p_zx_sa_Assertion_s a7n) {
    return zxidjniJNI.zxid_sp_sso_finalize(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), SWIGTYPE_p_zx_sa_Assertion_s.getCPtr(a7n));
  }

  public static int sp_anon_finalize(zxid_conf cf, zxid_cgi cgi, zxid_ses ses) {
    return zxidjniJNI.zxid_sp_anon_finalize(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses));
  }

  public static String saml2_map_nid_fmt(String f) {
    return zxidjniJNI.zxid_saml2_map_nid_fmt(f);
  }

  public static String saml2_map_protocol_binding(String b) {
    return zxidjniJNI.zxid_saml2_map_protocol_binding(b);
  }

  public static int protocol_binding_map_saml2(zx_str b) {
    return zxidjniJNI.zxid_protocol_binding_map_saml2(zx_str.getCPtr(b));
  }

  public static String saml2_map_authn_ctx(String c) {
    return zxidjniJNI.zxid_saml2_map_authn_ctx(c);
  }

  public static SWIGTYPE_p_zx_sa_Issuer_s issuer(zxid_conf cf, zx_str nameid, String affiliation) {
    long cPtr = zxidjniJNI.zxid_issuer(zxid_conf.getCPtr(cf), zx_str.getCPtr(nameid), affiliation);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_Issuer_s(cPtr, false);
  }

  public static void sigres_map(int sigres, SWIGTYPE_p_p_char sigval, SWIGTYPE_p_p_char sigmsg) {
    zxidjniJNI.zxid_sigres_map(sigres, SWIGTYPE_p_p_char.getCPtr(sigval), SWIGTYPE_p_p_char.getCPtr(sigmsg));
  }

  public static int validate_conditions(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, SWIGTYPE_p_zx_sa_Assertion_s a7n, zx_str myentid, SWIGTYPE_p_timeval ourts, SWIGTYPE_p_p_char err) {
    return zxidjniJNI.zxid_validate_conditions(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), SWIGTYPE_p_zx_sa_Assertion_s.getCPtr(a7n), zx_str.getCPtr(myentid), SWIGTYPE_p_timeval.getCPtr(ourts), SWIGTYPE_p_p_char.getCPtr(err));
  }

  public static int sp_slo_soap(zxid_conf cf, zxid_cgi cgi, zxid_ses ses) {
    return zxidjniJNI.zxid_sp_slo_soap(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses));
  }

  public static zx_str sp_slo_redir(zxid_conf cf, zxid_cgi cgi, zxid_ses ses) {
    long cPtr = zxidjniJNI.zxid_sp_slo_redir(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int sp_slo_do(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, SWIGTYPE_p_zx_sp_LogoutRequest_s req) {
    return zxidjniJNI.zxid_sp_slo_do(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), SWIGTYPE_p_zx_sp_LogoutRequest_s.getCPtr(req));
  }

  public static int idp_slo_do(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, SWIGTYPE_p_zx_sp_LogoutRequest_s req) {
    return zxidjniJNI.zxid_idp_slo_do(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), SWIGTYPE_p_zx_sp_LogoutRequest_s.getCPtr(req));
  }

  public static zx_str slo_resp_redir(zxid_conf cf, zxid_cgi cgi, SWIGTYPE_p_zx_sp_LogoutRequest_s req) {
    long cPtr = zxidjniJNI.zxid_slo_resp_redir(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), SWIGTYPE_p_zx_sp_LogoutRequest_s.getCPtr(req));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int sp_mni_soap(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, zx_str new_nym) {
    return zxidjniJNI.zxid_sp_mni_soap(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), zx_str.getCPtr(new_nym));
  }

  public static zx_str sp_mni_redir(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, zx_str new_nym) {
    long cPtr = zxidjniJNI.zxid_sp_mni_redir(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), zx_str.getCPtr(new_nym));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_ManageNameIDResponse_s mni_do(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, SWIGTYPE_p_zx_sp_ManageNameIDRequest_s mni) {
    long cPtr = zxidjniJNI.zxid_mni_do(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), SWIGTYPE_p_zx_sp_ManageNameIDRequest_s.getCPtr(mni));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_ManageNameIDResponse_s(cPtr, false);
  }

  public static zx_str mni_do_ss(zxid_conf cf, zxid_cgi cgi, zxid_ses ses, SWIGTYPE_p_zx_sp_ManageNameIDRequest_s mni, zx_str loc) {
    long cPtr = zxidjniJNI.zxid_mni_do_ss(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses), SWIGTYPE_p_zx_sp_ManageNameIDRequest_s.getCPtr(mni), zx_str.getCPtr(loc));
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int pep_az_soap(zxid_conf cf, zxid_cgi cgi, zxid_ses ses) {
    return zxidjniJNI.zxid_pep_az_soap(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi), zxid_ses.getCPtr(ses));
  }

  public static int az_cf_ses(zxid_conf cf, String qs, zxid_ses ses) {
    return zxidjniJNI.zxid_az_cf_ses(zxid_conf.getCPtr(cf), qs, zxid_ses.getCPtr(ses));
  }

  public static int az_cf(zxid_conf cf, String qs, String sid) {
    return zxidjniJNI.zxid_az_cf(zxid_conf.getCPtr(cf), qs, sid);
  }

  public static int az(String conf, String qs, String sid) {
    return zxidjniJNI.zxid_az(conf, qs, sid);
  }

  public static SWIGTYPE_p_zx_sa_Attribute_s find_attribute(SWIGTYPE_p_zx_sa_Assertion_s a7n, int nfmt_len, String nfmt, int name_len, String name, int friendly_len, String friendly, int n) {
    long cPtr = zxidjniJNI.zxid_find_attribute(SWIGTYPE_p_zx_sa_Assertion_s.getCPtr(a7n), nfmt_len, nfmt, name_len, name, friendly_len, friendly, n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_Attribute_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_AuthnRequest_s mk_authn_req(zxid_conf cf, zxid_cgi cgi) {
    long cPtr = zxidjniJNI.zxid_mk_authn_req(zxid_conf.getCPtr(cf), zxid_cgi.getCPtr(cgi));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_AuthnRequest_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_ArtifactResolve_s mk_art_deref(zxid_conf cf, zxid_entity idp_meta, String artifact) {
    long cPtr = zxidjniJNI.zxid_mk_art_deref(zxid_conf.getCPtr(cf), zxid_entity.getCPtr(idp_meta), artifact);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_ArtifactResolve_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_Status_s mk_Status(zxid_conf cf, String sc1, String sc2, String msg) {
    long cPtr = zxidjniJNI.zxid_mk_Status(zxid_conf.getCPtr(cf), sc1, sc2, msg);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_Status_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_Status_s OK(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_OK(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_Status_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sa_EncryptedID_s mk_enc_id(zxid_conf cf, SWIGTYPE_p_zx_sa_NameID_s nid, zxid_entity meta) {
    long cPtr = zxidjniJNI.zxid_mk_enc_id(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_sa_NameID_s.getCPtr(nid), zxid_entity.getCPtr(meta));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_EncryptedID_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sa_EncryptedAssertion_s mk_enc_a7n(zxid_conf cf, SWIGTYPE_p_zx_sa_Assertion_s a7n, zxid_entity meta) {
    long cPtr = zxidjniJNI.zxid_mk_enc_a7n(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_sa_Assertion_s.getCPtr(a7n), zxid_entity.getCPtr(meta));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_EncryptedAssertion_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_LogoutRequest_s mk_logout(zxid_conf cf, SWIGTYPE_p_zx_sa_NameID_s nid, zx_str ses_ix, zxid_entity idp) {
    long cPtr = zxidjniJNI.zxid_mk_logout(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_sa_NameID_s.getCPtr(nid), zx_str.getCPtr(ses_ix), zxid_entity.getCPtr(idp));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_LogoutRequest_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_LogoutResponse_s mk_logout_resp(zxid_conf cf, SWIGTYPE_p_zx_sp_Status_s st, zx_str req_id) {
    long cPtr = zxidjniJNI.zxid_mk_logout_resp(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_sp_Status_s.getCPtr(st), zx_str.getCPtr(req_id));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_LogoutResponse_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_ManageNameIDRequest_s mk_mni(zxid_conf cf, SWIGTYPE_p_zx_sa_NameID_s nid, zx_str new_nym, zxid_entity idp) {
    long cPtr = zxidjniJNI.zxid_mk_mni(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_sa_NameID_s.getCPtr(nid), zx_str.getCPtr(new_nym), zxid_entity.getCPtr(idp));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_ManageNameIDRequest_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_ManageNameIDResponse_s mk_mni_resp(zxid_conf cf, SWIGTYPE_p_zx_sp_Status_s st, zx_str req_id) {
    long cPtr = zxidjniJNI.zxid_mk_mni_resp(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_sp_Status_s.getCPtr(st), zx_str.getCPtr(req_id));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_ManageNameIDResponse_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sa_Assertion_s mk_a7n(zxid_conf cf, zx_str audience, SWIGTYPE_p_zx_sa_Subject_s subj, SWIGTYPE_p_zx_sa_AuthnStatement_s an_stmt, SWIGTYPE_p_zx_sa_AttributeStatement_s at_stmt, SWIGTYPE_p_zx_xasa_XACMLAuthzDecisionStatement_s az_stmt) {
    long cPtr = zxidjniJNI.zxid_mk_a7n(zxid_conf.getCPtr(cf), zx_str.getCPtr(audience), SWIGTYPE_p_zx_sa_Subject_s.getCPtr(subj), SWIGTYPE_p_zx_sa_AuthnStatement_s.getCPtr(an_stmt), SWIGTYPE_p_zx_sa_AttributeStatement_s.getCPtr(at_stmt), SWIGTYPE_p_zx_xasa_XACMLAuthzDecisionStatement_s.getCPtr(az_stmt));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_Assertion_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sa_Subject_s mk_subj(zxid_conf cf, zxid_entity sp_meta, SWIGTYPE_p_zx_sa_NameID_s nid) {
    long cPtr = zxidjniJNI.zxid_mk_subj(zxid_conf.getCPtr(cf), zxid_entity.getCPtr(sp_meta), SWIGTYPE_p_zx_sa_NameID_s.getCPtr(nid));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_Subject_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sa_AuthnStatement_s mk_an_stmt(zxid_conf cf, zxid_ses ses) {
    long cPtr = zxidjniJNI.zxid_mk_an_stmt(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_AuthnStatement_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sp_Response_s mk_saml_resp(zxid_conf cf) {
    long cPtr = zxidjniJNI.zxid_mk_saml_resp(zxid_conf.getCPtr(cf));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sp_Response_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_xac_Response_s mk_xacml_resp(zxid_conf cf, String decision) {
    long cPtr = zxidjniJNI.zxid_mk_xacml_resp(zxid_conf.getCPtr(cf), decision);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_xac_Response_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_xac_Attribute_s mk_xacml_simple_at(zxid_conf cf, SWIGTYPE_p_zx_xac_Attribute_s aa, zx_str atid, zx_str attype, zx_str atissuer, zx_str atvalue) {
    long cPtr = zxidjniJNI.zxid_mk_xacml_simple_at(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_xac_Attribute_s.getCPtr(aa), zx_str.getCPtr(atid), zx_str.getCPtr(attype), zx_str.getCPtr(atissuer), zx_str.getCPtr(atvalue));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_xac_Attribute_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_xasp_XACMLAuthzDecisionQuery_s mk_az(zxid_conf cf, SWIGTYPE_p_zx_xac_Attribute_s subj, SWIGTYPE_p_zx_xac_Attribute_s rsrc, SWIGTYPE_p_zx_xac_Attribute_s act, SWIGTYPE_p_zx_xac_Attribute_s env) {
    long cPtr = zxidjniJNI.zxid_mk_az(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_xac_Attribute_s.getCPtr(subj), SWIGTYPE_p_zx_xac_Attribute_s.getCPtr(rsrc), SWIGTYPE_p_zx_xac_Attribute_s.getCPtr(act), SWIGTYPE_p_zx_xac_Attribute_s.getCPtr(env));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_xasp_XACMLAuthzDecisionQuery_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_xaspcd1_XACMLAuthzDecisionQuery_s mk_az_cd1(zxid_conf cf, SWIGTYPE_p_zx_xac_Attribute_s subj, SWIGTYPE_p_zx_xac_Attribute_s rsrc, SWIGTYPE_p_zx_xac_Attribute_s act, SWIGTYPE_p_zx_xac_Attribute_s env) {
    long cPtr = zxidjniJNI.zxid_mk_az_cd1(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_xac_Attribute_s.getCPtr(subj), SWIGTYPE_p_zx_xac_Attribute_s.getCPtr(rsrc), SWIGTYPE_p_zx_xac_Attribute_s.getCPtr(act), SWIGTYPE_p_zx_xac_Attribute_s.getCPtr(env));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_xaspcd1_XACMLAuthzDecisionQuery_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_sa_Attribute_s mk_attribute(zxid_conf cf, String name, String val) {
    long cPtr = zxidjniJNI.zxid_mk_attribute(zxid_conf.getCPtr(cf), name, val);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_sa_Attribute_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_di_Query_s mk_di_query(zxid_conf cf, String svc_type) {
    long cPtr = zxidjniJNI.zxid_mk_di_query(zxid_conf.getCPtr(cf), svc_type);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_di_Query_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_a_Address_s mk_addr(zxid_conf cf, zx_str url) {
    long cPtr = zxidjniJNI.zxid_mk_addr(zxid_conf.getCPtr(cf), zx_str.getCPtr(url));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_a_Address_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_dap_Select_s mk_dap_select(zxid_conf cf, String dn, String filter, String attributes, int deref_aliases, int scope, int sizelimit, int timelimit, int typesonly) {
    long cPtr = zxidjniJNI.zxid_mk_dap_select(zxid_conf.getCPtr(cf), dn, filter, attributes, deref_aliases, scope, sizelimit, timelimit, typesonly);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_dap_Select_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_dap_QueryItem_s mk_dap_query_item(zxid_conf cf, SWIGTYPE_p_zx_dap_Select_s sel, String objtype, String predef, String sort, String changed_since, int incl_common_attrs, int offset, int count, String setreq, String setid, String contingent_itemidref) {
    long cPtr = zxidjniJNI.zxid_mk_dap_query_item(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_dap_Select_s.getCPtr(sel), objtype, predef, sort, changed_since, incl_common_attrs, offset, count, setreq, setid, contingent_itemidref);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_dap_QueryItem_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_dap_TestOp_s mk_dap_testop(zxid_conf cf, String dn, String filter, String attributes, int deref_aliases, int scope, int sizelimit, int timelimit, int typesonly) {
    long cPtr = zxidjniJNI.zxid_mk_dap_testop(zxid_conf.getCPtr(cf), dn, filter, attributes, deref_aliases, scope, sizelimit, timelimit, typesonly);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_dap_TestOp_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_dap_TestItem_s mk_dap_test_item(zxid_conf cf, SWIGTYPE_p_zx_dap_TestOp_s top, String objtype, String predef) {
    long cPtr = zxidjniJNI.zxid_mk_dap_test_item(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_dap_TestOp_s.getCPtr(top), objtype, predef);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_dap_TestItem_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_dap_ResultQuery_s mk_dap_resquery(zxid_conf cf, SWIGTYPE_p_zx_dap_Select_s sel, String objtype, String predef, String sort, String changed_since, int incl_common_attr, String contingent_itemidref) {
    long cPtr = zxidjniJNI.zxid_mk_dap_resquery(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_dap_Select_s.getCPtr(sel), objtype, predef, sort, changed_since, incl_common_attr, contingent_itemidref);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_dap_ResultQuery_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_dap_Subscription_s mk_dap_subscription(zxid_conf cf, String subsID, String itemidref, SWIGTYPE_p_zx_dap_ResultQuery_s rq, String aggreg, String trig, String starts, String expires, int incl_data, String admin_notif, String notify_ref) {
    long cPtr = zxidjniJNI.zxid_mk_dap_subscription(zxid_conf.getCPtr(cf), subsID, itemidref, SWIGTYPE_p_zx_dap_ResultQuery_s.getCPtr(rq), aggreg, trig, starts, expires, incl_data, admin_notif, notify_ref);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_dap_Subscription_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_dap_Query_s mk_dap_query(zxid_conf cf, SWIGTYPE_p_zx_dap_TestItem_s tis, SWIGTYPE_p_zx_dap_QueryItem_s qis, SWIGTYPE_p_zx_dap_Subscription_s subs) {
    long cPtr = zxidjniJNI.zxid_mk_dap_query(zxid_conf.getCPtr(cf), SWIGTYPE_p_zx_dap_TestItem_s.getCPtr(tis), SWIGTYPE_p_zx_dap_QueryItem_s.getCPtr(qis), SWIGTYPE_p_zx_dap_Subscription_s.getCPtr(subs));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_dap_Query_s(cPtr, false);
  }

  public static int map_sec_mech(SWIGTYPE_p_zx_a_EndpointReference_s epr) {
    return zxidjniJNI.zxid_map_sec_mech(SWIGTYPE_p_zx_a_EndpointReference_s.getCPtr(epr));
  }

  public static SWIGTYPE_p_zx_e_Envelope_s wsc_call(zxid_conf cf, zxid_ses ses, SWIGTYPE_p_zx_a_EndpointReference_s epr, SWIGTYPE_p_zx_e_Envelope_s env) {
    long cPtr = zxidjniJNI.zxid_wsc_call(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), SWIGTYPE_p_zx_a_EndpointReference_s.getCPtr(epr), SWIGTYPE_p_zx_e_Envelope_s.getCPtr(env));
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_e_Envelope_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_e_Envelope_s new_envf(zxid_conf cf, String body_f) {
    long cPtr = zxidjniJNI.zxid_new_envf(zxid_conf.getCPtr(cf), body_f);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_e_Envelope_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_e_Envelope_s callf(zxid_conf cf, zxid_ses ses, String svctype, String body_f) {
    long cPtr = zxidjniJNI.zxid_callf(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), svctype, body_f);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_e_Envelope_s(cPtr, false);
  }

  public static zx_str simple_call(zxid_conf cf, zxid_ses ses, String svctype, String url, String env) {
    long cPtr = zxidjniJNI.zxid_simple_call(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), svctype, url, env);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static zx_str simple_callf(zxid_conf cf, zxid_ses ses, String svctype, String url, String env_f) {
    long cPtr = zxidjniJNI.zxid_simple_callf(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), svctype, url, env_f);
    return (cPtr == 0) ? null : new zx_str(cPtr, false);
  }

  public static int nice_sha1(zxid_conf cf, String buf, int buf_len, zx_str name, zx_str cont) {
    return zxidjniJNI.zxid_nice_sha1(zxid_conf.getCPtr(cf), buf, buf_len, zx_str.getCPtr(name), zx_str.getCPtr(cont));
  }

  public static int epr_path(zxid_conf cf, String dir, String sid, String buf, int buf_len, zx_str svc, zx_str cont) {
    return zxidjniJNI.zxid_epr_path(zxid_conf.getCPtr(cf), dir, sid, buf, buf_len, zx_str.getCPtr(svc), zx_str.getCPtr(cont));
  }

  public static SWIGTYPE_p_zx_a_EndpointReference_s get_epr(zxid_conf cf, zxid_ses ses, String svc, int n) {
    long cPtr = zxidjniJNI.zxid_get_epr(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), svc, n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_a_EndpointReference_s(cPtr, false);
  }

  public static SWIGTYPE_p_zx_a_EndpointReference_s find_epr(zxid_conf cf, zxid_ses ses, String svc, int n) {
    long cPtr = zxidjniJNI.zxid_find_epr(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), svc, n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_a_EndpointReference_s(cPtr, false);
  }

  public static int cache_epr(zxid_conf cf, zxid_ses ses, SWIGTYPE_p_zx_a_EndpointReference_s epr) {
    return zxidjniJNI.zxid_cache_epr(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses), SWIGTYPE_p_zx_a_EndpointReference_s.getCPtr(epr));
  }

  public static void snarf_eprs_from_ses(zxid_conf cf, zxid_ses ses) {
    zxidjniJNI.zxid_snarf_eprs_from_ses(zxid_conf.getCPtr(cf), zxid_ses.getCPtr(ses));
  }

  public static void setStd_basis_64(String value) {
    zxidjniJNI.std_basis_64_set(value);
  }

  public static String getStd_basis_64() {
    return zxidjniJNI.std_basis_64_get();
  }

  public static void setSafe_basis_64(String value) {
    zxidjniJNI.safe_basis_64_set(value);
  }

  public static String getSafe_basis_64() {
    return zxidjniJNI.safe_basis_64_get();
  }

  public static void setZx_std_index_64(SWIGTYPE_p_unsigned_char value) {
    zxidjniJNI.zx_std_index_64_set(SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public static SWIGTYPE_p_unsigned_char getZx_std_index_64() {
    long cPtr = zxidjniJNI.zx_std_index_64_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static String base64_fancy_raw(String p, int len, String r, String basis_64, int line_len, int eol_len, String eol, char eq_pad) {
    return zxidjniJNI.base64_fancy_raw(p, len, r, basis_64, line_len, eol_len, eol, eq_pad);
  }

  public static String unbase64_raw(String p, String lim, String r, SWIGTYPE_p_unsigned_char index_64) {
    return zxidjniJNI.unbase64_raw(p, lim, r, SWIGTYPE_p_unsigned_char.getCPtr(index_64));
  }

  public static String sha1_safe_base64(String out_buf, int len, String data) {
    return zxidjniJNI.sha1_safe_base64(out_buf, len, data);
  }

  public static String zx_zlib_raw_deflate(zx_ctx c, int in_len, String in, SWIGTYPE_p_int out_len) {
    return zxidjniJNI.zx_zlib_raw_deflate(zx_ctx.getCPtr(c), in_len, in, SWIGTYPE_p_int.getCPtr(out_len));
  }

  public static String zx_zlib_raw_inflate(zx_ctx c, int in_len, String in, SWIGTYPE_p_int out_len) {
    return zxidjniJNI.zx_zlib_raw_inflate(zx_ctx.getCPtr(c), in_len, in, SWIGTYPE_p_int.getCPtr(out_len));
  }

  public static int zx_url_encode_len(int in_len, String in) {
    return zxidjniJNI.zx_url_encode_len(in_len, in);
  }

  public static String zx_url_encode_raw(int in_len, String in, String out) {
    return zxidjniJNI.zx_url_encode_raw(in_len, in, out);
  }

  public static String zx_url_encode(zx_ctx c, int in_len, String in, SWIGTYPE_p_int out_len) {
    return zxidjniJNI.zx_url_encode(zx_ctx.getCPtr(c), in_len, in, SWIGTYPE_p_int.getCPtr(out_len));
  }

  public static int read_all(int maxlen, String buf, String logkey, String name_fmt) {
    return zxidjniJNI.read_all(maxlen, buf, logkey, name_fmt);
  }

  public static int name_from_path(String buf, int buf_len, String name_fmt) {
    return zxidjniJNI.name_from_path(buf, buf_len, name_fmt);
  }

  public static SWIGTYPE_p_fdtype open_fd_from_path(int flags, int mode, String logkey, String name_fmt) {
    return new SWIGTYPE_p_fdtype(zxidjniJNI.open_fd_from_path(flags, mode, logkey, name_fmt), true);
  }

  public static int read_all_fd(SWIGTYPE_p_fdtype fd, String p, int want, SWIGTYPE_p_int got_all) {
    return zxidjniJNI.read_all_fd(SWIGTYPE_p_fdtype.getCPtr(fd), p, want, SWIGTYPE_p_int.getCPtr(got_all));
  }

  public static int write_all_fd(SWIGTYPE_p_fdtype fd, String p, int pending) {
    return zxidjniJNI.write_all_fd(SWIGTYPE_p_fdtype.getCPtr(fd), p, pending);
  }

  public static int write_all_path_fmt(String logkey, int len, String buf, String path_fmt, String prepath, String postpath, String data_fmt) {
    return zxidjniJNI.write_all_path_fmt(logkey, len, buf, path_fmt, prepath, postpath, data_fmt);
  }

  public static int close_file(SWIGTYPE_p_fdtype fd, String logkey) {
    return zxidjniJNI.close_file(SWIGTYPE_p_fdtype.getCPtr(fd), logkey);
  }

  public static long curl_write_data(SWIGTYPE_p_void buffer, long size, long nmemb, SWIGTYPE_p_void userp) {
    return zxidjniJNI.zxid_curl_write_data(SWIGTYPE_p_void.getCPtr(buffer), size, nmemb, SWIGTYPE_p_void.getCPtr(userp));
  }

  public static long curl_read_data(SWIGTYPE_p_void buffer, long size, long nmemb, SWIGTYPE_p_void userp) {
    return zxidjniJNI.zxid_curl_read_data(SWIGTYPE_p_void.getCPtr(buffer), size, nmemb, SWIGTYPE_p_void.getCPtr(userp));
  }

  public static void setZx_ns_tab(zx_ns_s value) {
    zxidjniJNI.zx_ns_tab_set(zx_ns_s.getCPtr(value));
  }

  public static zx_ns_s getZx_ns_tab() {
    long cPtr = zxidjniJNI.zx_ns_tab_get();
    return (cPtr == 0) ? null : new zx_ns_s(cPtr, false);
  }

}
