/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zxidjava;

public class zxid_need {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected zxid_need(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(zxid_need obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      zxidjniJNI.delete_zxid_need(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setN(zxid_need value) {
    zxidjniJNI.zxid_need_n_set(swigCPtr, zxid_need.getCPtr(value));
  }

  public zxid_need getN() {
    long cPtr = zxidjniJNI.zxid_need_n_get(swigCPtr);
    return (cPtr == 0) ? null : new zxid_need(cPtr, false);
  }

  public void setAt(zxid_attr value) {
    zxidjniJNI.zxid_need_at_set(swigCPtr, zxid_attr.getCPtr(value));
  }

  public zxid_attr getAt() {
    long cPtr = zxidjniJNI.zxid_need_at_get(swigCPtr);
    return (cPtr == 0) ? null : new zxid_attr(cPtr, false);
  }

  public void setUsage(String value) {
    zxidjniJNI.zxid_need_usage_set(swigCPtr, value);
  }

  public String getUsage() {
    return zxidjniJNI.zxid_need_usage_get(swigCPtr);
  }

  public void setRetent(String value) {
    zxidjniJNI.zxid_need_retent_set(swigCPtr, value);
  }

  public String getRetent() {
    return zxidjniJNI.zxid_need_retent_get(swigCPtr);
  }

  public void setOblig(String value) {
    zxidjniJNI.zxid_need_oblig_set(swigCPtr, value);
  }

  public String getOblig() {
    return zxidjniJNI.zxid_need_oblig_get(swigCPtr);
  }

  public void setExt(String value) {
    zxidjniJNI.zxid_need_ext_set(swigCPtr, value);
  }

  public String getExt() {
    return zxidjniJNI.zxid_need_ext_get(swigCPtr);
  }

  public zxid_need() {
    this(zxidjniJNI.new_zxid_need(), true);
  }

}
