/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zxidjava;

public class zxsig_ref {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected zxsig_ref(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(zxsig_ref obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      zxidjniJNI.delete_zxsig_ref(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setSref(SWIGTYPE_p_zx_ds_Reference_s value) {
    zxidjniJNI.zxsig_ref_sref_set(swigCPtr, SWIGTYPE_p_zx_ds_Reference_s.getCPtr(value));
  }

  public SWIGTYPE_p_zx_ds_Reference_s getSref() {
    long cPtr = zxidjniJNI.zxsig_ref_sref_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_zx_ds_Reference_s(cPtr, false);
  }

  public void setBlob(zx_elem_s value) {
    zxidjniJNI.zxsig_ref_blob_set(swigCPtr, zx_elem_s.getCPtr(value));
  }

  public zx_elem_s getBlob() {
    long cPtr = zxidjniJNI.zxsig_ref_blob_get(swigCPtr);
    return (cPtr == 0) ? null : new zx_elem_s(cPtr, false);
  }

  public zxsig_ref() {
    this(zxidjniJNI.new_zxsig_ref(), true);
  }

}
